### ISSUE TITLE
Guests/Voices Cheat Sheet

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#10]
Update cheat sheet with current recording software... if we are using Pamela still or not.

**Comment by porteriffic** [comment]
I will work with Stephanie to make the cheat sheets look nicer, Corey will update with the new recording process.

**Comment by porteriffic** [comment]
@coreysmart92 Do you have an update for us? I'm coordinating with Voices and Producers for Polyglot Day and unfortunately I have to send them our current cheat sheets which are highly out of date. 

I'm more than happy to work with you on this. Just name a time and/or date. Would like to get updated cheat sheet soon.

**Comment by coreysmart92** [comment]
Closing because it is a duplicate of #64.
