### ISSUE TITLE
Record Podcast for Rhythmically Inclined

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#100]
@halclark and @amb141330 can you both record a new podcast discussing bumpers for:
- Sound & Data
- Indie Game Nation

Because we didn't a podcast up for May, shoot for another podcast by the end of June.

**Comment by halclark** [comment]
Plan on recording this week.

**Comment by porteriffic** [comment]
@halclark Close issue when podcast has been recorded.
