### ISSUE TITLE
Rollout podcasts

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#102]
@coreysmart92 @porteriffic @amb141330 @halclark @kkondas 
Have uploaded two podcasts in gdrive (need editing folder) for the Voices from the Crowd channel
or the Femgineer's one - it's all about AEC market and technology entrepreneurship, so I'm not sure where it should go.. will fill out the forms later this week..

**Comment by porteriffic** [comment]
@yvantina The Femgineers channel won't be up until (by the earliest) the beginning of August. So probably Voices of the Crowd for now. We can always ask Eun Ah about putting the podcast on the Femgineers channel once they have their first podcast up.

**Comment by yvantina** [comment]
okay no worry then ! Voices from the Crowd would be good enough
