### ISSUE TITLE
leads for youth day

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#103]
here is a lead
to get three high school students to do pocasts
i will see if i can get any set up in time

roger

Hi Roger - Great thanks so much for  a great opportunity for the students - they produced their posters as part of their participation in NetSciHigh - more details here https://sites.google.com/a/binghamton.edu/netscihigh/
I'm happy to write an intro if you give me parameters for length etc
The podcasts is a fantastic idea! The only hitch is school just let out for the summer but we could produce this in the fall - let me know what you think 
Happy to answer more questions
Thanks
Best
Catherine

**Comment by rmalina** [comment]
josephine corey
why dont you do an email to all producesr and voices to nominate
high school/secondary ( its not called high school outside of usa)
who we could do podcasts with in art/eci/tech topics
roger
@porteriffic

**Comment by cassininazir** [comment]
Would like to review the email before it goes out to make sure it fits within the templates that @heiwanalady is working on.

**Comment by porteriffic** [comment]
@cassininazir I will be at the lab tomorrow with Stephanie until 12:30ish. We'll be working on the email

**Comment by porteriffic** [comment]
@rmalina Should we expect to get a podcast from her? If so, I will make a note of it on our [WYSD Doc](https://docs.google.com/document/d/1YXE71afggR8x4AJofYQHe75uEaSTMgkVdeClxksLLng/edit) in the Google Drive.

**Comment by rmalina** [comment]
go ahead and contact her
ccramer@nysci.org]

she said since its summer it may be hard to get podcasts from the students

roger @porteriffic 
From: Catherine Cramer [mailto:ccramer@nysci.org] 
Sent: Wednesday, June 10, 2015 9:25 PM
To: Malina, Roger
Cc: Stephen Uzzo; Lori Sheetz; Hiroki Sayama
Subject: Network Science posters from high school students

Hi Roger - I attended the Leonardo symposium in Zaragoza last week - which was excellent! Afterwards when we were taking down our NetSci High students' posters you came over and mentioned that you might have interest in publishing one or more of the posters - so I am just getting in touch about that! Let us know if we can give you any additional information etc.
Thanks~
Best,
Catherine

**Comment by porteriffic** [comment]
Youth Day is over. Will use as a contact for future feature days.
