### ISSUE TITLE
Podcast with Ethan Friedericks

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#105]
Would like to do a podcast with Ethan Friedericks who is the Senior Dialog Editor at Disney Publishing Worldwide. Need to ask Scot if it's okay to use his channel.

**Comment by porteriffic** [comment]
Let's contact him for World Day for Audiovisual Heritage to do a podcast with us.
efriedericks@mac.com

**Comment by porteriffic** [comment]
Emailed him finally. Scot says it's okay to post on Sound & Data. Just gotta let him listen to it first.(9/11)

**Comment by porteriffic** [comment]
Still haven't heard from him (9/18)

=(

**Comment by porteriffic** [comment]
Still haven't heard back. (9/29)

**Comment by coreysmart92** [comment]
Closing: Never responded. (10/19/15)
