### ISSUE TITLE
please clean up drop box folders

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#106]
corey
i am totally confused by the podcast drop box folders- can you figure out/clean up

a) in my drop box i have a set of top level files for
new leonardos, virtual africa, frank malina , voice from the crowd
there dont seem to be any podcasts in those folders
B) separately i have a top level folder called creative disturbance
with sub folders for the same channels as in a) above
c) some of those folders have podcasts that have already been edited and published

i have been trying to fill out the forms for the podcasts forms for the podcasts
you assigned to me at the monday meeting but i have now spent an hour trying
to figure out how to do it

thanks

am copying this to cassini and josephine as this drop box clean up may already
be assigned/under way

roger
@cassininazir @porteriffic

**Comment by cassininazir** [comment]
This looks like its been cleared. Reopen if needed.
