### ISSUE TITLE
July Bumpers (Corey)

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#108]
Be ready to present these in next week's Monday meeting:

**Virtual Africa** 
- first draft by **July 20**
- completed by **July 27**

**Within the Margins**
- first draft by **July 13** 
- completed **July 20**

**Comment by coreysmart92** [comment]
Nothing new to report, other then these have been pushed back. (8/3/15)
Close: When both bumpers are completed and ready to be published

**Comment by coreysmart92** [comment]
Closing:
Hal created two bumpers in July, a general bumper and a bumper for Meta-Life.
Yvan submitted a bumper for Virtual Africa.
In August and going into September we are going to try a new method where each sound member chooses what channel to create for and when the deadlines will need to be.
