### ISSUE TITLE
Combine Issues 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#109]
Use the [GitHub Issue Mover](https://github-issue-mover.appspot.com/) to transfer all repos into the [Podcasts](https://github.com/creativedisturbance/podcasts/issues) issue space. 

Add appropriate labels when moving into this space. You may need to add new labels as well.

**Comment by cassininazir** [comment]
Can this issue be closed?

**Comment by halclark** [comment]
Done
