### ISSUE TITLE
New Bumpers

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#110]
_From @amb141330 on June 1, 2015 19:36_

Put the new bumpers on the experimental page.

_Copied from original issue: creativedisturbance/experimental#6_

**Comment by cassininazir** [comment]
New bumpers are located in [CD 2.2.1.5](https://drive.google.com/drive/folders/0B0RS2YDJUln1fng5aTlnd0tzTXVZamZOeUdHckN0OEJ4RXVDZVFITHlHOTJ4bzdrdjZNNHc). There are four there.

**Comment by halclark** [comment]
Under control, new bumpers will be posted to new experimental space's soundcloud page.
