### ISSUE TITLE
new bumper scheduling

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#111]
_From @rmalina on May 7, 2015 14:31_

ashton
can you make sure that you update the excel spread sheet- isnt that what we
agreed ? to track the new bumpers on the excel spraed sheet
anyway discuss with corey and josephine

can you tell me when the first new bumper will go up ?

roger

_Copied from original issue: creativedisturbance/experimental#4_

**Comment by cassininazir** [comment]
_From @amb141330 on May 26, 2015 18:39_

First bumper should go up on 5/30/15. This will be completed by @coreysmart92  for The Bold Roast. Will figure out a good format to add to the excel sheet once we have decided on stingers for the month of June.

**Comment by cassininazir** [comment]
Please also make sure that it appears on the Experimental Website and Soundcloud as well.

**Comment by cassininazir** [comment]
_From @rmalina on June 27, 2015 8:32_

please work with the new channel producers of RAMI to develop a bumper/stinger with them-this is culturally sensitive so important to collaborate with them
roger
@coreysmart92 @cassininazir

**Comment by amb141330** [comment]
I believe Corey has taken over this and has put the bumpers on the tracking sheet document.
