### ISSUE TITLE
Home Page Image Too Large + Wrong Link

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#112]
@halclark, thanks for pulling the Polyglot image from the home page yesterday. A few additional things:
- **Remove the image link.** Clicking the image takes you to the Polyglot Day page. This shouldn't take you there.
- **The image is too large.** Reduce to half the current size. 

Let me know if you need assistance.

**Comment by cassininazir** [comment]
Also, **change the link on Tiny Thumbs** to https://twitter.com/tiny_thumbs. Looks like the website is down.

**Comment by kkondas** [comment]
@cassininazir @halclark The site has been down, but we still have the Facebook if that helps: https://www.facebook.com/TinyThumbsArcade

**Comment by halclark** [comment]
Reduced size of the logo to half of it's resolution, and changed the link
of the tiny thumbs logo to it's twitter page.

However, not sure why the homepage logo is still going to polyglot day. The
hyperlink on the image is set to view it on it's own. Help!

**Comment by anvit** [comment]
Fixed it. The hyperlink for the featured page is currently set only through the code. Removed it for now.
