### ISSUE TITLE
podcast language missing in p and p mandlebroft title

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#113]
corey
todays podcast is in french but the (FR) doesn appear in the title
http://creativedisturbance.org/ 

-when you clock through to the podcast the (FR) is htere

roger

**Comment by halclark** [comment]
Updated.

**Comment by halclark** [comment]
Odd. Fixed in wordpress but not showing updates on the website. Will check later.

**Comment by halclark** [comment]
Fixed.
