### ISSUE TITLE
Podcast with Susan Eriksson

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#114]
For [World Youth Skills Day](https://docs.google.com/document/d/1YXE71afggR8x4AJofYQHe75uEaSTMgkVdeClxksLLng/edit#) 
Recording Monday morning @ 11am Central

**Comment by porteriffic** [comment]
Discussion Outline:

"Hello and welcome to the Art & Earth Science channel on Creative Disturbance. My name is Josephine Porter and today I have with me the producer of the Art & Earth Science Channel, Susan Ericksson."
- Go ahead and tell us a little bit about yourself. What is your current profession? 
- When did you discover your fascination/ passion for what you're currently doing?
- What goals did you set for yourself? What skills did you have to acquire and how did you acquire them?
- Where there any pivotal moments in your youth that led you to where you are now?
- What words of advice do you have for youths that are also passionate or interested in pursuing a career like yours?

"Well that's about all the time we have for today. Thank you for joining us and don't forget to share your thoughts with us on our Facebook and Twitter. We'd love to hear from you. I'm Josephine Porter..."

**Comment by cassininazir** [comment]
Not sure if the podcast happened yet. A few thoughts. Reword as needs so it's more comfortable for you:
- What are you doing to ensure you continue to grow and develop as a leader in your field?
- What sorts of things were you involved in as a young person that fostered the passion you currently have? How do you continue to "stoke the fire" currently?
- What impact, if any, have social networking and Web 2.0 made on young people aspiring to join a community of practice.

Sent from my iPhone

On Jul 12, 2015, at 8:19 PM, porteriffic <notifications@github.com<mailto:notifications@github.com>> wrote:

Discussion Outline:
-   Go ahead and tell us a little bit about yourself. What is your current profession?
-   When did you discover your fascination/ passion for what you're currently doing?
-   What goals did you set for yourself? What skills did you have to acquire and how did you acquire them?
-   Where there any pivotal moments in your youth that led you to where you are now?
-   What words of advice do you have for youths that are also passionate or interested in pursuing a career like yours?

**Comment by porteriffic** [comment]
Recorded the podcast. Was uploaded for WYSD!
