### ISSUE TITLE
clean up drop box after podcasts are published

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#115]
corey

please can you have someone  clean up the drop box files and remove from needs editing podcasts that are already
published on CD

the two podcasts  with J Mandelbrojt are still in pioneers and pathbreakers but are already on drop box

roger 

cassini-i guess this needs to be part of the archiving process ?
@cassini @halclark

**Comment by coreysmart92** [comment]
I will take care of this. (8/3/15)
Close: When dropbox is up-to-date

**Comment by coreysmart92** [comment]
Closing: I will do this on a regular basis, and each sound member should be doing this them selves when a podcast is published. (9/1/15)
