### ISSUE TITLE
Noisy People Image

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#122]
Images for Noisy People on Libsyn are not correct. If you look back at the older ones, they are different AND they are the correct ones. The gray looking one is not correct.

**Comment by coreysmart92** [comment]
02: Joëlle Léandre is correct, I will go through and shift all of them to this one. (8/3/15)
Close: when completed and check the images on wordpress

**Comment by coreysmart92** [comment]
Closing:
I have checked and the website is correct. I have also fixed all of the incorrect ones in Libsyn. @porteriffic if there are any that are still incorrect let me know. (8/25/15)
