### ISSUE TITLE
help lilla submit a podcast for new leonardos

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#124]
_From @rmalina on July 7, 2015 15:15_

please send instructions on how to sumit a podcast to

Lilla LoCurto loc.out@verizon.net

_Copied from original issue: creativedisturbance/intellectual-dating#19_

**Comment by halclark** [comment]
_From @porteriffic on July 10, 2015 15:54_

@coreysmart92 I made some minor changes to the [Podcast Production Cheat Sheet](https://docs.google.com/document/d/1Io4Cj1Btt56jifbt4I8R1K4fdX1JYHPEzaYHbLAQBKY/edit). Please download this document as a PDF to send to Lilla and others you are assigned to. Call, email, or text if you need help compiling an email.

**Comment by coreysmart92** [comment]
I will send the Cheat Sheet soon and see if they need any assistance. (8/3/15)

**Comment by coreysmart92** [comment]
Emailed on August 8. No response yet (8/17/15).

**Comment by coreysmart92** [comment]
Lilla emailed me on 8/20/15. I have responded. It seems she is going to Europe and it could take awhile before she can record a podcast. (8/25/15)

**Comment by coreysmart92** [comment]
Closing: Lilla has submitted a podcast, this podcast has been scheduled to publish 1/27/16.
(1/25/16)
