### ISSUE TITLE
help sasha submit a podcast to new leonardos

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#125]
_From @rmalina on July 7, 2015 15:13_

can you assign to someone

Sasha Petrenko sashpetrenko@gmail.com
Sasha Petrenko
5:44 PM (23 hours ago)

to roger 
hello Roger

This sounds very intriguing. I will think on this a while and get back to you in a few weeks with more information and an abstract. I am quite sure I'd like to take advantage of this. I think I'd like to do something around the idea art in the age of climate change. Thank you for the invitation.

Best,
Sasha

_Copied from original issue: creativedisturbance/intellectual-dating#18_

**Comment by halclark** [comment]
_From @rmalina on July 7, 2015 15:52_

she may want to set up a channel
can you also send her info how to set up a temporary channel
roger

sasha
if you want to do several podcasts that are somehow related thematically
we can actually set up a 'temporary channel" with you as producer
we can open the channel when you submit a first podcast then you can
add others as you have time- if they all have connections with art in the
age of climate change that could make a could title for the channel

you can then also host the channel on your own web site so when people
go to your web site you can feature the podcasts

roger

roger

**Comment by halclark** [comment]
_From @rmalina on July 7, 2015 16:35_

This all sounds fantastic. I'm leaving for Germany in a few days to attend an Artist Residency in Bavaria. This will certainly be one of the projects I'll be working on. I think what I'll do is make a pilot so to speak, a shorter intro episode then on to my first interviewee. I've been reading up on techniques to record podcasts via Skype so I can do this all while still abroad. I have a number of artists/researchers in mind. In fact I've been invited to participate in a think-tank at yerba buena center for the arts on the subject of ecology and I think this podcast will be a great way to engage with my colleagues and a broader audience there! 

Once I have two episodes complete I'd love to start that channel.
So far this is my idea: I'll be interviewing culture makers and researchers on a range of subjects at the intersection of Art, Science and Activism in the Age of Climate Change... 

Art in the Age of Climate Change might be too narrow of a title. It's more like, hmmm. I'll go for a walk and put my mind to it. But as a working title it's fine.

Thanks for this Roger. 
best,
Sasha

**Comment by halclark** [comment]
_From @rmalina on July 7, 2015 16:40_

corey
can you put setting up this new channel on the agenda for next monday- sasha
has several podcasts in prep and this will be a good way to build up backlog
she needs instructions both on
- how to set up a new channel/producer instructions
  -how to record and submit a podcast

this could be a channel like noisy people where we get totally ready podcasts submitted

a stinger on art and climate change would be a nice projecgt !

roger

@porteriffic @coreysmart92 @halclark @cassininazir @amb141330

**Comment by coreysmart92** [comment]
I have added her to the New Channel part of the 8/3/15 sound meeting. We can discuss this then. (8/3/15)

**Comment by coreysmart92** [comment]
Emailed and received a response August 17. Expect to receive podcast Wednesday 8/19/15. (8/17/15)

**Comment by porteriffic** [comment]
@coreysmart92 Did you ever get the podcast?

**Comment by cassininazir** [comment]
@amb141330 can you follow up on this?

**Comment by amb141330** [comment]
Will add Sasha Petrenko to the list of people who should be contacted. Will create a new issue for that purpose.
