### ISSUE TITLE
help marti hearst submit a podcast

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#129]
_From @rmalina on July 5, 2015 8:43_

josephine
can you assign this to someone to help this person submit a podcast for the
new leonardo channel-they need clear instructions on how to submit a podcast

roger

if you can get these podcasts submitted it will help you build up hte back log

roger

@coreysmart92 

Marti A HEARST via alum.mit.edu 
7:54 PM (14 hours ago)

to roger 
I could be interested, but do not want to take the time to edit the
recording you have of me.

marti hearst
hearst@berkeley.edu

_Copied from original issue: creativedisturbance/intellectual-dating#12_

**Comment by cassininazir** [comment]
@halclark any update on this?

**Comment by halclark** [comment]
Sent email at the end of July (7/23), no response. Sent email mid August (8/16), no response. Sent last email today (9/15). Closing issue.
