### ISSUE TITLE
Images...

### ISSUE THREAD

**Issue by kkondas** [creativedisturbance/podcasts#13]
Hey guys,
The new Indie Game Nation is up, but we're still missing images for the podcast and voice (Adam).
I shot you Adam's pic in the paperwork. Let me know if you got it and if I need to send it again. We also need the Indie Game Nation Channel Pic up on the main page so that people that only go there know a new podcast has gone up. Let me know if I need to send that also.
Thanks,
Kyle

**Comment by halclark** [comment]
Image and voice is up but the pic is not 300x300. I will fix.
