### ISSUE TITLE
help julia buntaine submit a podcast

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#130]
_From @rmalina on July 5, 2015 8:40_

josephine
can you assign this to someone- i didnt mean you to do all of these but as you are the overall coordinator i thought it best to have you assign them

corey- there are now about 5 people willing to send in podcasts themselves-but we
need to get them clear instuctions how to submit podcasts-this will help you build up the back log
@coreysmart92 

roger

Hi Roger,

I would love to add a podcast to Creative Disturbance. I've been following this project and think it's fantastic. Send along instructions!

Take care.

Julia Buntaine
info@sciartcenter.org

_Copied from original issue: creativedisturbance/intellectual-dating#11_

**Comment by coreysmart92** [comment]
I have add this topic into the meeting and I will contact Julia Buntaine soon to assist her. (8/3/15)

**Comment by coreysmart92** [comment]
Emailed August 10. No response yet. (8/15/17)

**Comment by amb141330** [comment]
Opening a new issue with list of people to contact. Closing this one.
