### ISSUE TITLE
Morehshin Allahyari Suggestions

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#131]
_From @rmalina on July 1, 2015 17:59_

some great leads from a voice
to be followed up !!

roger---------- Forwarded message ----------
From: Morehshin Allahyari morehshin@gmail.com
Date: Tuesday, June 30, 2015
Subject: Creative Disturbance Metrics!
To: Creative Disturbance feedback.createdisturb@gmail.com

Hello,

Let me first say that I am so happy to see this being a discussion and issue Creative Disturbance is concerned with and working so hard to address and solve. I have some suggestions and some links that you might be interested in:

http://www.walkerart.org/magazine/2015/equity-representation-future-digital-art (scroll through the gallery/the dots on top to see the works)

http://hyperallergic.com/195049/where-are-the-women-of-color-in-new-media-art/ (look also at the comments and the list being gathered below the article)

http://bodyanxiety.com/gallery/landing/

http://gallerytally.tumblr.com/ (founded by Micol Herbon who might be a really great person to contact or do a podcast with)

Also, there is a possibility of having our fellows on your podcast if you might be interested.... This is part of a newly founded lab and fellowship program called "Experimental Research Lab" at Pier9/Autodesk which brings together artists, scientists, engineers, writers, activist to do research at Pier 9. Hopefully with focus on gender and diversity. I will be serving as the co-founder and assistant curator in research at this lab... so once things start moving and rolling we can collaborate or work together in one way or another. 

YES we could set up a channel for her ! roger

I will keep on sending you more links and names as I see them. 

Thank you again for this! 

Best,

_Copied from original issue: creativedisturbance/intellectual-dating#8_

**Comment by halclark** [comment]
_From @heiwanalady on July 1, 2015 23:51_

this is awesome.

**Comment by porteriffic** [comment]
Emailed Morehshin July 1st. She never responded. Maybe we can email her again? (8/17/15)

**Comment by porteriffic** [comment]
Emailed her again to see if anyone at her lab is interested in doing a podcast (10/2)
