### ISSUE TITLE
Intellectual Dating Opportunity with Women and Science in Australia

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#132]
_From @porteriffic on June 19, 2015 23:59_

josephine

can you add this to the intellectual dating tracking list
to be coordinated with eun ah

i offered that we post any podcasts they send us

thanks

roger

keith
ccc eun ah

happy to discuss ideas- if you have announcements
we can send them out through our leonardo network lists

i thought i would mention that on our creative disturbance platform
www.creativedisturbance.org
we are about to start a podcasts channel on women engineers
called 'femgineers' the producer will be eun ah lee here in dallas
who is copied- if you are interested in sending us short podcasts
tied to the conference for us to post we could do that also

in terms of other links we have a group called the Leonardo Education
and Art Forum which is educaiton focused- i can put you in touch

do you get our leonardo isast newsletter ?

roger

On Tue, May 5, 2015 at 3:40 AM, Keith Armstrong k.armstrong@qut.edu.au wrote:
Hi Roger

We spoke briefly during BuB in Phoenix a few weeks back. We spoke both about a Women + Science Conference/Exhibition we are developing, and:

I was interested in potentially linking our university (Queensland University of Technology, Brisbane, Australia) into the your art-science network. You said you’d send more information on this to me.

I look forward to your replies.

Kind Regards

Keith

---------------------------------------------------------------------------------->>
Dr. Keith Armstrong | QUT Senior Research Fellow (p/t)
A/Dir., T4 Creative Practices Research Group
School of Interaction and Visual Design | Creative Industries Faculty
Queensland University of Technology, Australia
Freelance Interdisciplinary Media Artist www.embodiedmedia.com

View Latest Mailout to Subscribers Critical Reviews in Realtime Magazine over past 18 years

Current and Forthcoming Exhibitions
| Long Time, No See? online till 2015 & The Cube Visualisation Centre, QUT Gardens Point, Dec 2013 onwards. (Read Review)
| Are We The One?, App Project, Arthouse DigiLab, Digital Theatre Project, Melbourne Australia

Recent Grants and Awards
| QUT Vice-Chancellor’s Performance Award, for significant and superior contribution to the work of the university, 2014
| QUT Vice-Chancellor’s Performance Award for Research, 2010
| Arts Queensland, Projects and Programs, The Night Fall Project, 2014-15.
| Australia Council, Creative Australia: Presentation and Promotion, Night Fall: A Series Of 'Seasonal' Media Artworks exploring the the 'extinction of human experience' - 2014

Roger F Malina
is in France
33-6-80-45-94-47

_Copied from original issue: creativedisturbance/intellectual-dating#7_

**Comment by porteriffic** [comment]
Was added on the Community Involvement tracking sheet. Will touch bases with Euh Ah next week (8/5)

**Comment by porteriffic** [comment]
Duplicated. Closing.
