### ISSUE TITLE
Organise a Podcast for Bold Roast with Astrid Slegten and Klara Alen

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#133]
_From @rmalina on June 16, 2015 14:36_

josephine
another lead for a podcast -i have a talk and asked for people to self nominate
it worked !

we now have several of these now waiting to be recorded
maybe we should have each of the students take one of these 
so we can get them done ?

roger

to Astrid, Koenraad 
Astrid Slegten Astrid.Slegten@arts.kuleuven.be
cc: Koenraad Brosens Koen.Brosens@arts.kuleuven.be
astrid
absolutely

we have two ways of doing this

a) you record the podcast yourself-we can send you an instruction
sheet with the 2 of you talking about your project- podcasts need
to be under 15 minutes and addressed to a professional audience
its very easy- you can even just do this on your pc using skype or other
software-

b) i can have one of our students set up a skype recording with you
and a time is set up and you do the skype recording-again we have instructions

podcasts by phd students go up on creative disturbance
www.creativedisturbance.org

on the "Bold Roast" channel

http://creativedisturbance.org/channel/the-bold-roast/

we need you to fill out some forms etc

delighted to follow up !

roger malina

On Tue, Jun 16, 2015 at 4:09 PM, Astrid Slegten
Astrid.Slegten@arts.kuleuven.be wrote:

> Dear Mr. Malina,
> 
> It was a pleasure to meet you at the Arts, Humanities, and Complex Networks
> symposium at NetSci2015 in Zaragoza a few weeks ago. We (Astrid Slegten and
> Klara Alen) are PhD students at the University of Leuven and we are working
> on a project that is interfacing tapestry scholarship with social network
> visualization and analysis (www.maptap.be). Our supervisor Prof. dr.
> Koenraad Brosens presented our project MAPTAP at the conference and we have
> just submitted our 1 page article for the Leonardo journal.
> 
> We spoke about the Creative Disturbance platform and wondered if we wouldn’t
> be interested in creating a podcast. Well, we are very much interested in
> making a podcast and telling the world about our research. Would you be
> interested in making a podcast with us? And can you tell us a bit more about
> the process of making such a podcast?
> 
> Thank you in advance for your reply.
> 
> Best wishes,
> 
> Astrid Slegten & Klara Alen
> 
> www.maptap.be
> 
> Follow us on Twitter: @maptap, @astridslegten, @klaraalen

_Copied from original issue: creativedisturbance/intellectual-dating#6_

**Comment by halclark** [comment]
_From @rmalina on June 16, 2015 15:5_

josephine
great-they want to do the podcast themselves
can you send them instruction sheet ?

roger

astrid klara
excellent- and july is fine

i am copying this to josephine porter who is our creative
disturbance coordinator and will send you the instructions
for podcasts

the podcast should be in the form of a dialogue not
a presentation like in a conference- and we can put up links
for people to look at your work further

roger

**Comment by halclark** [comment]
_From @porteriffic on June 20, 2015 1:8_

Contacted Astrid and Klara. Waiting to hear back.

**Comment by halclark** [comment]
_From @porteriffic on July 10, 2015 15:51_

Still have not heard back.

**Comment by halclark** [comment]
_From @rmalina on July 11, 2015 19:48_

i will send them a nudge
roger

**Comment by halclark** [comment]
_From @porteriffic on July 13, 2015 1:33_

Sounds good!

**Comment by porteriffic** [comment]
@rmalina Have you heard back from Astrid or Klara?

**Comment by porteriffic** [comment]
Heard back from Astrid, they a little delayed in doing the podcast due to holidays and such. They still plan on doing the podcast but it might take a little longer. I've asked them to keep us in the loop (8/11/15)
