### ISSUE TITLE
Email "Daters"

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#134]
_From @porteriffic on June 15, 2015 18:58_

Check in on "daters" and find out if there was an outcome.

_Copied from original issue: creativedisturbance/intellectual-dating#5_

**Comment by porteriffic** [comment]
Emailed Dhru about doing a podcast with Sam Viana. According to Dhru, they skyped once "but nothing interesting has popped up from [their] conversation about any collaboration apart from [their] mutual interest in both art and science." (8/12/15)

**Comment by porteriffic** [comment]
Closing until we further develop [Intellectual Dating Plan](https://docs.google.com/document/d/1wnCUf26h3cZSoBeVf4-lK5lQv4w-jDLKwJ9rwSUkgQk/edit).
