### ISSUE TITLE
Do a Podcast with ATEC Student Carlos Harleaux

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#137]
_From @rmalina on June 6, 2015 20:55_

roger to do in august for bold roast
roger

_Copied from original issue: creativedisturbance/intellectual-dating#1_

**Comment by rmalina** [comment]
podcast was recorded and deposited- close this when publishied
roger

**Comment by coreysmart92** [comment]
Closing: This podcast has been published. (10/15/15)
