### ISSUE TITLE
drop box problem

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#138]
_From @rmalina on July 15, 2015 17:46_

we still have a drop box problem
can you reply to her ?
roger
Hi

This is Annick Bureaud, the producer of Audiolats.
I wanted to upload 2 new podcasts for my Disturbances Audiolats and Meta-Life but it says that _my_ dropbox is full.
I thought that I were uploading in _your_ dropbox.
Roger said that I should contact you as I were not the only one that had faced this issue.

the dropbox url I had is this one
https://www.dropbox.com/home/CD%201.5%20Audiolats

In the meantime, I'll send them to Yvan via wetransfert

Thanks for your help.

_Copied from original issue: creativedisturbance/administrative#88_

**Comment by coreysmart92** [comment]
Cassini has increased the capacity for our dropbox. Are you still having this problem? (8/3/15)

**Comment by coreysmart92** [comment]
Closing:
I emailed Annick and resolved the dropbox problem, have not had any problems since then. (8/25/15)
