### ISSUE TITLE
Possible New Channel Climate sHeros

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#139]
_From @rmalina on July 12, 2015 14:38_

possible new channel for discussion monday
@coreysmart92 @porteriffic 
 from tara deporte

she has this podcast series called climate (s)heros of women in climate change
Wonderful!  
Also, feel free to repost and share our current podcasts for Human Impact Stories:  HumanImpactsInstitute.org/HumanImpactStories

is there an easy way for us to create a channel with her as producer and
then grab her podcasts as she puts them up onto sound cloud without
her having to fill out all our forms for each podcast ?

the answer may be no

roger

Tara DePorte
Executive Director and Founder
The Human Impacts Institute 
Tara@HumanImpactsInstitute.org
Office: +1 917 727 9761 
Like us! facebook.com/HumanImpactsInstitute
Follow us! @HumanImpacts

Tara DePorte Art, Teaching, and Speaking
TaraDePorte.com

---

Do LESS. Be more.

_Copied from original issue: creativedisturbance/administrative#87_

**Comment by porteriffic** [comment]
@cassininazir Have you contacted Tara about this yet? If not, I'll be more than happy to take over :)

**Comment by cassininazir** [comment]
Emailed Tara. Before proceeding want to confirm with Tara:
1. That we can upload their content to LibSyn. Unfortunately, LibSyn doesn't allow us to link out to other sources.
2. The scope of what is to be published and a schedule.

This should help us have a weekly flow of content for about 10 weeks that can be added into CD. Closing for now, will open a new ticket when I hear back.
