### ISSUE TITLE
Develop Clearer Guidelines for People to Submit Their Own Podcasts

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#141]
_From @rmalina on July 4, 2015 9:57_

to help create a back log of podcasts i have send an email to leonardo authors to submit their own podcasts (ie that the record themselves and send it)

the cheat sheet i sent them is the one for producers but i really think we need one redone for people to submit their own podcasts

ie Creative Disturbance Podcast Submittion Guidelines

can you rework this and keep in mind people who are NOT on our team of producers would be getting this so it needs to be addressed to people who dont understand our internal processes

here is the doc

Document CD 2.2.2.7
@porteriffic 
roger

_Copied from original issue: creativedisturbance/administrative#85_

**Comment by coreysmart92** [comment]
Nothing to report at this time (8/3/15)

**Comment by porteriffic** [comment]
This should be a pretty simple task. I'll take over.

**Comment by amb141330** [comment]
Old issue. Process will change once Skedge is released. Can write something up then if still needed.
