### ISSUE TITLE
Make sure we are "following" our community on social media platforms

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#142]
_From @porteriffic on June 26, 2015 3:12_

Go through our Voices and Producers and see if they have Twitter, Facebook, and make sure we are following them.

@anvit Is there a way to check this without having to manually go to each person's "page" on WordPress?

_Copied from original issue: creativedisturbance/administrative#82_

**Comment by porteriffic** [comment]
We are now following back all our followers on Twitter. Will implement weekly social media posts on Monday (9/14) using HootSuite.

**Comment by cassininazir** [comment]
Great!

**Comment by porteriffic** [comment]
Closing since I now update the social media platforms weekly.
