### ISSUE TITLE
change procedure so ENG is indicated for podcast titles in english

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#143]
_From @rmalina on June 23, 2015 20:15_

right now podcasts in english dont have ENG as the indicated language of the podcast
podcasts in all other languages indicate the language
if we want to be multilingual we should treat all languages equally
roger
@coreysmart92 

_Copied from original issue: creativedisturbance/administrative#81_

**Comment by porteriffic** [comment]
This process has been added to the Podcast Production Process sheet. It is being implemented on all incoming podcasts.
