### ISSUE TITLE
Archive Adventures in Crowdfunding Channel

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#144]
_From @rmalina on June 21, 2015 20:5_

david marlett doest plan to produce any more podcasts for the crowdfunding channel ( he will for cinemersia) - maybe we should create an archive section for channels that are no longer active ?
or find someone else to produce podcasts for the crowdfunding channel ?
roger @cassininazir @coreysmart92 

_Copied from original issue: creativedisturbance/administrative#78_

**Comment by halclark** [comment]
_From @porteriffic on June 22, 2015 17:8_

@anvit Is there a way we can archive the Adventures in Crowdfunding channel? If not, can we create an archive page?

**Comment by halclark** [comment]
_From @rmalina on June 22, 2015 20:56_

we need to keep the podcasts up- but somehow indicated that the channel is archival
and we can solicit crowdfunding related podcasts but will need a new channel producer
roger

**Comment by halclark** [comment]
_From @anvit on June 24, 2015 20:21_

@porteriffic There isn't a way to archive the channels at the moment but I can create a separate archive page and set up a simple process for showing the archived channels only on the archives page.

**Comment by halclark** [comment]
_From @porteriffic on June 24, 2015 20:53_

@anvit Yes, I think ideally we'd like to still have the channel and podcasts available for listening or downloading so a separate page would work, I think. I'll be in the lab Thursday morning around 10am if you'd like to discuss.

**Comment by halclark** [comment]
_From @anvit on June 24, 2015 21:11_

@porteriffic Will you still be here around 11am? I'll try coming earlier but I most probably will reach the lab around 11.

**Comment by halclark** [comment]
_From @porteriffic on June 24, 2015 23:24_

@anvit Yup! I'll be there. I have to leave around 11:30 though. See you then!

**Comment by halclark** [comment]
_From @heiwanalady on June 25, 2015 0:24_

@porteriffic will you still be meeting me and Cassini at the lab at 10am on
Thursday?

On Wednesday, June 24, 2015, porteriffic notifications@github.com wrote:

> @anvit https://github.com/anvit Yup! I'll be there. I have to leave
> around 11:30 though. See you then!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/administrative/issues/78#issuecomment-115044392
> .

## 

--- Sent from Stephanie's iPhone ---

**Comment by halclark** [comment]
_From @porteriffic on June 25, 2015 0:38_

@heiwanalady Yup! I'll be there!

**Comment by porteriffic** [comment]
@dylanorgeron Maybe we can actually implement this when we start the website redesign?

**Comment by cassininazir** [comment]
We need to define what's meant by archiving -- perhaps its not the right word. I propose it should be:
- The producer is informed that the channel will be "archived" or whatever we decide to call it.
- We put a notice on the channel that the position of producer is open to whomever wishes to cultivate content. 
- We let the previous guests know about the above (via email)?

**Comment by rmalina** [comment]
cassini

your procedure sounds fine

roger

On Mon, Sep 14, 2015 at 10:36 AM, Cassini Nazir notifications@github.com
wrote:

> We need to define what's meant by archiving -- perhaps its not the right
> word. I propose it should be:
> - The producer is informed that the channel will be "archived" or
>   whatever we decide to call it.
> - We put a notice on the channel that the position of producer is open
>   to whomever wishes to cultivate content.
> - We let the previous guests know about the above (via email)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/144#issuecomment-140117863
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by cassininazir** [comment]
@dylanorgeron can you prioritize this? We can discuss. Probably need a way to manage active vs inactive channels. 

Perhaps there's a way to do this automatically, so that after 3 months of inactivity?

**Comment by cassininazir** [comment]
Duplicated in #469. Closing this issue.
