### ISSUE TITLE
Transfer of Producer for The Bold Roast

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#145]
_From @heiwanalady on June 17, 2015 20:22_

@porteriffic , Just got off a Skype with @rmalina  

We need to discuss how to transfer producer duties to different person for The Bold Roast as well as discuss the possibility of using ArtSciLab alumni/alumna as the producers for the channel? 

How do we keep the alumni/alumna involved after they've graduated and maintain that network? 

I'd be open to co-producing on a team of students if that's a possibility. Would be more efficient I think. 

_Copied from original issue: creativedisturbance/administrative#76_

**Comment by halclark** [comment]
_From @sayloo on June 18, 2015 0:7_

I'd be more than happy to voluntarily work for the lab :+1:

**Comment by halclark** [comment]
_From @porteriffic on June 18, 2015 0:51_

This issue has been on the back burner for a while. I'd be more than happy to meet up to discuss. 

@sayloo That would be awesome!

**Comment by halclark** [comment]
_From @heiwanalady on June 25, 2015 16:49_

@rmalina @cassininazir @porteriffic @sayloo @anvit @heiwanalady

Josephine and I met this morning about how to handle this - and we are going to extend the invitation to Sruthi, Anvil, Cathryn and myself to run The Bold Roast together as an alumnae/alumna team :)
Still need to email Cathryn about this. I'm sure it will be easy to run the channel with 4+ people available to respond to questions or approval of podcasts etc.

**Comment by halclark** [comment]
_From @rmalina on June 25, 2015 20:30_

i think this is a FANTASTIC idea !!

**Comment by halclark** [comment]
_From @porteriffic on June 26, 2015 16:38_

Sruthi has agreed to be a producer!

**Comment by halclark** [comment]
_From @porteriffic on July 10, 2015 16:56_

Anvit and Stephanie agreed to be producer as well. Have not heard back from Cathryn

**Comment by porteriffic** [comment]
Sruthi, Anvit and Stephanie are the current producers of The Bold Roast Channel.
