### ISSUE TITLE
Email to Producers (Metrics, Podcasts, etc)

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#146]
_From @porteriffic on June 15, 2015 18:23_

Email community about the following:
- ~~Emails about upcoming days in July and August~~
- Let producers know how their channel is doing and give them stats. 
  - Emailed Scot and Tim so far. Will email more over the weekend and after I collect stats for Polyglot.
- If a producer isn't bringing in podcasts, let them know and encourage them and offer assistance.
  - Adventures of Crowdfunding will be archived. David Marlett won't be bringing in anymore podcasts for this channel.

Use Cassini's [tracking sheet](https://docs.google.com/spreadsheets/d/1JUtI3ecGsmmmIR9dKtSGxkuNFcKvmzhXc2ND69MSvd4/edit#gid=90106257)

_Copied from original issue: creativedisturbance/administrative#73_

**Comment by halclark** [comment]
_From @porteriffic on June 16, 2015 3:33_

Started working on drafts for the these emails. Will send out top priority ones tomorrow and the others on Thursday.

**Comment by porteriffic** [comment]
Emails to producers regarding stats have been sent. Also encouraged producers to bring in more podcasts. Will add to Community Building Plan on doing this more often.
