### ISSUE TITLE
Set Up "Pioneers in Print, Poetry & Performance between 1960s-1980s" Channel

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#147]
_From @rmalina on June 13, 2015 12:33_

poe
can you work with josephine to set up bronac's
new creative disturbance channel "P4"

bronac you need to fill out a new channel form-
and get the new instructions for producers and
making podcasts
work wiht poe to set up bronac ferran's new channel

 Pioneers in Print, Poetry & Performance between 1960s-1980s

roger
roger

On Wed, Jun 10, 2015 at 1:24 PM, bronac ferran bronacf@gmail.com wrote:

> Dear All
> 
> My suggestion for channel title, as promised:
> 
> Pioneers in Print, Poetry & Performance between 1960s-1980s
> 
> Is this going to work OK?
> 
> with best 
> 
> B
> 
> On Saturday, 6 June 2015, bronac ferran bronacf@gmail.com wrote:
> 
> > HI Roger thanks!  I do think this will work....
> > in a day or two will send suggested name and proposed interviews to Poe cc
> > all...
> > 
> > B
> > 
> > On 6 June 2015 at 22:20, roger malina rmalina@alum.mit.edu wrote:
> > 
> > > bronac
> > > happy to open new channels !! as long as a 'few' podcasts a year go up
> > > its viable
> > > its really neat- we hit 10,000 downloads so far !
> > > 
> > > roger
> > > 
> > > On Sat, Jun 6, 2015 at 9:22 PM, bronac ferran bronacf@gmail.com wrote:
> > > 
> > > > Dear Annick
> > > > 
> > > > Yes it would have been great to see you at Liliane's opening. I hope
> > > > you are
> > > > well?  A chap came who said he had worked closely with you on Art Tech
> > > > (?)
> > > > for several years.
> > > > 
> > > > I'll get in touch with Jean-Jacques and see if he is up for a podcast
> > > > and
> > > > which language he would prefer to do it in.  I have just purchased his
> > > > book
> > > > today which is in French so shall try to become a little better
> > > > informed
> > > > apart him beyond his liaison with Liliane about which I have heard a
> > > > good
> > > > deal.  My interest to some extent with him and also Stephen Bann and
> > > > Hansjorg Mayer with whom I am now working on some things also would be
> > > > to
> > > > approach this from the perspective of language (pioneering poetic
> > > > movements)
> > > > so a little aside from the art-science-tech triangle. It may be another
> > > > channel perhaps waiting to be born.
> > > > 
> > > > B
> > > > 
> > > > B
> > > > 
> > > > On 6 June 2015 at 11:07, Annick Bureaud abureaud@gmail.com wrote:
> > > > 
> > > > > Hi Bronac
> > > > > 
> > > > > I am sorry to have missed this opening too, that's life.
> > > > > 
> > > > > I didn't know Jean-Jacques Lebel had been Liliane boy friend ;-)
> > > > > It would be really great to do a podcast for P&P with him. French
> > > > > would be
> > > > > nicer actually.
> > > > > I don't know Denise René nephew, but that could be interesting too.
> > > > > 
> > > > > Annick
> > > > > 
> > > > > Le 06/06/15 10:21, roger malina a écrit :
> > > > > 
> > > > > > bronac
> > > > > > 
> > > > > > taking the liberty of copying the pioneers team on creative
> > > > > > disturbance
> > > > > > about the good news of the two podcasts you are interested in doing
> > > > > > !!
> > > > > > as one of the producers of the channel YES you are welcome to do this
> > > > > > 
> > > > > > our end here in dallas poe johnson will be your interface in terms
> > > > > > of getting them edited/posted once you have them in the can=
> > > > > > we have been changing/improving the system and poe can get you
> > > > > > the latest instructions
> > > > > > 
> > > > > > roger
> > > > > > 
> > > > > > On Sat, Jun 6, 2015 at 9:20 AM, bronac ferran bronacf@gmail.com
> > > > > > wrote:
> > > > > > 
> > > > > > > Hallo Roger
> > > > > > > 
> > > > > > > Missed you at the Opening!
> > > > > > > 
> > > > > > > Liliane was in fab form - which was good to see. Her first boyfriend
> > > > > > > in Paris Jean Jacques Labelle came along and seemed to think the
> > > > > > > work
> > > > > > > was great!
> > > > > > > 
> > > > > > > Hope Spain and Portugal have been nice. I asked Jean Jacques (who
> > > > > > > did
> > > > > > > the first Happenings in France) if he would be willing to be
> > > > > > > interviewed - he seemed amenable in general to this - and I also
> > > > > > > asked
> > > > > > > Denise Rene's nephew yesterday if he would let me do an interview
> > > > > > > (his
> > > > > > > English is basic but good but we could do it in French if you or
> > > > > > > Fabrice were around sometime when I am back).
> > > > > > > 
> > > > > > > Look forward to a catch up anyway.
> > > > > > > 
> > > > > > > B
> > > > > > > 
> > > > > > > On 06/06/2015, roger malina rmalina@alum.mit.edu wrote:

_Copied from original issue: creativedisturbance/administrative#72_

**Comment by halclark** [comment]
_From @porteriffic on June 19, 2015 22:48_

I've contacted Bronac about this channel. Waiting to hear back.

**Comment by halclark** [comment]
_From @porteriffic on June 30, 2015 23:47_

Still have not heard from Bronac or Poe.

**Comment by halclark** [comment]
_From @porteriffic on July 5, 2015 22:54_

Heard back from Bronac. She will get back to be in the next two days.

**Comment by halclark** [comment]
_From @porteriffic on July 10, 2015 16:55_

Bronac is in the process of filling out forms and getting a podcast ready.

**Comment by porteriffic** [comment]
Still have not heard from Bronac. Sent an email on 7/31 to touch bases and see how everything is going.

_Update_: She responded. First expected podcast will be October 1st.

**Comment by porteriffic** [comment]
Will contact Bronac tomorrow if we still haven't received the first podcast by end of today (10/1)

**Comment by porteriffic** [comment]
Emailed Bronac (10/2)

**Comment by porteriffic** [comment]
Bronac injured her wrist and won't be able to make any podcasts until next year.

**Comment by porteriffic** [comment]
Added this to the tracking sheet in Google Drive.
