### ISSUE TITLE
Appoint First Creative Disturbers from Kickstarter Funds

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#148]
_From @rmalina on June 5, 2015 8:42_

i had very succesful meetings in lisbon with patricia correia, anna rita fonseca and sam meyler
they have accepted to be our first creative disturbers with three $1000 grants to crowd source content
their channel will be called "roots of curiosity- with a formal launch planned for october when they have a book coming out with the same title

stephanie-i dont know if you have time to do this before you leave ! but we need to put a formal
invitation packagte together tosend them with terms and contidions and also instructions on how to set up a new channel and all the cheat sheets etc

anyway lets discuss in a skype

roger

_Copied from original issue: creativedisturbance/administrative#66_

**Comment by halclark** [comment]
_From @heiwanalady on June 5, 2015 20:33_

@rmalina - I will try and do as much as I can before I leave! I'm glad the
meeting went well! How was Lisbon?!

**Comment by heiwanalady** [comment]
@rmalina Am transferring this knowledge to lina. We had a meeting today!

**Comment by linamoon** [comment]
Will discuss with Roger, etc: 
- Also reference: https://github.com/creativedisturbance/podcasts/issues/201
- Document for reference: International Student Grant FAQ Sheet https://drive.google.com/open?id=1VNt0YZGX59WKhNJk2Kmv_brSK5TcbjSzcqmNd67ASh0
