### ISSUE TITLE
Student Grant to Egyptian Student

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#150]
_From @rmalina on May 29, 2015 20:1_

podcast voice haytham nawar teaches at the american university in cairo egypt- he says he has a student that could produce some podcasts

haytham is at Haytham Nawar haythamnawar@gmail.com

yvan tina is a liaison as haytham just did a podcast on virtual africa channel

josephine you need to discuss this with stephanie as this would be implemented
after she leaves but you can contact haytham

roger

_Copied from original issue: creativedisturbance/administrative#59_

**Comment by halclark** [comment]
_From @porteriffic on June 2, 2015 1:37_

@heiwanalady Maybe we can Skype or meet up this week? I'm flexible.

**Comment by halclark** [comment]
_From @heiwanalady on June 4, 2015 17:51_

@porteriffic I'm available! just let me know a time.

**Comment by halclark** [comment]
_From @porteriffic on June 9, 2015 19:8_

@heiwanalady Sorry for the late response. Can we Skype tomorrow morning? Around 10?

**Comment by halclark** [comment]
_From @heiwanalady on June 9, 2015 23:5_

@porteriffic sure, that should work for me.

**Comment by halclark** [comment]
_From @rmalina on June 10, 2015 6:38_

i am travelling today and cant do a skype but maybe you can go ahead and keep this moving
roger

**Comment by halclark** [comment]
_From @heiwanalady on June 23, 2015 22:28_

**Just sent Nawar this email:**

Mr. Nawar, 

I work with Yvan Tina and Dr. Roger Malina on Creative Disturbance and am currently coordinating the perk fulfillments for our recent Kickstarter. I believe you mentioned you had an Egyptian student in mind as a potential recipient of our International Student Grant. I would love to discuss this further with you. 

We are in the middle of sculpting our student grant program's terms and conditions and welcome any feedback you might have. Here is a document detailing the current scope of the grant program - feel free to comment! We are also collaborating with a few Portuguese students in Lisbon on this and we'd be happy to connect you. We are very interested in producing content around the globe and welcome different disciplines and languages (we just celebrated International Polyglot Day on our website). 

Please let me know if you have some free time to chat this month and we can set up a Skype meeting! 

Best,
Stephanie Brisendine

**Comment by halclark** [comment]
_From @cassininazir on July 13, 2015 22:37_

@linamoon including you on this thread.

**Comment by rmalina** [comment]
please do not contact egyptian contact until you coordinate with yvan tina as he
is in charge of our collaboration with haytham
roger
@linamoon @halclark @yvantina

**Comment by linamoon** [comment]
Discussed with @yvantina; will be updated by Yvan as necessary.

**Comment by linamoon** [comment]
Discussed with @yvantina; will be updated by Yvan as necessary.

**Comment by linamoon** [comment]
We have forward movement on this - updates will now take place in the Tracking List in the CD International Student Grants folder to avoid redundancy
- https://drive.google.com/drive/folders/0B1tS6I_YV9uPfnRYUTlfbV8wQU41bUFkcUpadnpWWnZhVHVYRk92YWF2SnRuNmNyRDZjZ2M
