### ISSUE TITLE
Provide a demo of Echo360 

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#152]
_From @cassininazir on May 26, 2015 18:12_

Please get up to date on Echo360 by June 9. What that includes:
- A demo recording, which might take the form of a tutorial
- Screen captures
- Explore the interface and become knowledgable about how to use/troubleshoot

Include any questions you have about the system. 

Be ready to present in the Monday meeting on June 15. 

_Copied from original issue: creativedisturbance/administrative#56_

**Comment by halclark** [comment]
_From @amb141330 on May 26, 2015 18:28_

Will contact Echo360 at UT Dallas to setup a training seminar.

**Comment by halclark** [comment]
_From @cassininazir on May 26, 2015 18:30_

Email from Echo360 people:

Thank you for requesting an Echo 360 account. Your account has been created, and your username is cnazir. Please call extension 4900 to receive your password and login instructions from a member of the Echo 360 team. Once you have your password you may login here - https://utdechoapp01.utdallas.edu:8443/ess/login.jsp and change your password. At your earliest convenience we strongly encourage you to setup an individual training session with one of our staff. We will happily work around your schedule. If you have any questions, feel free to email us at Echo360@utdallas.edu or call us at extension 4900.

**Please ring the number (972-883-4900) to get password and login info.**

**Comment by halclark** [comment]
_From @amb141330 on June 3, 2015 22:2_

Called and got my information. The person who sets up the training was not in the office today so I sent an email. Will call again tomorrow.

**Comment by amb141330** [comment]
Training is done and Yvan has already used this for recording a video for Roger.
