### ISSUE TITLE
How can we record Jabber sessions

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#153]
_From @cassininazir on May 25, 2015 19:5_

Find out how we may record Jabber sessions and create a sheet for it. Let's discuss in our Tuesday session.

_Copied from original issue: creativedisturbance/administrative#54_

**Comment by halclark** [comment]
_From @amb141330 on May 26, 2015 18:34_

We can check and see if we can use FRAPS with Jabber sessions. 

http://stream-recorder.com/forum/record-save-capture-jabber-xmpp-video-chat-t9701.html

That link talks about two different options for recording those sessions as well.

**Comment by halclark** [comment]
_From @cassininazir on May 26, 2015 18:34_

Please connect with Brian Merlo by end of week on this issue.

**Comment by halclark** [comment]
_From @amb141330 on May 26, 2015 18:35_

Waiting to hear back from Brain.

**Comment by amb141330** [comment]
I talked to Brian about this at the beginning of the summer/end of the last semester and we can record these sessions, but it has to be something we schedule in advance. We'll have to bring it up to Brian again to find out who to email about setting that up if we still need to do this.

**Comment by amb141330** [comment]
Is this still something we are interested in? I don't see the practical application for this currently.

**Comment by rmalina** [comment]
ashton
i want us to be able to routinely video tape skype
or jabber discussions as well as video tape discussions
we need to really ramp up so everyone is trained
on this

including jabber recordings

roger

On Mon, Sep 14, 2015 at 11:44 AM, amb141330 notifications@github.com
wrote:

> Is this still something we are interested in? I don't see the practical
> application for this currently.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/153#issuecomment-140140898
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
I'll email Brian about recording Jabber sessions if we're still interested in doing this. We don't use it often, but I understand wanting to be able to.

**Comment by cassininazir** [comment]
Please provide an update when you have new information.

**Comment by amb141330** [comment]
No new information. Still haven't heard whether or not the recording through Jabber was successful.

**Comment by amb141330** [comment]
Jabber was not working last week due to the power outage bringing down the server so Brian was not able to give me an update here.

**Comment by amb141330** [comment]
In the new three ring binders, there is a section about video conferencing with instructions on how to record Jabber sessions
