### ISSUE TITLE
Create Hand-off Template for Students

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#154]
_From @cassininazir on May 22, 2015 19:30_

This should allow any of the lab students to be able to wrap up at the end of semesters effectively and transfer knowledge.

Initial thoughts on document outline:
- Scope
- Responsibilities, duties 
- Passwords
- Code
- ?? 

_Copied from original issue: creativedisturbance/administrative#53_

**Comment by cassininazir** [comment]
Putting this on hold for now.

**Comment by cassininazir** [comment]
Completed. Online at [CD 1.7 Employee Handoff Document](https://docs.google.com/document/d/1JTv54-zNFzCF39g5ZOLbPydxAbumYiFoIPvnEIrTu1w/edit?usp=drive_web).
