### ISSUE TITLE
Create a Style Guide for Dropbox Procedure

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#156]
_From @porteriffic on May 15, 2015 22:11_

How to share folders with Producers. How to create a new folder for a channel. What goes in the folder. So on and so forth.

_Copied from original issue: creativedisturbance/administrative#48_

**Comment by halclark** [comment]
_From @porteriffic on May 26, 2015 2:17_

Will be cleaning up DropBox this week and transitioning Producers over to new folders. Will work on Style Guide once that has been completed

**Comment by halclark** [comment]
_From @porteriffic on May 27, 2015 3:2_

@cassininazir Would like your feedback. I've created the new folders but the only way I can share is if Dropbox sends an invite. For example, Roger's a producer for multiple channels, he'll multiple emails from Dropbox for each invite I send to him. Not sure how to handle this...

**Comment by halclark** [comment]
_From @cassininazir on May 27, 2015 3:6_

I think that Roger will be the exception. I can't think of any other producers in the same boat, except perhaps Yvan. Because they are part of the project team, we can setup a folder for them specifically.

**Comment by halclark** [comment]
_From @porteriffic on June 2, 2015 2:14_

@cassininazir I've assigned Kyle to start helping the team manage Dropbox. I will help send out the emails but after that I will need someone to take over Dropbox issues.

**Comment by porteriffic** [comment]
Located in the "Community Building Folder" under Production Team. [CD 2.2.6.2 Dropbox Procedure](https://docs.google.com/document/d/1lgiyo9CN_yjVcxMHKZD_DVX7MfZh0y35illbr0M767g/edit)
