### ISSUE TITLE
Create a Style Guide for Emails

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#157]
_From @porteriffic on May 14, 2015 22:6_

Need a template for sending emails out to the community.

Template for upcoming events, podcasts, metrics, coordinating, etc.

_Copied from original issue: creativedisturbance/administrative#47_

**Comment by halclark** [comment]
_From @porteriffic on May 18, 2015 19:30_

Use Cassini's redesigns

**Comment by halclark** [comment]
_From @cassininazir on May 19, 2015 4:9_

Working on final version of write up here is example of template so far. 

![template](https://cloud.githubusercontent.com/assets/1661430/7695280/e5702ba6-fdb2-11e4-8c31-2490a199f298.jpg)

**Comment by halclark** [comment]
_From @porteriffic on May 19, 2015 22:5_

Created a brief guideline. I've asked Stephanie to take a look when she gets a chance. @cassininazir You are welcome to add to it as well. 

[CD 2.2.6.4 Emails to Producers and Voices](https://docs.google.com/document/d/1l8OuGDLnWTP17HUtzj3A_7UTVcc4_Kb9T61QKRScG-c/edit)

**Comment by halclark** [comment]
_From @cassininazir on May 19, 2015 22:10_

This is very good. Uploaded the intriguingly awfully titled [How to Create Email Newsletters that Don't Suck](https://drive.google.com/open?id=0BwvQhnxKj6jFcV9QRnpFRmx5NmM&authuser=0) from HubSpot to Google docs. Recommend reviewing that as well.

**Comment by porteriffic** [comment]
[CD 2.2.6.4 Emails to Producers and Voices](https://docs.google.com/document/d/1l8OuGDLnWTP17HUtzj3A_7UTVcc4_Kb9T61QKRScG-c/edit) can be accessed in CD 2.2.6 Community Building folder. Refer to that document whenever you need assistance emailing the community.
