### ISSUE TITLE
Email Ann Maria De Mars (Ronda Rousey's mom)

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#158]
_From @porteriffic on April 28, 2015 1:54_

Ask Anna Maria De Mars if she can talk about STEM careers??? Possible podcasts?

_Copied from original issue: creativedisturbance/administrative#30_

**Comment by halclark** [comment]
_From @porteriffic on April 28, 2015 19:45_

annmaria@thejuliagroup.com

**Comment by halclark** [comment]
_From @cassininazir on April 29, 2015 3:0_

Thanks, @kkondas for finding the email address! @porteriffic would love to see this happen.

**Comment by halclark** [comment]
_From @porteriffic on April 29, 2015 3:53_

Yes, thank you, @kkondas! This will be my summer project! :+1:

**Comment by halclark** [comment]
_From @porteriffic on May 19, 2015 22:15_

I'll email her once I get my official Creative Disturbance email address linked with my current one so I don't look like some creeper.

**Comment by porteriffic** [comment]
http://www.thejuliagroup.com/blog/
http://www.7generationgames.com/about/our-team-2/annmaria-de-mars/

**Comment by porteriffic** [comment]
Email sent on 10/1. That was the most nerve-racking email I've ever sent.
