### ISSUE TITLE
Proposal to do Yuri's Night (April 12, 2016)

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#159]
_From @rmalina on April 27, 2015 13:58_

colleagues

AUDIOLATS space exploration and the arts producers are proposing a theme week
for 12 april 2016 

on the topic of the artist as space explorer

roger

About Yuri’s Night
Our Roots

Yuri’s Night is a global celebration of humanity’s past, present, and future in space. Yuri’s Night parties and events are held around the world every April in commemoration of Yuri Gagarin becoming the first human to venture into space on April 12, 1961, and the inaugural launch of the first Space Shuttle on April 12, 1981.

Yuri’s Night events combine space-themed partying with education and outreach. These events can range from an all-night mix of techno and technology at a NASA Center, to a movie showing and stargazing at your local college, to a gathering of friends at a bar or barbecue.

In 2011, the 50th anniversary of human spaceflight, over 100,000 people attended 567 officially-recognized events in 75 countries on all 7 continents, while tens of thousands more watched the 12-hour live Yuri’s Night Global Webcast and participated online in the virtual world of Second Life.

Since 2001, Yuri’s Night has:

Featured talks and presentations by Ray Bradbury, Will Wright, George Takei, Richard Garriott, Anousheh Ansari, and many others
Been celebrated at the South Pole, Hayden Planetarium, and in orbit on the International Space Station
Planted hundreds of “moon trees” around the world in collaboration with American Forests
Received the “Best Presentation of Space” award from the Space Frontier Foundation
Trained the next generation of space leaders for organizations such as the National Space Society, Virgin Galactic, and Space Florida
Anyone can start a Yuri’s Night event, and it’s completely free. Are you interested? Register an event today →

Our Mission

The mission of Yuri’s Night is to use the excitement and inspiration of space as a catalyst for educating and developing the next generation of explorers. We fulfill this mission through a commitment to:

empowering leaders: in making a difference, pursuing their dreams, and inspiring others to do the same.
building communities: working shoulder to shoulder on visionary projects, overcoming barriers and finding common ground.
bridging cultures: be they geographic, social or technical, we are all learning to speak each other’s languages.
encouraging science literacy: bringing people hands-on experiences and passionate storytelling to explore their physical world and nurture their love of learning.
promoting a sustainable and peaceful future: sharing “the Overview Effect” with all people, inspiring them to take ownership of our home planet and the future of humanity.
Our Team

The Yuri’s Night Global Executive Team is a small but dedicated group of volunteers distributed around the world. The Global Team is the group that runs the Yuri’s Night website and Worldwide Event List, newsletters, social media efforts, and the higher level global tasks. Learn more about the Global Team →

_Copied from original issue: creativedisturbance/administrative#27_

**Comment by rmalina** [comment]
hal
@ChazLilly 
hal- this needs to be coordinated with chaz lilly who will work with annick bureaud
on organising the content for yuri's night on  CD next april
chaz is producing an arts and space exploration ebook that will be out by
then and we can do podcasts with some of the article authors

roger
