### ISSUE TITLE
Community Building Plan

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#160]
_From @porteriffic on February 18, 2015 0:48_

Focus on fleshing out CBP. (Especially for producers). Include frequency of contacting producers (and team).

_Copied from original issue: creativedisturbance/administrative#1_

**Comment by halclark** [comment]
_From @porteriffic on March 2, 2015 18:39_

Work with Cassini, Vivek, and Chaz.

**Comment by halclark** [comment]
_From @porteriffic on May 13, 2015 2:9_

Tag @mitpress on Twitter so they can retweet.

**Comment by halclark** [comment]
_From @porteriffic on May 13, 2015 23:15_

Dedicate a section to Social Media Prep

**Comment by halclark** [comment]
_From @porteriffic on May 13, 2015 23:15_

Located in Google Drive. [CD 2.1.5 Community Building Plan](https://docs.google.com/document/d/1qOUdULI8sq3-Lls5S6obyZDaVqEG_tt4aHdpKh75S5w/edit).

**Comment by halclark** [comment]
_From @porteriffic on May 23, 2015 1:58_

Added a few more things. Would like to sit down with @cassininazir to talk about it more.

**Comment by porteriffic** [comment]
Still working of CBP. It is continuously growing as we're trying to implement actions.

**Comment by porteriffic** [comment]
Will narrow down "brainstorming" to NEW [Community Building Plan doc](https://docs.google.com/document/d/1QcRZOlyIHZyF7UXuvF3raP9wiE7oIHcOgdYqy0ES74E/edit)
