### ISSUE TITLE
World Day for Audiovisual Heritage

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#162]
Contact Frank Dufour about this event ASAP.

Describe what we'd like from him and ask him for possible podcast/ideas. 
Coordinate with Josephine and/or @cassininazir. Refer to [CD 2.2.10 Feature Day Action Plan](https://docs.google.com/document/d/1lA0UaMrmaxg-rOLGox4mCvvn_tB3DBqwo5PoWWsPgZA/edit#) for more info.

**Comment by halclark** [comment]
moved  to another issue
