### ISSUE TITLE
publish olats podcasts one a week for next two weeks

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#163]
corey
can you coordinate with yvan to get these podcasts into the excel
and then published

they need NO editing needed
as with me i suggest you go ahead now and schedule these one a week

@yvantina 
roger

Yvan Hello,

I have sent the forms for the 2 Trust Me, I'M An Artist podcasts that I did in London in April.
I have sent you the podcasts themselves earlier this week.
You already have my picture as producer.

I have asked the two guests to fill the release forms. I can't know if they have done it or not.

Martin O'Brien form does not have a picture of the guest. Do not wait that we have received it to upload the podcast.

I didn't know what was meant on the form by the "image for the podcast". Is this new ? I was used to the picture of the people, is there a new format ?

Those podcasts are READY. They do not need editing.

They go under AUDIOLATS and META-LIFE.

I would like to have them uploaded on CD before the next event so that I can do some communication about them before announcing the next event and also updating the Olats website, the TMIAA website and the blog.
That is before September 1st (the next event is September 11th).
I am fully aware that this is rather short considering that we are in the middle of the Summer break but as there is no need for editing may be the Dallas team can make it.

Thank you for keeping me posted and sending me the urls so that I can link them on the Olats website.

**Comment by yvantina** [comment]
@coreysmart92 Corey, any update for these two podcasts  ?  I can't find them on the production tracking sheet.. Can we publish one this week and the other one next week ?
Please let me know if you have any question

**Comment by yvantina** [comment]
Also these podcasts should go both to Audiolats AND Meta-Life. Thanks

**Comment by porteriffic** [comment]
@yvantina I believe these podcasts are now on the tracking sheet. Hopefully it will be FULLY updated by Monday (8/3).

**Comment by yvantina** [comment]
Okay . can you please have them published the same week ? I just received an inquiry from Annick. 
thank you !

**Comment by coreysmart92** [comment]
Closing: I have scheduled them both to publish this week. (8/3/15)
