### ISSUE TITLE
for monday meeting- metrics on whether we are posting 5 podcasts a week

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#164]
corey

for the monday meeting can you present a summary of how many podcasts
a week you have published each week during the summer- say since may 1

and whether you have been publishing on the average 5 a week

if you have been publishing 5 a week we have met our goal for summer weeks

if not lets discuss how you can make sure that for the rest of the summer
at leat 5 podcasts a week go up each week

this is your responsibility to meet this goal- get the team to work !

then lets discuss how for the fall semester we can star publishing
6 a week- this means building up a backlog

i now have recorded ten podcasts so thats a back log of one a week
for the next ten weeks !!!!

roger
@cassininazir

**Comment by coreysmart92** [comment]
Closing: I have added it to the meeting and we will discuss it on 8/3/15. (8/3/15)
