### ISSUE TITLE
new leonardo podcasts with tara deporte- please give priority

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#165]
corey
i just loaded two podcasts into the new leonardo's channel
with Tara DePorte

since this is with a woman guest can you give it priority to publish ahead
of all the podcasts i have loaded with male guests

thanks

also she is talking about the UN environmental conference COP 21 in december
which would be a natural theme for us

roger

**Comment by coreysmart92** [comment]
Closing: I have scheduled your podcast for editing and publishing. They will be published next week 8/10-8/16. (8/3/15)
