### ISSUE TITLE
nov/dec art and climate change month for COP 21

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#166]
hal

i have a strong recommendation that from nov 20 to dec 20 we do a month
on art and climate change- with susan erickson but also tara deporte-see details 
below

i have added to your document

roger

http://www.cop21.gouv.fr/en/cop21-cmp11/what-cop 

In 2015, France will be hosting and presiding the 21st Session of the Conference of the Parties to the United Nations Framework Convention on Climate Change (COP21/CMP11), otherwise known as “Paris 2015” from November 30th to December 11th. COP21 will be a crucial conference, as it needs to achieve a new international agreement on the climate, applicable to all countries, with the aim of keeping global warming below 2°C. France will therefore be playing a leading international role to ensure points of view converge and to facilitate the search for consensus by the United Nations, as well as within the European Union, which has a major role in climate negotiations.

tara deporte has agreed to let us stream her podcasts from her podcast web site
http://www.humanimpactsinstitute.org/#!inspire/cjg9

@coreysmart92 @cassininazir @porteriffic

**Comment by porteriffic** [comment]
This has been added to the Feature Day Document. Open issue for this feature sometime in September.
