### ISSUE TITLE
inform producers of where new forms are

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#167]
_From @rmalina on July 19, 2015 7:33_

pleaes inform the producers of where the forms are and ask them to report
any problems

anvit- where are you on being able to save incomplete forms ?
@anvit 

roger

tim
i totally apologise for this- you should have received an email as a producer
the forms are now at

http://creativedisturbance.org/forms

anvit is working on improving the forms -and also so you
can save partially completed forms to fill in later

if you have any suggestions for improving the forms
YELL

roger

On Sat, Jul 18, 2015 at 10:40 PM, tim perkis tim@perkis.com wrote:

> Josephine, Corey –
> 
> I couldnt access createdisturb.com – it seems to just go to some commercial
> domain parking page. Is that no longer the repository of forms to publish a
> new episode?
> 
> Well, in any case, I DO have a new episode, entitled "Poly-Stylistic
> Guitarist/Composer John Schott",  and the media file for it can be found at
> 
> http://noisypeople.net/audio/09_john_schott.mp3
> 
> cheers
> 
> Tim
> ---
> 
> tim perkis    tim@perkis.com       perkis.com     +1 510 717 3450
> ---
> 
> On Thu, Mar 19, 2015 at 6:32 PM, Josephine Porter porteriffic@gmail.com
> wrote:
> 
> > Hello Tim,
> > 
> > My name is Josephine Porter. I'm one of the audio editors/coordinators
> > here at Creative Disturbance. Roger passed along your email to me and we're
> > delighted to hear that you're interested in starting a channel with us!
> > 
> > Since you'll be starting a new channel you'll need to fill out a few
> > forms. You wont have to fill out this many each time you have a podcast. But
> > for now, you'll need to fill out the New Channel Proposal Form, New Producer
> > Request, and the Producer's Agreement.
> > 
> > For each podcast you want on your channel, you'll need to fill out the New
> > Podcast Info Form (so if you have 3 podcasts, you'll need to fill out 3
> > Podcast Info Forms). Last but not least, any voices featured in the podcast
> > outside of yourself will need to fill out a Guest Release Form.
> > 
> > Click here to access the forms.

_Copied from original issue: creativedisturbance/public-website#124_

**Comment by anvit** [comment]
@rmalina I'm working on them at the moment and I should be able to finish up the save functionality by the end of the day.

**Comment by coreysmart92** [comment]
I have sent out an email update everyone to the Wufoo forms locations. However I do not have access to the new forms. When the new forms are completed I can send out an email. (8/3/15)
Close: when the new forms are completed and an email is sent informing producers and voices

**Comment by coreysmart92** [comment]
Closing: This has been sent to producers and voices. I will reopen a new issue for this when the "New Forms" are completed. (9/1/15)
