### ISSUE TITLE
Update Virtual Africa Producers

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#168]
_From @yvantina on July 3, 2015 10:45_

Welcoming Marcus Neustetter on board ! @cassininazir @porteriffic @ChazLilly  @anvit  Do you mind updating this page http://creativedisturbance.org/channel/virtual-africa/  this way as Marcus is co-producing the channel with me now ?  "Hosted by Marcus Neustetter and Yvan Tina"
Please remove Roger's and Annick's name. Thank you !

_Copied from original issue: creativedisturbance/public-website#119_

**Comment by coreysmart92** [comment]
Closing: I checked and this has already been updated. (8/3/15)
