### ISSUE TITLE
New RAMI Channel

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#170]
_From @yvantina on May 26, 2015 21:26_

@cassininazir @heiwanalady @rmalina 
Cassini, I've been contacted by Renaud Vercey and Claudine Dussolier this morning for an inquiry about their channel (Stephanie created their logo over 3 months ago). So they have 2 new podcasts both in english and arabic that are ready to be edited/published and are wondering what is the next step..I thought it would be great release those podcasts during the polyglot week and to announce the creation of a new disturbance around the same period.. but have you received all the required documents they need to provide ? 

_Copied from original issue: creativedisturbance/public-website#116_

**Comment by halclark** [comment]
_From @heiwanalady on May 26, 2015 21:58_

Awesome! That's perfect. Let me know if they need help with anything
concerning their album artwork.

Best,
Stephanie

**Comment by halclark** [comment]
_From @cassininazir on May 27, 2015 5:15_

We've received the forms for the RAMI channel back in February so **we can create the channel**. We haven't yet received any forms for the podcasts. **Next step is to turn in forms for the two new podcasts.**

**Comment by halclark** [comment]
_From @yvantina on May 27, 2015 6:45_

Sounds great ! Thanks

**Comment by halclark** [comment]
_From @porteriffic on June 5, 2015 19:16_

I can start working on getting the channel up as soon as Monday.

**Comment by halclark** [comment]
_From @yvantina on June 18, 2015 22:7_

@porteriffic @heiwanalady @cassininazir @coreysmart92 @amb141330 
Josephine, any update on that ? can the RAMI channel be ready for next week ? I told them it would be up for polyglot day.. Also, did the sound team received all the forms for the podcasts ? meanwhile I suggest you create a new RAMI folder on Dropbox which would allow them to upload their own files without having to go through several emails.. they are a bit confused so far and we need to streamline the process..

**Comment by halclark** [comment]
RAMI channel is up

**Comment by halclark** [comment]
_From @rmalina on July 17, 2015 18:53_

the rami channel is already up
http://creativedisturbance.org/channel/rami/
roger

**Comment by porteriffic** [comment]
RAMI channel is up
