### ISSUE TITLE
Procedure for creating Splash page images

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#171]
_From @cassininazir on May 11, 2015 18:45_

Continue to add to [CD 2.1.5](https://docs.google.com/document/d/1ZcSPNNKoEBiKdFMP4lEb-QtYoLpFxI_Hg1qgKeDoerg/edit)

_Copied from original issue: creativedisturbance/public-website#109_

**Comment by cassininazir** [comment]
[CD 2.1.5](https://docs.google.com/document/d/1ZcSPNNKoEBiKdFMP4lEb-QtYoLpFxI_Hg1qgKeDoerg/edit) and [CD 5.1](https://docs.google.com/document/d/1I7wcy-BkpTK5QDva5prW8ZCNboTlYaNF2nq0uY0FQEk/edit) explain this.
