### ISSUE TITLE
Change update process for 'featured voices'

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#172]
_From @rmalina on May 8, 2015 17:26_

the 'featured voices' list is not getting up dated at the same time as the featured pocasts
is getting updated

suggest you modifiy process so that the featured voics are automatically updated with the featured podcasts and are those voices

roger

_Copied from original issue: creativedisturbance/public-website#107_

**Comment by halclark** [comment]
_From @porteriffic on May 8, 2015 22:2_

Voices must be updated manually. Will work with dev team to make it so that it is updated automatically.

**Comment by halclark** [comment]
_From @cassininazir on May 19, 2015 4:54_

@anvit am assigning this to you.

**Comment by anvit** [comment]
The 'featured' field is now checked by default every time a new podcast or voice is created. An old podcast/voice would still have to be manually unchecked so that only a limited number of voices/podcasts show up.
