### ISSUE TITLE
chrome compatibility

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#180]
_From @rmalina on March 30, 2015 3:56_

on line form doesnt work in chrome-make sure new form works on all browsers

_Copied from original issue: creativedisturbance/public-website#79_

**Comment by halclark** [comment]
_From @cassininazir on March 30, 2015 14:35_

Will do testing to review this. Was this on your computer or reported from a producer/guest? Would like to reproduce the problem if possible.

**Comment by halclark** [comment]
_From @rmalina on March 30, 2015 15:15_

on my computer
roger

On Mon, Mar 30, 2015 at 9:35 AM, Cassini Nazir notifications@github.com
wrote:

> Will do testing to review this. Was this on your computer or reported from
> a producer/guest? Would like to reproduce the problem if possible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/public-website/issues/79#issuecomment-87703923
> .

## 

Roger F Malina
is in texas
1-510-853-2007

**Comment by cassininazir** [comment]
Closing this item. Re-open if this is still occurring.
