### ISSUE TITLE
language in podcast titles

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#181]
_From @rmalina on March 30, 2015 3:55_

we have a real problem that we dont indicate the language of each podcast when we list
it on featured page or under each channel list- its really stupid that you have to click on the podcast itself to figure out what language its in-can we indicate clearly in the TITLE of each podcast what language it is in
roger

_Copied from original issue: creativedisturbance/public-website#78_

**Comment by halclark** [comment]
_From @cassininazir on May 19, 2015 4:55_

@coreysmart92 can you review? Can you track down where this is written? If it's not in the tracking sheet, please add.

**Comment by halclark** [comment]
_From @coreysmart92 on June 3, 2015 16:29_

Closing.
The [CD 2.2.2.5 Posting a Completed Podcast](https://docs.google.com/document/d/124eiA3g5XaeDlbtN-yrAfTi9yVGz-2DwgWn5s0HqnlY/edit) has been updated.

**Comment by coreysmart92** [comment]
Standardized how to add Language to Podcast Title. Add ENG to end of English podcast.
Closing
