### ISSUE TITLE
Add page (or info) on how to submit a new podcast 

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#183]
_From @cassininazir on June 29, 2015 18:47_

How do new users or listeners submit a new podcast? Or a even new podcast idea? Create a page for individuals to submit (podcast, ideas) and contact us. 

_Copied from original issue: creativedisturbance/public-website#118_

**Comment by cassininazir** [comment]
@dylanorgeron Also putting this on hold, but assigning to you. Recommend where to place this on the website. This should appear on the public website.

**Comment by dylanorgeron** [comment]
is this for users with an account or for guests?

**Comment by rmalina** [comment]
I guess with account

**Comment by cassininazir** [comment]
Yes for those with accounts. This is for individuals who either (1) have an idea for a podcast that they'd like to submit or (2) for those who would like to submit a recorded podcast for inclusion on Voices from the Crowd channel.

**Comment by dylanorgeron** [comment]
We've discussed this as part of skedge development. Will most likely happen this summer during the redesign.

**Comment by amb141330** [comment]
Will include an instructional page/tutorial as a part of the redesign. Allowing for producers AND guests to submit podcasts.
