### ISSUE TITLE
Anthropodcast Channel Setup

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#184]
_From @cassininazir on March 9, 2015 20:21_

@yvantina let us know that we are expecting a new podcast from Switzerland. Have not received forms as of yet. 

_Copied from original issue: creativedisturbance/public-website#57_

**Comment by halclark** [comment]
_From @yvantina on March 9, 2015 20:49_

@cassininazir 
*\* A new Channel to be more precise - they will filled the forms as soon as
possible !
thanks !

yvan

2015-03-09 14:21 GMT-06:00 Cassini Nazir notifications@github.com:

> @yvantina https://github.com/yvantina let us know that we are expecting
> a new podcast from Switzerland. Have not received forms as of yet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/public-website/issues/57.

## 

check out this website for more information on art, synthetic biology and
a-life
http://synthbioart.texashats.org/

**Comment by halclark** [comment]
_From @cassininazir on May 19, 2015 5:18_

@yvantina any update on the Anthropodcast? May have missed an email about this.

**Comment by halclark** [comment]
_From @yvantina on May 19, 2015 6:42_

@rmalina @cassininazir  I sent him a reminder few days ago, given he said he would get the forms filled about two months ago... but Jonathan never followed up with tangible actions ! so..still waiting...

**Comment by halclark** [comment]
_From @cassininazir on June 25, 2015 21:11_

Unassigning Vivek from this task. Leaving this open in case the channel forms.

**Comment by porteriffic** [comment]
@yvantina Any word on setting this channel up? I can contact these people and maybe give them a nudge?

**Comment by yvantina** [comment]
Yes please go ahead. Haven't heard back from them since March though

**Comment by porteriffic** [comment]
@yvantina If I can get the contact info, that would be great!

**Comment by yvantina** [comment]
sorry for the slow answer

Jonathan Maitrot >> webmaster@voyagecast.ch

http://www.anthropodcast.fr/

2015-08-11 16:32 GMT-05:00 porteriffic notifications@github.com:

> @yvantina https://github.com/yvantina If I can get the contact info,
> that would be great!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/184#issuecomment-130084301
> .

## 

check out this website for more information on art, synthetic biology and
a-life
http://synthbioart.texashats.org/

**Comment by porteriffic** [comment]
Emailed Jonathan. Waiting to hear back (8/25).

**Comment by porteriffic** [comment]
Still have not heard back. (8/31). Putting on hold.

**Comment by rmalina** [comment]
i future copy me on this kind of email with no producers so i can chime in
can you send me the email you send them ?

roger

On Mon, Aug 31, 2015 at 11:45 AM, porteriffic notifications@github.com
wrote:

> Still have not heard back. (8/31). Putting on hold.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/184#issuecomment-136425115
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by porteriffic** [comment]
Finally got a response (9/4). Here's what he said:

---

Hello Josephine.

Yes, we where interesting, but I've read all of the conditions to be in Creative Disturbance, and it was a lot of things, complicated. Like the fact we must have like a contract with all of our host, we can't do that, it's to complicated and we made interview with Skype, we don't meet all of our guest. 

Creative Disturbance make a good job, for sure, and we are interesting to be a part in the project, but we are just two to work in the project, with a lot of work, and we can't spend hours just to have a channel. It's possible to have a more simple way to do that ? 

Sorry for my bad English, and I hope we can work together !

Best,
Jonathan

---

So it seems with all the forms and guest release forms that it's a bit complicated for him, especially since his English is not very good. I think he may be overthinking it or getting things confused, but I understand everything can seem overwhelming for a potential producer.

**Comment by yvantina** [comment]
if we talk about it during next meeting I can write him an email afterwards to try to remove his fears and complexes..

**Comment by porteriffic** [comment]
@yvantina Feel free to contact him. We can discuss at the meeting on Monday at 1pm. Will you be there?

**Comment by yvantina** [comment]
Yes. Will do

**Comment by rmalina** [comment]
josephine
talk to cassini
we can now do an aggregation without getting
them to resubmit their podcasts

roger

On Sat, Sep 12, 2015 at 8:51 PM, yvantina notifications@github.com wrote:

> Yes. Will do
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/184#issuecomment-139838043
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
Their website no longer exists. Closing this issue
