### ISSUE TITLE
Draft pages for "Voices" and "New Post"

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#185]
_From @porteriffic on March 6, 2015 2:44_

Not sure if this is just happening to me, but each time I scroll to the bottom of the page when posting a "Voice" or a "New Post", I am not able to scroll back up. This has happened each time I do this. Is this just my stupid computer? I don't have any page scrolling issues on any other site. Just on WordPress stuff. Is anyone else having this issue?

_Copied from original issue: creativedisturbance/public-website#55_

**Comment by halclark** [comment]
_From @vivraman on March 6, 2015 2:55_

it only happens when you update the picture specifically, accessing the
media section while editing a voice or podcast or channel causes it to
disappear

**Comment by halclark** [comment]
_From @vivraman on March 6, 2015 2:56_

in other news Nah its not just you

**Comment by halclark** [comment]
_From @porteriffic on March 9, 2015 18:15_

Gotcha! Thank you!

**Comment by halclark** [comment]
_From @sayloo on March 9, 2015 18:29_

This is because of the "Transposh" (Language Translation)  plugin which is basically trying to translate the image along with the text. I am not sure if we can avoid this.
If possible, I'll try to come up with a decent workaround.

**Comment by halclark** [comment]
_From @cassininazir on March 9, 2015 21:59_

We may not be able to fully fix. One workaround to the not being able to scroll issue:

Hit Cmd (or Control on Windows) + F and do a search for the word �Publish�; usually pulls you back to the top of the page and allows you to save the document or as a drafty.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by porteriffic** [comment]
Issue resolved a LONG time ago.
