### ISSUE TITLE
Community Building via Buddypress

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#186]
_From @cassininazir on March 3, 2015 17:54_

BuddyPress plugin has been installed on the production server. http://buddypress.com

This task is to 
1. Get Buddypress working! 
2. Move current users from WP Members to BuddyPress
3. Create interactions among community members 

_Copied from original issue: creativedisturbance/public-website#53_

**Comment by halclark** [comment]
_From @cassininazir on April 21, 2015 18:1_

This would also include:
1. Registration - New members would register through BuddyPress
2. Confirmation Screen - What page comes up after someone creates an account? 
3. Emails - What email(s) get pushed after account creation?

**Comment by cassininazir** [comment]
This will handled by Skedge system
