### ISSUE TITLE
Usage Patterns

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#187]
_From @cassininazir on March 3, 2015 17:54_

_From @cassininazir on January 30, 2015 19:57_
- People who come to the website to listen on mobile devices (home page has to scroll a great deal)
- Title and descriptions of Non-English podcasts should be written in the language podcast was written in

_Copied from original issue: cassininazir/creativedisturbance#73_

_Copied from original issue: creativedisturbance/public-website#50_

**Comment by porteriffic** [comment]
Not sure how to handle this @cassininazir. "People who come to the website to listen on mobile devices (home page has to scroll a great deal)". I think Google Analytics can track this? Should we include in metrics?

 I believe we're already labeling podcasts in the language spoken (English and Non-English).

**Comment by amb141330** [comment]
The website is being redesigned and podcasts are now titled in the language they are produced in.
