### ISSUE TITLE
Create Design Process and Principle for Generating New Album Art

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#188]
_From @cassininazir on March 2, 2015 22:11_

_From @cassininazir on February 2, 2015 17:13_

_Copied from original issue: cassininazir/creativedisturbance#76_

_Copied from original issue: creativedisturbance/public-website#48_

**Comment by linamoon** [comment]
Documents started by @cassininazir: 
- CD 5.1 Brand Standards https://docs.google.com/document/d/1I7wcy-BkpTK5QDva5prW8ZCNboTlYaNF2nq0uY0FQEk/edit?usp=sharing and 
- CD 2.1.5 Images for Creative Disturbance https://drive.google.com/open?id=1ZcSPNNKoEBiKdFMP4lEb-QtYoLpFxI_Hg1qgKeDoerg 

Will continue drafting.
