### ISSUE TITLE
Improve 404 Error Page

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#189]
_From @cassininazir on March 2, 2015 22:11_

_From @cassininazir on February 2, 2015 18:26_

Current 404 Page says "You Broke the Internet" but doesn't help users get to what they were looking for. Perhaps add:
- Search
- Recent podcasts

_Copied from original issue: cassininazir/creativedisturbance#84_

_Copied from original issue: creativedisturbance/public-website#46_

**Comment by anvit** [comment]
Added search bar and recent podcasts to production server's 404 page

**Comment by cassininazir** [comment]
Thanks for these updates. A few small changes:

The page needs to be more friendly:
-   Remove the default error title from "404: Page not Found" do this also for 500, 503, etc page
-   Change "Page not found" to a better title
-   Increase size of search box width to double what it is currently
-   Add below the search box "Let us know about this error. Email us at feedback@creativedisturbance.org"

Cassini

**Comment by anvit** [comment]
Completed!
