### ISSUE TITLE
Channel Subscriptions for Users

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#190]
_From @cassininazir on March 2, 2015 22:10_

_From @vivraman on February 9, 2015 17:49_

Develop a way for specific users to subscribe to channels that they wish to listen to. The user would be notified every time the channel uploads a new podcast. 

_Copied from original issue: cassininazir/creativedisturbance#90_

_Copied from original issue: creativedisturbance/public-website#45_

**Comment by amb141330** [comment]
This is an old issue. Dylan if you'd like to close it you can, I've setup subdomains for all the channels, but it's a work in progress. Feel free to close.
