### ISSUE TITLE
Podcast Categorization

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#191]
_From @cassininazir on March 2, 2015 22:10_

_From @cassininazir on February 9, 2015 20:36_

Alpha
Language
Newest
By most famous
Most interesting
Most discussed
Most forwarded
Least ?

_Copied from original issue: cassininazir/creativedisturbance#95_

_Copied from original issue: creativedisturbance/public-website#43_

**Comment by cassininazir** [comment]
This should be a simple sort. @anvit assigning to you.

**Comment by dylanorgeron** [comment]
@cassininazir 
would this be something we should incorporate into the CD redsign or should i take care of it now?

**Comment by cassininazir** [comment]
There's little immediate value added. Would rather you handle this with the redesign. Putting this on hold for now.
