### ISSUE TITLE
Create Communication Plan

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#193]
_From @cassininazir on March 2, 2015 22:9_

_From @cassininazir on January 22, 2015 18:29_
- Identify our methods of communication (email, website, social media, etc)
- Frequency of communication
- Methods of communication during the Podcast Production Process

_Copied from original issue: cassininazir/creativedisturbance#43_

_Copied from original issue: creativedisturbance/public-website#39_

**Comment by cassininazir** [comment]
Closing this issue. Will address with the online scheduler.
