### ISSUE TITLE
2 virtual africa podcasts in Gdrive 

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#196]
@coreysmart92 @porteriffic @halclark @amb141330 
Just wanted to have an update on the TWO podcats (with Koffi Sename) I have uploaded on Gdrive 2 weeks ago as I don't see them on your production tracking sheet..The podcasts have been uploaded on Gdrive as we couldn't access Dropbox back in the time.. Please edit and post as soon as you can. Thank you !

**Comment by yvantina** [comment]
The podcasts have been uploaded on Dropbox as well

**Comment by porteriffic** [comment]
@yvantina I see the podcasts in the GDrive. Is there a New Podcast form for these podcasts? I see the guest release form but I couldn't find a New Podcast form. That might be why it's not on the tracking sheet. We use the forms to look for upcoming podcasts.

**Comment by yvantina** [comment]
These podcasts have been uploaded to dropbox as well. Same files. I've
filled out two info forms so don't understand why you can't find them. Will
forward in another msg

**Comment by yvantina** [comment]
TITLE: FabCamp, W.Afate, Woelab !

This is confirmation that you have uploaded a new Podcast for you Creative Disturbance Channel.

CREATIVE DISTURBANCE - New Podcast Info Form
Channel Name \*  
Virtual Africa
Producer's Name \*       yvan tina
Producer's Email \*      yvantina@gmail.com
Podcast Title \*  
FabCamp, W.Afate, Woelab !

Short Description of this Podcast \*  
Le WɔɛLab compte probablement parmi les rares fablabs aujourd’hui présents sur le continent. Le “premier espace africain de démocratie technologique”, situé à Lomé, au Togo, est un “espace d'innovation partagée où s'élabore au quotidien de nouvelles approches de la collaboration productive vertueuse en contexte africain.” Ses membres sont à l’origine de W.Afate, une imprimante 3D réalisée à partir de déchets électroniques.

Key Words for this Podcast \*  
Low-High Tech, Imprimante 3D, Fablab, Camp

Date of Recording \*     Monday, July 6, 2015
Has the sound file been uploaded to CD Google Docs under "Podcasts-Need Editing"? \*     

```
Yes
```

Method of Recording this Podcast \*  
Skype
Estimated Length of Podcast (in Minutes)  
18
Primary Language of this Podcast \*  
French
Website (if any) specific to this Podcast   http://www.woelabo.com/wafate 
Guest \*  
Koffi Sénamé
Short Bio of Guest \*    

Architecte et anthropologue de formation, Sénamé explore depuis des années, la possibilité d’un fonds commun symbolique aux espaces anciens africains et son potentiel de questionnement de la contemporanéité. Après une expérience dans la construction humanitaire, il fonde la plateforme L’Africaine d’architecture sur la ligne « Modernité ancrée » dont l’ambition est de fournir les moyens conceptuels d’une alternative architecturale valorisant des canons, esthétiques, ressources et dynamiques du cru. Il devient le promotteur de la vision d’un vernaculaire numérique émergent, en 2012 quand il croit identifier une correspondance entre l’”Ethique Hacker” et les valeurs des sociétés traditionnelles africaines. Le concept #LowHighTech nait alors pour souligner cette proximité et favoriser une approche originale de la technologie qui la rendrait accessible aux couches les plus modestes. Le projet de smart cité à l’afriacine « Hubcité »; le WoeLab (premier Espace africain de Démocratie Technologique) et la W.Afate (première imprimante 3D africaine, entièrement construite en déchets informatique) sont aujourd’hui les meilleurs ambassadeurs de cette vision de société. Sénamé dirige l'incubateur WoeLab qui est devenu un lieu atypique qui rend possible la mutualisation de ressources et le brassage de populations diverses adoptant des usages à faible empreinte environnementale.
Sénamé Koffi Agbodjinou est le maître d’oeuvre du projet de l’Ecole Tammari, complexe scolaire pour 200 enfants réalisé en terre crue et techniques mixtes, avec les bâtisseurs traditionnels betammaribe et la communauté du village de Koulangou (Contexte culturel tammari- Patrimoine mondial de l’Unesco/ 2006).
Photo of Guest (preferably square and no less than 400 x 400 pixels)    koffi_sename1.png 394.25 kB · png
Email of Guest \*        contact@lafricainedarchitecture.com
Did the Guest(s) complete a Guest Release Form(s)? \*        

```
Yes
```

Guest's Website (if any)    http://www.woelabo.com/ 
May CD publish Guest's website (if any)?    

```
Yes
```

This email notification is powered by Wufoo, the free online form builder.
Make your own HTML forms for free at wufoo.com
Get Started!

**Comment by yvantina** [comment]
TITLE:  L'Africaine d'architecture et le style néo-vernaculaire

This is confirmation that you have uploaded a new Podcast for you Creative Disturbance Channel.

CREATIVE DISTURBANCE - New Podcast Info Form
Channel Name \*  
Virtual Africa
Producer's Name \*       yvan tina
Producer's Email \*      yvantina@gmail.com

Podcast Title \*  
L'Africaine d'architecture et le style néo-vernaculaire

Short Description of this Podcast \*  
Ce podcast est la première partie d’un entretien avec Koffi Sénamé, architecte et anthropologue de nationalité togolaise, fondateur de l’espace de démocratisation technologique Woelab à Lomé, dans lequel nous évoquons des questions liées à l’urbanisme et à l’architecture néo-vernaculaire en particulier.

Key Words for this Podcast \*  
ville, dispositif, néo-vernaculaire, Hassan Fathy

Date of Recording \*     Monday, July 6, 2015
Has the sound file been uploaded to CD Google Docs under "Podcasts-Need Editing"? \*     

```
Yes
```

Method of Recording this Podcast \*  
Skype
Estimated Length of Podcast (in Minutes)  
14
Primary Language of this Podcast \*  
French
Website (if any) specific to this Podcast   http://www.lafricainedarchitecture.com/ 

Guest \*  
Koffi Sénamé

Short Bio of Guest \*    

Architecte et anthropologue de formation, Sénamé explore depuis des années, la possibilité d’un fonds commun symbolique aux espaces anciens africains et son potentiel de questionnement de la contemporanéité. Après une expérience dans la construction humanitaire, il fonde la plateforme L’Africaine d’architecture sur la ligne « Modernité ancrée » dont l’ambition est de fournir les moyens conceptuels d’une alternative architecturale valorisant des canons, esthétiques, ressources et dynamiques du cru. Il devient le promotteur de la vision d’un vernaculaire numérique émergent, en 2012 quand il croit identifier une correspondance entre l’”Ethique Hacker” et les valeurs des sociétés traditionnelles africaines. Le concept #LowHighTech nait alors pour souligner cette proximité et favoriser une approche originale de la technologie qui la rendrait accessible aux couches les plus modestes. Le projet de smart cité à l’afriacine « Hubcité »; le WoeLab (premier Espace africain de Démocratie Technologique) et la W.Afate (première imprimante 3D africaine, entièrement construite en déchets informatique) sont aujourd’hui les meilleurs ambassadeurs de cette vision de société. Sénamé dirige l'incubateur WoeLab qui est devenu un lieu atypique qui rend possible la mutualisation de ressources et le brassage de populations diverses adoptant des usages à faible empreinte environnementale.
Sénamé Koffi Agbodjinou est le maître d’oeuvre du projet de l’Ecole Tammari, complexe scolaire pour 200 enfants réalisé en terre crue et techniques mixtes, avec les bâtisseurs traditionnels betammaribe et la communauté du village de Koulangou (Contexte culturel tammari- Patrimoine mondial de l’Unesco/ 2006).
Photo of Guest (preferably square and no less than 400 x 400 pixels)    koffi_sename.png 394.25 kB · png
Email of Guest \*        contact@lafricainedarchitecture.com
Did the Guest(s) complete a Guest Release Form(s)? \*        

```
Yes
```

Guest's Website (if any)    http://www.lafricainedarchitecture.com/ 
May CD publish Guest's website (if any)?    

```
Yes
```

This email notification is powered by Wufoo, the free online form builder.
Make your own HTML forms for free at wufoo.com
Get Started!

**Comment by yvantina** [comment]
![koffi sename](https://cloud.githubusercontent.com/assets/10967939/9021598/e686b4a0-380f-11e5-9f9f-032da1e876db.png)

**Comment by coreysmart92** [comment]
Sorry for the delay. I have scheduled them to be edited and published. Let me know if there is anything else I can do. (8/3/15)
Close: When podcasts are published

**Comment by yvantina** [comment]
Corey
Please use the description I used on github for those two podcasts. There's
a small change with the original one (podcast form)
thank you

**Comment by coreysmart92** [comment]
Closing:
They have both been published. (8/25/15)
