### ISSUE TITLE
poor netiquette

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#197]
corey
thanks for sending this email out
Dear Producers and Guests,
It has been brought to our attention that the links to the Wufoo forms are not working. Here are the updated links for Creative Disturbance: New Podcast Info Form, Guest Release Form, New Channel Proposal Form. Please inform us if there are any continuing problems.
Sincerely Creative Disturbance

BUT you put the WHOLE LIST visible in the cc list- so i got an email with two pages of email addresses
this is bad netiquette

when you send an email to a list put all the names in the bcc ( blind cc) on the email so everyone doesnt get the whole email- most people will just delete before reading all that garbage

next time you send an email to a distribution list please put the cc list in the bcc blind list
so everyone isnt deluged with the list of all the email addresses

roger

**Comment by rmalina** [comment]
corey
i got this complaint from a person you sent our cc lst to

roger

Roger-

Never send these by CC

ALWAYS by BCC

It's not nice to have my email send out to 2 thousand strangers!!!

**Comment by porteriffic** [comment]
Refer to [CD 2.2.6.4 Emails to Producers and Voices](https://docs.google.com/document/d/1l8OuGDLnWTP17HUtzj3A_7UTVcc4_Kb9T61QKRScG-c/edit) if you are unsure about sending emails out to the community.
