### ISSUE TITLE
wrong email list

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#198]
corey

this is the email list you sent that annoucement out to

who did you mean to send it to ?

it includes producers, voices, kickstarter donors

i think you meant to send this out to the producers email list ?
in which case you sent it to the wrong list

roger

a.shelby.c@gmail.com
(a.shelby.c@gmail.com)
Abdo Nawar
Adam Bayacal
Adrian Avendaño
Al Banda
Ale de la Puente
Alexander Djerassi (gmail.com)
alisanazir@yahoo.com
(alisanazir@yahoo.com)
Amal Alayan
Amal Shafek
Alan Malina (mail.eunet.pt)
Amanda Sparling (aksparling@gmail.com)
Amy Ho (amy.ho576@gmail.com)
Ana Rita Fonseca (neuro.fchampalimaud.org)
andersoncraig@live.com
Andrew Scott (axs123130@utdallas.edu)
Anna Dumitriu (annadumitriu@hotmail.com)
Annick Bureaud (abureaud@gmail.com)
Antonio Smith
Anvit Srivastav (anvit.srivastav@gmail.com)
anvit1@hotmail.com
(anvit1@hotmail.com)
ANWESHA BHATTACHARJEE
Anwyl McDonald (anwylm@sonic.net)
Arnaud Fischer (arnaud@hervefischer.com)
Arthur Woods (arsastronautica.com)
arunaugustine@about.me
(arunaugustine@about.me)
Ashton Brillante (gmail.com)
åπ∆®£w °ı• ß|ªπ†°n
åπ∆®£w °ı• ß|ªπ†°n (awblanton@gmail.com)
Brian Burnham
Bronac Ferran (bronacf@gmail.com)
Camille Prunet
Carol Strohecker (gmail.com)
Caroline Ometz
Carolyn DeCristofano
Carolyne Ojwang (cao130230@utdallas.edu)
Cassini Nazir (utdallas.edu)
Cassini Nazir (gmail.com)
cassinin@yahoo.com
(cassinin@yahoo.com)
Cathryn Ploehn (hotmail.com)
Charissa Terranova (terranova@utdallas.edu)
Charles Lindsay (charleslindsay.carbonproject@gmail.com)
Charles Vincent (thecharlesvincent@gmail.com)
chris@chriswelch.co.uk
(chris@chriswelch.co.uk)
Christian La Mont
Christine Maxwell (cmalina@gmail.com)
Christine Yvonne Maxwell (christine.y.b.maxwell@gmail.com)
christine.bernier@umontreal.ca
(christine.bernier@umontreal.ca)
Christopher Coleman (chris.d.coleman@gmail.com)
Citalli Sanchez (cicali.9@gmail.com)
Carol LaFayette (wildblue.net)
Claudine Dussollier (ramimed.com)
cm@chelseamaxwell.com
(cm@chelseamaxwell.com)
cmax@vTapestry.com
cnazir@yahoo.com
(cnazir@yahoo.com)
Colette Tron (coletron@orange.fr)
Corey Smart (gmail.com)
Corey Smart (utdallas.edu)
Craig R Harris
Czarina Cando
Daniele Bianchi
dario.villarreal@utdallas.edu
David Marlett (dmarlett.com)
Deirdre Araujo (deirdre.araujo@gmail.com)
Dhameen Ansari
Dhruba Deb
Diane Burko
Diane Gromala (dgromala@sfu.ca)
Linda D Henderson (austin.utexas.edu)
Doron Goldfarb
Darlene Tong
Earl Powell (newproductllc.com)
edleeca@sbcglobal.net
Edward Shanken (rotorelief@gmail.com)
Ellen Wagner
Emily Moore
Époque, Martine (uqam.ca)
Eric Martin
Eva Craig (gmail.com)
Evan (exj100120@utdallas.edu)
Ewen Chardronnet (e.chardronnet@gmail.com)
f90lover@gmail.com
(f90lover@gmail.com)
Fabrice Lapelletrie
fernando.sapina@uv.es
(fernando.sapina@uv.es)
Florian Grond
fr (francescomonico@gmail.com)
Frieder Nake
frnkmxwll@gmail.com
(frnkmxwll@gmail.com)
Gagan Wig (gmail.com)
Giselle Malina (gmail.com)
Gladys Finyom (gladysfinyom@gmail.com)
Greta Poulsen (yogreta@gmail.com)
Guillermo Muñoz (uv.es)
Gustavo Andres Vallejo García
Hal Clark
Haytham Nawar (gmail.com)
Huda Hashim
Humphrey Muturi (onemic1@gmail.com)
Ingrid Kepinski (ingrid.kepinski@gmail.com)
Isabel Max (imaxwell@gmail.com)
J. Kyle Pittman
Jack Ox (bway.net)
Jakki Opollo
Jose-Carlos Mariategui (ata.org.pe)
Jean-Luc Soret (mep-fr.org)
Jeff Walker
Jennifer Steen Booher (jenn@boohers.org)
Jennifer Steen Booher (quercus@jenniferbooher.com)
Jillian Scott
Jon Ippolito (gmail.com)
Jon Raskin
jonesbp@me.com
(jonesbp@me.com)
Jose Quintana
Josephine Porter
Jupiter Jazz (inexosino@gmail.com)
John Vallerga
Karen Doore (kdoore@utdallas.edu)
Karen Doore (gmail.com)
Kathy Ellins (kellins@ig.utexas.edu)
Kei Takahashi
kgx21@outlook.com
(kgx21@outlook.com)
kick@teamatb.com
(kick@teamatb.com)
korbana@hotmail.fr
(korbana@hotmail.fr)
KOUNOU Gilles
Kyle Kondas
Lars Jan (gmail.com)
Lavanya Camsaripalli (lava.sies@gmail.com)
Leslie Davis
Liliane Lijn (liliane@lilianelijn.com)
Lina Moon
Lindsey French (lindseyfrench.com)
Lindsey Joyce (lxj132030@utdallas.edu)
lindsey joyce tuggle (Thejoycean@gmail.com)
lorella abenavoli
Lori Drozd (falonsade@gmail.com)
Lorin Benedict
Loris Gréaud
Petrovic, Lucy C (lpetrovic@utdallas.edu)
Lucinda Presley (lucinda.presley@gmail.com)
Maarten Noyons (maarten@imgawards.com)
Karen O'Rourke (mapper@wanadoo.fr)
Marco Buongiorno Nardelli
Marcus Neustetter
Margaret Schedel
Mark Tschaepe
Maryellenlacy
Matthew Garcia (desertartlab@gmail.com)
Maximilian Schich (schich.info)
Mayye Zayed (gmail.com)
Marc Hebert (yahoo.com)
Melfi & Associates
mert@u.northwestern.edu
(mert@u.northwestern.edu)
michael naimark
Michael Sherrod
Mike Winters
Mohamed Aziz Chafchaouni (chaf.aziz@gmail.com)
Mohamed Youssef
Monique Wedderburn (mmw110030@utdallas.edu)
Morehshin Allahyari (gmail.com)
Morgan Meyer
Morgan O'Hara (morganohara.com)
Nancy Bennett
Nanjing Gao
Natan Karczmar
Nathan Ortega
Neel Kar
Nicolas Collins
nigelnazir@yahoo.com
(nigelnazir@yahoo.com)
Nilufer Arsala
Nina Yankowitz (nyankowitz@gmail.com)
nisar keshvani
Oliver Kreylos
Patricia Correia (gmail.com)
Paul Fishwick (Paul.Fishwick@utdallas.edu)
Paul Fishwick (gmail.com)
Christiane Paul (newschool.edu)
Pauline Oliveros (pauline.oliveros@deeplistening.org)
Perrine Mathieu
Peter Wonica (peterwonica@gmail.com)
Poejohnson
prithvi_rm@yahoo.com
(prithvi_rm@yahoo.com)
Raphael Deluzio (diluzio@maine.edu)
Richard Clar (rclar@arttechnologies.com)
Rebekah Nix (gmail.com)
Reg Gadney
Research (sarahjanepell.com)
Reynaldo Thompson (thompson@ugto.mx)
Rhoda Finyom (rfinyom@gmail.com)
Ricardo Mbarkho (gmail.com)
Richard Wirth (gmail.com)
rnix@vTapestry.com
Rob La Frenais (roblafrenais@gmail.com)
Robert Root-Bernstein (rootbern@msu.edu)
Robert Thill (robert.thill@gmail.com)
(robert.thill@gmail.com)
Robertina Sebjanic
ron_elicit@yahoo.com
(ron_elicit@yahoo.com)
Russell Fincher
Ruth Catchen
Ruth Catchen (ruthcatchen@gmail.com)
s.ruffato@gmail.com
(s.ruffato@gmail.com)
Samuel Viana (sam_viana@yahoo.com)
Samuel Okoshken (Samuel@Okoshken.com)
(Samuel@okoshken.com)
Santosh Shettar (mail2santoshcs@gmail.com)
Sara Noemi Mata Lucio (sara@propuestacivicagto.org.mx)
Sara Noemi Mata Lucio (saranoemi@gmail.com)
Sarah Larson (sarahlarson48@gmail.com)
Sarosh A (ssarosh@gmail.com)
saskia.vanmanen@open.ac.uk
Scot Gresham-Lancaster (gmail.com)
Steve DiPaola (sfu.ca)
Sean B. Carroll
Sharon Hewitt (gmail.com)
Sharon Hewitt (sxh090220@utdallas.edu)
silk@omsoft.com
(silk@omsoft.com)
Simón Pérez (jmurieta01@gmail.com)
sito.org+kickstarter@gmail.com
(sito.org+kickstarter@gmail.com)
Sophia Roosth
Sruthi Ayloo
Stephanie Brisendine (sabrisendine@gmail.com)
Stephanie Vasko
Stephen Witt
Steve Bull
Steven J Oscherwitz (u.washington.edu)
Liliane Lijn (studio@lilianelijn.com)
sujatamajumdar@yahoo.com
(sujatamajumdar@yahoo.com)
Susan Eriksson (susan.eriksson@gmail.com)
Tiffany Shlain (tiffanyshlain.com)
Tania Hershman (shortstopsuk@gmail.com)
Tasnim McCormick Benhalim (tasnimbenhalim@gmail.com)
Teri Merrick
Thanos Korakidis (vkorakidou@yahoo.gr)
Thierry Bardini
tlueker@ucsd.edu
Tony Mugavero
tribalandethnicart@yahoo.fr
(tribalandethnicart@yahoo.fr)
Vanessa Badagliacca (vanessabadagliacca@gmail.com)
Vercey Renaud (renaud@renovercey.net)
Vic Simon
Vivek Raman
wahwho@yahoo.com
(wahwho@yahoo.com)
wdp Rainer (wdp.rainer@gmail.com)
Wendi Kavanaugh
Winfield Atherton (winsthorp@gmail.com)
Xavier Malina (xmalina@gmail.com)
Yasser Jeradi (alhouyem@yahoo.com)
yuri@designforamerica.com
(yuri@designforamerica.com)
Yvan Tina (gmail.com)

**Comment by porteriffic** [comment]
Please refer to [CD 2.2.6.4 Emails to Producers and Voices](https://docs.google.com/document/d/1l8OuGDLnWTP17HUtzj3A_7UTVcc4_Kb9T61QKRScG-c/edit) on how to properly email the community.
