### ISSUE TITLE
Create plan for March 8 International Women's Day

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#2]
Let's do some social media to drive traffic to podcasts in anticipation of March 8, Int'l Women's Day.

**Comment by porteriffic** [comment]
Go through podcasts and select those featuring voices of at least one woman.

**Comment by cassininazir** [comment]
Or maybe some one o  the sound team can find and schedule a speaker who can talk on a subject related to this.

Sent from my iPhone

On Feb 13, 2015, at 5:29 PM, porteriffic <notifications@github.com<mailto:notifications@github.com>> wrote:

Go through podcasts and select those featuring voices of at least one woman.

�

**Comment by porteriffic** [comment]
I'm working on a podcast with a classmate that is related to this topic. However, it wouldn't be 15 minutes long. I can ask my classmate if she'd be willing to let us use the podcast.

**Comment by porteriffic** [comment]
Classmate is happy to contribute. The podcast is only about 5 minutes long. Very short. She just needs to fill out a form. It can go on The Bold Roast?? 

Also, Roger is recording two podcasts with Patricia Correia on March 5. Those podcasts can be used for IWD.

**Comment by cassininazir** [comment]
@creativedisturbance/sound, @porteriffic, @halclark, @amb141330, @kkondas 

For all podcasts that will go up related to International Women's Day, use the tag "IWD" in WordPress.

If you've never done this before, see the page below for instructions: 
https://en.support.wordpress.com/posts/tags/
