### ISSUE TITLE
grants to portuguese students

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#201]
_From @rmalina on July 26, 2015 9:17_

cassini lina

where are we tracking the awarding of hte student grants ? i would like
to get the grants sent out to the three portuguese students

maybe we can have a meeting cassini lina and i week of aug 2-10 when i am
in town to organise the student grants ?

cassini wasnt sure where in github to put this item-can you move it to right place ?

roger

@cassininazir 

patricia, ana rita, sam
cc lina

just a quick hallo as this week i start making my way back to dallas after
a couple of really productive months in france ( and the visit with you is a ++)

i am hoping that you might have been in touch with Lina Moon who is taking over
from stephanie brisendine on the grants from  the kickstarter

lina- maybe we can meet when i am in dallas week of aug 2 and go over the plan

patricia/ana rita/ sam- i assume you will want the $1000 grants each to go into
your personal accounts so we will eventually need the bank account info etc-
but lina will get that request to you

we should also put together a schedule for what we are doing for the next
few months until your book comes out and we do the work around that

anyway hoping you are having a good summer

roger

On Fri, Jun 5, 2015 at 11:11 AM, Patrícia Correia patricia.correia@neuro.fchampalimaud.org wrote:

> Hi Roger,
> 
> Thank you for such a rich day!
> 
> Meanwhile and just related with the sound for the beginning/end of each
> podcast channel, check out this initiative below. 
> Roger, you should add the sound of trees growing!
> We'll try to make a composition of sounds of neurons - "the sounds of
> curiosity" :)
> 
> ---------- Mensagem encaminhada ----------
> 
> Bernie Hobbs, of the Science Unit at Australian Broadcasting Commission
> says:
> 
> I’ve started a new segment on Radio National and online called the Sounds of
> Science.
> 
> It’s like the old school mystery sounds done on radio everywhere, but it’s
> all sounds from scientists.
> The episodes recorded so far are:
> 1.  The sound of a plant dying of thirst
>    http://www.abc.net.au/science/articles/2015/05/21/4239360.htm
> 2.  The sound of a single atom
>    http://www.abc.net.au/science/articles/2015/05/28/4244126.htm
> 
> I’m trying to gather as many varied science-related sounds as I can.
> 
> I’ve got 
> 
> peacock spiders drumming, 
> X-ray fluorescent spectroscopy,  
> lyrebird imitating the sound of a chainsaw etc, 
> a slinky doing the Star  Wars laser SFX and some actual micro robots playing
> the STAR WARS theme song.
> 
> BUT I’d love it if you could get the word out to your scientists and
> communicators that I want their sounds and their stories of what they were
> trying to find out and how they recorded them!
> 
> It’s a great way of getting obscure/non-news science into the media – the
> two so far are from work done 20 and 10 years ago respectively!
> 
> Please give the following info with the sound:
> -          What it is
> -          Who recorded it
> -          Why!
> -          How it was recorded
> -          What’s the research/activity it’s part of
> -          If it was recorded a while ago, what’s the status of the
>   research/activity now?
> 
> Please contact her direct.
> 
> Hobbs.bernadette@abc.net.au
> 
> On Fri, Jun 5, 2015 at 9:38 AM, roger malina rmalina@alum.mit.edu wrote:
> 
> > patricia anna rita sam
> > first just a quick thank you !! for a great day\
> > and discussions and i loof forward to working with
> > you to set up the roots of curiosity channel, the playground
> > of art and science !!
> > 
> > stephanie- they are on board to be our first creative disturbers !
> > we wish you had been with us !
> > 
> > meanwhile i will put a git hub item in so that we put together
> > a formal invitation package for us to send to them- with a full cheat
> > sheet on how to set up a new channel etc
> > 
> > roger
> > 
> > On Tue, May 26, 2015 at 6:05 PM, Patrícia Correia
> > patricia.correia@neuro.fchampalimaud.org wrote:
> > 
> > > Hi Roger,
> > > 
> > > Lovely that we get to meet your brother too and have him on board for
> > > our
> > > conversation! Thanks for joining Alan :)
> > > 
> > > Here is a brief overview of the program for your visit on June 4th. Let
> > > us
> > > know if it's all good.
> > > 
> > > Schedule
> > > 11:00 - meeting point CCU entrance; tour of the building
> > > 11:45  - prepare computer for presentation
> > > 12:00 - talk 45 min max + 15 questions
> > > 13:00 - lunch in the cafeteria with all interested
> > > 14:30 - discussion with Ana Rita/Pat/Sam about CD
> > > ... time for some more conversations ... (if you want to meet with
> > > anyone in
> > > particular let us know)
> > > 20:30 - dinner in Lisbon with Ana Rita/Pat/Sam
> > > 
> > > Audience for the talk
> > > It should be a small group of curious people. We'll open the talk to all
> > > our
> > > neuroscience community + some invited colleagues related with our Roots
> > > of
> > > Curiosity project.
> > > 
> > > What we need from you
> > > 
> > > If you can send us the following information at your convenience:
> > > 
> > > 1) Title of your talk;
> > > 
> > > 2) Abstract (small paragraph is sufficient)
> > > 
> > > Please have my phone number in case you need anything: +351 963258407.
> > > 
> > > Thanks so much and see you next week!
> > > ## 
> > > 
> > > Patrícia A. Correia
> > > Systems Neuroscience Laboratory
> > > Champalimaud Centre for the Unknown
> > > Av. Brasília, Doca de Pedrouços
> > > 1400-038 Lisboa, Portugal
> > > (+351) 210480116
> > > www.neuro.fchampalimaud.org
> > ## 
> > 
> > Roger F Malina
> > is in France
> > 33-6-80-45-94-47
> ## 
> 
> Patrícia A. Correia
> Systems Neuroscience Laboratory
> Champalimaud Centre for the Unknown
> Av. Brasília, Doca de Pedrouços
> 1400-038 Lisboa, Portugal
> (+351) 210480116
> www.neuro.fchampalimaud.org
## 

Roger F Malina
is in France
33-6-80-45-94-47

_Copied from original issue: cassininazir/creativedisturbance#123_

**Comment by linamoon** [comment]
Meeting on this planned for when @rmalina is in town next week; document for reference:
- International Student Grant FAQ Sheet https://drive.google.com/open?id=1VNt0YZGX59WKhNJk2Kmv_brSK5TcbjSzcqmNd67ASh0

**Comment by linamoon** [comment]
We have forward movement on this - updates will now take place in the Tracking List in the CD International Student Grants folder to avoid redundancy
- https://drive.google.com/drive/folders/0B1tS6I_YV9uPfnRYUTlfbV8wQU41bUFkcUpadnpWWnZhVHVYRk92YWF2SnRuNmNyRDZjZ2M
