### ISSUE TITLE
guest release from doesnt work for people in france

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#202]
_From @rmalina on July 18, 2015 20:2_

anvit
i just tried to fill out the guest release form
i put in france as a country'
and it asked for for what state with a list of american states

when you put in france you should not be asked for state !

roger
@anvit 

_Copied from original issue: cassininazir/creativedisturbance#122_

**Comment by anvit** [comment]
The Wufoo forms have already been fixed - the state field has a 'Not applicable' option at the top for people outside the US. They can chose to leave it blank as well since state isn't a required field.
