### ISSUE TITLE
Get Radio Play from Scot Gresham-Lancaster

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#203]
_From @cassininazir on March 2, 2015 20:37_

_From @cassininazir on January 28, 2015 18:52_

Scot mentioned that students worked on a radio play (I may have the name wrong). Email Scot requesting this by Friday, Jan. 30. 

_Copied from original issue: cassininazir/creativedisturbance#65_

_Copied from original issue: creativedisturbance/public-website#9_

**Comment by cassininazir** [comment]
_From @vivraman on January 30, 2015 17:8_

Update: he has "some radio play related material but its not ready yet"; he said he'll let us know when it's ready.

I'll probably bug him again in a week or so.

**Comment by cassininazir** [comment]
@amb141330 reassigning this task to you. Scot Gresham-Lancaster students produced a radio play. Please check in with him (via email) to see if it's ready. This can go in the Experimental website.

**Comment by porteriffic** [comment]
@cassininazir As far as I know, Scot should have all the radio plays. @amb141330 and I were in that class.

**Comment by porteriffic** [comment]
Emailed Scot. Waiting to hear back. (8/5/2015)

**Comment by porteriffic** [comment]
Never heard back from Scot regarding the radio plays even though he's been responsive to other emails. (8/12/2015).

**Comment by amb141330** [comment]
We should talk to Scot in person now that we see him in person. I believe I have a class with him on Friday and I will talk with him then.

**Comment by cassininazir** [comment]
@amb141330 good idea. Also shoot him an email as a courtesy.

**Comment by amb141330** [comment]
Email sent. I will talk to Scot tomorrow during class as well.

**Comment by amb141330** [comment]
I got the Radioplays from Scot. We'll now have to sift through them and see which ones are reasonable/appropriate to upload.
