### ISSUE TITLE
Create databases for the new Forms

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#204]
_From @cassininazir on March 2, 2015 22:5_

_From @sayloo on September 30, 2014 20:47_

_Copied from original issue: cassininazir/creativedisturbance#30_

_Copied from original issue: creativedisturbance/public-website#18_

**Comment by cassininazir** [comment]
Sruthi, could you post the images you took? Would like to make sure we preserve those.

**Comment by cassininazir** [comment]
_From @sayloo on March 12, 2015 20:52_

![20150302_130949](https://cloud.githubusercontent.com/assets/8712694/6627925/9cc26e4a-c8cf-11e4-879e-a8f642259b22.jpg)
![20150303_133603](https://cloud.githubusercontent.com/assets/8712694/6627929/a0c894ce-c8cf-11e4-8db5-5ebfc489ea66.jpg)
![20150303_133631](https://cloud.githubusercontent.com/assets/8712694/6627932/a379ad02-c8cf-11e4-84ac-0ed5b4d05070.jpg)
![20150303_133731](https://cloud.githubusercontent.com/assets/8712694/6627938/b388baa8-c8cf-11e4-86be-29914924e791.jpg)
![20150303_133746](https://cloud.githubusercontent.com/assets/8712694/6627939/b6cf460a-c8cf-11e4-9202-bc35bc43e56f.jpg)

**Comment by cassininazir** [comment]
Basic testing for internal team begins - Friday, April 24
QA - April 24-29. 
Implement QA fixes April 30-May 7

**Comment by cassininazir** [comment]
@anvit have assigned to you and timeline is:
- Complete forms by May 23
- Testing week of May 24

**Comment by cassininazir** [comment]
_From @anvit on May 21, 2015 19:24_

Researched different methods for Wordpress authentication since creating a custom plugin for forms would take a while. For now, going with standalone website hosted on the production server. Plan to have a rudimentary version up by tomorrow.

**Comment by cassininazir** [comment]
_From @anvit on May 25, 2015 15:19_

Database is up on the production server (atec_cd_forms). Currently the forms can be accessed at http://production.cd2.texashats.org/forms/all.php . The forms save the records to the database in a secure manner but some tasks still remain before they can be pushed live(Dynamically populating channels and languages from wordpress database, putting the forms behind a wordpress login).

**Comment by cassininazir** [comment]
_From @anvit on June 5, 2015 22:49_

The forms now use wordpress authentication(i.e. You must be logged into the wordpress site to access the forms). They can be accessed at http://production.cd2.texashats.org/forms/ .

**Comment by cassininazir** [comment]
_From @rmalina on June 5, 2015 22:50_

i tried the links and they just took me to the cd web site
the new forms dont work
roger
please check again

**Comment by cassininazir** [comment]
_From @rmalina on June 5, 2015 22:51_

even weirder
the link takes me to international womens day banner
roger

**Comment by cassininazir** [comment]
_From @anvit on June 5, 2015 23:12_

Yes, that is because you need to be signed-in to access the forms. (I will put up a warning/alert in order to avoid confusion if someone tries to access it without being signing-in). Also, currently this is hosted on our production server which is for our internal testing purposes, hence it isn't updated and still has the women's day banner.

**Comment by cassininazir** [comment]
_From @heiwanalady on June 9, 2015 23:21_

Worked for me (when I signed in!)
See screenshot below

One small thing: I don't like both of the logo marks sitting on top of each
other. I'd say just use the wordmark and leave out the symbol.

​

**Comment by cassininazir** [comment]
@anvit please indicate on the page that users need to be logged in before they can use the forms. Also, please add a link to the "Create an Account page" here in case a user has no login. 

Also, please see (CD 2.2.2.9a Archiving Podcast) [https://docs.google.com/document/d/1IoYkLJMJkRPqp_F7HD6GZE1EBzCghXxbdZ_tiY6MdQU/edit], which addresses where the files should be stored (/public/storage) and naming conventions.

**Comment by cassininazir** [comment]
A few changes: 
- Remove username from forms. This should be known since users have had to login. 
- Indicate required fields (displays when you submit, but should have a red asterisk next to each required field on page load)
- **New Channel Form** 
  - We should already have Producer name and email already. Remove these two from the page.  
  - Reference image for the channel, remove 1400 x 1400 requirement. Since we are creating the graphics, we don't need to enforce size limitation here. 
- **Guest Form**
  - Says "New Producer Form", change to "Guest Form"
  - Add "Guest" to First Name and Last Nmae. 
  - Get Terms of Agreement from (this form) [https://creativedisturbance.wufoo.com/forms/creative-disturbance-guest-release-form/] and change content 
  - Make "Bio" required as well
  - Photo, minimum size of 300x300 pixels
- **New Podcast Form**
  - If **yes** is selected for "Is this podcast for an exisiting channel?" then hide "New Channel Name" 
  - If **no** is selected for "Is this podcast for an exisiting channel?" then hide Primary and Secondary Channel
  - Add "other" to "Primary language of the podcast" - if selected, then show "Other Language" input field
  - Reference image for the podcast, remove 1400 x 1400 requirement
  - "Method of recording the podcast" 
    - add a space after radio buttons 
    - If "Other" selected, show input field. Hide otherwise. 
  - Make "Number of voices" a dropdown that goes from 2 to 10 in ascending order. 
- **Producer Form** 
  - Remove: username, first, last name. Should be known from user registration. 
  - If information has been supplied when a user has joined, auto-populate content from (Join/Register) [http://creativedisturbance.org/registration/] page.

**Comment by cassininazir** [comment]
Please push your latest updates to the production server and comment on what is remaining. I'm adding the following to the list of feature updates:
- Enable "save" functionality
- When a user logins to the page at http://production.cd2.texashats.org/forms/, they should be able to see prior saved forms. See image below for a suggested layout.

![img_0774](https://cloud.githubusercontent.com/assets/1661430/8661592/4ff94146-297e-11e5-9d09-7d6fc2564392.JPG)

**Comment by anvit** [comment]
The latest forms are up and working with the Save functionality in place. Some fields are broken (mostly the language and the select channel ones which I'm fixing currently) but the everything else should be in order.

**Comment by cassininazir** [comment]
@anvit created a layout for the landing page at http://production.cd2.texashats.org/forms2/all.php 

Also a basic layout for individual forms at http://production.cd2.texashats.org/forms2/new_podcast.html# (rename to .php and you won't see the errors). The forms should include the common header and footer.

**Comment by cassininazir** [comment]
Closing this item. Congrats @anvit on closing the longest-runnign GitHub item!
