### ISSUE TITLE
hints on running a meeting

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#206]
corey
today's meeting was great- you got a lot done !

and the youth skills day has gone really well

here are a few hints on running a meeting that are useful

a) the person organising and running the meeting should show up
ten minutes ahead of the meeting so everything is ready so the meeting starts
on time

you had 4 of us waiting for you and you joined in late
so we all wasted 5-10 minutes  watiting for the meeting
to start

b) if the meeting is allocated one hour- the meeting should
take on hour- the meeting today lasted 90 minutes

obviously if there is a crisis meetings can run on a bit

i had planned to do somthing else after an hour as other
meeting participans may have planned also

its the responsibility of the person running the meeting
to drive the meeting to finish in one hour

c) meeting preparation must be done before the meeting
- you now are updating the excel tracking sheet ahead of the meeting
  which is great
- but indeed you need to review the gitbub items status
  ahead of the meeting so gihub actions that are stuck can
  be discussed at the meeting- you said you would be doing this
  ahead of the next meeting which is good

anyway great meeting ! keep up the good work

roger

**Comment by coreysmart92** [comment]
Closing: Thanks for the hints, most of this I have been try to implement and will try to do better in the future. (8/3/15)
