### ISSUE TITLE
1 new podcast for Pioneer and Pathbreaker !!!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#207]
@coreysmart92 @porteriffic @halclark @amb141330 @kkondas 

One new podcast between Roger Malina and fireworks' master Pierre-Alain Hubert

Title :
FRENCH
Pierre-Alain Hubert sur les feux d’artifice et la musique dans les espaces urbains (FR)
ENGLISH
Fireworks innovator Pierre Alain Hubert discusses fireworks and music in urban spaces (FR).

Summary 
FRENCH
L’ artificier Pierre Alain Hubert, pionnier des arts, des sciences et des nouvelles technologies s’entretient avec Roger Malina. Il revient sur ses premiers contacts avec l’art cinétique dans les années 70 et sur sa passion pour la création d’œuvres d’art monumentales qui servent aussi d’illuminations dans les espaces publics. Dès son arrivée à Marseille, Pierre-Alain Hubert s’intéresse à des problématiques relatives à l’organisation de l’espace dans la ville et à la distribution de la lumière qu’il conçoit comme des formes d’écriture urbaine. Il a depuis lors développé une carrière internationale qui comprend, entre d’autres, des performances publiques de feux d’artifices avec d’illustres compositeurs tels que Iannis Xenakis et Mikis Theodorakis. Son œuvre Waterworks, http://www.alvincurran.com/waterworks.htm, avec Alvin Curran fut notamment montrée à Ars Electronica en 1987.

ENGLISH
Firework artist Pierre Alain Hubert, a pioneer of the art, science, technology community, discusses with Roger Malina. He explains his contact with early kinetic artists and his developing interest in
making large scale sculptures that were also light shows in public spaces. He moved to Marseille where he became involved in the problems around cities at night and light as urban writing, and became fascinated by the use of fireworks as a crossing of fine and popular art. He went on to a successful international career staging public events of innovative firework displays  with composers such as Xenakis, Mikis Theodorakis . The work Waterworks, http://www.alvincurran.com/waterworks.html, was performed at Arts Electronica with Alvin Curran in 1987.

**Comment by yvantina** [comment]
Please use these french descriptions !!

**Comment by yvantina** [comment]
BIO
French:

Pierre-Alain Hubert, pionniers des arts,sciences et nouvelle technologies des années 1970, un itinéraire d’artiste-plasticien a rapidement fait le choix d’une œuvre liant arts plastiques et arts populaires : les feux d’artifices. Il a donné, à cette activité, un sens personnel où arts plastiques, scénographie et artifices créent un évènement pour un lieu, pour une date. " Je cherchais un moyen pour communiquer. C’est alors que j’ai compris que le feu d’artifice réunissait tous les paramètres que je cherchais à assembler. Il est gratuit, démocratique et s’adresse à un large public qui peut en faire plusieurs lectures à plusieurs niveaux ; c’est véritablement de la culture populaire. Je conçois le feu d’artifice comme l’un des Beaux-Arts "

English

Pierre-Alain Hubert a pioneer of the art, science and technology movement since the 1070s, is a migrant artist who early made the decision to create work that linked the fine arts and popular culture; firework 
art. He injected into this profession a personal meaning that linked visual and sound arts, performance and fireworks which are site and location specific. : “ I was trying to find a way to communicate. That’s 
when I understood that fireworks as a medium brought together all me interests. Its free to watch, 
democratic and reaches a large audience which can enjoy the work at several levels; its truly a popular 
art. I see fireworks as part of the fine arts”.

Urls :

http://www.pyrohubert.com/  

https://www.youtube.com/watch?v=a66zRsDOp7I  small fireworks

**Comment by porteriffic** [comment]
Take note: This podcast is located in the New Leonardos Dropbox.

**Comment by coreysmart92** [comment]
Closing, because it is duplicate of #208. There are two podcasts both located in the New Leonardos folder, but this description and title are in the #208 issue. (8/3/15)
