### ISSUE TITLE
1 new podcast for New Leonardos !!!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#208]
@coreysmart92 @porteriffic @halclark @amb141330 @kkondas 

One new podcast between Roger Malina and fireworks' master Pierre-Alain Hubert

Title
FRENCH
K0 : Le nouveau terrain des artistse pyrotechniciens (FR)
ENGLISH
K0 : the new territory of firework artists.(FR)

Summary
FRENCH
L’artiste Pyrotechnicien Pierre-Alain Hubert discute avec Roger Malina de ses performances publiques au milieu d’espaces urbains et naturels et de sa fascination pour les notions d’échelle. Pierre-Alain Hubert a entrepris un échange avec le chercheur en nano sciences Jim Gimzewski au sujet des questions d’échelle et des phénomènes physiques afférents. Hubert lui a notamment fait part des plus petits feux d’artifices créés avec son maître japonais Takeo Shimizu. Gimzewski fut intrigué par cette démonstration qui amena les deux hommes à collaborer pour des projets de feux d’artifices qui explorent ces questions. Hubert s’intéresse tout autant à la physique quantique et cherche à traduire les concepts de cette discipline en des œuvres accessibles (perceptibles) par les sens humains. Pierre-Alain Hubert collabore aussi avec le chercheur Ricardo Lima (CNRS) dans le but de créer des œuvres d’art pour le laboratoire de Jim Gimzewski à l’Université de Californie (UCLA). Lorsque Gimzewski voulut savoir quelles étaient les motivations de Pierre-Alain Hubert, ce dernier lui répondit « K0 ». Gimzewski se demanda alors si cette appellation désignait la constante de Boltzmann. Hubert lui expliqua que « K0 » est le nom donné aux feux d’artistes réalisables sans crainte que la police ne vous emprisonne ; le travail de l’artiste pyrotechnicien occupe désormais des territoires beaucoup plus restreints, à l’échelle nano notamment, puisque les lois anti-terroriste actuelles rendent dorénavant impossible le travail avec les feux d’artifices (http://firework.online.fr/legislation/classification.php ).

ENGLISH
Fireworks artist Pierre Alain Hubert discusses , in French, with Roger Malina his public performances in urban and outdoors spaces and his fascination with questions of scale. Hubert develops his discussions with nano scientists Jim Gimzewski and their discussion on scale and physical phenomena. Hubert showed him the smallest fireworks that he had produced with Japanese colleague Takeo Shimizu. Gimzewski became intrigued and they went on to explore the questions
around scale and fireworks. Hubert is now interesting in quantum mechanics and how to translate quantum concepts into comprehensible work accessible to the human senses. He is current in discussions with Marseille scientist Ricardo Lima to understand quantum phenomena suffiently well to create art works with Gimzewski at the UCLA Art and Nano Science Labs. When Gimzewski asks Hubert what motivates him , he reply is “K0”. Gimzezewski asks him if this is Boltzmann’s constant;
no Hubert explains, K0 is the largest firework you can make without the police putting you in jail
(http://firework.online.fr/legislation/classification.php ). He notes that the work of fireworks artists is now nearly impossible because of current anti-terrorist regulations and he must now work on nano
scales.

**Comment by yvantina** [comment]
Please use these french descriptions !!

**Comment by yvantina** [comment]
BIO
French:

Pierre-Alain Hubert, pionniers des arts,sciences et nouvelle technologies des années 1970, un itinéraire d’artiste-plasticien a rapidement fait le choix d’une œuvre liant arts plastiques et arts populaires : les feux d’artifices. Il a donné, à cette activité, un sens personnel où arts plastiques, scénographie et artifices créent un évènement pour un lieu, pour une date. " Je cherchais un moyen pour communiquer. C’est alors que j’ai compris que le feu d’artifice réunissait tous les paramètres que je cherchais à assembler. Il est gratuit, démocratique et s’adresse à un large public qui peut en faire plusieurs lectures à plusieurs niveaux ; c’est véritablement de la culture populaire. Je conçois le feu d’artifice comme l’un des Beaux-Arts "

English

Pierre-Alain Hubert a pioneer of the art, science and technology movement since the 1070s, is a migrant artist who early made the decision to create work that linked the fine arts and popular culture; firework 
art. He injected into this profession a personal meaning that linked visual and sound arts, performance and fireworks which are site and location specific. : “ I was trying to find a way to communicate. That’s 
when I understood that fireworks as a medium brought together all me interests. Its free to watch, 
democratic and reaches a large audience which can enjoy the work at several levels; its truly a popular 
art. I see fireworks as part of the fine arts”.

Urls :

http://www.pyrohubert.com/  

https://www.youtube.com/watch?v=a66zRsDOp7I  small fireworks

**Comment by rmalina** [comment]
corey

can you bring this to the attention of who you assign to edit the pierre alain hubert podcasts

roger

apologise for the confusion on the pierre alain hubert podcasts

i put the two podcasts for pierre alain hubert in the new leonardos drop box as for some reason i no longer have access to the  pioneers and pathbreakers drop box

podcast no 1 with pierre alain hubert should go in the pioneers channel
podcast no 2 with pierre alain hubert  goes into new leonardos channel

and here are the FINAL descriptions of each podcast in english and french- the versions in woofoo are not right

roger

if necessary we can skyp about the mess i created

roger

Final summaries in french and english to use for pierre alain hubert podcasts

Channel: Pioneers and Pathbreakers

Title 1:

Artiste Pyrotechnicien P A Hubert discute ses feux d’artifice et musique dans les
espaces urbains (FR)

Summary 1:

L’ artificier Pierre Alain Hubert, pionnier des arts, des sciences et des nouvelles technologies s’entretient avec Roger Malina. Il revient sur ses premiers contacts avec l’art cinétique dans les années 70 et sur sa passion pour la création d’œuvres d’art monumentales qui servent aussi d’illuminations dans les espaces publics. Dès son arrivée à Marseille, Pierre-Alain Hubert s’intéresse à des problématiques relatives à l’organisation de l’espace dans la ville et à la distribution de la lumière qu’il conçoit comme des formes d’écriture urbaine. Il a depuis lors développé une carrière internationale qui comprend, entre d’autres, des performances publiques de feux d’artifices avec d’illustres compositeurs tels que Iannis Xenakis et Mikis Theodorakis. Son œuvre Waterworks,http://www.alvincurran.com/waterworks.htm , avec Alvin Curran fut notamment montrée à Ars Electronica en 1987.
 Fireworks innovator Pierre Alain Hubert discusses fireworks and music
in urban spaces (FR).

Summary 1

Firework artist Pierre Alain Hubert, a pioneer of the art, science,
technology community, discusses with Roger Malina. He explains his
contact with early kinetic artists and his developing interest in
making large scale sculptures that were also light shows in public
spaces. He moved to Marseille where he became involved in the problems
around cities at night and light as urban writing, and became
fascinated by the use of fireworks as a crossing of fine and popular
art. He went on to a successful international career staging public
events of innovative firework displays  with composers such as
Xenakis, Mikis Theodorakis . The work Waterworks ,
http://www.alvincurran.com/waterworks.html ,was performed at Arts with
Alvin Curran in 1987.

Podcast 2 with pierre alain Hubert 

Channel New Leonardos

Title 2 K0 : Le nouveau terrain des artistse pyrotechniciens P A Hubert (FR)

Summary 2: 

L’artiste Pyrotechnicien Pierre-Alain Hubert discute avec Roger Malina de ses performances publiques au milieu d’espaces urbains et naturels et de sa fascination pour les notions d’échelle. Pierre-Alain Hubert a entrepris un échange avec le chercheur en nano sciences Jim Gimzewski au sujet des questions d’échelle et des phénomènes physiques afférents. Hubert lui a notamment fait part des plus petits feux d’artifices créés avec son maître japonais Takeo Shimizu. Gimzewski fut intrigué par cette démonstration qui amena les deux hommes à collaborer pour des projets de feux d’artifices qui explorent ces questions. Hubert s’intéresse tout autant à la physique quantique et cherche à traduire les concepts de cette discipline en des œuvres accessibles (perceptibles) par les sens humains. Pierre-Alain Hubert collabore aussi avec le chercheur Ricardo Lima (CNRS) dans le but de créer des œuvres d’art pour le laboratoire de Jim Gimzewski à l’Université de Californie (UCLA). Lorsque Gimzewski voulut savoir quelles étaient les motivations de Pierre-Alain Hubert, ce dernier lui répondit « K0 ». Gimzewski se demanda alors si cette appellation désignait la constante de Boltzmann. Hubert lui expliqua que « K0 » est le nom donné aux feux d’artistes réalisables sans crainte que la police ne vous emprisonne ; le travail de l’artiste pyrotechnicien occupe désormais des territoires beaucoup plus restreints, à l’échelle nano notamment, puisque les lois anti-terroriste actuelles rendent dorénavant impossible le travail avec les feux d’artifices (http://firework.online.fr/legislation/classification.php ).

Title  K0:The new territory of firework artist Pierre Alain Hubert.(ENG)

> Summary 2 english
> 
> > > Fireworks artist Pierre Alain Hubert discusses , in French, with Roger
> > > Malina his public performances in urban and outdoors spaces and his
> > > fascination with questions of scale. Hubert develops his discussions
> > > with nano scientists Jim Gimzewski and their discussion on scale and
> > > physical phenomena. Hubert showed him the smallest fireworks that he
> > > had produced with Japanese master Takeo Shimizu.
> > > Gimzewski became intrigued and they went on to explore the questions
> > > around scale and fireworks. Hubert is now interesting in quantum
> > > mechanics and how to translate quantum concepts into comprehensible
> > > work accessible to the human senses. He is current in discussions with
> > > Marseille scientist Ricardo Lima to understand quantum phenomena
> > > suffiently well to create art works with Gimzewski at the UCLA Art and
> > > Nano Science Labs. When Gimzewski asks Hubert what motivates him , he
> > > reply is “K0”. Gimzezewski asks him if this is Boltzmann’s constant;
> > > no Hubert explains, K0 is the largest firework you can make without
> > > the police putting you in jail
> > > (http://firework.online.fr/legislation/classification.php). He notes
> > > that the work of fireworks artists is now nearly impossible because of
> > > current anti-terrorist regulations and he must now work on nano
> > > scales.

**Comment by coreysmart92** [comment]
No problem I will add a comment and link to help the editor. Thank you for the update. (8/3/15)
Close when podcasts are published.

**Comment by coreysmart92** [comment]
Closing:
Both of Pierre-Alain Hubert's podcast have been published. (8/25/15)

**Comment by rmalina** [comment]
thanks !
roger
