### ISSUE TITLE
rapid scheduling of audiolats and noisy people podcasts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#209]
corey

it was agreed that we would post podcasts received in final edited form very quickly
this applies both to
a) noisy people
i see you got the noisy podcast up today saturday which is great

b) audiolats- see the complaint email from annick below

can we discuss monday how we could make sure that noisy people and audiolats podcasts get posted within X days of receipt and then we can inform the producers of what we are able to commit to

roger
@porteriffic 

---------- Forwarded message ----------
From: Annick Bureaud abureaud@gmail.com
Date: Sat, Aug 1, 2015 at 8:47 AM
Subject: Trust Me podcast
To: malina rmalina@alum.mit.edu, Chaz Lilly Dallas ebook cll093020@utdallas.edu, Yvan Tina yvantina@gmail.com

Do you know when the 2 Trust Me podcasts will be online ?
Do you need anything ?

**Comment by coreysmart92** [comment]
I understand the idea behind this and currently it will not cause any major disruptions. However we do need to discuss the implementation of this alongside a podcast backlog. (8/3/15)

**Comment by rmalina** [comment]
i dont understand why this is on hold- lets just put a procedure that all noisy people and audiolats podcasts must by published within 2 weeks of receipt maximum

am i missing something ?

the way to have backlog is to community build with the producers not to hold up publication
in my opinion- your decision but thats my input !!
roger

roger

**Comment by porteriffic** [comment]
@rmalina @coreysmart92 Not sure why this is on hold either. It was already established all podcasts from Noisy People and Audiolats to be published immediately, regardless if we have a back log or not. If no one opposes then please close this issue, otherwise bring this up during our next meeting on 9/6.

**Comment by coreysmart92** [comment]
Closing: I have begun to rapidly schedule all podcast that come in completed. If this changes or becomes an issue later on re-open this issue. (9/1/15)
