### ISSUE TITLE
Add Diversity, Gender Info to Website

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#210]
_From @cassininazir on March 2, 2015 22:8_

_From @cassininazir on February 13, 2015 18:30_

Add to the About page. This should help members and potential members understand the community. Should demonstrate and encourage diversity.

_Copied from original issue: cassininazir/creativedisturbance#103_

_Copied from original issue: creativedisturbance/public-website#28_

**Comment by cassininazir** [comment]
Have added a Gender field to all our voices. Working on a page that gives us up-to-date information from LibSyn and voices pages:

  http://production.cd2.texashats.org/forms2/stats.php 

Will combine the above two pages into one. When fully working, we can add this to our voices page.

**Comment by cassininazir** [comment]
@anvit can you find a way to include this content into a live page? If the database connection dies, we'd just not publish anything.

**Comment by anvit** [comment]
Yes, I can easily show this content. Just let me know where you want it to be shown and I'll put it in.

**Comment by cassininazir** [comment]
@dylanorgeron assigning to you. I have a written PHP script to do this, but didn't do any testing. Putting this on hold until you get forms up and running.

**Comment by dylanorgeron** [comment]
add bits of stats page to the about page
