### ISSUE TITLE
Create a blog post about International Student Grants

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#211]
_From @cassininazir on March 2, 2015 22:9_

_From @cassininazir on January 30, 2015 19:9_

_Copied from original issue: cassininazir/creativedisturbance#72_

_Copied from original issue: creativedisturbance/public-website#32_

**Comment by cassininazir** [comment]
@linamoon once complete, can you post a write-up on our blog?

**Comment by linamoon** [comment]
Blog posts have (finally!) been scheduled and published on Wordpress site.
