### ISSUE TITLE
Online Intellectual Dating?

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#212]
cassini

hmm-here is someone doing intellectual dating

roger

The Bridge
Experiments in Science and Art
SciArt Center is excited to announce an open call to all members for our new virtual residency program, The Bridge: Experiments in Science and Art. With the ultimate goal of bridging the gulf between the sciences and the creative humanities in our culture at large, we will be forming three pairs of one artist and one scientist each to explore and document the collaborative potential between the two disciplines. 

Collaboration between the arts and sciences is an increasingly popular notion, described as the solution to our 21st century problems. It is one of the many tangible ways in which art and science can productively interact. But what does collaboration mean? What does it look like, and how does it function? Is it possible to have a two-way collaborative street, or does that even matter? Can art influence science, as science often influences art? These are some of the many questions our program asks. The form, process, and results of each team’s collaboration are entirely up to them. The Bridge will serve as the first documentation of the full and natural collaborative process between an artist and scientist. 

Learn more about The Bridge program, the schedule, and how to apply here:
http://www.sciartcenter.org/the-bridge.html

**Comment by amb141330** [comment]
Worth revisiting I think. Closing this issue and adding to list of contacts for new issue when I open it up.
