### ISSUE TITLE
Bumpers/Stingers from Brian Merlo

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#214]
i have asked brian merlo to create some bumpers and stingers for the channels i produce
so you can expect in the next few weeks

we are giving brian the cheat sheet on bumpers and stingers and as he works
suggest improvements for the cheat sheet

can you contact brian to coordiante

roger

**Comment by coreysmart92** [comment]
Can you give me Brain Merlo's preferred email address. (8/25/15)

**Comment by cassininazir** [comment]
Search for him on the UT Dallas directory.
