### ISSUE TITLE
This podcast doesn't work !

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#216]
@coreysmart92 
Corey
this podcast doesn't work properly - can you please fix this ? Thanks
http://creativedisturbance.org/podcast/taste-of-flesh-bite-me-im-yours-as-seen-by-the-curator-meeting-with-jareh-das-eng/

**Comment by coreysmart92** [comment]
@yvantina can you be more specific, it seems that everything is working fine on my end. (8/10/15)

**Comment by cassininazir** [comment]
The podcast was not playing when Yvan made the note. Not sure who fixed, but seems to be working now.

Cassini

**Comment by yvantina** [comment]
Hey Corey. Yes, Cassini is right ! not sure who fixed it but it didn't work
properly last week.
Thank you

2015-08-10 11:28 GMT-05:00 Cassini Nazir notifications@github.com:

> The podcast was not playing when Yvan made the note. Not sure who fixed,
> but seems to be working now.
> 
> Cassini
> 
> ---
> 
> From: coreysmart92 [notifications@github.com]
> Sent: Monday, August 10, 2015 8:09 AM
> To: creativedisturbance/podcasts
> Subject: Re: [podcasts] This podcast doesn't work ! (#216)
> 
> @yvantinahttps://github.com/yvantina can you be more specific, it seems
> that everything is working fine on my end. (8/10/15)
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/creativedisturbance/podcasts/issues/216#issuecomment-129437391
> 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/216#issuecomment-129517742
> .

## 

check out this website for more information on art, synthetic biology and
a-life
http://synthbioart.texashats.org/

**Comment by cassininazir** [comment]
Please close if this is fixed.

**Comment by coreysmart92** [comment]
Closing: This is fixed. (8/17/15)
