### ISSUE TITLE
gresham lancaster dropbox problem

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#218]
@coreysmart92 @halclark 

please please sort this out rapidly
its embarassing that this didnt get dealt with when scot originally asked

roger

Scot Gresham-Lancaster
11:30 PM (10 hours ago)

to Cassini, roger 
I have a podcast for David Worral and Alexis Emelianoff that have been in the can since July, but my repeated requests for access to the box, dropbox, google drive or whatever have elicited no response. The address I had from before does not work for me. Please help me out here.

Scot

Scot Gresham-Lancaster ph +1 510-512-8344 ◯◦ ◦◯⃝⃝ ⃝ ◌◌⃝ ⃝ ◌⃝ ◌⃝ ◯○ ◦◌ ◌ ○ ◯◦ ◦◯⃝⃝ ⃝ ◌◌⃝ ⃝ ◌⃝ ◌⃝ ◯○ ◦◌ ◌ ○ ◦◌ ◌ ○ ◯◦ ◦◯⃝⃝ ⃝ ◌◌⃝ ⃝ ◌⃝ ◌⃝ ◯○ ◦ 
http://about.me/scotgl

**Comment by porteriffic** [comment]
Just emailed him.

I actually sent him multiple invites to his own Dropbox and emails notifying him back in June and again in July but they must've gotten lost in his inbox.

**Comment by porteriffic** [comment]
Podcasts received and are in Google Drive. Once we transition to the new forms, it will help resolve a lot of the issues we are facing with Dropbox.
