### ISSUE TITLE
Contacts for Audiovisual Heritage Day

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#219]
Contact Frank, Scot, and Filip about the upcoming splash page for audiovisual heritage day. Ask about description, and request podcasts.

**Comment by halclark** [comment]
Sent emails

**Comment by rmalina** [comment]
hal

for audiovisual archive heritage month

i would be willing to organise a podcast with philippe queau - a really important figure
in the audivisual archive world if you are willing to work with me to set up and do
the podcast recording

here is details about queau

http://world-information.org/wio/program/participants/992284253 

roger

**Comment by halclark** [comment]
Excellent! Have talked to Scot and Filip, with no reply from Frank. Will have more info by the end of this week.

**Comment by cassininazir** [comment]
Good! Can you add information and the outcome from Scot and Filip? You may need to chat with Frank after class to get a few minutes of his time. He's quite busy.

**Comment by halclark** [comment]
Team decided that we will do ArtCOP21 instead of Audio Visual Heritage Day.
