### ISSUE TITLE
Add nomination requisite to Podcast Production Process

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#22]
At the end of every podcast, ask the guest/voices to nominate:
- Someone they know, and someone they don't know
- Find out if okay to get that individual's content

**Comment by coreysmart92** [comment]
Add to Producer/Guest Cheat Sheet

**Comment by porteriffic** [comment]
Add to Summer Plan

**Comment by porteriffic** [comment]
Already on Cheat Sheet. Need to clean up cheat sheet over summer.
