### ISSUE TITLE
International Coffee Day Prep

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#220]
Start preparing for International Coffee Day.

**Comment by porteriffic** [comment]
Email has been sent. Will feature a select few from The Bold Roast channel along with any other podcasts we get from other channels.

**Comment by porteriffic** [comment]
@amb141330 You've been put in charge of the splash page, according to the (Feature Day Action Plan)[https://docs.google.com/document/d/1lA0UaMrmaxg-rOLGox4mCvvn_tB3DBqwo5PoWWsPgZA/edit]. Let's have the splash page ready to go by the Monday, Sept. 21st. 

@linamoon How much time would you need to create graphics for the splash page and social media posts?

**Comment by linamoon** [comment]
Should be pretty straightforward, let's say a few days so I'll have it done by this upcoming Thursday?

**Comment by porteriffic** [comment]
@linamoon Great! Would be cool to attach some graphics with the social media posts.

**Comment by porteriffic** [comment]
- Roots of Curiosity Conference: Symbiosis of Art and Science feat. Patricia Correia, Ana Rita Fonseca & Sam Viana
- Cancer: Finding Beauty in the Beast
- El Futuro de las Prótesis Robóticas/ The Future of Robotic Prostheses
- Gender and Economics with Nobel Prize Winner Amartya Sen
- The Intertwining Constructions of Blackness
- タイトル "DNA-RNAキメラリピッドから考える生命起源" (1/3) [JA]

**Comment by porteriffic** [comment]
Splash Page is ready to go.
