### ISSUE TITLE
audiolats update

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#221]
corey
am just putting this in github so we have a record of it

thanks for sorting out the drop box etc problems- looks
like she is now happy ! great work

roger

Dear Corey

Sorry for my long silence and my communication only via Yvan. I had been a bit "out", reconnecting now. Thank you for the podcasts online. Everything is excellent. I'll recheck everything about the dropbox and if I have any problems I'll let you know. Again thank you for the work and your patience.

Best
Annick

Le 06/08/15 23:34, Yvan Tina a écrit :
Hi Corey
We're missing Martin O'Brien picture for this podcast
http://creativedisturbance.org/podcast/taste-of-flesh-bite-me-im-yours-as-seen-by-the-artist-meeting-with-martin-obrien-eng/

Were you able to pull it out from Annick's form or do you
need her to send it again ?
Please let me know -Thank you

yvan

2015-08-03 9:46 GMT-05:00 Creative Disturbance
<feedback.createdisturb@gmail.com
<mailto:feedback.createdisturb@gmail.com>>:

```
Dear Ms. Bureaud and Yvan,
Thank you for the information, I have everything sorted
out. One of your podcast will publish this week and the
other will follow next week. Please let me know if you
have any problems in the future with the dropbox.
Corey

On Fri, Jul 24, 2015 at 12:19 PM, Creative Disturbance
<feedback.createdisturb@gmail.com
<mailto:feedback.createdisturb@gmail.com>> wrote:
```

**Comment by coreysmart92** [comment]
Closing:
The problem with Martin O'Brien's picture has been fixed, it had to do with the apostrophe. Yvan and Annick sent me his preferred picture which has already been published. Glad to hear that all problems are resolved. (8/25/15)
