### ISSUE TITLE
metrics on social media

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#224]
josephine
i just discovered we only have 100 followers on twitter ? might as well stop !

or else we need a concerted effort to increase our social media metrics !

what is our metrics of number of people following us on social media ?

for discussion at hte team team meeting

roger

**Comment by porteriffic** [comment]
@rmalina Agreed! @cassininazir and I were discussing earlier today to find a way to properly track metrics on social media. I can add this to the agenda for Monday and Tuesday.

**Comment by porteriffic** [comment]
@rmalina We currently have 169 followers and are now following everyone that is following us. I'll be making a concentrated effort to plan out the social media pushes. It'll be documented [here](https://docs.google.com/document/d/1DZhb-PAN5n4G51BaxLuJ9W3l9l8u_taEV6E5xkujn98/edit).

Closing for now.
