### ISSUE TITLE
Please help Diane Gromala to make a podcast !!!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#225]
@coreysmart92 @porteriffic @halclark 
Diane pledged for the KS campaign and is eager to contribute more
here's her email address  gromala@sfu.ca

Hi Diane

Well.. thanks so much then for pledging for the KS campaign and making this happen
thank you very much !!!

the only thing you have to do to be on the voice page is to submit your podcast to
feedback.createdisturb@gmail.com
or let me talk to the production team and they will come back to you pretty soon !!

I very much enjoyed the panel on art and pain and one idea would actually be for example to having you talking with Martin O'Brien whose "Taste of Flesh" has to do with chronic disease and ethics..
he has recently been interviewed by Annick Bureaud on the Audiolats channel 
but I would be curious to have your own input on that matter.. just an idea, nothing special..
-- (aside question, maybe less interesting) Do you know if psychological suffering (such as - provocated- heartache, social harassment, etc..) has been / is being explored by any contemporary / new media artist ? (e.g Laclos 'Dangerous Liaisons')

Thanks for following up on this
Will keep in touch

Best regards

yvan

2015-08-22 20:10 GMT-05:00 Diane Gromala gromala@sfu.ca:

```
Hi Yvan,

Actually, I joined Creative Disturbance via the kickstarter,
and am registered, but am not on the <voices> page.
How do I make that happen?

Cheers,
Diane

“If at first, the idea is not absurd, then there is no hope for it.”
                           --Albert Einstein
--------------------------------------------
Prof. Diane Gromala, PhD
Canada Research Chair
Simon Fraser University
Vancouver Environs, Canada

skype: dr.gromala
778-688-8340 mobile
www.siat.sfu.ca/faculty/Diane-Gromala/

www.confrontingpain.com 

---------------------------------------------
This e-mail may contain confidential information for the sole use of the intended recipient.
Any review or distribution by anyone other than the person for whom it was originally intended is prohibited.
If you have received this e-mail in error please delete all copies.
Opinions conclusions or other information contained in this e-mail may not be that of the organization. 



On Aug 22, 2015, at 3:30 PM, Yvan Tina <yvantina@gmail.com> wrote:
```

> ```
> Thank you very Thecla
> 
> I've also met Mahsoo Salimi who put me in touch with Dr. Diane Gromala, copied in this email
> Will let you figure out how we can further collaborate with SFU and the School of Interactive Art
> 
> Looking forward
> All the best
> 
> yvan
> 
> 2015-08-21 13:41 GMT-05:00 thecla schiphorst <thecla@sfu.ca>:
> 
>     hi roger and yvan,
> 
>     this is a wonderful idea!
> 
>     It just so happens that I will be the new director of SIAT starting 1 Sept 2015.
>     I will follow up with you when I return from my vacation after 1 september 2015 
> 
>     thecla
> 
>     - - - - - - - - - - - - - - - - - - - - - - - - - - - -
>     d r   t h e c l a   s c h i p h o r s t
>     symposium director ISEA2015
>     associate director SIAT | professor
>     director movingStories research partnership
>     school of interactive arts + technology
>     simon fraser university
>     m 604.726.9364
>     e thecla@sfu.ca
>     www.sfu.ca/~tschipho
>     www.movingstories.ca 
>     www.isea2015.org 
>     - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 
>     From: "roger malina" <rmalina@alum.mit.edu>
>     To: "Yvan Tina" <yvantina@gmail.com>
>     Cc: "Philippe Pasquier" <philippe_pasquier@sfu.ca>, isea2015-thecla@sfu.ca, hdaniel@sfu.ca
>     Sent: Thursday, August 20, 2015 8:27:35 PM
>     Subject: Re: SFU School of Interactive Art on Creative Disturbance ?
> 
> 
>     Philippe, Thecla and Daniel
>     first apologies for my no show at ISEA=by all reports it was a great isea
>     but delighted that Yvan connected with you
>     in any case as yvan indicated creative disturbance is available to you
>     ( we are also starting an aggregation service where we re post podcasts
>     you have already published- as a different option to setting up a channel)
>     we are moving the platform to mit press with a mit url which will also
>     help draw audience
> 
>     roger
> 
>     On Thu, Aug 20, 2015 at 10:02 PM, Yvan Tina <yvantina@gmail.com> wrote:
>     >
>     > Dear Philippe, Thecla and Daniel
>     > -cc Roger Malina
>     >
>     > it was very nice chatting with you at Isea and thanks again for the great
>     > work you've done to make it a successful event !!
>     >
>     > Just wanted to bring your attention to Creative Disturbance, the Leonardo
>     > audio platform for discussions on art, science and technology
>     > (http://creativedisturbance.org/ 
>     ) and suggest the idea, as we already
>     > pointed out, of having a channel produced by the School of Interactive Art
>     > faculty (and/or students); but if you rather like that option, you can
>     > simply send us your podcasts on art/sci/tech and we'll be happy to release
>     > it online (oui, après édition cher Philippe...)
>     > However, having a channel (a disturbance) give you more freedom on the
>     > content as producers since the podcast usually reflects the overall theme of
>     > your channel and it only requires a minimum of 7-8 podcasts a year to be
>     > kept active.. The logo can be designed either by you or our design team.. In
>     > any case, we can perfectly manage with your preference and work with the
>     > most convenient solution !
>     > The average length of a podcast is 15mn and it can be in any spoken language
>     > (i.e French of course, but Chinese, German, Swahili..).
>     > Feel free to send us more recommendations about things you'd like to hear,
>     > ideas you want to discuss and people of interest we need to contact for a
>     > podcast..
>     > We have more channels on their way and we're nearing about 15000 downloads
>     > after one year of activity. so please check it out !
>     >
>     > Kind regards
>     >
>     > yvan
> 
>     > --
>     > check out this website for more information on art, synthetic biology and
>     > a-life
>     > http://synthbioart.texashats.org/ 
> ```

**Comment by yvantina** [comment]
from Diane

---

I am planning on developing podcasts this fall, but would like to Skype with
your production team to learn what common problems are, what the best formats
are and that sort of thing.

**Comment by cassininazir** [comment]
Josephine, this can be filed under the "intellectual dating" category!

Cassini Nazir

Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
Director of Design and Research, ArtSciLab
The University of Texas at Dallas

**Comment by porteriffic** [comment]
@yvantina You are more than welcome to join our production meeting today at 1pm.

**Comment by porteriffic** [comment]
Emailed Diane. Waiting to hear back (8/25).

**Comment by porteriffic** [comment]
Still have not heard back (8/31).

**Comment by yvantina** [comment]
Josephine - any news from Diane ?

**Comment by porteriffic** [comment]
@yvantina Unfortunately, no. I can contact her again but you are welcome to do it instead. Let me know what you decide.

**Comment by yvantina** [comment]
---------- Forwarded message ----------
From: Yvan Tina yvantina@gmail.com
Date: 2015-10-14 1:37 GMT-05:00
Subject: Re: Creative Disturbance_PainLab Channel (Dr Gromala)
To: Mahsoo Salimi salimi@sfu.ca, Diane Gromala gromala@sfu.ca
Cc: Roger Malina rmalina@alum.mit.edu, Cassini Nazir cassini@utdallas.edu

Thank you very much ! Mahsoo
Please let me share this with Roger Malina and Cassini Nazir
for the implementation of this disturbance. No where else ! Yay !
Someone will contact you soon to proceed.
Very best

2015-10-13 17:16 GMT-05:00 Mahsoo Salimi salimi@sfu.ca:

```
Dear Yvan,

I have attached the logo and name (NOWHERE ELSE) for our channel (with Dr Gromala and PianLab at SFU).
Please let me know how we could upload our personal info.

Bests,
Mahsoo
```

## 

check out this website for more information on art, synthetic biology and a-life 
http://synthbioart.texashats.org/
and listen to our podcasts !
http://creativedisturbance.org/
