### ISSUE TITLE
2 Virtual Africa podcasts on Dropbox

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#227]
@coreysmart92 @porteriffic @halclark Can you please take a look to those files and make a quick edit ? I may need to remove a little part on the Streak' one.. just let me know. Thanks

**Comment by yvantina** [comment]
podcast form completed for Henry Daniel's podcast !

**Comment by yvantina** [comment]
podcast form completed for Greg Streak's podcast !

**Comment by coreysmart92** [comment]
Closing: Both podcasts have been published. (9/14/15)
