### ISSUE TITLE
Meet with Anvit for Hand-Off

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#228]
@anvit, want to make sure @dylanorgeron is up to speed on items. Can you both schedule a time to meet this week (week of Aug 24) to discuss:
- Creative Disturbance website
- CD Forms
- Internal processes

Will you also give him any access he needs to the sites? He already has Google Drive access.

**Comment by dylanorgeron** [comment]
@cassininazir, anvit and I met and discussed the current way development is handled, and he is working on getting me access to the documents and accounts I will need.
