### ISSUE TITLE
Review Usability Testing Reference Materials

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#229]
Steven Krug's Dont Make Me Think Ch 9: Usability Testing.

@linamoon recommend you also review. Would like you and @dylanorgeron to do usability tests soon on the CD Forms and the CD website.

**Comment by linamoon** [comment]
Believe you also mentioned this, putting here for reference: 
- Basic explanation: https://www.gov.uk/service-manual/user-centred-design/user-research/lab-based-user-testing.html  
- Rocket surgery made easy: http://www.sensible.com/rsme.html

**Comment by linamoon** [comment]
Need to write up plan with @dylanorgeron on our testing process and who to test on for next week:
- List of tools to use (perhaps @cassininazir could point us towards some useful tools)
- List of tasks for users to perform
- Types of users to contact
- Etc. from literature

After testing, we will write up a summary of research findings and present.

**Comment by cassininazir** [comment]
This is a good overview document [A Complete Guide to User Testing Your Next Project](http://downloads.usertesting.com/white_papers/UserTesting-eBook_A-Complete-Guide-to-User-Testing-Your-Next-Project.pdf). Some of it is common sense, but organized.

**Comment by linamoon** [comment]
Created folder Usability Testing for Forms to upload store all relevant files, in the 2.1 Development Team: https://drive.google.com/open?id=0B1tS6I_YV9uPRXQ5a096anpkWVk
