### ISSUE TITLE
Review Google Drive documents

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#230]
Specifically, start here: 

1.0 Project Mgmt
2.1 Dev Team
2.2 Production Team 
5.0 Key Public Docs

**Comment by linamoon** [comment]
Might be a little outdated, but still very useful: 
- Podcast Production Process: https://drive.google.com/open?id=0BwvQhnxKj6jFeWJjT2VDR0pENXc 
- Process Overview: https://drive.google.com/open?id=0BwvQhnxKj6jFa00wRkl3YmlPTkE

**Comment by cassininazir** [comment]
Thanks, Lina! @dylanorgeron, review the podcast production process and suggest ways to make it more efficient.
