### ISSUE TITLE
Yearly Contact with Producer - Audiolats

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#234]
Contact Annick regarding Audiolats and how many podcasts we can expect for the rest of the year. Also what her expectations are from us, any feedback, etc.

**Comment by yvantina** [comment]
emailed Annick. keep posted

**Comment by yvantina** [comment]
Nothing to report. "Trust Me" podcast series and pioneer artist Fred Forest to come.

**Comment by amb141330** [comment]
I contacted Annick seperately and am in contact with her about upcoming podcasts. Closing issue
