### ISSUE TITLE
Yearly Contact with Producer - Within the Margins

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#239]
Contact Poe Johnson's future and plan out the rest of the year for their channel. Also ask what their expectations are, gather their feedback, etc.

**Comment by coreysmart92** [comment]
I have emailed the producer, Poe Johnson, about Within the Margins to setup a meeting. (9/14/15)

**Comment by coreysmart92** [comment]
I have met with Poe Johnson about the Within the Margins channel. (9/16/15)

**Comment by cassininazir** [comment]
Great! Saw you both meeting. Provide a quick update in the GitHub or Google Docs on the outcome of the meeting (what was agreed to, action items, etc).
