### ISSUE TITLE
Dropbox Space!

### ISSUE THREAD

**Issue by kkondas** [creativedisturbance/podcasts#24]
Hey guys, 
I was trying to up-load a podcast that needs editing to the dropbox, but it won't let me saying that I'm out of space. Can you all go through and start compiling and saving the ones that have already been edited so that we can put them on the ArtSciLab Computer, and then go through and take down the original up-loaded files so that we can up-load future ones. For now, I will take the one that I was trying to up-load and a few more I am grabbing from the lab and will post them on Google Drive. I'll e-mail you later with the titles and which channels they go into ones I've put them on the Drive.

**Comment by cassininazir** [comment]
I created a Dropbox account for ArtSciLab (see 1.1.3 for Password). Also installed the DropBox app on the Mac in the ArtSciLab. This Mac gets backed up regularly, so downloading and archiving files to this Mac is a good idea.

Please do make a physical backup of your podcast (to a thumb drive or other) before removing from Dropbox.
