### ISSUE TITLE
Yearly Contact with Producer - Indie Game Nation

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#240]
Contact Kyle about Indie Game Nation's future and plan out the rest of the year for their channel. Also ask what their expectations are, gather their feedback, etc.

**Comment by rmalina** [comment]
move this channel to the archive section as we discussed-see cassini for how to do this
roger

**Comment by rmalina** [comment]
josephine
can you discuss with cassini how to move indiegame nation to archive status
and we can see if we can find a new producer
roger

**Comment by porteriffic** [comment]
@rmalina Just added to my to-do list.

**Comment by amb141330** [comment]
Closing the issue. Roger spoke with Kyle.
