### ISSUE TITLE
Yearly Contact with Producer - Meta-Life

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#241]
Contact Yvan about Meta-Life's future and plan out the rest of the year for their channel. Also ask what their expectations are, gather their feedback, etc.

**Comment by amb141330** [comment]
Emailed Yvan for a time to meet. Waiting on response.

**Comment by amb141330** [comment]
Will talk with Yvan when he gets back from Africa

**Comment by amb141330** [comment]
Met with Yvan. Gave me information, but still has to email me more information and contacts.

**Comment by amb141330** [comment]
Information has been received.
