### ISSUE TITLE
Yearly Contact with Producer - Pioneers & Pathbreakers

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#242]
Contact Roger about Pioneer & Pathbreaker's future and plan out the rest of the year for their channel. Also ask what their expectations are, gather their feedback, etc.

**Comment by coreysmart92** [comment]
I have emailed the producer, Roger, about Pioneers & Pathbreakers to setup a meeting. (9/14/15)

**Comment by coreysmart92** [comment]
I have met with Roger about Pioneers & Pathbreakers channel. (9/16/15)
