### ISSUE TITLE
Yearly Contact with Producer - New Leonardos

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#243]
Contact Roger about New Leonardo's future and plan out the rest of the year for their channel. Also ask what their expectations are, gather their feedback, etc.

**Comment by coreysmart92** [comment]
I have emailed the producer, Roger, about New Leonardos to setup a meeting. (9/14/15)

**Comment by coreysmart92** [comment]
I have met with Roger about New Leonardos Channel. (9/16/15)
