### ISSUE TITLE
podcast with anvit srivastav

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#247]
lina
if anvit gets the job offer would you be willing to work with him to
a) write a short annnouncement for publicaiton on the art scilab web site announcing
his being hired
b) record a podcast with him before he leaves for the bold roast channel !

roger
@anvit

**Comment by linamoon** [comment]
Yes of course! @anvit and I will discuss - is there a time good for you this week, Anvit?

**Comment by anvit** [comment]
Sure @linamoon , I'll be at the lab between 12pm -5pm tomorrow and day after. Will you be free any of those days?

**Comment by linamoon** [comment]
@anvit I can be there later today at 2:30pm!

**Comment by anvit** [comment]
@linamoon I'll be at the lab around 2:30 then!

**Comment by linamoon** [comment]
Discussed with Anvit today - will put blog post up when official job offer comes in, and record podcast next Thursday.

**Comment by linamoon** [comment]
@anvit I actually realized I have a meeting 11am next Thursday - does 11am Wednesday work better?

**Comment by linamoon** [comment]
Recorded today and uploaded to Dropbox for the Bold Roast!

**Comment by linamoon** [comment]
Working title: Research and development in the ArtSciLab with Anvit Srivastav
