### ISSUE TITLE
Yearly Contact with Producer - Space Art & Culture

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#248]
Contact Roger about Space Art & Culture's future and plan out the rest of the year for their channel. Also ask what their expectations are, gather their feedback, etc.

**Comment by coreysmart92** [comment]
I have emailed the producer, Roger, about Space Art & Culture to setup a meeting. (9/14/15)

**Comment by coreysmart92** [comment]
I have met with Roger about Space Art & Culture. (9/16/15)
