### ISSUE TITLE
Yearly Contact with Producer - Frank Malina

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#249]
Contact Roger about Frank Malina's future and plan out the rest of the year for their channel. Also ask what their expectations are, gather their feedback, etc.

**Comment by amb141330** [comment]
Emailed @rmalina about a time to meet. Waiting for response.

**Comment by amb141330** [comment]
@coreysmart92 Did you meet with Roger on this? He mentioned that you met with him on all his channels. I know I was assigned to this so I'm not sure if it happened.

**Comment by rmalina** [comment]
no we did not discuss this channel
corey maybe we should do a follow up meeting
and go over what we decided last time and also
discuss this channel
roger
@coresmart92

On Wed, Sep 23, 2015 at 10:15 AM, amb141330 notifications@github.com
wrote:

> @coreysmart92 https://github.com/coreysmart92 Did you meet with Roger
> on this? He mentioned that you met with him on all his channels. I know I
> was assigned to this so I'm not sure if it happened.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/249#issuecomment-142636184
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
Roger, I'd be happy to meet with you and discuss this channel. If you'd rather do this with Corey since he is coordinating your other channels that's fine too. Just let me know.

**Comment by amb141330** [comment]
Met with Roger. Will keep our agenda for this channel up to date on g-drive.
