### ISSUE TITLE
Schedule Design Review Meeting 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#250]
@dylanorgeron let's schedule a design review meeting in Sept to prioritize what we should work on and 

Should be all hands: 
- Podcast 
  - Design Team
  - Admin team 

Help me schedule this.

**Comment by dylanorgeron** [comment]
Use doc with people who arent available, use contact info doc, update with own info

**Comment by dylanorgeron** [comment]
@cassininazir friday at either 11am or 4pm seems to work for everyone according to the 1.2.1 Team Schedule doc. Do either of those times seem like they would work to you?

**Comment by cassininazir** [comment]
Yes, either of those work. This Friday, Sept 11?

**Comment by dylanorgeron** [comment]
That's fine with me. Would you like me to write up the email, or would you like to do it?

**Comment by cassininazir** [comment]
Please send it out.

Cassini Nazir

Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
Director of Design and Research, ArtSciLab
The University of Texas at Dallas

**Comment by dylanorgeron** [comment]
Email just went out, let me know if I missed anyone.
