### ISSUE TITLE
Quality Test Forms - Hal

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#254]
We need your help to launch the new version of Producer Forms! Please take time to **complete these  before the Saturday, Aug. 29**  and **add your comments/suggestions to this GitHub issue**. 
1. Login to test server at http://production.cd2.texashats.org/login. Note that you may reset your password or register as a new user. 
2. Click the link to **Forms for producers and guests**. (Yes, this link needs to be improved!) 
3. Then do the following: 
   - Submit 1 of each of the 4 forms (new channel, guest, submit podcast, producer) 
   - Partially complete each of the four forms and "save" your content for later
   - Delete at least one of your saved forms

Remember, this form will be used by producers and guests. Help us identify pain points for them. A few thoughts to get you started: 
- How can we improve the completion page? 
- What tasks can be made easier? 
- What information might be missing from these forms? 
- What information does the podcast team need that should be included on these forms?

**Comment by halclark** [comment]
Will do ASAP

**Comment by cassininazir** [comment]
@halclark would like your feedback on these forms before @dylanorgeron goes live with updates. Please get this ASAP.
