### ISSUE TITLE
Quality Test Forms - Corey

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#255]
We need your help to launch the new version of Producer Forms! Please take time to **complete these  before the Saturday, Aug. 29**  and **add your comments/suggestions to this GitHub issue**. 
1. Login to test server at http://production.cd2.texashats.org/login. Note that you may reset your password or register as a new user. 
2. Click the link to **Forms for producers and guests**. (Yes, this link needs to be improved!) 
3. Then do the following: 
   - Submit 1 of each of the 4 forms (new channel, guest, submit podcast, producer) 
   - Partially complete each of the four forms and "save" your content for later
   - Delete at least one of your saved forms

Remember, this form will be used by producers and guests. Help us identify pain points for them. A few thoughts to get you started: 
- How can we improve the completion page? 
- What tasks can be made easier? 
- What information might be missing from these forms? 
- What information does the podcast team need that should be included on these forms?

**Comment by coreysmart92** [comment]
Can we reduced the max number of voices to 5. (8/25/15)

**Comment by coreysmart92** [comment]
I have completed the forms. The producer form would not save, and anything after a ' would be deleted when saving. (8/25/15)

**Comment by coreysmart92** [comment]
I thought that in the New podcast Info Form we would have a place to submit the podcast audio. Are we planning on doing that, or are we going to continue the audio file submission through dropbox. (9/1/15)

**Comment by cassininazir** [comment]
@anvit @dylanorgeron review the other forms to make sure we're not missing the request for the podcast file! This is what QA is for! Thanks, @coreysmart92

**Comment by coreysmart92** [comment]
The biggest thing I noticed was that in the new podcast info form there is no where to insert the audio files. (9/14/15)

**Comment by anvit** [comment]
There is now an option in the podcast form to upload a podcast audio file.

**Comment by coreysmart92** [comment]
Closing: The forms are functioning and look great. I will create new issues if anything arises. (10/7/15)
