### ISSUE TITLE
Quality Test Forms - Josephine

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#256]
We need your help to launch the new version of Producer Forms! Please take time to **complete these  before the Saturday, Aug. 29**  and **add your comments/suggestions to this GitHub issue**. 
1. Login to test server at http://production.cd2.texashats.org/login. Note that you may reset your password or register as a new user. 
2. Click the link to **Forms for producers and guests**. (Yes, this link needs to be improved!) 
3. Then do the following: 
   - Submit 1 of each of the 4 forms (new channel, guest, submit podcast, producer) 
   - Partially complete each of the four forms and "save" your content for later
   - Delete at least one of your saved forms

Remember, this form will be used by producers and guests. Help us identify pain points for them. A few thoughts to get you started: 
- How can we improve the completion page? 
- What tasks can be made easier? 
- What information might be missing from these forms? 
- What information does the podcast team need that should be included on these forms?

**Comment by porteriffic** [comment]
Visual Improvements
- Having the Saved Forms at the top of the home page is confusing. I initially thought I was supposed to click on them to access the forms.
- Under the Saved Forms, I think it's a little redundant to label the channels. It's already under Channel Forms.
- Only the channels under Channel Forms are in bold.
- "Save" button to "Save for later" 
- More color? To help distinct between information being given vs information needed.
  - For example, to submit a podcast the font color above the "Podcast Process" and information above is the same color as the font color for the forms below.
  - Also, the "Podcast Process" should have some visual component added to the text. Like an icon or something.

Functional Improvements
- If I change the language of the podcast, it doesn't update to the newly selected language. 
- Information for New Producer did not save. I tried a couple times and each time the info was gone. 
- Is there a way for me to go back to the "Home" page after selecting a Saved form besides hitting the back button on my browser?
