### ISSUE TITLE
Quality Test Forms - Dylan

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#257]
We need your help to launch the new version of Producer Forms! Please take time to **complete these  before the Saturday, Aug. 29**  and **add your comments/suggestions to this GitHub issue**. 
1. Login to test server at http://production.cd2.texashats.org/login. Note that you may reset your password or register as a new user. 
2. Click the link to **Forms for producers and guests**. (Yes, this link needs to be improved!) 
3. Then do the following: 
   - Submit 1 of each of the 4 forms (new channel, guest, submit podcast, producer) 
   - Partially complete each of the four forms and "save" your content for later
   - Delete at least one of your saved forms

Remember, this form will be used by producers and guests. Help us identify pain points for them. A few thoughts to get you started: 
- How can we improve the completion page? 
- What tasks can be made easier? 
- What information might be missing from these forms? 
- What information does the podcast team need that should be included on these forms?

**Comment by dylanorgeron** [comment]
This page is primarily for forms. The site statistics don't have a place near the top of the page. They are already trying to submit a podcast, we don't have to keep trying to sell the site to them.

**Comment by dylanorgeron** [comment]
When no forms are saved, there should be text beneath each header letting people know that section is empty. I was expecting a link to a list of forms I had saved, and instead it was just text. 
![image](https://cloud.githubusercontent.com/assets/6401465/9499627/1b5e8be6-4be6-11e5-9fa3-f6566b8a09ac.png)

The icon should also be on the same line as the text.

**Comment by dylanorgeron** [comment]
The dashboard link goes to the same forms2 page

**Comment by dylanorgeron** [comment]
![image](https://cloud.githubusercontent.com/assets/6401465/9499666/5f8d0edc-4be6-11e5-8555-461c488a6ea0.png)

Icon should be centered here

**Comment by dylanorgeron** [comment]
![image](https://cloud.githubusercontent.com/assets/6401465/9499791/20a22760-4be7-11e5-8ecb-575af5a0c034.png)
Lots of text, consider using icons or arrows or something here.

**Comment by dylanorgeron** [comment]
Validators for forms should be clearer. The small red \* doesn't do much to draw my attention to where it needs to me.

**Comment by dylanorgeron** [comment]
When uploading a podcast for a new channel, the channel name isn't required. 
![image](https://cloud.githubusercontent.com/assets/6401465/9499862/9cd58390-4be7-11e5-80a2-b31ee7adcf3d.png)

**Comment by dylanorgeron** [comment]
Limit of 10 voices in a podcast?

**Comment by dylanorgeron** [comment]
![image](https://cloud.githubusercontent.com/assets/6401465/9499887/c0cfe236-4be7-11e5-8ff3-1c287d27e074.png)
Erroneous text on producer tile.
