### ISSUE TITLE
Missing data from podcast....

### ISSUE THREAD

**Issue by kkondas** [creativedisturbance/podcasts#26]
Corey there is some missing data from two of the podcasts, one which I think you up-loaded. 

On the Personalized Learning Using Modeling podcast, when you go to the episode page, Sharon Hewitt's name is missing from the title. Also, both her and Paul Fishwick's pics are missing for the voices. Paul is already one of the voices, so could you grab his pic and add it, and also e-mail Sharon and ask her to send a pic. 

The other one is in Nubean Textures (Textures need to be capitalized). We are missing a picture for Huda Hashim. Will you check to see, or have who did upload the podcast check to see if there was a pic, and if not, email the producer for pic of Huda. Thanks.

**Comment by amb141330** [comment]
I just took care of the one with Huda Hashim. Yvan called me and brought it to my attention. I know what went wrong, but it's partially my fault and also something peculiar with the way wordpress uploads.

**Comment by cassininazir** [comment]
Thanks for the quick fix, Ashton. Next time you see me, show me the peculiarity and we'll see if we can fix it.
