### ISSUE TITLE
urls on bakshi post

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#262]
corey
oops
no urls on this one either
can you add ?

roger

http://creativedisturbance.org/podcast/portals-amar-bakshi-discusses-art-the-law-diplomacy-and-the-sharing-of-linked-virtual-spaces-eng/

**Comment by coreysmart92** [comment]
I just checked, but this ones wufoo form didn't have a website specific to that podcast.(8/25/15)

**Comment by rmalina** [comment]
h mm pretty i put in th url to the projects web site
its not specific to the podcast but its the link we need
to send people to

its

http://amarbakshi.com/  

cn you add ?

roger

**Comment by coreysmart92** [comment]
I have added the url to the description. However we have noticed that the wrong file might be uploaded onto libsyn. I have contacted the editor, Hal, and will close this issue when this is resolved. (8/26/15)

**Comment by halclark** [comment]
Fixed.
