### ISSUE TITLE
informing voices of podcast being up

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#263]
josephine
idle question

does someone every time a podcast is posted alert the voice that its been posted
and ask them to retween/blog it ? with the link

i know we put this in the plan but just wondering if we are doing ti

as you pointed out that spike was because of a conenction retweeting

maybe all is well-but i was about to alert a voice that a podcast just went up for

rohger

**Comment by porteriffic** [comment]
@rmalina We currently don't have system in place for that. We briefly discussed who could alert the Voices (Producers or sound team) but as of now, our assumption is that the producers are contacting Voices. 

I agree, we should email them and ask the Voices, not just Producers, to retweet/blog when we alert them that their podcast is up. I can add this to the agenda on Monday.

**Comment by cassininazir** [comment]
Thanks for adding, @porteriffic. This is the last part of the podcast production process, but we're not enforcing this. I think its part of a larger discussion about the process. For example, according to our processes, the team should make sure all forms are in good order before starting production, but not always the case. 

@coreysmart92 bringing you into the loop on this.

**Comment by porteriffic** [comment]
We've added this to the process and all team members are aware of this. Will update in a couple of weeks to see how we're doing with it.

**Comment by porteriffic** [comment]
@coreysmart92 Please add this to Monday's agenda so we can see how we're doing on implementing this.

**Comment by porteriffic** [comment]
I will address this at Monday's meeting on 10/5
