### ISSUE TITLE
Develop list of tools we use in the lab

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#264]
For Sound editing

For web editing

For project management

Start wit hthe passwords list

**Comment by porteriffic** [comment]
Started a document [here](https://docs.google.com/document/d/1Nec22I6Lr8aQ-M2QXES2d_uNrPn9bps-txognPJD4A4/edit).

**Comment by porteriffic** [comment]
@dylanorgeron Can you list any tools you use under the "web editing" section?

**Comment by dylanorgeron** [comment]
added sublime text 3, its all i use
