### ISSUE TITLE
Add inventory list of lab equipment into Quartzy

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#265]
Add all items: 
- Name
- Serial numbers
- Photo of each item

**Comment by amb141330** [comment]
Almost completed with this task. Should be completed by the end of the week.

**Comment by amb141330** [comment]
Only photos needed now. Everything is listed under inventory and everything that should be able to be checked out is under equipment sign ups

**Comment by amb141330** [comment]
Inventory is complete. Testing is next.

**Comment by rmalina** [comment]
ashton
i returned the zoom i took to europe and put it on t he
filing cabinet but didnt know how to check it in

it also needs to be checked to make sure the batteries
are ok and the memory card

roger

On Mon, Sep 14, 2015 at 11:43 AM, amb141330 notifications@github.com
wrote:

> Inventory is complete. Testing is next.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/265#issuecomment-140140500
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
Another Quartzy issue already. We should be getting rechargeable batteries from Brian.
