### ISSUE TITLE
Create checkout system for lab equipment in Quartzy

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#266]

**Comment by cassininazir** [comment]
@amb141330 can you provide an update on this? What's in the system? What's are the remaining to dos?

**Comment by amb141330** [comment]
Basically everything is already in the system except what is in the very bottom drawer. I haven't taken photos of any of the items yet, but this will be completed by the end of the week.

**Comment by amb141330** [comment]
The equipment list is in Quartzy. Only photos need to be added now.

**Comment by rmalina** [comment]
yeah!
have a good weekend
roger

On Fri, Sep 4, 2015 at 1:17 PM, amb141330 notifications@github.com wrote:

> The equipment list is in Quartzy. Only photos need to be added now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/266#issuecomment-137810375
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
I have determined that Quartzy is not an effective inventory check out for our needs. I will be testing out softwares that offer free trials. No free software seems to meet our needs that I could find.

**Comment by rmalina** [comment]
sandy
have you found any inventory systems we can use
to track equipment in my lab ?

roger

On Tue, Oct 20, 2015 at 1:40 PM, amb141330 notifications@github.com wrote:

> I have determined that Quartzy is not an effective inventory check out for
> our needs. I will be testing out softwares that offer free trials. No free
> software seems to meet our needs that I could find.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/266#issuecomment-149660318
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
Will start downloading trials for different programs and creating small inventories to test the software rather than wasting time putting in every single item

**Comment by cassininazir** [comment]
Please update status.

**Comment by amb141330** [comment]
Starting to use CheqRoom. Will begin adding inventory items this week.

**Comment by amb141330** [comment]
This issue has been moved to administration as we are waiting whether or not they will pay for this system.
