### ISSUE TITLE
non live link on pierre alain hubert link

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#267]
corey

thanks for adding the url for the link into the text about pierre alain hubert in this mornings
podcast

(http://firework.online.fr/legislation/classification.php )

but the link wasnt live- one could not click through-i had to copy and paste into my browser

in the future can you put the links in as live links ?

no need to fix this one , jujst make sure all future texts have url as a  live linke
roger

**Comment by coreysmart92** [comment]
No problem I will do that in the future. (9/1/15)
