### ISSUE TITLE
no card in zoom

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#269]
ashton
charissa terranova gave me the zoom she had used to record the podcast
with philip beasley

this morning i opened it to move hte podcat file into our system

there was NO card in the zoom so i assume that the podcast recording is lost

a) can we add to the lab equipment check list to make sure that hte zooms ALWAYS have storage card in them, and that the batteries are fresh

b) can you send charissa terranova an apolovy and copy me on it

roger

**Comment by cassininazir** [comment]
I made a copy of the SD card to my hard drive. I still have the original card and will return later today. 

Ashton, this raises a good issue of how to make sure we have equpiment to do a podcast on the fly and more importantly where to put the files once done!

**Comment by amb141330** [comment]
Can you provide me with her email? @rmalina 

Also, yes Cassini I agree. Both Zunes should be equipped and ready to record at any given moment. The files being uploaded is another topic depending on whether or not they remove the Zunes from the lab.

**Comment by rmalina** [comment]
cassini
does this mean that we DO have a copy of charissa's [pocast ?

ashton- she is prof charissa terranova at utd- you can get her email address via utd system

roger

**Comment by cassininazir** [comment]
Should have been more clear.Yes, we do have a copy of the podcast with Charissa and Philip Beesley.

**Comment by amb141330** [comment]
If Cassini does, in fact, not have a copy of the podcast I will send an email to Charissa later today.

**Comment by rmalina** [comment]
ashton
sounds like we are ok
we just need charrisa to fill out the form
can you email her and copy me

can we use the new forms ? if niot
send her an email with the list of things we need to fill 0ut
and i will complete what she doesnt and put it in the system

roger

**Comment by amb141330** [comment]
I don't believe we can use the new forms just yet.

Cassini the things she would need to fill out are the podcast form and the guest form right? That should be all as far as I know. I don't know either of these two individuals so I'm just double checking before I send an email.

**Comment by rmalina** [comment]
ashton
if you send me an email with a list of the things we need from her= you can
just copy over the descri[ptions in the existing form

she is going to fill in some and i will fill out the rest

roger

**Comment by amb141330** [comment]
Original issue topic is void. Email has been sent to @rmalina with the information on the form that needs to be filled out.
