### ISSUE TITLE
lab equipment problems- firefox

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#271]
ashton cassini
do we need to start a github folder for artscilab equipment problems

when we try and run the stetho software we have a problem on the lab computer
(mac) hooked up to the projector because apparently firefox doesnt run properly
you should check with brian on what the fix is

roger

**Comment by amb141330** [comment]
I didn't see the Stetho software, but I did update Firefox. Can we check again and see if it's working now?

**Comment by cassininazir** [comment]
The URL for Stetho is

stetho.herokuapp.com

and

stethox.herokuapp.com

Cassini Nazir

Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
Director of Design and Research, ArtSciLab
The University of Texas at Dallas

**Comment by amb141330** [comment]
This issue was fixed when I updated firefox.
