### ISSUE TITLE
replace batteries in lab computer mouse

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#272]
ashton

the batteries in the mouse in the lab mac for the projector are dead
can you replace the batteries
and maybe we should use a wired mouse rather than the wireless one !

roger

**Comment by amb141330** [comment]
@rmalina I much prefer wired mice, but I think given the configuration that a wireless mouse suits it better. Do we keep batteries somewhere in the ArtSciLab? Or somewhere I can get them in ATEC without supplying them myself?

**Comment by rmalina** [comment]
ashton
tell me exactly what we need to buy and i will buy some and bring them
in

roger

On Wed, Sep 2, 2015 at 10:05 AM, amb141330 notifications@github.com wrote:

> @rmalina https://github.com/rmalina I much prefer wired mice, but I
> think given the configuration that a wireless mouse suits it better. Do we
> keep batteries somewhere in the ArtSciLab? Or somewhere I can get them in
> ATEC without supplying them myself?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/272#issuecomment-137116238
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
Brian brought AA batteries and the batteries have been replaced in the mouse.

**Comment by rmalina** [comment]
ashton
do we need a monthly check list of things that need to be checked
periodically like replacing the batteries in things ?

roger

On Mon, Sep 14, 2015 at 11:42 AM, amb141330 notifications@github.com
wrote:

> Closed #272 https://github.com/creativedisturbance/podcasts/issues/272.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/272#event-408881421
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007
