### ISSUE TITLE
complex network student podcasts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#273]
josephine
i am working with catherine cramer to try and bring in some student podcasts=
will keep you informed

roger
@coreysmart92 

catherine
excellent- this is a standing offer so happy to work with
you with the current students and future students !

and separately the podcasts on creative disturbance
is available as a platform to you

roger

On Tue, Sep 1, 2015 at 8:52 AM, Catherine Cramer ccramer@nysci.org wrote:

> Roger and Nick! So sorry for radio silence. A very busy summer got away from
> me. And my NetSciEd colleagues have also been largely unavailable, meaning I
> would be unable to contact students anyway. So, here's the next step: We
> have our next NetSciEd call scheduled for September 15, and I will
> definitely have your proposal on the call agenda. Then I will know how
> feasible it will be to do this with the students - I don't have direct
> access to most of them. So after our call on the 15th I will be back in
> touch!!
> Thanks for your patience~
> Best,
> Catherine
> 
> On Thu, Jul 16, 2015 at 3:37 AM, roger malina rmalina@alum.mit.edu wrote:
> 
> > catherine
> > 
> > here is a suggestion
> > 
> > a) use the transactions camera ready template for all texts
> > b) you write a two page overview- a shortened version of your
> > complenet text/updated
> > c) you pick 6 of the best student projects - and they can do a one
> > page text in the transactions format-
> > we would have a slight orientation to projects that include arts,
> > humanities-but not strict since
> > they all involve visualisation- the ones presented in zaragoza plus 3
> > others ?
> > 
> > separately we are happy to record via skyps short podcasts (not
> > videos) of a student
> > discussing their project
> > 
> > anyway am flexible
> > 
> > roger
> > 
> > On Thu, Jul 16, 2015 at 1:39 AM, Catherine Cramer ccramer@nysci.org
> > wrote:
> > 
> > > Roger and Nick - Apologies for radio silence on our end - conferences
> > > and
> > > travel mostly to blame.
> > > I think it would be helpful if we rewound the conversation slightly.
> > > Originally, my colleague mentioned to Roger (at the end of our NetSciEd
> > > symposium in Zaragoza) that 3 of our NetSci High students won NY State
> > > Science Honor Scholarships. I think that's where the number 3 came from.
> > > But
> > > there are also additional excellent posters from the last three years.
> > > I've
> > > attached the full list of NetSci High students research projects, going
> > > back
> > > to the beginning of the project, and there is a poster for each. I'm not
> > > sure what your format would be for publishing these. We did present
> > > NetSci
> > > High at the CompleNet 2015 conference in March; I've attached that paper
> > > as
> > > well, which is published in the CompleNet proceedings.
> > > Please advise how to proceed from here - you also mentioned videos of
> > > the
> > > students at one point.
> > > Thanks much~
> > > Catherine
> > > 
> > > On Mon, Jun 29, 2015 at 1:04 PM, Nick Cronbach nc@leonardo.info wrote:
> > > 
> > > > Dear Catherine,
> > > > 
> > > > Thank you for sending your text. Attached is our 1-page Transactions
> > > > template. Please let us know if you have any questions.
> > > > 
> > > > Best,
> > > > Nick
> > > > 
> > > > On 6/28/2015 3:21 AM, roger malina wrote:
> > > > 
> > > > > nic
> > > > > can you log in the attached manuscript as a draft
> > > > > curators intro
> > > > > 
> > > > > there are three high school students that were given
> > > > > prizes and the idea is to give each of them the opportunity
> > > > > to describe their project in a one page Transactions format
> > > > > ( nick could you send catherine the blank template
> > > > > for transactions ? catherine can you take a look at this
> > > > > and see if you think the students cold turn their posters
> > > > > into this kind of format ?
> > > > > 
> > > > > catherine- once we have the student texts i think
> > > > > we will need you to revise your text with an explanation
> > > > > at the end of how the students were selected and then
> > > > > introduce their texts that would follow
> > > > > 
> > > > > pam/nick- i would have isabelle meirelles and max schich
> > > > > 'peer review' the final section with suggestions for clarification
> > > > > or improvement
> > > > > 
> > > > > roger
> > > > > 
> > > > > ---------- Forwarded message ----------
> > > > > From: Malina, Roger rxm116130@utdallas.edu
> > > > > Date: Sat, Jun 27, 2015 at 10:29 PM
> > > > > Subject: FW: Network Science posters from high school students
> > > > > To: roger malina rmalina@alum.mit.edu
> > > > > 
> > > > > From: Catherine Cramer [mailto:ccramer@nysci.org]
> > > > > Sent: Saturday, June 27, 2015 9:15 PM
> > > > > To: Malina, Roger
> > > > > Subject: Re: Network Science posters from high school students
> > > > > 
> > > > > Roger - Having a not very clear idea of how this will be used, I put
> > > > > the attached intro together. Please let me know if it needs revising -
> > > > > happy to provide what you need with more guidance.
> > > > > 
> > > > > Thanks
> > > > > 
> > > > > Catherine
> > > > > 
> > > > > On Fri, Jun 26, 2015 at 12:59 PM, Malina, Roger
> > > > > rxm116130@utdallas.edu
> > > > > wrote:
> > > > > 
> > > > > Catherine
> > > > > 
> > > > > If you can do a 500 word into that would be great
> > > > > 
> > > > > roger
> > > > > 
> > > > > From: Catherine Cramer [mailto:ccramer@nyscience.org]
> > > > > Sent: Friday, June 26, 2015 6:58 PM
> > > > > To: Malina, Roger
> > > > > Cc: Catherine Cramer; roger malina; Stephen Uzzo; Lori Sheetz; Hiroki
> > > > > Sayama
> > > > > Subject: Re: Network Science posters from high school students
> > > > > 
> > > > > Hi Roger - Great thanks so much for  a great opportunity for the
> > > > > students - they produced their posters as part of their participation
> > > > > in NetSciHigh - more details here
> > > > > https://sites.google.com/a/binghamton.edu/netscihigh/
> > > > > 
> > > > > I'm happy to write an intro if you give me parameters for length etc
> > > > > 
> > > > > The podcasts is a fantastic idea! The only hitch is school just let
> > > > > out for the summer but we could produce this in the fall - let me know
> > > > > what you think
> > > > > 
> > > > > Happy to answer more questions
> > > > > 
> > > > > Thanks
> > > > > 
> > > > > Best
> > > > > 
> > > > > Catherine
> > > > > 
> > > > > Sent from my iPhone
> > > > > 
> > > > > On Jun 26, 2015, at 11:46 AM, Malina, Roger rxm116130@utdallas.edu
> > > > > wrote:
> > > > > 
> > > > > Catherine
> > > > > 
> > > > > Yes would be interested ! where can I look up details
> > > > > 
> > > > > I can send you the format for a Leonardo Transactions
> > > > > 
> > > > > Publication ( one page in the journal) – but it would be
> > > > > 
> > > > > Good to have an intro from you
> > > > > 
> > > > > Can you point me to details ?
> > > > > 
> > > > > One other opportunity is that we run short podcasts
> > > > > 
> > > > > ( 15 minutes) on our www.creativedisturbance.org platform
> > > > > 
> > > > > And the students might be interested in being recorded-
> > > > > 
> > > > > And broadcast-we do the recording by phone or skype
> > > > > 
> > > > > roger
> > > > > 
> > > > > From: Catherine Cramer [mailto:ccramer@nysci.org]
> > > > > Sent: Wednesday, June 10, 2015 9:25 PM
> > > > > To: Malina, Roger
> > > > > Cc: Stephen Uzzo; Lori Sheetz; Hiroki Sayama
> > > > > Subject: Network Science posters from high school students
> > > > > 
> > > > > Hi Roger - I attended the Leonardo symposium in Zaragoza last week -
> > > > > which was excellent! Afterwards when we were taking down our NetSci
> > > > > High students' posters you came over and mentioned that you might have
> > > > > interest in publishing one or more of the posters - so I am just
> > > > > getting in touch about that! Let us know if we can give you any
> > > > > additional information etc.
> > > > > 
> > > > > Thanks~
> > > > > 
> > > > > Best,
> > > > > 
> > > > > Catherine
> > > > > ## 
> > > > > 
> > > > > Catherine Cramer
> > > > > 
> > > > > Program Manager
> > > > > New York Hall of Science
> > > > > 47-01 111th Street
> > > > > Queens, NY 11368-2950
> > > > > T: 718 699 0005 x396
> > > > > F: 718 699 1341
> > > > > www.nysci.org
> > > > > 
> > > > > What's t
> > > > > 
> > > > > he best way to know what's
> > > > > 
> > > > > happening
> > > > > 
> > > > > at NYSCI?
> > > > > 
> > > > > S
> > > > > 
> > > > > omething for everyone, every day: Facebook | Twitter | Google+
> > > > > 
> > > > > | Tumblr

**Comment by porteriffic** [comment]
Great!

**Comment by amb141330** [comment]
This was an old issue assigned to Josephine. Since it's so old, long gone, and our focus is on other things I am closing this issue to clear clutter.
