### ISSUE TITLE
Video Tutorial Feedback and Comments-Ashton

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#278]
Watch the [Video Tutorial First Draft](https://drive.google.com/drive/u/0/folders/0B0RS2YDJUln1fnJGenZoTWMxUl9pR3ZteFRRTDMySjR3YkwzaENlbVJQRVlMcVBpZzFhZ3M) and make any feedback, comments, or suggestions either on this github issue or on [Video Tutorial Content Comments](https://docs.google.com/document/d/1djOL94hSZyf7aYKsk8Ipaw8b6YQQnxhc9K7w20jJG5A/edit). Close when you have watch the video and made any necessary comments.

**Comment by amb141330** [comment]
Meet with me on how to use Echo360 for videos like this..
Record Audio seperately.
Have a tentative script for hitting key points in sequential order.
Make more specific, shorter, videos for each element. Using audacity, using jabber, using skype, sending a file, etc.
Recording audio seperately, after the video is already finished, will allow the talking to be much more smooth.
Don't forget to give time to record background noise.

**Comment by rmalina** [comment]
ashton
 maybe you can train me on echo360
next time you are in the lab- knock on my office door
roger

On Wed, Sep 2, 2015 at 10:19 AM, amb141330 notifications@github.com wrote:

> Meet with me on how to use Echo360 for videos like this..
> Record Audio seperately.
> Have a tentative script for hitting key points in sequential order.
> Make more specific, shorter, videos for each element. Using audacity,
> using jabber, using skype, sending a file, etc.
> Recording audio seperately, after the video is already finished, will
> allow the talking to be much more smooth.
> Don't forget to give time to record background noise.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/278#issuecomment-137125468
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
Video being edited. Another github issue should be created for the new one. I can help with any of this if need be.
