### ISSUE TITLE
Add Shortened URL to Podcast Production Checksheet

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#28]
Use bit.ly to shorten podcasts. This should be shared with producers so that they may share and forward.

**Comment by porteriffic** [comment]
Bitly.com (Use Creative Disturbance to log in. Log in information is in CD 1.1.3)

**Comment by porteriffic** [comment]
This has been added to the [CD 2.2.2.9 Podcast Production Process](https://docs.google.com/document/d/1zYIkYATPUnkd2sHSWAZUX9kHgJxld5LHs5ZjvEC32Jw/edit) and [CD 2.3.0 Podcast Production Process Overview](https://docs.google.com/document/d/1bpp1B-l_pNffAbKo06guml-GhTHJilB-EQQGrc9y-2Y/edit).
