### ISSUE TITLE
Video Tutorial Feedback and Comments-Roger

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#281]
Watch the [Video Tutorial First Draft](https://drive.google.com/drive/u/0/folders/0B0RS2YDJUln1fnJGenZoTWMxUl9pR3ZteFRRTDMySjR3YkwzaENlbVJQRVlMcVBpZzFhZ3M) and make any feedback, comments, or suggestions either on this github issue or on [Video Tutorial Content Comments](https://docs.google.com/document/d/1djOL94hSZyf7aYKsk8Ipaw8b6YQQnxhc9K7w20jJG5A/edit). Close when you have watch the video and made any necessary comments.

**Comment by rmalina** [comment]
corey
i put a few comments in your document-more on the formal than
content aspects
roger

On Tue, Sep 1, 2015 at 2:49 PM, coreysmart92 notifications@github.com
wrote:

> Watch the Video Tutorial First Draft
> https://drive.google.com/drive/u/0/folders/0B0RS2YDJUln1fnJGenZoTWMxUl9pR3ZteFRRTDMySjR3YkwzaENlbVJQRVlMcVBpZzFhZ3M
> and make any feedback, comments, or suggestions either on this github issue
> or on Video Tutorial Content Comments
> https://docs.google.com/document/d/1djOL94hSZyf7aYKsk8Ipaw8b6YQQnxhc9K7w20jJG5A/edit.
> Close when you have watch the video and made any necessary comments.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/281.

## 

Roger F Malina
is in Dallas
1-510-853-2007
