### ISSUE TITLE
Old Podcast URLs

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#283]
Go back through all podcast and check if they have the URL within the description. Close when you have checked all previously published podcasts.

**Comment by coreysmart92** [comment]
I have gone through and checked/fixed Rhythmically Inclined, RAMI, Within the Margins, Noisy People, Cellphonia, Audiolats. (9/1/15

**Comment by cassininazir** [comment]
@coreysmart92 feel free to solicit team members for help. You may assign them in GitHub.

**Comment by coreysmart92** [comment]
The Johannesburg Rocket Factory has a youtube video as a link. When inputting the link it adds the video to the webpage. Do we want this or just the link? (10/6/15)

**Comment by coreysmart92** [comment]
I have gone through and checked/fixed Space Art and Culture, Frank Malina, Bold Roast, Indie Game Nation, Voices from the Crowd, Pioneers and Pathbreakers. Still have to finish: Virtual Africa, Sound & Data, Art and Earth Science, New Leonardos, Meta-Life, Adventures in Crowdfunding, Cinemersia, Thoughts on Big Design.
Close: After the following are checked/fixed. Then open a new issue to fix all links to remove http://www. 
(10/6/15)

**Comment by coreysmart92** [comment]
Closing: I have checked/fixed all urls in old podcast.
Now creating an issue to standardize formatting of all of them. (10/7/15)
