### ISSUE TITLE
miriam sedel podcasts for art and climate change

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#284]
corey
would you be willing to work with me to get these podcasts in the door
before mid november ?

roger

Miriam Seidel miriamseidel1@gmail.com
3:24 PM (5 hours ago)

to rmalina, Diane 
Dear Dr. Molina,

We saw your call for podcasts through the LinkedIn Scientist Artist Collaborations Group, and would like to propose a podcast for your planned Creative Disturbance podcast series, Art and Science of Climate Change. The podcast would offer a conversation between artist Diane Burko and me, about how her work addresses the urgent issue of climate change. 

Diane Burko is known for her visual explorations of climate change through paintings and photographs, notably her ongoing Politics of Snow series. She has traveled to polar regions including the Arctic island of Svalbard, Greenland, the Southern Patagonian ice field of Argentina, and the Antarctic, gathering information and images for her work. Her paintings and photographs on this subject have been included in numerous exhibitions including the Zimmerli Museum of Rutgers University, Locks Gallery in Philadelphia, and the National Academy of Sciences in Washington D.C., among others. 

As an art critic and curator based in Philadelphia, I have known Diane Burko and her work for many years, since interviewing her for a weekly newspaper here. Last September, we traveled together to the People’s Climate March in New York. I have written many reviews and articles on contemporary art for Art in America, where I was a Corresponding Editor, as well as for the Philadelphia Inquirer, ARTNews, Art on Paper, Philadelphia Magazine, and Public Art Review. As a curator, I have organized several exhibits addressing environmental issues including climate change. 

You can read more about us at www.dianeburko.com and www.miriamseidel.com. 

Best wishes,
Miriam Seidel

**Comment by coreysmart92** [comment]
I have been emailing with Miriam Seidel, she plans to record the podcast mid-October. (9/14/15)

**Comment by porteriffic** [comment]
@coreysmart92 Please provide an update.

**Comment by coreysmart92** [comment]
I have emailed again on 11/1/15, yet to receive a response.

**Comment by porteriffic** [comment]
@coreysmart92 Did you use the Creative Disturbance email or your personal one?

**Comment by coreysmart92** [comment]
Closing: This podcast has been submitted and edited. It will be published 12/1/15. (11/30/15)
