### ISSUE TITLE
pioneers podcast with judy malloy

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#285]
corey
i just put in the new leonardos drop box a podcast with pionner
judy malloy
its for publication on the pioneers and pathbreakers channel
but i dont see to have access to that folder

an you confirm you can find the podcast file

and a woman pioneer !! so lets give it priority

roger

**Comment by rmalina** [comment]
corey
can you take over the correspondce with judy and send her the final version for approval\
roger

yes fine of course
corey
can you make sure you use the pre edited podcast with judy malloy
roger

**Comment by coreysmart92** [comment]
Closing: This podcast has been published. (10/15/15)
