### ISSUE TITLE
swiss web site for our aggregator mechanism

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#287]
josephine
talk to cassini
given they are already publishing podcasts we just
need to aggregate their podcasts with their agreement
with no additional paperwork
@cassininazir @yvantina 

roger

Finally got a response. Here's what he said:

Hello Josephine.

Yes, we where interesting, but I've read all of the conditions to be in Creative Disturbance, and it was a lot of things, complicated. Like the fact we must have like a contract with all of our host, we can't do that, it's to complicated and we made interview with Skype, we don't meet all of our guest.

Creative Disturbance make a good job, for sure, and we are interesting to be a part in the project, but we are just two to work in the project, with a lot of work, and we can't spend hours just to have a channel. It's possible to have a more simple way to do that ?

Sorry for my bad English, and I hope we can work together !

Best,

Jonathan

So it seems with all the forms and guest release forms that it's a bit complicated for him, especially since his English is not very good. I think he may be overthinking it or getting things confused, but I understand everything can seem overwhelming for a potential producer.

yvantina
6:21 PM (2 hours ago)

to creativedistur., me 
if we talk about it during next meeting I can write him an email afterwards to try to remove his fears and complexes..

**Comment by amb141330** [comment]
Will revisit this soon.

**Comment by rmalina** [comment]
No hurry on this one
Get the Portuguese and Turkish channels up

**Comment by amb141330** [comment]
Would like to revisit this, but there's no contact information for me to contact them by.

**Comment by yvantina** [comment]
Same people than for the late Anthropodcast channel, you just deleted that issue.
Just in case, here's the email address of the potential producer Jonathan Maitrot  webmaster@voyagecast.ch 
Not sure it worth it though
