### ISSUE TITLE
COP 21 Art and Climate Change Prep

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#288]
sorry
i cant find the github item on t he cop 21  art ajnd climate change for november
not sure who to assign this to-is someone in charge of this splash page ?

roger

i have registered us for the art and cop21 committee

we need to start NOW getting art and climate change podcasts
did the CD liaison talk to susan erickson about it ?

roger

Dear roger malina,

Thank you for registering your event Creative Disturbance: Art and Climate Change with ArtCOP21.

We will be reviewing all event submissions and will get back to you as soon as we can using the details you've provided. The registration details are copied below for your reference.

If you have a question or need further information, please don’t hesitate to contact us.

Thank you again, 
The ArtCOP21 Team, www.artcop21.com

ARTCOP21 EVENT REGISTRATION

EVENT CONTACT
Organisation name

Creative Disturbance

Contact person

roger malina

Email address

rmalina@alum.mit.edu

Phone number

5108532007

Preferred language

English

EVENT DESCRIPTION
ENGLISH

Event title

Creative Disturbance: Art and Climate Change

Event by

Creative Disturbance

Summary

We are publishing a number of podcasts leading up to COP21 on art and geosciences and art and climate change. We welcome submissions. Check out Creativedisturbance.org
Some of the podcasts to date can be found at http://creativedisturbance.org/channel/art-and-earth-science/

Event description

Creative Disturbance is the podcast platform for the art-science technology community:
http://creativedisturbance,org
We feature 20 channels on different art science topics ranging from art and biology, to art and space exploration

We are publishing a number of podcasts leading up to COP21 on art and geosciences and art and climate change. We welcome submissions. Check out Creativedisturbance.org
Some of the podcasts to date can be found at http://creativedisturbance.org/channel/art-and-earth-science/

Credits

FRENCH

Event title

Creative Disturbance" Art et Changement Climatique

Event by

Creative Disturbane

Summary

Nous publions des podcasts sur l'occasion de CPOP 21sur art et changement climatique,up to COP21 on art and geosciences and art and climate change. Nous solicitons des soumissions pour publication.. Voir Creativedisturbance.org
Ecouter des podcasts deja a ://creativedisturbance.org/channel/art-and-earth-science/

Event description

Creative Disturbance est une podcast platforme sur les relations arts-sciences=technologies
\Nous publions des podcasts sur l'occasion de CPOP 21sur art et changement climatique,up to COP21 on art and geosciences and art and climate change. Nous solicitons des soumissions pour publication.. Voir Creativedisturbance.org
Ecouter des podcasts deja a ://creativedisturbance.org/channel/art-and-earth-science/

Credits

EVENT DETAILS
Date
Start date

2015-11-20

End date

2015-12-10

Time
Start time

00:00

End time

00:00

Or all day

All day

Special notes

Location
Venue name

roger malina

Address

university of texas at dallas

City/town

Richardson

State/country

Texas

Postcode

75080-3021

Country

USA

Event Type
Event Type

Talks

Further information
Further info URL

http://www.creativedisturbance.org

Tickets
Entrance charge

No

How much

Booking page URL

IMAGES & MEDIA

Your logo:

cd-logo-english-e1436328780705.png

Link:

Main image:

art-and-earth-science.jpg

Credit:

creative disturbance

Image 2:

art-and-earth-science.jpg

Credit:

creative disturbance

Image 3:

Credit:

Image 4:

Credit:

Image 5:

Credit:

YouTube video:

ADDITIONAL

**Comment by rmalina** [comment]
Olivia Gray oliviagray@capefarewell.com via alum.mit.edu 
7:46 AM (1 hour ago)

to Cape 
Hello,

Thank you for registering to be a part of ArtCOP21 - I am pleased to say that your event has been chosen to be included on our website, which launches on the 17th September. When the website is up and running we will send you the link for your own promotion.

We will now start promoting all the fantastic climate-related events that have been accepted, so with this in mind please use #artcop21 and @artcop21 wherever possible. If you do this we will be able to see your posts and will share them onto our extended social media networks. Please also document any projects with images etc and again we will share via twitter and facebook. 

On the website there will also be a live social media feed, so any #'s that your visitors/staff/followers do will be included too.

Please also make sure to use the ArtCOP21 logos (attached) on any printed material.

A huge thanks to everyone for taking part, and we look forward to hearing/seeing all the amazing things that you fantastic people are organising right across the globe!

If you need any further information or assistance please do get in touch.

Best Regards,

Olivia

Instagram - @artcop21
Facebook - @artcop21
Twitter - @art_cop21

## 

---

Olivia Gray

## Research and Projects Assistant

Cape Farewell
University of the Arts London
Chelsea College of Arts
16 John Islip Street
London SW1P 4JU 

---

t:   +44 (0)20 7514 8079
e:  oliviagray@capefarewell.com

## w: www.capefarewell.com

www.facebook.com/capefarewell

**Comment by rmalina** [comment]
for our art and climate change push use these social media

Instagram - @artcop21
Facebook - @artcop21
Twitter - @art_cop21

roger

**Comment by porteriffic** [comment]
@rmalina I will forward this information to Susan. I've also added their social media accounts to the Feature Day Action plan for when it's time to do the social media push.

**Comment by porteriffic** [comment]
Just finished Skyping with Susan. Here are my notes:

Susan will contact:
- Tamara Ledley
  - Climate Literacy Network
  - Can provide other names
- Geological Society of America 
  - Takes place November 1-4 
  - Can possibly record podcasts
- Kathy Ellins

She told me to bug her in 3 weeks or on 9/30.

**Comment by yvantina** [comment]
Morgan Trevor will be a perfect fit for art and cop21 on virtual africa
would be great if I could sent him a blurb by the end the month

---------- Forwarded message ----------
From: Yvan Tina yvantina@gmail.com
Date: 2015-09-07 18:52 GMT-05:00
Subject: Re: LOVELY WEATHER: ART AND CLIMATE CHANGE: Proposal to submit a paper
To: Morgan Trevor morgan.trevor@unn.edu.ng

```
2015-08-27 16:16 GMT+02:00 Morgan Trevor <morgan.trevor@unn.edu.ng>:

    Please, here's my skype id: trevor.morgan81.
    We can talk between now and the next 2 hours. if you are not able to call I'm going to get another time for it, possibly by next week.

    Sorry for the delay. A number of things have being the reason for my inability to set out a time.

    Thanks

    On Sun, Aug 23, 2015 at 7:22 AM, Yvan Tina <yvantina@gmail.com> wrote:

        Hey Morgan

        Following back on this..haven't heard you for a long time
        hope you're fine - please let me know if we can do a skype call during the first week of september

        thanks

        2015-08-01 20:45 GMT-05:00 Yvan Tina <yvantina@gmail.com>:

            Hi Morgan

            just checking to know what would be your preferred date for a podcast..
            hope this finds you well !

            yvan

            2015-07-15 10:21 GMT-05:00 Yvan Tina <yvantina@gmail.com>:

                Hi Morgan

                What would be the most convenient time for you ?
                I'm happy to do this podcast between now and August 3rd..

                all the best

                yvan

                2015-07-14 5:19 GMT-05:00 Morgan Trevor <morgan.trevor@unn.edu.ng>:

                    Yes Tina,

                    Sorry for the delay in response. I shall be willing to talk about my work. But in few days I shall determine the appropriate time. Meanwhile, let me like to know when you think is best to get it done. I am just trying to set up my skype...

                    Thanks

                    Trevor
                -- 
                check out this website for more information on art, synthetic biology and a-life 
                http://synthbioart.texashats.org/
```

**Comment by porteriffic** [comment]
@yvantina Yes, please do! That would be great!

**Comment by yvantina** [comment]
Josephine - I would need a draft. Do you already have something I can share ?

**Comment by porteriffic** [comment]
@yvantina The only description and info I have on COP21 is in the [Feature Day Action Plan](https://docs.google.com/document/d/1lA0UaMrmaxg-rOLGox4mCvvn_tB3DBqwo5PoWWsPgZA/edit). Scroll down to number 5.

**Comment by rmalina** [comment]
josephine
i am happy to work on the cop21 material
who is the lead student on this one ?

roger

On Sat, Sep 12, 2015 at 5:39 PM, porteriffic notifications@github.com
wrote:

> @yvantina https://github.com/yvantina The only description and info I
> have on COP21 is in the Feature Day Action Plan
> https://docs.google.com/document/d/1lA0UaMrmaxg-rOLGox4mCvvn_tB3DBqwo5PoWWsPgZA/edit.
> Scroll to #5 https://github.com/creativedisturbance/podcasts/issues/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/288#issuecomment-139825557
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by porteriffic** [comment]
@rmalina No one is assigned to it yet. So far I've contacted Susan about it and I think Yvan might have a person to do a podcast with for COP21. That's as far as we've gone.

**Comment by porteriffic** [comment]
All team members have been assigned based on the [Feature Day Action Plan](https://docs.google.com/document/d/1lA0UaMrmaxg-rOLGox4mCvvn_tB3DBqwo5PoWWsPgZA/edit)

**Comment by rmalina** [comment]
hi
who is working on the art and climate change splash page
we are now up on the COP 21 web site
http://www.artcop21.com/events/creative-disturbance-art-and-climate-change/

they ask us to post their URL, LOGO and twitter hashtac details below
on our web site so these need to go on our splash page

who is assigned to work in the splash page for art and climate change
lets meet as soon as possible

roger

Bonjour,

Vous avez proposé un événement à l’agenda culturel Paris Climat 2015.

Nous sommes ravis de vous annoncer que votre événement a été sélectionné et qu’il est aujourd’hui visible sur notre plateforme www.artcop21.com
Nous vous invitons à consulter votre fiche événement et à nous faire part de toute demande éventuelle de modification à l’adresse suivante : communication@artcop21.com

Nous vous demanderons également de bien faire apparaître les éléments suivants sur vos outils de communication:
- Le logo ArtCOP21 avec la mention « ArtCOP21 – Agenda culturel Paris Climat 2015 » ;
- Le site internet www.artcop21.com;
- Le #ArtCOP21

Enfin, n’hésitez pas à revenir vers nous si vous avez besoin de plus amples informations pour votre communication concernant l’ensemble du programme ArtCOP21.

L’équipe ArtCOP21,
@porteriffic @coreysmart92

**Comment by porteriffic** [comment]
@rmalina All team member have been assigned to their roles according to the Feature Day Action Plan.
- Description - Josephine
- Splash Page - Corey
  - Replace Creative Disturbance logo on homepage with bumper graphics that links to splash page
  - Create the splash page (example here and here) that is linked from the home page (instructions on - CD 2.2.6.1)
  - Graphics - Lina
  - Facebook - 1200x900
  - Twitter - Square+
  - Blog Banner - 960x548
- Blog Post - Josephine
  - Explain content and celebration
  - Share blog post on social media platforms
- Social Media - Ashton
  - Use HootSuite (see CD 1.1.3 Passwords) to schedule posts Facebook, Twitter
- Email - Lina
  - Create emails to send out announcements, deadlines, etc.

**Comment by porteriffic** [comment]
Idea from Yvan: https://www.artsy.net/article/artsy-editorial-nine-artists-respond-to-climate-change

**Comment by yvantina** [comment]
3 artists to contact in Perth, Australia
Devon Ward  >> devon.ward@uwa.edu.au
Cat Jones >> catmjones@gmail.com
Loren Kronemyer >> l.kronemyer@gmail.com 

---------- Forwarded message ----------
From: Cat Jones catmjones@gmail.com
Date: 2015-10-08 21:12 GMT-05:00
Subject: Re: Art and Climate Change Podcasts for COP21 !!
To: Yvan Tina yvantina@gmail.com
Cc: Loren Kronemyer l.kronemyer@gmail.com, devon.ward@uwa.edu.au

Dear Yvan

It was a pleasure to meet you too and wish we could have talked some more!

Thanks so much for the information and links below and for the encouragement. Great to know that the podcasts are part of a strategy around cop21.

I look forward to reading more and more about what you are up to (and Roger) and hopefully making submissions.

all the best

Cat

Cat Jones
catjones.net
@_jonescat

2015 Projects 
Lamentable You, Sydney Art Month, March
Synapse, BiM UniSA, Adelaide, February and May
Distant Yet Connected, 643 Project Space, Ventura CA April
The Institute of Art and Olfaction, Los Angeles CA, April
Somatic Drifts, ANAT/Hawke Centre, Adelaide July
Force Majeure, Perth August
EcoSexual Bathhouse, Pony Express, Perth, September
NeoLife, SLSA Conference, Perth, October
National Experimental Arts Forum, Perth, October
Climate Century, Vitalstatistix, Adelaide October November

**Comment by yvantina** [comment]
Rebecca Perry looks at the effects of nuclear radiation on seashells
should be definitely contacted - can you put her in touch with Susan Eriksson for a podcast ?
rebperry@mit.edu
sciencesphere@gmail.com

Dear Yvan,
It was wonderful to meet you in Perth, and thank you for all of this good information and links! I hope we can find time to continue some of the interesting conversational threads in Houston. Are you presenting there?

You must be incredibly jet lagged, with such a quick trip to Australia. I'm settling in to a new job in a new state, and I am  feeling a bit "place-lagged."  I often spend time on the East Coast but never before in the south...it feels strange, though Fall is beautiful here.

I do not know Susan Eriksson, but she sounds great--I will definitely check out her work.  I look forward to exploring creative disturbance! Thanks again for our conversation and for staying in touch.

Warmly,

Rebecca

On Thu, Oct 8, 2015 at 10:13 PM, Yvan Tina yvantina@gmail.com wrote:

```
Dear Rebecca

it was a pleasure to meet you in Perth even though we didn't have time to interact as much as we could have - hopefully we'd be able to catch up in Houston..

so, as i said, it would be a great thing if you would like to share your work/research on creative disturbance http://creativedisturbance.org/      

and I thought I should bring this to your attention (see below)
it would be great to hear from you and to make the actual records before the beginning of the conference if you want to --  do you know Susan Eriksson ?? she runs the Art and Earh Science channel on Creative Disturbance and would be a great person to talk with http://creativedisturbance.org/people/susan-eriksson/ 

anyway, just wanted to keep in touch as i'm still recovering from the jetlag before it's too late
http://www.artcop21.com/events/creative-disturbance-art-and-climate-change/ 

hope this finds you well and do not hesitate to ask any question or concern you may have
feedback.creativedisturb@gmail.com

all the best

yvan



---------- Forwarded message ----------
From: roger malina <rmalina@alum.mit.edu>
Date: 2015-09-28 23:29 GMT-05:00
Subject: [Yasmin: Art and Climate Change- help us broadcast the trouble you are making for COP21 !!
To: yasmin_announcements <yasmin_announcements@estia.media.uoa.gr>


 Yasminers


Art and Climate Change- help us broadcast the trouble you are making
for COP21 !!

http://www.artcop21.com/events/creative-disturbance-art-and-climate-change/ 



CALL FOR PODCASTS

Join us in exploring how different fields push us towards a clean future

http://www.artcop21.com/events/creative-disturbance-art-and-climate-change/ 

Climate is everyone’s business. In anticipation of the United Nations
Conference on Climate Change (COP21) on Nov 15, Creative Disturbance
will feature podcasts discussing:

Sustainable global culture and economy
Environmental change and awareness
Ways citizens are active in promoting a greener future

Kind of podcasts to submit:

Professionals in the field can discuss if they already see changes
occurring to help the environment. What movements have they overseen
that are now successful?
Students can discuss how ways to encourage environmental change and
awareness. How important it is for us to implement these changes now?

Can’t submit a podcast? Other ways you can help:

Learn about COP21 and share the movement within your local community
Blog about promoting a green future
Spread the word on social media using #ArtCOP21 #FightForTheFuture

Facebook: Artcop21
Twitter: @art_cop21
Instagram: @artcop21

To learn more, please visit
http://www.artcop21.com/events/creative-disturbance-art-and-climate-change/ 


Some of our art and earth science podcasts can be heard at

http://creativedisturbance.org/channel/art-and-earth-science/ 


and we will be posting new podcasts regularly over the coming weeks

With much thanks,

The Creative Disturbance Team
```

**Comment by rmalina** [comment]
josephine- as soon as you fill better lets meet and plan a week by week task list for the cop21 art and climate change/ i am out next week oct 20-24
roger
@porteriffic

**Comment by yvantina** [comment]
@porteriffic A UTD student that might be of interest for COP 21  
http://www.utdallas.edu/news/2015/10/28-31758_Hall-of-Fame-Scholarship-Winner-Sees-Money-in-Sust_story-wide.html?WT.mc_id=NewsEmail

**Comment by porteriffic** [comment]
@yvantina Thanks, Yvan. I'll email him this week.

_Update_: Emailed Hazem.

**Comment by yvantina** [comment]
Just FYI - no pressure, just wanted to bring this to your attention !

Hello,

Below is some information about an upcoming NYC event regarding the art and science of climate change.
Thought you might be interested.  If the email is not displaying properly, please view it online here <https://vr2.verticalresponse.com/emails/14293651189741?contact_id=14293659617303&sk=a9qwB2JgNjBIby6ZRAPIF5PcQJn6sr8YYMSRwMyRiz28=/aHR0cHM6Ly92cjIudmVydGljYWxyZXNwb25zZS5jb20vZW1haWxzLzE0MjkzNjUxMTg5NzQxP2NvbnRhY3RfaWQ9MTQyOTM2NTk2MTczMDM=/3LaAsCuO9pDs8YyhZJhnlQ== 

> .  Additional information from Cooper Union is available here <http://cooper.edu/VCC
> .

Please let me know if you have any questions.

Thanks!

Melissa Fleming
—
Melissa Fleming
Web: www.melissafleming.com 
<http://www.melissafleming.com/ 

> Twitter: @mf_360

The Weather Gamut
Web: www.weathergamut.com 
<http://www.weathergamut.com/ 

> Twitter: @weathergamut
> 
> Begin forwarded message:
> 
> View Online x-msg://11/{VR_HOSTED_LINK}
>  x-msg://11/{VR_SOCIAL_SHARE_FACEBOOK} x-msg://11/{VR_SOCIAL_SHARE_TWITTER}
> 
> Glacial Lake, Alaska, 2013
> Art Update: November 2015
> Greetings!
> 
> Please join me on Monday, November 16th for two events at The Cooper Union Institute for Sustainable Design.
> 
> First, at 6PM, I will be giving a special lecture that I developed called “The Art and Science of Climate Change." Blending my two worlds, this slide presentation explores how art can help broaden the public conversation and create new pathways to understanding climate change.  It will introduce the basic science of climate change and explore how artists from around the globe are reacting to its diverse impacts and possible solutions. This event is co-sponsored by the SciArt Center <http://www.sciartcenter.org/ 
> .
> 
> After the talk, from 7PM to 8:30PM, there will be a reception for the group exhibition, "Visualizing Climate Change" in which I will be showing images from my ongoing series on American Glaciers <http://www.melissafleming.com/gallery.html?gallery=American%20Glaciers&folio=Portfolios 
> . The exhibit and reception will be held in the 7th Floor Lobby of the same building as the lecture. The show runs through November 23rd.  For more information about the exhibition please click here <http://cooper.edu/VCC
> .
> 
> The Cooper Union Institute for Sustainable Design
> The Cooper Union Foundation Building
> ​7 East 7th Street, Room 715
>  (between Third and Fourth Avenues)
> New York, NY 10003
> 
> TO ATTEND THE TALK, you must RSVP via email to: isd@cooper.edu mailto:isd@cooper.edu. Space is limited.
> 
> No RSVP is required for the exhibition reception following the talk.
> ​
> Hope to see you there!
> 
> All the best,
> Melissa
> 
> Primarily Color
> This image from my Wax Flora <http://www.melissafleming.com/gallery.html?folio=Portfolios&gallery=Wax%20Flora 
> series will be part of a group exhibition called "Primarily Color" at the Atlantic Gallery in Chelsea from December 1-12.
> 
> Opening Reception:
> ​Thursday, December 3 from 5-8 PM.
> 
> The Atlantic Gallery
> 548 West 28th Street, Suite 540
> New York, NY 10001
> 
> Inquiries
> Please contact me to arrange a presentation of "The Art and Science of Climate Change" for your organization.
>  x-msg://11/{VR_TWITTER_URL}
> Stay in Touch!
> Web: www.melissafleming.com 
> <http://www.melissafleming.com/index.html 
> 
> Email: mf@melissafleming.com mailto:mf@melissafleming.com
> Twitter: @mf_360 <https://twitter.com/MF_360
> 
> Studio Melissa Fleming
> melissafleming.com 
> <http://melissafleming.com/ 
> 
> New York, NY 10036
> 
> Update your Email Preferences x-msg://11/{EMAIL_PREFERENCES} or Unsubscribe x-msg://11/{UNSUBSCRIBE_LINK}
>  x-msg://11/{VR_MARKETING_URL}

**Comment by porteriffic** [comment]
@yvantina Very cool! I'll email her this week. Thank you!

**Comment by yvantina** [comment]
When art meets science meets climate change issues meets education meets pleasure ....

I know I know.. Just FYI for podcasts in Spanish 
http://www.smproart.com/sm-news/
