### ISSUE TITLE
meta-life audiolats podcasts

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#289]
@coreysmart92 @halclark @amb141330 @porteriffic 

Hey guys ! Can you please place those podcasts under the Meta-Life channel as well ? as they belong to the two channels
"Performing with Jellyfishes ..."
"Taste of Flesh... O'Brien"
"Taste of Flesh...Jareh Das"

more generally Audiolats podcasts are meant to go on their associated channel when they share common topics (either on space art, virtual africa, pioneers or meta-life) - note that this is only one way: from Audiolats to its associated channel = not every 'associated podcast' will go to Audiolats. If you need to identify the topics or have any doubt  (e.g podcast in french) please let me or Annick know but if the relationship seems obvious please go ahead and feed the correspondant disturbance with the existing Audiolats soundcast - so they can appear on both channels and have more visibility
Thanks

**Comment by coreysmart92** [comment]
Closing: All of the three podcast above have been checked/fixed, they all have Meta-Life as the secondary channel. (9/8/15)

**Comment by yvantina** [comment]
seems like we have a problem with O'brien's picture and the "Performing with Jellyfishes ..." podcast
