### ISSUE TITLE
DropBox Update

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#29]
Just based on my recent communication with Tim Perkis:

I shared the Noisy People dropbox folder with him and he was unable to upload his podcasts. It seems the only way he can upload is if I invite him to the CD Dropbox. I'm not sure if he tried dragging and dropping his podcasts though...

I'd like to test this out on someone who doesn't have access to the dropbox yet and see if they are running in to the same issues. Unless there's a completely simple way around this that I have forgotten or haven't discovered.

**Comment by cassininazir** [comment]
Good idea. Try testing with another email account (setup a new one just for this if you like).

Do you know what error message he received?

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by porteriffic** [comment]
Hmm. Okay. I tried using my UTD email to see if I had any issues accessing the DropBox. It might be that I'm accessing the DropBox from the same computer. Maybe this issue pops up when the user has never used DropBox before...

**Comment by porteriffic** [comment]
This is what Tim said:

"Dropbox solution doesnt work for me without it trying to download to my hardrive a local copy of everything in every Creative Disturbance channel folder!  I don't want that!"

**Comment by porteriffic** [comment]
He should still be able to access the Dropbox on a web browser. He can just ignore or refuse to download Dropbox on his hard drive... Idk...

**Comment by cassininazir** [comment]
Ok. Kyle and I investigated. Looks like the _solution_ is to move all channel information to the top-level of Dropbox. I haven't done this because it will require sending out new invites to producers again. 

So, everything here:

![screen shot 2015-04-14 at 2 53 18 pm](https://cloud.githubusercontent.com/assets/1661430/7146011/0ca3e856-e2b6-11e4-8af6-9854cf4e95d0.png)

Will need to be moved here:

![screen shot 2015-04-14 at 2 53 32 pm](https://cloud.githubusercontent.com/assets/1661430/7146012/115e9512-e2b6-11e4-8749-8c7623d3053f.png)

And then re-invite producers to the space.

**Comment by cassininazir** [comment]
Also, Dropbox had functionality to share sub-folders at one point. Looks like it is now only for Pro and Business users.

**Comment by porteriffic** [comment]
Would you mind going over this with me sometime this week, Cassini?

**Comment by porteriffic** [comment]
Ashton, I'll work with you on reorganizing DropBox

**Comment by cassininazir** [comment]
@amb141330 please work with @porteriffic on this. We need to this up as soon as possible. Producers are unable to upload podcasts. 

Let me know if by Wed, May 13 if you need help with this.

**Comment by cassininazir** [comment]
Just FYI, we get 100GB from Box.com. http://utdallas.app.box.com

**Comment by porteriffic** [comment]
Do I log in with my Net ID or does it have to be an ArtSciLab log in?

**Comment by cassininazir** [comment]
_Net ID_. I did some exploring and this can be a space that we use for the internal team. 

Google Drive gives us 15 GB of space. Box gives us 100 GB and as Roger indicated in another GitHub issue, we may be able to request additional space. 

Not sure that we'll need it, but thought to add it here as a resource.

@amb141330 any status update on progress?

**Comment by porteriffic** [comment]
Okay. I'll look into it. I'd like to have the Dropbox cleaned up. I'll work on it a little tomorrow.

**Comment by porteriffic** [comment]
Updated the Dropbox as @cassininazir mentioned with @amb141330 on Friday 5/15. Will be sending producers access to individual channel folders soon.

**Comment by cassininazir** [comment]
[CD 2.2.2.9a Archiving Podcasts](https://docs.google.com/document/d/1IoYkLJMJkRPqp_F7HD6GZE1EBzCghXxbdZ_tiY6MdQU) explains current thinking on setup.

**Comment by rmalina** [comment]
for what its worth- i am proposing we not assign DOIs to podcasts until the aggregator starts operation at mit press early next year-dont know if this affects this discussion

**Comment by porteriffic** [comment]
I will be cleaning up Dropbox more and start transitioning Producers to new folders.

**Comment by porteriffic** [comment]
Transferred Dropbox to @kkondas. He will be in charge of Dropbox from now on.
