### ISSUE TITLE
Carlos Harleaux Podcast - Missing Forms

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#290]
@halclark @rmalina This is an issue to keep track of the Carlos Harleaux podcast forms. Currently Carlos Harleaux for Bold Roast is missing forms. Close this issue when the forms are completed. (9/8/15)

**Comment by rmalina** [comment]
corey
here is status=
wait for his reply before publishing
roger

carlos
here mis the form i filled out for your podcast
can you look at the text for the pocast description
i need the name and url of your project indieblok ?

if you see any other corrections that need making
make them and send the form back to me

sorry its taken so long for me to get to this

i enjoyed doing the podcast with you- if you
ever want us to publish a podcast about your
work again in the future would be delighted to do it

roger
---------- Forwarded message ----------
From: CREATIVE DISTURBANCE no-reply@wufoo.com
Date: Sun, Sep 20, 2015 at 12:56 PM
Subject: CREATIVE DISTURBANCE - New Podcast Info Form
To: rmalina@alum.mit.edu

This is confirmation that you have uploaded a new Podcast for you Creative Disturbance Channel.

CREATIVE DISTURBANCE - New Podcast Info Form
Channel Name \*  
New Leonardos
Producer's Name \*   roger malina
Producer's Email \*  rmalina@alum.mit.edu
Podcast Title \* 
Kickstarting new Characters and different Endings for a Novel
Short Description of this Podcast \* 
Carlos Harleaux ( www.peauxeticexpressions.com ) discusses with Roger Malina his work as an on line poet who succesfully crowdfunded via kickstarter his latest novel "Fortune Cookie"; kickstarter donors above a giving level can be a character in the book, or each get a different version of the novel ending. Harleaux and also his resource site for online and digital writers called Indiblock- carlos what is speling and url

Key Words for this Podcast \*  
poetry, digital literature, crowdfunding, kickstarter
Date of Recording \* Monday, August 3, 2015
Has the sound file been uploaded to CD Google Docs under "Podcasts-Need Editing"? \* 
Yes
Method of Recording this Podcast \*  
In Person
Estimated Length of Podcast (in Minutes)  
15
Primary Language of this Podcast \*  
English
Website (if any) specific to this Podcast   http://www.peauxeticexpressions.com
Host (if not Producer)  
roger malina
Did the Host (if not Producer) complete a Guest Release Form(s)?  
Yes
Guest \* 
Carlos Harleaux
Short Bio of Guest \*  
Carlos Harleaux is a poet and author of three poetry books, Blurred Vision, Hindsight 20/20 and Honesty Box. In 2013, he started his own publishing company, 7th Sign Publishing, which has released 6 books to date. Later this year, he will be releasing his first novel Fortune Cookie, which he used Kickstarter to raise funds for (https://www.kickstarter.com/projects/1458478645/fortune-cookie-a-novel). He currently works at Frito Lay in the Supply Chain division and is a graduate student in the EMAC program at UTD.
Photo of Guest (preferably square and no less than 400 x 400 pixels)  
carlos_harleaux.jpg
59.34 KB · JPG
Email of Guest \*    carlos.harleaux@gmail.com
Did the Guest(s) complete a Guest Release Form(s)? \*  
Yes
Guest's Website (if any)    http://www.peauxeticexpressions.com
May CD publish Guest's website (if any)?  
Yes

This email notification is powered by Wufoo, the free online form builder. 
Make your own HTML forms for free at wufoo.com

GET STARTED!

@coreysmart92 
Roger F Malina
is in Dallas
1-510-853-2007

**Comment by coreysmart92** [comment]
The forms are in but the podcast file has not be added to Libsyn. @halclark can you add the completed version on to Libsyn. (9/28/15)

**Comment by rmalina** [comment]
am confused

you have the form and the podcasts right
it just needs to be published

do you need anything from me ?

roger

On Mon, Sep 28, 2015 at 11:41 AM, coreysmart92 notifications@github.com
wrote:

> The forms are in but the podcast file has not be added to Libsyn.
> @halclark https://github.com/halclark can you add the completed version
> on to Libsyn. (9/28/15)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/290#issuecomment-143799845
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by halclark** [comment]
No, we don't need anything else. About to upload the podcast to libsyn. Thanks roger!
