### ISSUE TITLE
Christopher Germann - Missing Podcast Forms

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#291]
@coreysmart92 @rmalina This issue is to keep tracking of Christopher Germann's Bold Roast podcast form completion. Close this issue when the forms are complete. (9/8/15)

**Comment by rmalina** [comment]
corey
i have filled out the form for christopher germann and will tell you once
he has approved the form

roger
@coreysmart92

**Comment by rmalina** [comment]
corey

you have the guests approval to publish this podcast if you make the
changes and use this version of the form

roger

On Sun, Sep 20, 2015 at 2:04 PM, Christopher Germann christopher.germann@plymouth.ac.uk wrote:
Hi Rodger,

looks really good - many thanks for your efforts! I made some minor adjustments to the title, the description, and the biography section. 
I look forwards to listening to the podcasts. You are a great conversationalist and I thank you very much for this! Hopefully my DMT-rap doesn't sound too bugged-out  ;-)

Cheers,

Chris

Am 20.09.2015 um 19:37 schrieb roger malina:
chris

i finally did the form on our podcast ( we had a reall interesting discussion !)
if you want to edito/change anything if filled out do so and send it back to
me and send the form to me-if its ok just ok it

look forward to futher interactions and if you ever have podcasts you
would like to publish would be delighted to do so

roger
---------- Forwarded message ----------
From: CREATIVE DISTURBANCE no-reply@wufoo.com
Date: Sun, Sep 20, 2015 at 1:34 PM
Subject: CREATIVE DISTURBANCE - New Podcast Info Form
To: rmalina@alum.mit.edu

This is confirmation that you have uploaded a new Podcast for you Creative Disturbance Channel.

CREATIVE DISTURBANCE - New Podcast Info Form
Channel Name \*  
new leonardos
Producer's Name \*   Roger Malina
Producer's Email \*  rmalina@alum.mit.edu
Podcast Title \* 
From Quantum Cognition and Decision Making to the role of DMT in the brain
Short Description of this Podcast \* 
Christopher Germann and Roger Malina discuss Chris' current work in the CogNovo PhD program, on quantum cognition which applies the mathematical formalisms of quantum theory to understanding cognitive processes. Chris is currently working on non-commutativity in decision theory, with laboratory experiments in visual decision making. He is also studying the role of the endogenous neurotransmitter DMT (N,N-Dimethyltryptamine) in perception and cognition.
Key Words for this Podcast \*  
serotonin, cognition, philosophy of science, creativity
Date of Recording \* Friday, July 31, 2015
Has the sound file been uploaded to CD Google Docs under "Podcasts-Need Editing"? \* 
Yes
Method of Recording this Podcast \*  
In Person
Estimated Length of Podcast (in Minutes)  
15
Primary Language of this Podcast \*  
English
Did the Host (if not Producer) complete a Guest Release Form(s)?  
I Don't Know
Guest \* 
Christopher Germann
Short Bio of Guest  
Chris Germann is a Marie-Curie research fellow in the CogNovo doctoral programme at the Cognition Institute of Plymouth University, which is
government-funded by the European Commission. Chris has broad interdisciplinary interests and he is momentarily mainly focusing on cognitive psychology and neuroscience. He is particularly interested in irrationality and decision making and the neuronal Serotonin system and its role in perception and cognition (for instance, creativity and neuroplasticity). Furthermore, philosophy of science and mind capture his deepest curiosity.
Photo of Guest (preferably square and no less than 400 x 400 pixels)  
christopher_germann_.jpg
18.36 KB · JPG
Email of Guest \*    christopher.germann@plymouth.ac.uk
Did the Guest(s) complete a Guest Release Form(s)? \*  
Yes
Guest's Website (if any)    http://www.cognovo.eu/christopher-germann
May CD publish Guest's website (if any)?  
Yes

**Comment by coreysmart92** [comment]
Closing: The forms are in and the podcast is scheduled to publish. (9/28/15)
