### ISSUE TITLE
Agi Haynes - Missing Podcast Forms

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#293]
@halclark @rmalina This issue is to keep track of Agi Haynes Bold Roast form completeion. Close when the forms are complete. (9/8/15)

**Comment by rmalina** [comment]
can you confirm she filled out the rights release form ?
same for the others you sent me emails for
roger

On Tue, Sep 8, 2015 at 2:38 PM, coreysmart92 notifications@github.com
wrote:

> Assigned #293 https://github.com/creativedisturbance/podcasts/issues/293
> to @rmalina https://github.com/rmalina.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/293#event-404055792
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by rmalina** [comment]
corey
i have filled out the form
roger
@halclark

On Tue, Sep 8, 2015 at 2:38 PM, coreysmart92 notifications@github.com
wrote:

> @halclark https://github.com/halclark @rmalina
> https://github.com/rmalina This issue is to keep track of Agi Haynes
> Bold Roast form completeion. Close when the forms are complete. (9/8/15)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/293.

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by rmalina** [comment]
corey hal
i mispelled agi's name in the pocast form

can you fix

roger

@halclark   @coreysmart92 
Agatha Haines via alum.mit.edu 
11:56 AM (5 hours ago)

to roger 
Hi Roger,

Yes this is great, the only thing is that my name is spelt with an i as in Haines.
Thanks.

Looking forward to listening to the others,
All the best,
Agi

---

Agi Haines
Speculative Designer
Research Fellow: CogNovo (Marie Curie ITN)
Contributing Researcher: Transtechnology Research
University of Plymouth
www.agihaines.com
www.cognovo.eu
www.trans-techresearch.net

**Comment by coreysmart92** [comment]
Closing: I have fixed this. (9/28/15)
