### ISSUE TITLE
art video history and beyond

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#295]
@halclark 
Hal
please follow this discussion for ideas on guests we should invite
for our art and video history video day
see moderator list at the bottom of the page

---------- Forwarded message ----------
From: empyre-request@lists.artdesign.unsw.edu.au
Date: 2015-09-09 21:00 GMT-05:00
Subject: empyre Digest, Vol 129, Issue 2
To: empyre@lists.artdesign.unsw.edu.au

Send empyre mailing list submissions to
        empyre@lists.artdesign.unsw.edu.au

To subscribe or unsubscribe via the World Wide Web, visit
        http://lists.artdesign.unsw.edu.au/mailman/listinfo/empyre

or, via email, send a message with subject or body 'help' to
        empyre-request@lists.artdesign.unsw.edu.au

You can reach the person managing the list at
        empyre-owner@lists.artdesign.unsw.edu.au

When replying, please edit your Subject line so it is more specific
than "Re: Contents of empyre digest..."

----------empyre- soft-skinned space----------------------

Today's Topics:
1. Re: -empyre- September, 2015, Video: Behind and Beyond (ETC)
2. Re: -empyre- September, 2015, Video: Behind and Beyond
     (carolyn tennant)

---

Message: 1
Date: Tue, 8 Sep 2015 20:48:02 -0400
From: ETC etc@experimentaltvcenter.org
To: soft_skinned_space empyre@lists.artdesign.unsw.edu.au
Subject: Re: [-empyre-] -empyre- September, 2015, Video: Behind and
        Beyond
Message-ID:
        <CABaSjUANve6M_OU+sRsM4insJz3veadOtyZdVsPBhpOWgX76Uw@mail.gmail.com>
Content-Type: text/plain; charset="utf-8"

First, thanks to empyre ? and especially to Tim and Renate ? for the
invitation to participate this month. I have been a long time, mostly
silent observer, and have learned so much over the years from all of you.

I have spent over 40 years working with the ETC, a (very) small ? and
intentionally so ? media arts ?organization? in Upstate New York. When we
decided to end the Residency, Research, Grants and Sponsorship programs at
ETC in 2011, I was often asked, ?So, are you closing? Will you retire??

I was unprepared for the query and had no answers. I didn?t feel retired. I
looked at the ?? open reel videotapes which still fill our beer cooler qua
climate-controlled storage facility, and wondered about our respective
fates.

At the time we closed many of the ETC programs, I was very involved with
Kathy High and Mona Jimenez, along with many brilliant scholars and
artists, on completing the two volume book ?The Emergence of Video
Processing Tools: Television Becoming Unglued?. Once the book was finally
published in 2014, I took a step back and reconsidered some of the topics
we had tried to address: from ideas as general as how do art, science and
technology intersect, and are the collaborations that evolve specific to
cultural and social environments; to topics as specific as those involving
talk of codecs, wrappers and containers.

We became involved in the topics of media history and preservation in the
1990s.
-  were among the founding organizations of the groups that became Media
  Alliance and Independent Media Arts Preservation
-  organized the conference Video History: Making Connections (Syracuse,
  1998)
-  participated in the National Moving Image Database (NAMID) project of
  the American Film Institute as they created a template for cataloging
  moving image media works, that addressed specific properties of electronic
  media as opposed to film
-  organized several symposia on preservation at Buffalo State College
  and in NYC in 2002
-  began (1996) and continue the History website.

Some of you were also at some of those meetings, I'm sure.

One result of the book was a mass of research materials, historical texts,
artists? statements, technical descriptions which have not been put on the
History site and even more questions:
-  how do we preserve instruments; what about functionality
-  where will the ephemera live: how do we preserve cultural context
-  can you preserve the ethos, the spirit, the hungers of a particular
  time
-  what is lost if ephemera is disassociated from instrument
-  how does history matter; looking back and looking forward with
  contemporary makers
-  how can we create environments that nurture collaborations of art,
  technology and science; can we devise models for the sustenance of these
  collaborations.
-  what are reasonable criteria for determining which works are
  preserved; by whom and how are these determined

ET is very grateful that the Rose Goldsen Archive of New Media Art at
Cornell has accepted the ETC?s collection of ephemera, to accompany our
videotape collection; it is a very compatible home for us. Over the summer
I had the privilege of working with two creative and intelligent Cornel
grad stuents, Alana Staiti and Lauren van Haaften-Schick, on constructing
an inventory for these materials. It proved to be an overwhelming,
exciting, hilarious, tedious, exhilarating and at time cringe-worthy
experience. It can be difficult to understand the history of something you
have been so much involved with.

The ephemera will form one of the major sections for the upcoming
exhibition organized by Hunter College Art Galleries and the Rose Goldsen
Archive of New Media Art at Cornell, "The Experimental Television Center: A
History, Etc . . . " opening at the Galleries on September 24th, and
running through November 21st. The exibition was organized by Tim Murray of
Cornell and Sarah Watson, Curator at Hunter. Also on view are videotapes by
over 40 artists, hand-crafted now obsolete analog processing equipment,
performances by contemporary artists working with custom-designed
instruments, and tools built by artist/technologists for day?s
practitioners.

We are always looking for conversations about video and its histories, and
I?m sure I?ve come to the right place.

Sherry

On Tue, Sep 8, 2015 at 1:42 PM, Timothy Conway Murray tcm1@cornell.edu
wrote:

> ----------empyre- soft-skinned space----------------------
> 
> Hello, -Empyreans-,
> 
> Now that the US holidays have passed and the heat of the summer has
> finally settled into Upstate New York, it's time to look to the fall
> startup of the 2015-16 season of -empyre?.  We look forward to a a
> wide-ranging discussion throughout the remainder of September of "Video and
> Beyond."  Information about the topic and this week's guests is below:
> 
> _September, 2015 Video: Behind and Beyond_
> 
> Moderated by Tim Murray (US) and Renate Ferro(US) with invited discussants
> 
> Week 1 September 8-13: Andrew Deutsch (US) Kathy High (US), Sherry Hocking
> Miller (US), Renate Ferro (US), Tim Murray (US) Isak Berbic (US),  John
> Conomos (AU), Carolyn Tennant (US)
> 
> Week 2 September  14-20: Megan Roberts (US), Raymond Ghirardo (US), Lynne
> Sacks (US), Alan Sondheim (US)
> 
> Week 3 September  21-26 Maureen Turim (US), Benton C Bainbridge ( US)
> 
> Week 4 September  27-30  Sarah Watson (US), Gabriel Menotti (BR), Anca
> Rujoiu (SG)
> In celebration of the legacy of the Experimental Television Center,
> -empyre- dedicates the month of September to discussion of ?Video: Behind
> and Beyond.?  For over forty years, the Experimental Television Center in
> Owego, New York, was one of North America?s preeminent residencies and
> funding sources for video art, fostering a community for creative and
> innovation in technology.  Through its residency program and practical
> research program artists worldwide passed through its doors.  The
> Experimental Television Center was founded by Ralph Hocking, in 1971, who
> collaborated with Nam June Paik and others in the creation of innovative
> tools used by ETC artists for experimental creation in and around video.
> Throughout the years both Ralph Hocking and Sherry Miller Hocking have
> provided support and services to the media and technology community by
> encouraging electronic media technologies and honoring independently
> creating moving-image history.  They have single handedly initiated
> projects that encouraged partnerships for research, education, and
> preservation.
> 
> During the month of September, we encourage discussion of the early days
> of video art and its movement beyond the analogue into pairings with
> digital technologies.  ETC fostered and encouraged these pairings from the
> very beginning.  In addition to hearing from international guests with
> specialized artistic and critical interests in video art, we will be joined
> by many of the artists and technicians who have been affiliated with ETC.
> 
> The month?s discussion coincides with a major exhibition, opening
> September 24, at the Hunter College Art Gallery in New York City with the
> collaboration of the Rose Goldsen Archive for New Media Art, which holds
> the ETC archive.
> 
>  the center over these past several years to celebrate the history and
> heritage of ETC during Week 1, to examine the affect of the center?s
> influence beyond the scope of a regional video center to an influential
> player in the digital and internet age nationally and globally during
> Week 2 and 3, and finally during Week 4 to discuss the Center?s
> preservation and archival drive for the future.
> 
> TO MAKE A POST TO THE SUBSCRIPTION LIST USE:
> 
> empyre@lists.artdesign.unsw.edu.au
> 
> TO ACCESS TEN YEARS WORTH OR ARCHIVES USE THIS URL:
> 
> http://lists.artdesign.unsw.edu.au/pipermail/empyre/
> 
> TO ACCESS THE WEBSITE FROM THE CORNELL SERVER TO FIND OUT MORE ABOUT
> EMPYRE GO TO:
> 
> *http://empyre.library.cornell.edu
> <http://empyre.library.cornell.edu
> *
> 
> Biographies:
> 
> Moderators:
> 
> Renate Ferro (US) Renate Ferro?s creative work resides in the area of
> emerging technology, new media and culture. By aligning artistic, creative
> practice with critical approaches to technology her work broadly spans
> installation, interactive net-based projects, digital time-based media,
> drawing, text, and performance. Her artistic work has been featured at The
> Freud Museum (London), The Dorksy Gallery (NY), The Hemispheric Institute
> and FOMMA (Mexico), The Janus Pannonius Muzeum (Hungary), and The Free
> University Berlin (Germany).  Her writing has been published in such
> journals as Diacritics, Theatre Journal, and Epoch.. She also is the
> founder of the Tinker Factory <http://www.tinkerfactory.net/ 
> Lab. Ferro
> is a Visiting Associate Professor of Art at Cornell University.  She has
> been on the moderating team for -empyre soft-skinned space since 2007 and
> is currently the managing moderator.
> 
> Tim Murray (US) Tim Murray is Curator of the Rose Goldsen Archive of New
> Media Art, Director of the Society for the Humanities and Professor of
> Comparative Literature and English at Cornell University.  A Moderator of
> -empyre-, he sits on the Executive Committee of the Humanities, Arts,
> Science, and Technology Advanced Collaboratory (HASTAC). Author of Digital
> Baroque: New Media Art and Cinematic Folds (Minnesota 2008) and Zonas de
> Contacto: el arte en CD-ROM (Centro de la imagen, 1999), he is completing
> two books on Virtual Archives and Media Art in Asia, and editing volumes on
> Jean-Luc Nancy and Xu Bing.
> 
> Weekly Guests:
> 
> Week 1
> 
> Isak Berbic (BA) is an artist primarily working with photography, moving
> image and performance. His recent artworks reimagine popular narratives,
> crossing them with social and personal histories, often appropriating
> anecdotes and myths, politics and contemporary issues, environmental and
> economic ecologies, art history, cooking, migration, humor, tragedy, the
> global circulation of images and the limits of representation. Reflecting
> on contested histories, he uses fiction and documents, found and primary
> material, exploring the image and the literary in the construction of his
> pieces. His work takes on different forms of presentation, including
> image-text-object installations, photographic prints, videos, actions,
> texts and publications.
> 
> John Conomos (AU) is an artist, critic and theorist who exhibits
> extensively both locally and internationally.  He is an Associate Professor
> at Sydney College of the Arts, the University of Sydney.  His art practice
> cuts across a variety of art forms-video, new media, installation,
> photo-performance, and radio-phonic art?and deals with autobiography,
> identity, language, memory, post-colonialism and the ?in-between? links
> between cinema, literature, critical theory and the visual arts. Conomos is
> a prolific writer and artist. He is currently working on three new video
> projects.
> 
> Kathy High (US) is an interdisciplinary artist, educator working with
> arts and biology. In the early 1980's she studied for her masters in film
> and video at University of Buffalo with media pioneers Hollis Frampton,
> Steina Vasulka
> and Tony Conrad. She has received awards including Guggenheim Memorial
> Foundation, Rockefeller Foundation, and NEA. Her art works have been
> shown at Guggenheim Museum, Museum of Modern Art (NYC), Science Gallery,
> (Dublin), NGBK,
> (Berlin), Fesitval Transitio_MX (Mexico), MASS MoCA (North Adams),
> Videotage Art Space (Hong
> Kong). High is Professor of Video and New Media in the Department of Arts
> at
> Rensselaer. She was co-editor of The Emergence of Video Processing Tools:
> Television Becoming Unglued with Sherry Miller Hocking, Assistant
> Director of the Experimental Television Center, and Mona Jimenez,
> Associate Professor of the Moving Image and Preservation Program, In
> Cinema Studies at NYU, a two volume anthology about the history of video
> imaging tools, Intellect Books
> (UK)/Chicago University Press (IL), 2014.
> 
> Sherry Miller Hocking (US) has worked since 1972 with the Experimental
> Television Center, which until 2011 served the media arts community by
> providing an international residency program, educational opportunities and
> sponsorship for independent media and film artists and projects. For over
> 40 years she helped administer the artist in residence program, inviting
> over 1500 artists to create new works. She also worked to support
> individual artists? projects; ETC helped raise almost 2 million dollars in
> direct funding to media artists. For 22 years Hocking directed the
> Electronic Arts Grants Program, providing funding to individuals and arts
> organizations. In 1994 she designed and continues to direct the Video
> History Project, an online informational research database for media
> scholars worldwide. She has helped organize a number of preservation
> conferences, notably the _Video History Conference_ at Syracuse
> University.  With Kathy High and Mona Jimenez, she is co-editor of _The
> Emergence of Video Processing Tools: Television Becoming Unglued_(Intellect,
> 2014). The archives of ETC are in the collection of the Rose Goldsen
> Archive of New Media Art at Cornell University.
> http://www.experimentaltvcenter.org
> 
> Carolyn Tennant (US) has been a champion in Upstate New York of
> collaborative efforts to digitize and preserve video.   The Director of
> Archives and Migrating Media at Hallwalls Contemporary Art Center, in
> Buffalo, New York, Carolyn has been a primary consultant in efforts to
> archive the collections of the Experimental Television Center, Hallwalls,
> and other New York experimental venues.
> 
> Timothy Murray
> Professor of Comparative Literature and English
> Taylor Family Director, Society for the Humanities
> http://www.arts.cornell.edu/sochum/
> 
> Curator, Rose Goldsen Archive of New Media Art
> http://goldsen.library.cornell.edu
> 
> A D White House
> Cornell University,
> Ithaca, New York 14853
> ---
> 
> empyre forum
> empyre@lists.artdesign.unsw.edu.au
> http://empyre.library.cornell.edu
## 

Sherry Hocking
Assistant Director
Experimental Television Center Ltd.
109 Lower Fairfield Rd.
Newark Valley NY 13811
607.687.4341
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.artdesign.unsw.edu.au/pipermail/empyre/attachments/20150908/61581948/attachment-0001.html

---

Message: 2
Date: Wed, 9 Sep 2015 12:36:14 -0400
From: carolyn tennant carolyn@hallwalls.org
To: soft_skinned_space empyre@lists.artdesign.unsw.edu.au
Subject: Re: [-empyre-] -empyre- September, 2015, Video: Behind and
        Beyond
Message-ID: BC35650E-1F17-49BD-B7F6-3D8E3DAC1794@hallwalls.org
Content-Type: text/plain; charset="windows-1252"

Hello empyre!
Thanks for the invitation to participate, and in advance to all for what is sure to be an engaging conversation. And thank you Sherry for kicking off the conversation, in addition to ALL that you have done and continue to do!
Recently the "memories" function on Facebook reminded me that yesterday marks the anniversary of the Great Flood of Owego, back in 2011. While the ETC studio, which at that point had ceased operating as a residency space, did not suffer from the flood, the disaster resulted in an expedited move of the video library to Cornell University. It's exciting to know that the Center's paper archives and ephemera are now united with this A/V collection, and I look forward to learning how all of these materials will be made publicly accessible.
As a curator I have found that a chance to exhibit is a chance to preserve. Exhibitions have often led to the preservation of artist projects--either by requiring the resurrection of early electronic art works or the migration of media to new presentation platforms. When the Center produced its phenomenal DVD box set "Experimental Television Center: 1969-2009" many contributing artists benefited from the opportunity to preserve their early analog videos. I also look forward to learning more about the Hunter exhibition and how it has inspired the preservation of early ETC works.
Carolyn

On Sep 8, 2015, at 8:48 PM, ETC wrote:

> ----------empyre- soft-skinned space----------------------
> First, thanks to empyre ? and especially to Tim and Renate ? for the invitation to participate this month. I have been a long time, mostly silent observer, and have learned so much over the years from all of you.
> 
> I have spent over 40 years working with the ETC, a (very) small ? and intentionally so ? media arts ?organization? in Upstate New York. When we decided to end the Residency, Research, Grants and Sponsorship programs at ETC in 2011, I was often asked, ?So, are you closing? Will you retire??
> 
> I was unprepared for the query and had no answers. I didn?t feel retired. I looked at the ?? open reel videotapes which still fill our beer cooler qua climate-controlled storage facility, and wondered about our respective fates.
> 
> At the time we closed many of the ETC programs, I was very involved with Kathy High and Mona Jimenez, along with many brilliant scholars and artists, on completing the two volume book ?The Emergence of Video Processing Tools: Television Becoming Unglued?. Once the book was finally published in 2014, I took a step back and reconsidered some of the topics we had tried to address: from ideas as general as how do art, science and technology intersect, and are the collaborations that evolve specific to cultural and social environments; to topics as specific as those involving talk of codecs, wrappers and containers.
> 
> We became involved in the topics of media history and preservation in the 1990s.
> -  were among the founding organizations of the groups that became Media Alliance and Independent Media Arts Preservation
> -  organized the conference Video History: Making Connections (Syracuse, 1998)
> -  participated in the National Moving Image Database (NAMID) project of the American Film Institute as they created a template for cataloging moving image media works, that addressed specific properties of electronic media as opposed to film
> -  organized several symposia on preservation at Buffalo State College and in NYC in 2002
> -  began (1996) and continue the History website.
> 
> Some of you were also at some of those meetings, I'm sure.
> 
> One result of the book was a mass of research materials, historical texts, artists? statements, technical descriptions which have not been put on the History site and even more questions:
> -  how do we preserve instruments; what about functionality
> -  where will the ephemera live: how do we preserve cultural context
> -  can you preserve the ethos, the spirit, the hungers of a particular time
> -  what is lost if ephemera is disassociated from instrument
> -  how does history matter; looking back and looking forward with contemporary makers
> -  how can we create environments that nurture collaborations of art, technology and science; can we devise models for the sustenance of these collaborations.
> -  what are reasonable criteria for determining which works are preserved; by whom and how are these determined
> 
> ET is very grateful that the Rose Goldsen Archive of New Media Art at Cornell has accepted the ETC?s collection of ephemera, to accompany our videotape collection; it is a very compatible home for us. Over the summer I had the privilege of working with two creative and intelligent Cornel grad stuents, Alana Staiti and Lauren van Haaften-Schick, on constructing an inventory for these materials. It proved to be an overwhelming, exciting, hilarious, tedious, exhilarating and at time cringe-worthy experience. It can be difficult to understand the history of something you have been so much involved with.
> 
> The ephemera will form one of the major sections for the upcoming exhibition organized by Hunter College Art Galleries and the Rose Goldsen Archive of New Media Art at Cornell, "The Experimental Television Center: A History, Etc . . . " opening at the Galleries on September 24th, and running through November 21st. The exibition was organized by Tim Murray of Cornell and Sarah Watson, Curator at Hunter. Also on view are videotapes by over 40 artists, hand-crafted now obsolete analog processing equipment, performances by contemporary artists working with custom-designed instruments, and tools built by artist/technologists for day?s practitioners.
> 
> We are always looking for conversations about video and its histories, and I?m sure I?ve come to the right place.
> 
> Sherry
> 
> On Tue, Sep 8, 2015 at 1:42 PM, Timothy Conway Murray tcm1@cornell.edu wrote:
> ----------empyre- soft-skinned space----------------------
> Hello, -Empyreans-,
> 
> Now that the US holidays have passed and the heat of the summer has finally settled into Upstate New York, it's time to look to the fall startup of the 2015-16 season of -empyre?.  We look forward to a a wide-ranging discussion throughout the remainder of September of "Video and Beyond."  Information about the topic and this week's guests is below:
> 
> September, 2015 Video: Behind and Beyond
> 
> Moderated by Tim Murray (US) and Renate Ferro(US) with invited discussants
> 
> Week 1 September 8-13: Andrew Deutsch (US) Kathy High (US), Sherry Hocking Miller (US), Renate Ferro (US), Tim Murray (US) Isak Berbic (US),  John Conomos (AU), Carolyn Tennant (US)
> 
> Week 2 September  14-20: Megan Roberts (US), Raymond Ghirardo (US), Lynne Sacks (US), Alan Sondheim (US)
> 
> Week 3 September  21-26 Maureen Turim (US), Benton C Bainbridge ( US)
> 
> Week 4 September  27-30  Sarah Watson (US), Gabriel Menotti (BR), Anca Rujoiu (SG)
> 
> In celebration of the legacy of the Experimental Television Center, -empyre- dedicates the month of September to discussion of ?Video: Behind and Beyond.?  For over forty years, the Experimental Television Center in Owego, New York, was one of North America?s preeminent residencies and funding sources for video art, fostering a community for creative and innovation in technology.  Through its residency program and practical research program artists worldwide passed through its doors.  The Experimental Television Center was founded by Ralph Hocking, in 1971, who collaborated with Nam June Paik and others in the creation of innovative tools used by ETC artists for experimental creation in and around video.  Throughout the years both Ralph Hocking and Sherry Miller Hocking have provided support and services to the media and technology community by encouraging electronic media technologies and honoring independently creating moving-image history.  They have single handedly init
>  iated projects that encouraged partnerships for research, education, and preservation.
> 
> During the month of September, we encourage discussion of the early days of video art and its movement beyond the analogue into pairings with digital technologies.  ETC fostered and encouraged these pairings from the very beginning.  In addition to hearing from international guests with specialized artistic and critical interests in video art, we will be joined by many of the artists and technicians who have been affiliated with ETC.
> 
> The month?s discussion coincides with a major exhibition, opening September 24, at the Hunter College Art Gallery in New York City with the collaboration of the Rose Goldsen Archive for New Media Art, which holds the ETC archive.
> 
>  the center over these past several years to celebrate the history and heritage of ETC during Week 1, to examine the affect of the center?s influence beyond the scope of a regional video center to an influential player in the digital and internet age nationally and globally during Week 2 and 3, and finally during Week 4 to discuss the Center?s preservation and archival drive for the future.
> 
> TO MAKE A POST TO THE SUBSCRIPTION LIST USE:
> 
> empyre@lists.artdesign.unsw.edu.au
> 
> TO ACCESS TEN YEARS WORTH OR ARCHIVES USE THIS URL:
> 
> http://lists.artdesign.unsw.edu.au/pipermail/empyre/
> 
> TO ACCESS THE WEBSITE FROM THE CORNELL SERVER TO FIND OUT MORE ABOUT EMPYRE GO TO:
> 
> http://empyre.library.cornell.edu
> 
> Biographies:
> 
> Moderators:
> 
> Renate Ferro (US) Renate Ferro?s creative work resides in the area of emerging technology, new media and culture. By aligning artistic, creative practice with critical approaches to technology her work broadly spans installation, interactive net-based projects, digital time-based media, drawing, text, and performance. Her artistic work has been featured at The Freud Museum (London), The Dorksy Gallery (NY), The Hemispheric Institute and FOMMA (Mexico), The Janus Pannonius Muzeum (Hungary), and The Free University Berlin (Germany).  Her writing has been published in such journals as Diacritics, Theatre Journal, and Epoch.. She also is the founder of the Tinker Factory Lab. Ferro is a Visiting Associate Professor of Art at Cornell University.  She has been on the moderating team for -empyre soft-skinned space since 2007 and is currently the managing moderator.
> 
> Tim Murray (US) Tim Murray is Curator of the Rose Goldsen Archive of New Media Art, Director of the Society for the Humanities and Professor of Comparative Literature and English at Cornell University.  A Moderator of -empyre-, he sits on the Executive Committee of the Humanities, Arts, Science, and Technology Advanced Collaboratory (HASTAC). Author of Digital Baroque: New Media Art and Cinematic Folds (Minnesota 2008) and Zonas de Contacto: el arte en CD-ROM (Centro de la imagen, 1999), he is completing two books on Virtual Archives and Media Art in Asia, and editing volumes on Jean-Luc Nancy and Xu Bing.
> 
> Weekly Guests:
> 
> Week 1
> 
> Isak Berbic (BA) is an artist primarily working with photography, moving image and performance. His recent artworks reimagine popular narratives, crossing them with social and personal histories, often appropriating anecdotes and myths, politics and contemporary issues, environmental and economic ecologies, art history, cooking, migration, humor, tragedy, the global circulation of images and the limits of representation. Reflecting on contested histories, he uses fiction and documents, found and primary material, exploring the image and the literary in the construction of his pieces. His work takes on different forms of presentation, including image-text-object installations, photographic prints, videos, actions, texts and publications.
> 
> John Conomos (AU) is an artist, critic and theorist who exhibits extensively both locally and internationally.  He is an Associate Professor at Sydney College of the Arts, the University of Sydney.  His art practice cuts across a variety of art forms-video, new media, installation, photo-performance, and radio-phonic art?and deals with autobiography, identity, language, memory, post-colonialism and the ?in-between? links between cinema, literature, critical theory and the visual arts. Conomos is a prolific writer and artist. He is currently working on three new video projects.
> 
> Kathy High (US) is an interdisciplinary artist, educator working with
> arts and biology. In the early 1980's she studied for her masters in film
> and video at University of Buffalo with media pioneers Hollis Frampton, Steina Vasulka
> and Tony Conrad. She has received awards including Guggenheim Memorial
> Foundation, Rockefeller Foundation, and NEA. Her art works have been shown at Guggenheim Museum, Museum of Modern Art (NYC), Science Gallery, (Dublin), NGBK,
> (Berlin), Fesitval Transitio_MX (Mexico), MASS MoCA (North Adams), Videotage Art Space (Hong
> Kong). High is Professor of Video and New Media in the Department of Arts at
> Rensselaer. She was co-editor of The Emergence of Video Processing Tools: Television Becoming Unglued with Sherry Miller Hocking, Assistant Director of the Experimental Television Center, and Mona Jimenez, Associate Professor of the Moving Image and Preservation Program, In Cinema Studies at NYU, a two volume anthology about the history of video imaging tools, Intellect Books
> (UK)/Chicago University Press (IL), 2014.
> 
> Sherry Miller Hocking (US) has worked since 1972 with the Experimental Television Center, which until 2011 served the media arts community by providing an international residency program, educational opportunities and sponsorship for independent media and film artists and projects. For over 40 years she helped administer the artist in residence program, inviting over 1500 artists to create new works. She also worked to support individual artists? projects; ETC helped raise almost 2 million dollars in direct funding to media artists. For 22 years Hocking directed the Electronic Arts Grants Program, providing funding to individuals and arts organizations. In 1994 she designed and continues to direct the Video History Project, an online informational research database for media scholars worldwide. She has helped organize a number of preservation conferences, notably the Video History Conference at Syracuse University.  With Kathy High and Mona Jimenez, she is co-editor of The
>  Emergence of Video Processing Tools: Television Becoming Unglued(Intellect, 2014). The archives of ETC are in the collection of the Rose Goldsen Archive of New Media Art at Cornell University.     http://www.experimentaltvcenter.org
> 
> Carolyn Tennant (US) has been a champion in Upstate New York of collaborative efforts to digitize and preserve video.   The Director of Archives and Migrating Media at Hallwalls Contemporary Art Center, in Buffalo, New York, Carolyn has been a primary consultant in efforts to archive the collections of the Experimental Television Center, Hallwalls, and other New York experimental venues.
> 
> Timothy Murray
> Professor of Comparative Literature and English
> Taylor Family Director, Society for the Humanities
> http://www.arts.cornell.edu/sochum/
> 
> Curator, Rose Goldsen Archive of New Media Art
> http://goldsen.library.cornell.edu
> 
> A D White House
> Cornell University,
> Ithaca, New York 14853
> ---
> 
> empyre forum
> empyre@lists.artdesign.unsw.edu.au
> http://empyre.library.cornell.edu
> ## 
> 
> Sherry Hocking
> Assistant Director
> Experimental Television Center Ltd.
> 109 Lower Fairfield Rd.
> Newark Valley NY 13811
> 607.687.4341
> ---
> 
> empyre forum
> empyre@lists.artdesign.unsw.edu.au
> http://empyre.library.cornell.edu

-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.artdesign.unsw.edu.au/pipermail/empyre/attachments/20150909/fdae96ad/attachment-0001.html

---

**Comment by yvantina** [comment]
@halclark Hal, in case you're still missing for content for audio visual heritage

**Comment by porteriffic** [comment]
Closing since we're no longer doing Audiovisual Heritage.

**Comment by rmalina** [comment]
but we can still record podcasts on the topic
i will do the one with guy
roger

On Fri, Oct 23, 2015 at 5:45 PM, porteriffic notifications@github.com
wrote:

> Closing since we're no longer doing Audiovisual Heritage.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/295#issuecomment-150612746
> .

## 

Roger F Malina
is in Spain
