### ISSUE TITLE
Artisthinktive Iran: A Forum for Distinctive Thinking on Iranian Arts Channel

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#296]
@rmalina @cassininazir @porteriffic 
I had a meeting yesterday with Fatemeh Tashakori (ftphilosophy@googlemail.com ) who wants to be a disturber for a channel on contemporary and new media art from Iran. She and Moreshin were originally supposed to be the producers but Moreshin is actually too busy to assume that responsibility and said she would be happy to contribute from time to time - that's for the genealogy of the idea that goes back to last year. Fatemeh contacted me this week and shared with me two farsi podcasts she made while in Teheran this summer and said she's ready to open that channel. 
Josephine, can you or someone else share with her the producer forms she needs to fill out ?
Cassini, can you assigned someone to work on the logos and everything else ?
Roger, would you agree to publish those podcasts in Voices from the Crowd in the meantime ? they will be moved to her channel when ready.. I will help her on the first podcast info forms.. am uploading them on Gdrive as she doesn't already have access to Dropbox
I assume this is part of our multi-lingual and international strategy
yvan

**Comment by yvantina** [comment]
Forgot to mention that Fatemeh is doing a PhD in A&H. You probably know her already

**Comment by porteriffic** [comment]
@yvantina She can access the Producer Forms [here](http://creativedisturbance.org/forms/). I can email her if you'd like but it might be better if you remain her contact since you know her. I'll leave it up to you.

**Comment by yvantina** [comment]
@porteriffic I told her someone from the team will contact her and I think it looks more professional if you or someone else send her an email to assist her on the process. My support can be more informal (filling out the podcast forms, translations issues, etc) and i'll be in touch with her throughout the months but it's better if she feels like she's part of an organization - not just a friend of mine..

**Comment by porteriffic** [comment]
@yvantina Ah, I understand. I'll shoot her an email sometime tomorrow.

**Comment by porteriffic** [comment]
@yvantina I'm assuming her email is ftphilosophy@gmail.com not ftphilosophy@googlemail.com?

**Comment by yvantina** [comment]
@porteriffic 
ftphilosophy@googlemail.com is the address i have in my inbox. but here is her utd one
fxt131130@utdallas.edu

**Comment by cassininazir** [comment]
Googlemail.com is the same as Gmail.com. Either will send to the same person.

**Comment by porteriffic** [comment]
Emailed Fatemeh (9/15)

**Comment by porteriffic** [comment]
@linamoon Will need your assistance with album artwork at some point for this channel.

**Comment by cassininazir** [comment]
FYI: The registration form has been sent through Wufoo.

**Comment by porteriffic** [comment]
Close when first podcast goes up.

**Comment by linamoon** [comment]
Album art has been finalized and uploaded on the Drive folder CD 5.1 Album Artwork folder: https://drive.google.com/open?id=0BwvQhnxKj6jFdGN2MVpfYUx5ZHM

(Reference issue #314 )

**Comment by yvantina** [comment]
Love it !
Did you check back with Fatemeh?

yvan

**Comment by linamoon** [comment]
Yes I did!

**Comment by yvantina** [comment]
Cool. Love it !

**Comment by yvantina** [comment]
@linamoon is this a public image ? hope we don't get in trouble with owners...

**Comment by linamoon** [comment]
@rmalina said before it would be all right under educational fair use - perhaps should confirm again with Roger?

**Comment by rmalina** [comment]
what was the question

you have a go to publish the first podcast and open the artisthjinkive
channel
roger

On Sat, Oct 17, 2015 at 3:28 PM, Lina Moon notifications@github.com wrote:

> @rmalina https://github.com/rmalina said before it would be all right
> under educational fair use - perhaps should confirm again with Roger?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/296#issuecomment-148949273
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by linamoon** [comment]
@rmalina Yvan was wondering whether we could use the use the image in the background of the album artwork, I thought I remembered you saying it was all right under educational fair use.

You can see it in the Drive - https://drive.google.com/open?id=0B1tS6I_YV9uPTXk1Q0NvRlZJbTA

**Comment by yvantina** [comment]
@linamoon @coreysmart92 Thanks Lina ! yep I guess Corey this means you have the green light to release the channel and its first podcast !

**Comment by yvantina** [comment]
@coreysmart92 Please let me know when the channel is up so I can close this issue

**Comment by porteriffic** [comment]
First podcast for this channel is scheduled to go up on Monday. Close when podcast and channel are live.

**Comment by porteriffic** [comment]
Channel and podcast are live.
