### ISSUE TITLE
develop stingers based on USTs

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#297]
hal

i would like to meet with you and scot to discuss the idea of your experimental team developing bumpers and stingers that illustrate sound icons known as UST's- scot knows all about it
and i am really interested in seing this done and would be pleased to work with you on this
for discussion at your experimental meeting -when is it ?

i talked to frank dufour and scot about the idea and they would be delighted to
work with us on this

frank already has a few examples we can use and imitate
frank has stuff we can read

roger
@cassininazir 

here is the article by michael austin

ANALYSIS
A CASE STUDY IN ANALYZING MUSICAL
MULTIMEDIA USING
UNITÉS SÉMIOTIQUES TEMPORELLES
Unités Sémiotiques Temporelles, (or USTs) are 19 phenomenologically perceived
units that constitute a system developed at the Laboratoire Musique et Informatique
de Marseille (MIM) to analyze and teach the composition of
electro-acoustic music. This label instantly suggests a heavy emphasis on time
and temporality; however, the name of each unit describes sound in terms of movement
over time (Chute, Qui avance, Par vagues1
, etc.). In his essay, “Les Unités
Sémiotiques Temporelles: Problématique et essai de définition”, François Delalande
defines USTs as:
… A musical segment, which, without regard to context, has a precise temporal significance
as a morphological organization of sound (the USTs themselves are equivalent,
and abstract, segments that present, without regard to context, temporal
significance as with similar modes of morphological organization).2 [translation
mine]
87
- Author contact information: michael@mlaustin.com
  1 “Falling, advancing, by waves”, respectively.
  2 Laboratoire Musique et Informatique de Marseille, Les Unités Sémiotiques Temporelles: Élé-
  ments nouveaux d’analyse musicale, 1996, 19.
  Article received on15th September 2011
  Article accepted on 7th October 2012
  UDC: 78.01:316.77
  78.01:81'22
  Michael Austin*
  Missouri Western State University
  Department of Music
  USTs have traditionally been used to define temporally significant segments
  of music at the level of the Schaefferian sound object (objet sonore); however,
  Leigh Landy believes USTs are useful tools for analysis on several levels, writing:
  This system offers a tool for analysis that works a three levels: the global morphological
  level, the semantic description level, and the level at which other characteristics
  that are found to be relevant are formulated. Its focus and its ability to be applied
  as a tool for classification are clear. Although not based solely on sound-based music
  analysis–it also covers the traditional forms of music–it has potential to be used to
  group perceived aural characteristics. Like Schaeffer’s work, it relies on descriptive
  terminology to a large extent. It is a significant project, one of a very few.3
  In order to address the notions of time and motion as expressed semantically
  by USTs, Delalande explains that “time will be accessible through duration or
  variations [over time] from one or more morphological qualities of the sound;
  however, the variations [over time] of qualities of the sound often represent movement”4
  [translation mine].
  USTs have been a successful tool in analyzing music and sonic phenomena
  at the level of the Schafferian “sound object (l’objet sonore) i.e. a singular and
  rather short fragment of material (usually only seconds in length)5; however, in
  this paper, I demonstrate an expansion of the use of USTs to include any possible
  experiences of time and/or movement in a work – both in the experience of the
  sonic elements of a piece and in other constituent elements (vis. multimedia).
  Broadening the scope of time and movement that is analyzable by USTs provides
  a framework around which a theory of form in electroacoustical music and sonic
  art can develop. I will further demonstrate the usefulness of USTs as an analytical
  technique by analyzing Three Tales, Act III, Scene I (“Cloning”) by Steve Reich
  and Beryl Korot as a model; by its nature as a mixed media piece, as with other
  works lying at the “edge of analysis”, a phenomenological analysis of this piece
  would reveal important aspects of this work that traditional types of analyses
  would not.6 The process can be outlined in three steps:
  New Sound 38, II/2011
  88
  3 Leigh Landy, Understanding the Art of Sound Organization, Cambridge, MA, The MIT Press,
  2007, 190.
  4 Ibid., 23.
  5 For further examples of previous uses of USTs, see Laboratoire Musique et Informatique de
  Marseille, Les Unités Sémiotiques Temporelles: Éléments nouveaux d’analyse musicale, 1996,
  19, and Austin, Michael. The Phenomenological Impact of Interface on the Analysis of Digital
  Music and Sonic Art. Ph.D. Dissertation, University of Texas at Dallas, 2011. 6 While this work is originally scored for vocalist, instrumentalists, and multimedia, only the
  video/DVD version of this work (by Nonesuch Records) will be examined due to its wider
  availability (i.e. one can order a copy of the DVD much more easily than one can find a live
  performance to attend). 
- First, a work is broken down into significant sound objects, providing a means by
  which one can reduce the piece phenomenologically to the epoché (i.e. bracketed
  from outside meanings in order to analyze the characteristics of distinct sound objects
  as independent elements of the piece in question).
- Next, the sound objects are mapped onto a descriptive map based on the analyst’s experience
  of time. This mapping presents a unique way in which to observe relationships
  within a particular medium and among other constituent media via interface.
- The analyst then applies semantic and morphological descriptions of each sound
  object and can introduce extra-musical meanings that may further influence the
  analysis of the work.7
  As with most phenomenological investigations, an analysis using USTs begins
  with Edmond Husserl’s notion of epoché,
  8 or bracketing, wherein the observer
  suspends any preconceptions of the world in order to observe a phenomenon as it
  exists. Husserl writes:
  We put out of action the general positing which belongs to the essence of the natural
  attitude; we parenthesise everything which that positing encompasses with respect
  to being: thus the whole natural world which is continually “there for us” [...] If I do
  that, as I can with complete freedom, then I am not negating this “world” as though
  I were a solipsist; I am not doubting its factual being as though I were a skeptic; rather
  I am exercising the “phenomenological” έποχή which also completely shuts me off
  from any judgment about spatiotemporal factual being [...] Thus I exclude all sciences
  relating to this natural world no matter how firmly they stand there for me.9
  This technique closely correlates with the acousmatic10 and Pierre Shaeffer’s
  notion of “reduced listening” (or écoute réduite). Reduced listening is a “brackAustin,
  M.: A Case Study in Analyzing Musical Multimedia ... (87–95)
  89
  7 These steps were developed in my doctoral dissertation. Austin, Michael. The Phenomenological
  Impact of Interface on the Analysis of Digital Music and Sonic Art. Ph.D. Dissertation,
  University of Texas at Dallas, 2011.
  8 Greek: ἐποχή 9 Edmund Husserl, Ideen zu einer reinen Phänomenologie und phänomenologishen Philosophie,
  Erstes Buch: Allgemeine Einfürung in die reine Phänomenologie (1913), Husserlania III,
  ed. K. Schuhmann (The Hague: Martinus Nijhoff, 1976); Ideas Pertaining to A Pure Phenomenology
  and to a Phenomenological Philosophy, First Book: General Introduction to a Pure
  Phenomenology, trans. F. Kersten, The Hague: Martinus Nijhoff, 1982, §32. 10 Greek: from ἀκουσματικοί. A Pythagorian term reintroduced in 1955 by Jérôme Peignot
  which considers the „distance which separates sounds from their origin”, i.e., an audio-only
  presentation of sound common to electroacoustic music. For some, the term is very precise
  and refers specifically to this listening situation. However, the term has gained wider usage, in
  describing a genre, which, to a large extent derives from the Musique Concrète tradition and
  is founded upon this listening situation. (Source: EARS: ElectroAcoustic Resource Site.
  http://www.ears.dmu.ac.uk/spip.php?rubrique216)
  eting off” of a sound object from its real or imagined source (and consequent
  meaning) and a mode of listening to the sound for its own sake, i.e. we listen to
  the qualities of the sound itself and not to the “object” to which it refers. Michel
  Chion further explains that reduced listening “reverses the twofold curiosity about
  causes and meaning (which treats sound as an intermediary allowing us to pursue
  other objects) and turns it back on to the sound itself. In reduced listening, our listening
  intention targets the event which the sound object is in itself (and not to
  which it refers) and the values which it carries in itself (and not the ones it suggests)”.11
  Reduced listening frees the sound object from our presuppositions of
  meaning and opens new possibilities for interpretation of sonic material; however,
  art is inherently bound by the cultural milieu within which it is created and/or perceived.
  Therefore, a thorough analyst of music or sonic art also takes the cultural
  implications and preconceived interpretations of a work into consideration. The
  sound object is merely the carrier for the invariants to be analyzed, and the UST,
  then is the tool that affords an analysis of both the experience of time and relationships
  among the constituent elements of a multimedia piece. In order, then,
  to analyze a piece using USTs, one must first reduce a work to its constituent
  “sound objects” but should not consider this morphological reduction to be an end
  in itself. In the case of “Dolly”, these sound objects are often short sections of
  spoken texts.12
  The piece begins with an image of a robot singing “And placed them in the
  Garden of Eden, to serve it and to keep it” (beginning 38:41, mm. 732-743 of
  “Bikini”, the previous movement of Three Tales). While this melody is modal and
  resembles other common practice music, it also seems to be “floating”, with no
  direction toward a cadential pattern or other closing figure. The next sonic event
  is a statement spoken by a woman: “Process is as follows…” While this statement
  semantically suggests more information will follow, the phrase as a sound object
  can be divided into two USTs (see Figure 1):
  New Sound 38, II/2011
  90
  11 Chion, Michel. Guide des objets sonores: Pierre Schaeffer et la recherche musicale. trans.
  John Dack and Christen North. 2009, Paris: INA-GRM, 1983, 30-31.
  12 I would like to point out the fact that, while in this paper USTs are used in succession, USTs
  can also be used in a nested, almost Schenkerian, fashion that can lead to a more thorough
  analysis of the elements of a multimedia piece and the interrelationships among them.
  Figure 1. “The process is as follows…” analyzed as Propulsion + Conclusive
  USTs in Three Tales, Act III, Scene I
  “The process is as follows”
  “The process is” as a sound object in-and-of-itself presents the feeling of leading
  forward to another sound object, hence its label “Propulsion: sound that pushes
  or pulls forward.” The remaining cadence of the statement sounds like a completely
  predictable, natural end to the momentum created by the first part of the
  statement, thus the “Conclusive: predictable end to the energy of sound” label.13
  Because this work is both aural and visual, there are visible clues that lead to a
  similar analysis. Figures 2 and 3 are screenshots of this phrase as it is spoken.
  When watching these images in motion, one can see the speakers head raise
  (see Figure 2) as if to pull the words she is about to speak into existence; she then
  lowers her head (as in Figure 3) to signal the conclusion of the statement. At 38:58,
  the speaker again says, “The process is”, which again is labeled with the “Propulsion”
  UST; however, this time, there is no matching conclusion. These observations
  are then laid out in a descriptive map,14 allowing for a clearer comparison of
  of sonic material (see Figure 4). This descriptive map fills a ubiquitous void often
  Austin, M.: A Case Study in Analyzing Musical Multimedia ... (87–95)
  91
  Figure 2. Screenshot at 38:51, Three Tales (“The process is…”)
  13 While the actual words are not predictable, as with most declarative statements spoken in
  English, one can assume there will be a general vocal cadence leading to the end of a statement.
  It is also important to note that in the phenomenological epoché, there is a distinction made
  between the semantic meaning of the sound and the essential, morphological qualia of the
  sound; therefore, one would ignore the implied meaning of the statement “The process is as
  follows:” (expecting something to follow) and simply examine the qualities of the sound itself.
  14 Cf. Lochhead, Judith. “’How Does It Work?’ Challenges to Analytic Explanation.” Music
  Theory Spectrum, 28/2 (Fall 2006), 233–254.
  associated with electronic multimedia – the lack of a score; at a primary level, the
  descriptive map provides a foundation upon which analyses can be built (ex. an
  examination of nested phenomenological structures, a survey of the use of certain
  USTs in a particular genre or style, an evaluation of the rationale behind choosing
  to describe a sound object with one UST rather than another, etc.).
  Perhaps the most interesting elements of this piece do not lie in the sound objects
  or music alone, but rather in the extra-musical, cultural implications of the
  piece. In the “acousmatic”, “epoché” listening of the piece, one would notice that
  there are different characters (including a robot) speaking through the scene. It is
  important to note that these characters are not actors hired to recite this text, but
  rather, they are world-renowned scientist, philosophers, and writers connected to
  the development of genetic engineering and the cloning of Dolly the Sheep. The
  robot singing at the beginning of this scene is Kismet, created at MIT and designed
  specifically to interact socially with humans. The first woman to appear on the
  screen, describing the cloning process is Ruth Deech, the chair of the U.K. Human
  Fertilization and Embryology Authority, Pro-Vice-Chancellor of Oxford University,
  and a Fellow of the Royal Society of Medicine; the other woman to appear
  in this scene is Gina Kolata, a science writer for the New York Times who first
  broke the story of Dolly in America. The first man to appear in the video, and who
  repeats “…are machines…, “ is ethologist and evolutionary biologist Richard
  Dawkins, the first Charles Simonyi Professor of Public Understanding of Science
  at Oxford University; the other man to appear in this scene is James D. Watson,
  who with Francis Crick and Maurice Wilkins, won the Nobel Prize for their work
  New Sound 38, II/2011
  92
  Figure 3. Screenshot at 38:53, Three Tales (“…as follows”)
  Austin, M.: A Case Study in Analyzing Musical Multimedia ... (87–95)
  93Figure 4. Descriptive map of 38:41-39:38 of Three Tales, Act III, Scene I (“Cloning”)
  in discovering the structure of DNA. Knowing who is speaking this text lends a
  sort of gravitas and credibility to the interviews, effecting the perception (and by
  extension the experience) of the work.
  Watching the visual elements of this work on DVD also provides some extramusical
  information that affects the experience of the scene. The scene on the
  DVD begins with Kismet singing; upon examination of the score, this entire act
  actually begins a moment after Kismet’s solo, when Ruth Deech says “Process is
  as follows.”
  In watching the video, one notices the movement of the robot does not seem
  realistic, suggesting that the image is computer generated–as is the voice–and the
  affected, computerized singing contributes to this scientific, sterile aesthetic. Behind
  each of the interviewees are action scenes depicting the process of genetic
  engineering or cloning. While there are times in which the background video
  matches the steps in the process being described by the interviewees, there are
  also clips that are repeated, mimicking the music or repeated text. There are also
  times wherein there the screen is black with white writing; this stripping of other
  visual elements and replacing them with text alone occurs at other points within
  the entire video opera, symbolizing the divine, scripture, or other religious subtexts
  within the work. In this scene, Korot visually interjects the work “created” several
  times Richard Dawkins says the word “created”, further accentuating references
  to the Garden of Eden.
  While this is by no means an exhaustive analysis of this work, it does present
  a framework within which the phenomenological experience of this piece elucidates
  some particularly interesting aspects of this scene that would not be analyzable
  by means of other, traditional analytical techniques. In performing an initial
  bracketing of the sound objects and observing them as essential objects, a nuanced
  interpretation of the spatiotemporal and energetic experience of the text, constituent
  sound objects, and some of the visual elements of the piece was possible;
  further, adding some of the extra-musical elements associated to these sound and
  visual objects provided an additional level of interpretation. It is my hope that my
  expansion of the use of USTs as an analytical technique contributes to their acceptance
  as a viable tool in analyzing music, sonic art, and other works in other
  media, and leads to a deeper understanding of the phenomenological structure of
  time and movement in these works.
  New Sound 38, II/2011
  94
  REFERENCES
  Austin, Michael, The Phenomenological Impact of Interface on the Analysis of Digital
  Music and Sonic Art, Ph.D. Dissertation, University of Texas at Dallas, 2011
  Chion, Michel. Guide des objets sonores: Pierre Schaeffer et la recherche musicale,
  trans. John Dack and Christen North. 2009, Paris: INA-GRM, 1983, 30-31
  Delalande, François, “Les Unités Sémiotiques Temporelles: Problématique et essai de definition”,
  Les Unités Sémiotiques Temporelles: Éléments nouveaux d’analyse musicale,
  Laboratoire Musique et Informatique de Marseille, 1996, 19.
  Husserl, Edmund, Ideen zu einer reinen Phänomenologie und phänomenologishen Philosophie,
  Erstes Buch: Allgemeine Einfürung in die reine Phänomenologie (1913),
  Husserlania III, ed. K. Schuhmann (The Hague: Martinus Nijhoff, 1976); Ideas Pertaining
  to A Pure Phenomenology and to a Phenomenological Philosophy, First
  Book: General Introduction to a Pure Phenomenology, trans. F. Kersten, The Hague:
  Martinus Nijhoff, 1982, 32
  Leigh Landy, Understanding the Art of Sound Organization, Cambridge, MA: The MIT
  Press, 2007, 190
  Lochhead, Judith, “’How Does It Work?’ Challenges to Analytic Explanation”, Music Theory
  Spectrum, 28/2, Fall 2006, 233–254
  Reich, Steve, Three Tales, New York: Hendon Music, 2002
  Austin, M.: A Case Study in Analyzing Musical Multimedia ... (87–95)
  95

**Comment by halclark** [comment]
Good understanding of what needs to be produced. Produced a few already with more coming.
