### ISSUE TITLE
Creative Europe logo for Trust Me podcast series

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#298]
@porteriffic 
Josephine - we need to have the logo of Creative Europe (see attached) for each "Trust Me I'm an Artist" podcast that Annick sends us as part of the collaboration with the European Commission . As of today we ONLY need it done for these two ones:
- http://creativedisturbance.org/fr/podcast/taste-of-flesh-bite-me-im-yours-as-seen-by-the-curator-meeting-with-jareh-das-eng/
- http://creativedisturbance.org/fr/podcast/taste-of-flesh-bite-me-im-yours-as-seen-by-the-artist-meeting-with-martin-obrien-eng/
  Thank you
  ![eu_flag_creative_europe_co_funded_pos_ rgb _left](https://cloud.githubusercontent.com/assets/10967939/9858086/391bb188-5ae4-11e5-8793-4d368f522671.jpg)
  ![eu_flag_creative_europe_co_funded_pos_ rgb _right](https://cloud.githubusercontent.com/assets/10967939/9858087/392a9a18-5ae4-11e5-9dff-9d5ac6ff0a4b.jpg)

---

---------- Message transféré ----------
De : Annick Bureaud abureaud@gmail.com
Date : 14 septembre 2015 10:15
Objet : A ajouter sur Audiolats sur CD
À : Yvan Tina yvantina@gmail.com, malina rmalina@alum.mit.edu

Yvan, Roger,

La Commission est assez pointilleuse pour les projets Creative Europe. Si on ne met pas le logo, ils considèrent que l'on ne peut pas inclure l'action dans le rapport d'activité (no comment).
Pouvez-vous donc mettre le logo (ci joint, celui que vous voulez) sur ces pages et sur les futures pages des podcasts de Trust Me ? (uniquement Trust me).

http://creativedisturbance.org/fr/podcast/taste-of-flesh-bite-me-im-yours-as-seen-by-the-curator-meeting-with-jareh-das-eng/

http://creativedisturbance.org/fr/podcast/taste-of-flesh-bite-me-im-yours-as-seen-by-the-artist-meeting-with-martin-obrien-eng/
Annick

**Comment by porteriffic** [comment]
@yvantina You might want to bring @linamoon in the loop on this. She's in charge of creating any graphics we need.

**Comment by yvantina** [comment]
Yes @linamoon can you please take care of this as soon as you can ? choose any of the two logos -you don't have to use both of them. Thanks

**Comment by linamoon** [comment]
@porteriffic @yvantina This doesn't seem to be creating any logos, but more like just updating those podcast pages with the pictures above? I can just do that as well.

**Comment by linamoon** [comment]
Added to all "Trust me I'm an artist" pages - ideally should make a note for future podcasts like these.

**Comment by linamoon** [comment]
@yvantina would like the logo next to the podcast title on the Disturbance pages (Audiolats and Meta-Life) as per below - 

![screen shot 2015-09-15 at 2 40 32 pm](https://cloud.githubusercontent.com/assets/10729556/9887945/f51aa65e-5bb7-11e5-9496-0a5fd8ed2476.png)

The WP dashboard backend doesn't seem to allow this easily though - perhaps @dylanorgeron would know better if this is possible?
