### ISSUE TITLE
Submit Bio - Corey

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#3]
We will need short descriptions of your overall background and current majors to put on the team page for CD. Corey, can you help get these from the team members? 

Basic example: [ Your name ] is currently pursuing her ____ degree at UTD and is focusing on ____. She is interested in ___ with ___ and the effects it has on ___. Current qualifications? Future goals?

**Comment by coreysmart92** [comment]
Corey Smart is currently pursuing his Arts and Technologies degree at UTD with a focus in Sound Design.  He is interested in sound for movies or games and the effects it has on the final product.  He has an extensive background in music and is currently working towards an interest in foley for movies and games.

**Comment by cassininazir** [comment]
@vivraman Please edit and add to Meet the Team page.
