### ISSUE TITLE
Images for Voices

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#30]
Some pictures of the voices are coming out squished. How are you guys editing images? Are you resizing it or cropping it?

**Comment by cassininazir** [comment]
Marcus Neustetter's photo is one that is like this.

**Comment by porteriffic** [comment]
Create a guideline on how to properly resize/crop in Word Press and find a new one if necessary.

**Comment by porteriffic** [comment]
Add to Podcast Production Sheet
