### ISSUE TITLE
Add Bumper "Authors" to Each Podcast

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#300]
Prioritize this. With the new forms process this should be easier. Let's add this to WordPress.

**Comment by rmalina** [comment]
this is a really important one
corey can you make sure that from now on
every podcast text credits the author of the bumper
that is used

start this with the one going up this week

roger

On Mon, Sep 14, 2015 at 2:11 PM, Cassini Nazir notifications@github.com
wrote:

> Prioritize this. With the new forms process this should be easier.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/300.

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by dylanorgeron** [comment]
bumper authors can now be specified when adding a podcast. the author will show under the voices at the top of the page unless no author was specified.
