### ISSUE TITLE
Create "Human Impacts Institute" Channel 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#302]
@porteriffic Create a new channel for HII. Adapt content from http://www.humanimpactsinstitute.org/#!about/cil3 for the description. 

Website is http://www.humanimpactsinstitute.org/

Work with @linamoon on album art.

**Comment by cassininazir** [comment]
Better description for their channel at http://www.humanimpactsinstitute.org/#!human-impact-stories/c1cet

**Comment by porteriffic** [comment]
Started a draft.

@cassininazir @linamoon Should we use their album art? Maybe we can still use their logo but make it look nicer? It's located on their [SoundCloud](https://soundcloud.com/humanimpactsinstitute)

**Comment by linamoon** [comment]
Album art (large and small) is done and uploaded to 5.1 Album Artwork:

https://drive.google.com/open?id=0BwvQhnxKj6jFdGN2MVpfYUx5ZHM

(Art is slightly modified from their original logo to look nicer)

@porteriffic

**Comment by rmalina** [comment]
thjis seems to be the wrong file
its not the human impacts institute
roger

On Wed, Sep 23, 2015 at 11:12 PM, Lina Moon notifications@github.com
wrote:

> Album art (large and small) is done and uploaded to 5.1 Album Artwork:
> 
> https://drive.google.com/open?id=0BwvQhnxKj6jFNDFUOXNkWTgwYjg
> 
> (Art is slightly modified from their original logo to look nicer)
> 
> @porteriffic https://github.com/porteriffic
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/302#issuecomment-142806778
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by linamoon** [comment]
Ah oops, the link should be fixed now.

**Comment by rmalina** [comment]
thanks
great
has tara approved it
dont use until she does
rpoger

On Thu, Sep 24, 2015 at 11:23 AM, Lina Moon notifications@github.com
wrote:

> Ah oops, the link should be fixed now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/302#issuecomment-142978384
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by linamoon** [comment]
Right - will send her to approval. Definitely

**Comment by porteriffic** [comment]
Close when first podcast goes up 10/16

**Comment by porteriffic** [comment]
Podcast is up.
