### ISSUE TITLE
Album Artwork for "Human Impacts Institute" Channel

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#303]
@linamoon Can you create the album art for the HII channel? Use their logo (a few links to it below) to create an image that fits our design parameters (1400 x 1400 px, etc) while also confirming to their colours, logo, typeface. 

Use Illustrator's Trace Image tool to create a vectorized version of their logo

http://static.wixstatic.com/media/677366_93141673e489429896c7aa13742d2d1e.png_srb_p_74_76_75_22_0.50_1.20_0.00_png_srb
https://soundcloud.com/humanimpactsinstitute
http://www.humanimpactsinstitute.org/

**Comment by linamoon** [comment]
Album art (large and small) is done and uploaded to 5.1 Album Artwork:

https://drive.google.com/open?id=0BwvQhnxKj6jFdGN2MVpfYUx5ZHM

Not fond of the logo but thought this was a nice compromise P:

@porteriffic

**Comment by cassininazir** [comment]
https://drive.google.com/folderview?id=0BwvQhnxKj6jFdGN2MVpfYUx5ZHM&usp=drive_web

This is a good compromise!

**Comment by linamoon** [comment]
Tara DePort has approved the album art - @amb141330 Feel free to upload it now
