### ISSUE TITLE
New Channel

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#304]
@coreysmart92 @porteriffic 

We have the approval for a new channel for the Human Impact Institute's stories (19 podcasts). Can you begin scheduling these? 

http://www.humanimpactsinstitute.org/#!human-impact-stories/c1cet

**Comment by coreysmart92** [comment]
Yes I will start scheduling these podcast for publish next week October 6th and on. (9/28/15)
Close: When podcast have started to be published.

**Comment by coreysmart92** [comment]
Closing: @amb141330 has been working on this. The first podcast will be published 10/16/15. After the first publishing I will work with @amb141330 to schedule and plan out the rest of the Human Impacts podcasts. (10/15/15)
