### ISSUE TITLE
Blog Post for International Coffee Day

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#305]
I noticed we forgot to put up a blog post for Look Back Day, so thought I'd make a Github item for this. Assigning to Corey as per 2.2.10 Feature Day Action Plan.

https://docs.google.com/document/d/1lA0UaMrmaxg-rOLGox4mCvvn_tB3DBqwo5PoWWsPgZA/edit
- Explain content and celebration
- Share blog post on social media platforms

**Comment by porteriffic** [comment]
@coreysmart92 I recommend you start the blog post now that way you have plenty of time to proof and edit it. Please send either Cassini or I your draft no later than Wednesday 9/23.

**Comment by porteriffic** [comment]
@coreysmart92 What happened? No blog post?

**Comment by coreysmart92** [comment]
I made it to late, Cassini didn't have time to check it. I is ready to go I am just waiting on his go ahead. (9/29/15)

**Comment by porteriffic** [comment]
Send it to me please

**Comment by porteriffic** [comment]
Send it to me

**Comment by coreysmart92** [comment]
The link is http://creativedisturbance.org/2015/04/celebrate-international-coffee-day-sep-29/. It is a draft in wordpress. Is there a specific way you want me to  send it to you? (9/29/15)

**Comment by coreysmart92** [comment]
Closing: Blog post was made but never approved for publishing. (10/5/15)
