### ISSUE TITLE
Hi-res channel images for soundcloud 

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#308]
Someone point me in the right direction to get the highest res possible images for each of the channel images. Images are blurry. http://x.creativedisturbance.org/project/stingers/. Thanks!

**Comment by cassininazir** [comment]
CD 5.1 on Google Drive.

Or right click on the images on http://creativedisturbance.org/disturbances/ and you can save them that way.

**Comment by linamoon** [comment]
High-res photos are on soundcloud channel. Closing issue.
