### ISSUE TITLE
possible podcast with jenifer wightman on art and climate change

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#309]
possible podcast wi9th jenifer wightman on art and climate change

can you see if susan would like to record this ?

enifer
another thought
for COP21 we are doing art and climate change
podcasts on our creative disturbance podcast platform
susan erickson has a channel on art and earth science

http://creativedisturbance.org/channel/art-and-earth-science/

might you be willing to record a podcast via skype ?

roger
cc susan

On Wed, Sep 16, 2015 at 8:09 AM, Jenifer Wightman jenifer.wightman@cornell.edu wrote:

> Hey Roger,
> 
> Don't know if I've told you about one of my latest projects - 
> Addending the Gutenberg Bible with contemporary science.
> So far more than 30 Gutenberg Bibles have been updated with my letter press
> broadside…
> 
> Here is the website:http://audiblewink.com/Addendum.html
> And Here is the blog about the delivery of the Addendum to institutions that
> hold a Gutenberg in their collections: http://audiblewink.com/blog/?cat=7
> 
> Hope all is well – your daughter must have graduated from Cornell by now,
> no?
> Jeni
## 

Roger F Malina

**Comment by porteriffic** [comment]
@rmalina Does Susan know about this?

**Comment by porteriffic** [comment]
I've emailed Susan regarding doing a possible podcast with Jenifer Wightman but I haven't heard from her all week.

**Comment by porteriffic** [comment]
Will suggest Susan contact Jenifer for recording future podcasts and will create a new issue for it.
