### ISSUE TITLE
Celebrate 100 Podcasts

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#31]
As of April 9, 2015 we are 22 "episodes" away from 100 podcasts. The page at https://itunes.apple.com/us/podcast/creative-disturbance/id931330050?mt=2 is helpful in determining this. 

We should plan for the 100th podcast and think about what it should be and how to announce. Would be a good time to ping our community as well. 

@porteriffic, @kkondas can you discuss in the next Sound Team meeting? @porteriffic can you add to the Coordinators meeting agenda? @heiwanalady will need a good graphic for this.

**Comment by porteriffic** [comment]
~20 podcasts away.

**Comment by cassininazir** [comment]
If we estimate 4 podcasts a week, that puts us five weeks away (roughly around May 19, or the week after finals).

**Comment by porteriffic** [comment]
@coreysmart92 @heiwanalady Let's coordinate on this next week after Earth Day

**Comment by cassininazir** [comment]
Also include the 10 top most popular podcasts as well on this page.

**Comment by porteriffic** [comment]
Will need a logo/banner for splash page @heiwanalady

**Comment by cassininazir** [comment]
Wow. We are 2 away!

**Comment by heiwanalady** [comment]
I'm on it!

**Comment by porteriffic** [comment]
Splash page is already up. Will continue to work with @coreysmart92 this week for the 100th Podcast Celebration.

**Comment by porteriffic** [comment]
@coreysmart92 @cassininazir One thing I noticed is that the Nobel Prize Winner Amartya Sen podcasts have the same description. Perhaps we should break up the descriptions so it doesn't seem so thoughtless and repetitive?

**Comment by coreysmart92** [comment]
Closing. 100th podcast has been up with no issues and will be taken down soon.
