### ISSUE TITLE
open the femgineers channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#310]
meet with eun ah lee
has she filled out new channel form

Dr. Malina, Josephine,

I hope the fall semester is going well for all of you.
I have contacted women engineering student groups, and they show enthusiastic interests in this podcast project. It seems that we are going to be able to record our first podcast soon.

So, I'd like to ask your help to prepare the recording.
As you suggested, it would be the best if we record it at your lab.
Can I visit the lab sometime during the next week, to learn what to prepare and how to do it?

Best,
Eun Ah Lee

Femgineers: A Podcast Project Proposal
• “Femgineers” is a podcast project to let the voice of women engineers be heard to the public.
• “Femgineers” aims to provide an outlet for women engineering students to express their ideas
and concerns, and to explore women engineering students’ micro-culture.
• Any interested women engineering students can participate in recording podcasts about their
thought, visions, stories, and other issues.
• “Femgineers” is run by The Center for Values in Medicine, Science, and Technology ( http://
www.utdallas.edu/c4v/ ) at UT Dallas and presented by the Creative Disturbance podcast
platform run by SciArt Lab at UT Dallas ( http://creativedisturbance.org ).
The Center for Values in Medicine, Science, and Technology have been observing engineering student project
groups working on their senior design projects (SDP) for the NSF funded project. There are fewer female than male
engineering students, so only a couple of teams during our two-year study had more women than men. During the
observations, we have noticed that these teams seemed to have unique characteristics such as more socially
empathetic implicit understanding. There might be a micro-culture that makes these characteristics prevalent in
teams with women members. Therefore we would like to propose a podcast project to explore this micro-culture of
women engineering students.
For questions or more information, please contact at EunAh.Lee@utdallas.edu

**Comment by porteriffic** [comment]
Sent Eun Ah an email to set up a time to meet. Started a draft for the channel on WordPress.

@linamoon Is the album art located in the Google Drive? I couldn't find it in there.

**Comment by coreysmart92** [comment]
The first podcast is being edited this week by Corey Smart. (10/5/15)

**Comment by linamoon** [comment]
Have album artwork drafts ready, planning to email Eun Ah for approval early this week.

**Comment by porteriffic** [comment]
@coreysmart92 Has the first podcast been emailed to Eun Ah?

**Comment by coreysmart92** [comment]
I have sent the podcast to Eun Ah Lee. (10/19/15)

**Comment by linamoon** [comment]
Eun Ah has approved the album art, and I've uploaded the images in the Google Drive in the Album Artwork folder (below) so they can be used when ready.
- https://drive.google.com/open?id=0BwvQhnxKj6jFdGN2MVpfYUx5ZHM

**Comment by coreysmart92** [comment]
The first submitted podcast will be completed by 11/5/15. The second podcast is scheduled for editing.
Close: when the Femgineers podcast has been published. (11/2/15)

**Comment by amb141330** [comment]
Is this still not up? Can I get an exact date this will be launched? I know we've been waiting on feedback, but we need to get this up.

**Comment by coreysmart92** [comment]
Closing: This channel has gone live with the first podcast. The second podcast is scheduled to publish 2/5/16.
(1/25/16)
