### ISSUE TITLE
please publish podcast by diego maranan

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#311]
i have filled out the form for diego maranan but couldnt fint a github item on him-
do you have his podcast and has it been edited ?

am waiting for guest to ok the content
wait for this ok to publish it

roger

**Comment by coreysmart92** [comment]
I thought I had sent the content check, but I was mistaken. I have now sent the content check to both Dr. Malina and Mr. Maranan. I have scheduled it to publish October 2, I will change this if I have not heard back from Mr. Maranan by then. (9/28/15)
Close: When podcast is published.

**Comment by rmalina** [comment]
OK
Charge ahead

roger malina

**Comment by coreysmart92** [comment]
Closing: This podcast has been published. (10/15/15)
