### ISSUE TITLE
Album Art: Artisthinktive Iran: A Forum for Distinctive Thinking on Iranian Arts

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#314]
Channel Name
- Artisthinktive Iran: A Forum for Distinctive Thinking on Iranian Arts

Short Description of the Channel 
- This channel provides a forum to introduce and analyze contemporary Iranian arts. Its main goal is to illustrate how Iranian artists are contributing to a wide array of artistic forms. The channel wishes to be a window to an area of artistic activity that has been neglected by western media due to political events ensuing after Iran's 1979 revolution.

Anticipated Key Words for the Channel 
- Contemporary Iranian Arts, New media Arts, Artistic movements , Art and Politics, Art and Religion, Art and Islam

Primary Language for this Channel \* 
- Other

Other Language (if "Other" was selected above)  
- Farsi

Estimated Date of First Podcast Recording 
- Sunday, July 5, 2015

Approximately how many Podcasts per Year will the Channel produce? \*    
- 5 to 8

Your Name: Fatemeh Tashakori
Your Email: fxt131130@utdallas.edu

**Comment by linamoon** [comment]
Met with Fatemeh about album art - will send draft by upcoming Wednesday (educational rights for images?)

**Comment by linamoon** [comment]
Emailed Fatemeh drafts - waiting for response.

**Comment by linamoon** [comment]
Album art (small and large) has been finalized and uploaded in the Drive CD 5.1 Album Artwork folder: https://drive.google.com/open?id=0BwvQhnxKj6jFdGN2MVpfYUx5ZHM
