### ISSUE TITLE
Big Design Podast: UX Professional: Year One

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#315]
@coreysmart92 please re-assign to the appropriate person. 

Use the following information for Art Sanchez 

![art-sanchez-262x272](https://cloud.githubusercontent.com/assets/1661430/9995654/e553eeb6-6048-11e5-9601-2066cff30aac.jpg)

ART SANCHEZ
Art Sanchez is a UX designer with many years of experience in sales and marketing. He enjoys building prototypes and performing usability testing. On most nights, you will find Art reading the latest UX book or watching movies. Art is very active in the Dallas community–attending various meetings, book clubs, hackathons, and meetups.

**Comment by coreysmart92** [comment]
This goes with the podcast I am editing. (9/28/15)
Close: When podcast is scheduled to publish.

**Comment by coreysmart92** [comment]
Closing: This podcast as been published.
(2/22/16)
