### ISSUE TITLE
Forms for Judy Malloy Podcast

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#318]
Podcast ready to go up on completion of forms.

**Comment by rmalina** [comment]
hal  corey dylan 

i have been trying to submit my form with judy malloy but
a) i couldnt find the place to put the bio of the voice
b) i saved the form but then it wouldnt let me submit it

anyway there is a saved form that has part of the info
here is the rest of the info can you inset it

dylan-maybe we need some more test submissions ?

roger
@halclark @coreysmart92 @dylanorgeron 

Podcast Title  :Pioneer Judy Malloy thinks aloud about her role in the birth of electronic literature

Short Description of this Podcast *

Art and Technology pioneer Judy Malloy discusses with Roger Malina her work beginning in the mid 1970's when -- inspired by her work on early library databases in the 1960's -- she began to introduce card catalogs into her writing practice as a precursor to hypertext concepts, and then about her use of computers to create electronic literature, beginning in 1986 with "Uncle Roger"
http://www.well.com/user/jmalloy/uncleroger/uncle.html
http://www.well.com/user/jmalloy/

Guest *Judy Malloy

Short Bio of Guest *

Following a vision of hypertextual narrative, begun in the 1970’s with experimental artist books, beginning in the 1980’s, Judy Malloy wrote and programmed over 17 internationally exhibited and published works of electronic literature. Recently, she has been a Distinguished Fellow and Visiting Lecturer at Princeton University.

On 9/2/2015 12:37 PM, roger malina wrote:
judy
if you decide to authorise posting of the podcast can you
spend 5 minutes filling this out/cleaning up my draft ?

roger

Podcast Title  :Pioneer Judy Malloy thinks aloud about her role in the
birth of electronic literature

**Comment by dylanorgeron** [comment]
you should be able to submit the form now. sorry for the delay. im 
working on add bios for voices.

**Comment by rmalina** [comment]
podcast is up
