### ISSUE TITLE
Human Impacts Group

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#319]
Schedule podcasts for Human Impacts Group for the next few weeks. Send to Tara Deporte (tara@humanimpactsinstitute.org) to keep her informed. 

You can schedule them all in WordPress and LibSyn. Get from: 
http://www.humanimpactsinstitute.org/#!human-impact-stories/c1cet 

You'll need to work on the Voice information as this doesn't necessarily appear on the website.

**Comment by amb141330** [comment]
Email has been sent to Tara Deporte letting her know I will be handling her podcasts and we will begin to upload content next week.

**Comment by amb141330** [comment]
First podcast scheduled to be uploaded on Friday 10/16/2015
