### ISSUE TITLE
Create a description for Art & Climate Change 

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#323]
Ask Susan and Cassini for feedback on draft

**Comment by yvantina** [comment]
@porteriffic here's an example of what I just received from the YALI network

---------- Forwarded message ----------
From: YALI Network yalin.mailer@state.gov
Date: 2015-09-23 2:31 GMT-05:00
Subject: #YALICHAT on climate change and green solutions - join today! 
To: yvan yvantina@gmail.com

Dear YALI Network,

Climate change affects more than the environment -  businesses, farmers and individuals must take steps to find renewable solutions as well. Mandela Washington Fellows Peace Musonge and Andrew Chikomba are finding green solutions in Uganda and Zimbabwe. What questions do you have for them about climate change?

WHAT: #YALICHAT with Mandela Washington Fellows Peace Musonge and Andrew Chikomba

WHEN: Wednesday, September 23 – Friday, September 25

WHERE: Post your questions on the YALI Network Facebook page

Peace is a scientist and social entrepreneur from Uganda, and founder of Uganda Artemia Fish Farms Enterprise, which researches innovative green technologies to diversify organic aquaculture produce. She is passionate about using science and technology to engage and improve the livelihoods of communities.

Andrew founded Gemwitts Enterprises, a green solutions company, in Zimbabwe in 2012. He has a passion for technology and entrepreneurship and serves communities by providing honest and practical solutions to their problems using appropriate technology and renewable solutions.

Peace and Andrew will be hosting this Facebook chat to personally engage with YALI Network members and answer questions related to agriculture, water, health and renewable energy. Be sure to log onto the YALI Network Facebook page today to post your questions, read their responses and be part of the conversation.

Sincerely,

Macon Phillips
Coordinator, Bureau of International Information Programs
U.S. Department of State

P.S.: Read an interview with Andrew and other Mandela Washington Fellows on the YALI Network blog.
Facebook
Facebook
Twitter
Twitter
LinkedIn
LinkedIn
Website
Website

unsubscribe from this list    update subscription preferences 

Privacy Policy 
    Forward to Friend
View this email in your browser

## 

check out this website for more information on art, synthetic biology and a-life 
http://synthbioart.texashats.org/

**Comment by porteriffic** [comment]
@yvantina Would content from the emails be sufficient or do you need me to create something else?

**Climate is everyone’s business**. In anticipation of the United Nations Conference on Climate Change ([**COP21**](http://www.artcop21.com/about/)) on Nov 15, Creative Disturbance will **feature podcasts** discussing:
- Sustainable global culture and economy
- Environmental change and awareness
- Ways citizens are active in promoting a greener future

**Kind of Podcasts to Submit**
- **Professionals in the field** can discuss if they already see changes occurring to help the  environment. What movements have they overseen that are now successful? 
- **Students** can discuss how ways to encourage environmental change and awareness. How important it is for us to implement these changes now? 

**Can’t Submit a Podcast? There are other ways you can help!**
- Learn about COP21 and share the movement within your local community
- Blog about it!
- Spread the word on social media using #ArtCop21 #FightForTheFuture
  - Facebook: Artcop21
  - Twitter: @art_cop21
  - Instagram: @artcop21
