### ISSUE TITLE
Podcast of Helen and Newton Harrison (COP21 Art & Climate Change)

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#325]
corey
i have loaded a podcast with helen and newton harrison to be published
by nov 20 for our cop 21 art and climate change month
it is in drop box new leonardos under art and climate change folder

roger

please assign it to an editor to work with me

**Comment by coreysmart92** [comment]
I have scheduled it to be edited by myself. (9/28/15)
Close: When podcast is completed and ready to publish.

**Comment by coreysmart92** [comment]
The podcast editing is complete, I have sent it to Roger for a content check and for the form completion.
Close: when the podcast is published. (11/2/15)

**Comment by porteriffic** [comment]
@coreysmart92 Please have the podcast appear by December 1st at the very latest.

**Comment by rmalina** [comment]
i found the podcast-but please lets get it published this month-roger

**Comment by porteriffic** [comment]
@rmalina The podcast is already in the tracking sheet. It's scheduled to publish some time next week.

**Comment by rmalina** [comment]
do you have the forms?
roger

On Fri, Nov 6, 2015 at 7:29 AM, porteriffic notifications@github.com
wrote:

> @rmalina https://github.com/rmalina The podcast is already in the
> tracking sheet. It's scheduled to publish some time next week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/325#issuecomment-154438386
> .

## 

Roger F Malina
is in Dallas

**Comment by rmalina** [comment]
corey plese contact the harrisons-they want to edit the podcast
you may want to send them your edited version, roger

**Comment by rmalina** [comment]
i have deposited the version of the harrison podcast that was edited by the harrisons PLEASE make sure to use this version for your edit and posting
roger
@coreysmart92 @halclark @amb141330

**Comment by porteriffic** [comment]
@coreysmart92 I don't see this podcast anywhere on the website. Why was this podcast not published?

**Comment by rmalina** [comment]
I only just did the form

**Comment by porteriffic** [comment]
Podcast has been published.
