### ISSUE TITLE
Channel idea for MIT aggregator

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#326]
@rmalina @cassininazir 
Just listened the three gates media podcast on Symbiotica and thought they could be a good fit for the CD and the aggregator..two independent women from Australia.. please check their website
http://www.threegatesmedia.com/aboutus/
http://www.threegatesmedia.com/blog-adirondack/2015/9/22/rare-air-11-ionat-zurr-and-oron-catts

**Comment by cassininazir** [comment]
Great! Assign to Ashton or your sound designer to make contact and invite.

**Comment by yvantina** [comment]
assigned to @amb141330

**Comment by amb141330** [comment]
I will write up an email to send to them next time I am able to meet with Yvan.

**Comment by amb141330** [comment]
Email should be going out this week

**Comment by amb141330** [comment]
Waiting on response from @cassininazir and or @rmalina on the email draft we wrote up to send out

**Comment by rmalina** [comment]
works this with cassini
roger

On Mon, Nov 2, 2015 at 10:16 AM, amb141330 notifications@github.com wrote:

> Waiting on response from @cassininazir https://github.com/cassininazir
> and or @rmalina https://github.com/rmalina on the email draft we wrote
> up to send out
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/326#issuecomment-153070638
> .

## 

Roger F Malina
is in Dallas

**Comment by cassininazir** [comment]
Reviewed draft.

**Comment by amb141330** [comment]
Will spend my lab hours, starting on Monday 11/16/15, on sending out these emails now. The document keeping track of who has been, and hasn't been, contacted can be found here.
https://docs.google.com/document/d/1dsQK5EoZlj4etQgvxWAxhd9m5su_IoBOowjNnhhvY6M/edit

**Comment by cassininazir** [comment]
Excellent progress! **Please update the list to remove blank spaces**: Looks like there are 181 but there are probably half or a third of that. 

Also **please indicate on the document those you've sent out and when**. Don't want to bombard these individuals with the same email from two separate people.

**Comment by yvantina** [comment]
Will meet with Ashton, tomorrow Friday 11/13 to work on this !

**Comment by amb141330** [comment]
Yvan and I have started sending out emails to the list of people last Friday. The document shows who has received emails so far.

**Comment by amb141330** [comment]
No update on further emails just yet in terms of sent and received.

**Comment by yvantina** [comment]
I did actually. From Amal Alayan, Laura Marks, and Tobias Van Veen with whom I actually made a podcast. Need to follow up with the other ones. and we need to plan our next emailing session this week !

**Comment by amb141330** [comment]
This is an old issue. Emails were sent out and new channels are coming out of it (Like Other Planes of There | Afrofuturism}
