### ISSUE TITLE
create blog post to post with new forms

### ISSUE THREAD

**Issue by dylanorgeron** [creativedisturbance/podcasts#327]

**Comment by dylanorgeron** [comment]
https://docs.google.com/document/d/1zCFVlsSV9fRSWii4MPmqjGcdHLM8KShFmtG8Yz9WsB4/edit?usp=sharing
@linamoon please read and review

**Comment by dylanorgeron** [comment]
https://drive.google.com/file/d/0Bww1-yjnkCeeSnZVX3Z4dXpvZVk/view?usp=sharing

**Comment by cassininazir** [comment]
Dylan, also create the blog post. Happy to review before it goes live.

**Comment by dylanorgeron** [comment]
@linamoon will have it up in a few minutes

**Comment by linamoon** [comment]
Blog post is up along with the forms.
