### ISSUE TITLE
Get Dylan's picture up on Creative Disturbance site

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#329]
- Need to schedule (sometime next week)

**Comment by dylanorgeron** [comment]
lets take care of this on monday

**Comment by cassininazir** [comment]
Where? I don't see your name or picture in the listing. 

A few _additional items_
- Remove Kyle from the list
- Add Anvit to the alumni list. Please email to ask which website we should link to.

**Comment by linamoon** [comment]
Kyle has been removed, Anvit is listed as alumni with a link to his site, and Dylan is finally up with a bio (!)
