### ISSUE TITLE
cleaning sd cards

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#331]
@coreysmart92 @amb141330 @halclark  hey guys ! can you please take a look to the sd card in the zoom audio recorder and remove files that have already been uploaded to dropbox or published on the website ? i get a bit confused a few minutes after having recording a podcast with Roger and Meredith Tromble earlier today.. thank you !

**Comment by amb141330** [comment]
I actually have never used an SD card reader and I am unsure which podcasts have already been uploaded. @coreysmart92 Work with me on this?

**Comment by amb141330** [comment]
Currently there's several unnamed files in the zoom. I haven't listened to every single podcast so it's difficult for me to know which ones have, and haven't, been uploaded yet. @yvantina

**Comment by yvantina** [comment]
closed
