### ISSUE TITLE
a new leonardo podcast with Meredith Tromble

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#332]
@coreysmart92 Please find a new podcast on dropbox under the new leonardo folder called "aesthetics of complexity: dystopia of scales" - Roger will may want to update/correct the title so please double check with him - thanks

**Comment by coreysmart92** [comment]
I have found and scheduled it for editing. (9/28/15)
Close: When podcast is published.

**Comment by yvantina** [comment]
@coreysmart92  please ask podcast info form to Roger - thanks

**Comment by coreysmart92** [comment]
No problem will do.

**Comment by porteriffic** [comment]
@coreysmart92 Is there an update for this?

**Comment by coreysmart92** [comment]
Ashton has finished editing, I will email and have Roger complete the forms.
Close: when podcast has been published. (11/2/15)

**Comment by coreysmart92** [comment]
Hal has put it on Libsyn, I will transfer this issue to Hal.
Close: When podcast has been published.(11/30/15)

**Comment by yvantina** [comment]
Any update on this ?

**Comment by cassininazir** [comment]
@amb141330 can you make sure that this goes on the Podcast Production Sheet?

**Comment by cassininazir** [comment]
@halclark any update on this?

**Comment by halclark** [comment]
Podcast was published March 18 http://creativedisturbance.org/podcast/aesthetics-of-complexity-the-distopias-of-scale-eng/
