### ISSUE TITLE
Podcast with Roger Malina & Eun Ah Lee

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#334]
@coreysmart92 I have the podcast that was recorded with Roger and Eun Ah last Friday. I'd like have Eun Ah listen to the podcast before uploading it. I'll create a file in Dropbox and upload it there. 

Close when you've received the podcast.

**Comment by rmalina** [comment]
dont publish this podcast without eun ah's approval
she may not want it published

roger

On Tue, Sep 29, 2015 at 10:21 AM, porteriffic notifications@github.com
wrote:

> @coreysmart92 https://github.com/coreysmart92 I have the podcast that
> was recorded with Roger and Eun Ah last Friday. I'd like have Eun Ah listen
> to the podcast before uploading it. I'll create a file in Dropbox and
> upload it there.
> 
> Close when you've received the podcast.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/334.

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by porteriffic** [comment]
@coreysmart92 Podcast is located in the Dropbox right now. Let me know when this podcast is done editing and I'll email Eun Ah and get her approval.

**Comment by coreysmart92** [comment]
This is the Femgineers podcast, it is scheduled to edit. (10/5/15)

**Comment by porteriffic** [comment]
@coreysmart92 Is this podcast done editing? If so, it needs to be sent to Eun Ah for review before scheduling.

**Comment by coreysmart92** [comment]
@porteriffic I have emailed the completed version of the podcast to you. Let me know if there is anything else I need to edit or do for this podcast. (10/16/15)

**Comment by linamoon** [comment]
Album art is ready to go in the Album Artwork folder (below) to be used when ready. Also see issue #310 
- https://drive.google.com/open?id=0BwvQhnxKj6jFdGN2MVpfYUx5ZHM

**Comment by coreysmart92** [comment]
The wrong audio file was uploaded to dropbox, this has been corrected and the podcast will be edited by 11/5/15.
Close: When the edited podcast has been sent to Eun Ah Lee. (11/2/15)

**Comment by rmalina** [comment]
corey
and make sure eun ah wants to publish it or not
this was a test podcast and she may not want to
publish it

roger

On Mon, Nov 2, 2015 at 11:20 AM, coreysmart92 notifications@github.com
wrote:

> The wrong audio file was uploaded to dropbox, this has been corrected and
> the podcast will be edited by 11/5/15.
> Close: When the edited podcast has been sent to Eun Ah Lee. (11/2/15)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/334#issuecomment-153089098
> .

## 

Roger F Malina
is in Dallas

**Comment by coreysmart92** [comment]
This podcast is done editing and has been sent to Eun Ah Lee.
Close: When podcast is published. (11/30/15)

**Comment by porteriffic** [comment]
@coreysmart92 When is this podcast scheduled to be published?

**Comment by rmalina** [comment]
I don't think eun ah wants to publish it

**Comment by porteriffic** [comment]
@rmalina She sent an email earlier this week approving it.

**Comment by rmalina** [comment]
Ok greAt

**Comment by coreysmart92** [comment]
Closing: This podcast has been published.
(1/25/16)
