### ISSUE TITLE
Podcast Awards!!!@!#!$!!!!! Exciting.

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#335]
Cassini mentioned we should look into the podcast awards for this upcomming year on http://podcastawards.com/

Here is a link to last years rules/regulations. This year's rules should be almost exactly the same. I think this is information to relay to our ELIGIBLE producers and see if they would like to participate/promote via social media.

http://podcastawards.com/index.php?option=rules

**Comment by rmalina** [comment]
cassini
we could either nominate creative disturbance as a whole or
one channel with more than ten podcasts or maybe both ?
eg virtual africa has 20 podcasts up

would we nominate it in the mitpress context as part
of the move with the new web site ?

roger

On Fri, Oct 2, 2015 at 12:41 PM, amb141330 notifications@github.com wrote:

> Cassini mentioned we should look into the podcast awards for this
> upcomming year on http://podcastawards.com/
> 
> Here is a link to last years rules/regulations. This year's rules should
> be almost exactly the same. I think this is information to relay to our
> ELIGIBLE producers and see if they would like to participate/promote via
> social media.
> 
> http://podcastawards.com/index.php?option=rules
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/335.

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by porteriffic** [comment]
@linamoon Let's come up with an email to send out to producers.

**Comment by porteriffic** [comment]
@dylanorgeron @cassininazir Roger is wanting to have the website redesigned before we submit to the Podcast Awards.

**Comment by linamoon** [comment]
@porteriffic Were we planning to send this email out this week (10/12)? Couldn't remember.

**Comment by porteriffic** [comment]
@linamoon I think so. I vaguely remember. Were we going to just send an announcement or ask producers to submit?

**Comment by amb141330** [comment]
Basically just ask eligible producers if they are interested in participating. As far as I know we will be the ones who submit their channel.

**Comment by amb141330** [comment]
@porteriffic @linamoon any update on that email?

**Comment by porteriffic** [comment]
@amb141330 Currently we're working on emails for Art COP21. I can put this on our to-do list for next week. Sorry it's taking so long.

**Comment by amb141330** [comment]
@porteriffic I think we should try and get these emails out before the middle of this month

**Comment by porteriffic** [comment]
@amb141330 Lina and I have it scheduled to be sent out this Thursday. I have the email content but may need your input before today's meeting.

**Comment by amb141330** [comment]
Issue #387 will have updates on this. The emails have been sent out to producers, but in that issue I will be providing a list of the eligible channels and suggested categories.
