### ISSUE TITLE
possible podcasts for art and climate change !!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#336]
@coreysmart92 @porteriffic 
just received from SLSA newsletter -
The organizers should be ideal persons to interview before the workshop ! 
please see attached 

---------- Forwarded message ----------
From: Susan M. Gaines smgaines@uni-bremen.de
Date: 2015-10-05 7:30 GMT-05:00
Subject: Fiction Meets Science workshop on climate change fiction
To: LITSCI-L@duke.edu

Dear SLSAers,

 This workshop may interest some of you, especially if you have plans to be in Europe next spring. 
Between fact and fiction: climate change fiction Fiction Meets Science Workshop
Hanse Wissenschaftskolleg, Delmenhorst, Germany 
22 - 23 April 2016 
[FMS Cli-fi workshop LET.pdf](https://github.com/creativedisturbance/podcasts/files/7819/FMS.Cli-fi.workshop.LET.pdf)
A call for papers is attached.
For more information, please contact the workshop organizers:
Dr. Sina Farzin (University of Hamburg) sina.farzin@wiso.uni-hamburg.de
Emanuel Herold (University of Bremen) emherold@uni-bremen.de

All Best,

Susan

---

Susan M. Gaines

Writer in Residence | Co-Director, Fiction Meets Science

Faculty of Linguistics and Literary Studies (FB10)

University of Bremen

Bibliothekstraße 1

28359 Bremen GERMANY

Tel: +49 (0)421 347 8030 | SKYPE: susan.m.gaines | Mobile: +49 (0)176 322 95462

www.fb10.uni-bremen.de/lehrpersonal/gaines.aspx

www.fictionmeetsscience.org

**Comment by porteriffic** [comment]
@yvantina Will be contacting the organizers.

**Comment by porteriffic** [comment]
@yvantina Any update on contacting the organizers? I will include this in the COP21 action plan.

**Comment by yvantina** [comment]
@porteriffic I thought you said you are going to contact them (see above) - I have no problem forwarding an email if you send me the right template

**Comment by porteriffic** [comment]
@yvantina I apologize I should've worded that better. What I meant was you will be contacting them. I tagged you in the post instead of actually saying your name.

I can go ahead and contact them but I won't be doing a podcast with them. I'll need someone else to do it.

**Comment by yvantina** [comment]
@porteriffic Josephine, I can't do podcasts with everyone on this planet :) no seriously i wish I could but am already overwhelmed with my own CD duties, not even mentioning school etc. what I can do, and i'm happy to do so, is forwarding an invitation to collaborate for this special day but I think it looks more professional if it's sent from CD's official email address letting them know that they can definitely sent their own podcast- at least we can suggest the idea or help them to do so by precising our specific format (duration, content...).  Here is where you (or someone else) could also recommend me (or someone else) as another option but the very idea is first to send an invite and spread out the information..

**Comment by porteriffic** [comment]
@yvantina I agree with you. I misunderstood you when we chatted about this in person. I would prefer to send the email but will have to find someone to do the podcast with them since I'll probably be doing the podcast with all the other people I invite (which are 9 people at this point). 

If there is someone on that list that interests you, let me know. You can view all the people I will be contacting [here](https://docs.google.com/document/d/1Cj5yhRLJsWVzmWLsy26_RRqU7uuTc5upaQF-V2PZ-UI/edit#), listed under "Leads".

**Comment by yvantina** [comment]
👍
still don't understand why you need to find someone to do a podcast with if you let them know they can submit their own podcast as long as it falls under our requirements... Suggest someone from our team only as a second or third option.. people are most likely willing to do something with their own colleagues and friends than with strangers

**Comment by yvantina** [comment]
@porteriffic one more (LAST) suggestion for guests - I Am happy to do podcasts with these ones if they're interested !!! http://zkm.de/en/event/2015/10/globale-exo-evolution

**Comment by porteriffic** [comment]
@yvantina Great. I'll add that to the list.

**Comment by porteriffic** [comment]
I've emailed the organizers of this workshop and the curator the Globale: Exo-Evolution Exhibit. Will update through the Art & Climate Change Action Plan
