### ISSUE TITLE
Process for Recording a Podcast in the ArtSciLab

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#337]
Write up a process for recording podcast in the ArtSciLab and ATEC building.

**Comment by coreysmart92** [comment]
Still on hold. Will resume 11/9/15.

**Comment by coreysmart92** [comment]
Closing: Ashton and Brian have made a process for recording in the ArtSciLab. I will make a new issue to write a process for other methods of recording.
(1/25/16)

**Comment by rmalina** [comment]
we were unable to use the system last friday-please close this when the
system has been checked out and htere is an instruction sheet
roger

On Mon, Jan 25, 2016 at 11:51 AM, coreysmart92 notifications@github.com
wrote:

> Closed #337 https://github.com/creativedisturbance/podcasts/issues/337.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/337#event-525326289
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by cassininazir** [comment]
Corey, please add a link to the document being referenced here.

Cassini Nazir

Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
Director of Design and Research, ArtSciLab
The University of Texas at Dallas
