### ISSUE TITLE
Contact Guy Edmonds

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#339]
Contact Guy Edmonds for World Day of Audiovisual Heritage Day

**Comment by coreysmart92** [comment]
I emailed Guy and have received a  response. He is very interested in making a podcast. He has told me the times he is available and I will try to setup a time for him to make a recording.
Close: When the podcast is recorded. (10/15/15)

**Comment by porteriffic** [comment]
@coreysmart92 Any update on the podcast recording?

**Comment by rmalina** [comment]
josephine
i am the one holding this one up as
i will do the podcast with him
roger

On Fri, Oct 23, 2015 at 11:40 PM, porteriffic notifications@github.com
wrote:

> @coreysmart92 https://github.com/coreysmart92 Any update on the podcast
> recording?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/339#issuecomment-150699918
> .

## 

Roger F Malina
is in Spain

**Comment by rmalina** [comment]
@coreysmart92 
corey i have recorded the guy edmonds podast it is in new leonardos drop box
i filled out the forms in the new forms
can you confirm you got the forms and are ready to go
you will need to edit the podcast a bit as there are some gaps
roger

**Comment by coreysmart92** [comment]
I have both the audio file and the forms. The podcast has been scheduled for editing.
Close: When podcast has been published. (11/2/15)

**Comment by porteriffic** [comment]
Podcast has been published.
