### ISSUE TITLE
Meet with Roger about Art & Climate Change

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#340]
Set up a meeting with Roger to discuss Art & Climate Change splash page.

**Comment by rmalina** [comment]
we need to meet and get going
for the social media plan for art and climate change here are so me places to twitter
roger

Climate Change Conference London 21st December 2015:

The next ‘Planning for Climate Change’ Conferences will be held on the 21st December 2015 in London and on the 28th October 2015 in Dublin. Details can be found here and details of the current speaker line up can be found here for London and here for Dublin.   Details can also be found on Facebook & Twitter.   The key focus of both days is to debate and discuss the key issues that face communities, economies and society when it comes to adapting to climate change and addressing the problems and opportunities that climate change brings.  We plan to have up to 30 speakers plus up to 150 delegates on the day.   To register as a delegate, or a speaker please access the registration page or email your requirements  to be a delegate or with your proposal for a speaking slot here.  The cost to attend as a delegate and/or speaker for either conference is as follows:

Delegate and/or Speaker full rate: £250 plus VAT (total of £300).
Reduced rate for students/researchers Delegate and/or Speaker: £125 plus VAT (total of £150).

Climate Change Journal Launch London 21st December 2015:

At the Planning for Climate Change Conference we will be launching a new academic, policy and research Journal called the Journal of Planning for Climate Change.  This Journal will be a focus point to promote and share research and good practice on how we plan and adapt to the challenges that we face from increasing climate change.  We welcome contributions from anyone who has an interest in this area of policy and we welcome anyone who would like to be a member of the Journal Editorial Board.  If you want to submit a paper for publication please email here. To subscribe to the Journal please visit the subscription page or email here.  Details of the Journal Editorial and Submission Guidance can be found here. 
To unsubscribe from future emails please unsubscribe here. 
Planning for Climate Change Team
Place and Space Research
86-90 Paul Street
LONDON EC2A 4NE
United Kingdom

**Comment by coreysmart92** [comment]
@porteriffic I am assigning this issue to you. I the last sound meeting (10/12/15) we decided that each splash page would have a coordinator. This position is the same person who does the description. The job is to coordinate with producers and voices to bring in or plan out podcast for the given splash page. Roger would like to setup a meeting and work out an action plan. Let me know if you need any help, or anything from me.
Close: When you have met with Roger and talked about an action plan for Cop21 podcasts. (10/15/15)

**Comment by porteriffic** [comment]
@rmalina I'll go ahead and start an action plan. I know you'll be out next week (10/19-10-23). Can you meeting on 10/36 Monday @ 10am?

**Comment by porteriffic** [comment]
Meeting @ 10am on Monday 10/19.
Closing. This is a duplicate.
