### ISSUE TITLE
podcasts in other languages

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#341]
for any podcast in a language that the sound editor doestn know
a second person needs to listen to it to validate that it conforms to
our policies on acceptable language etf ( swearing, insults etc)

please modify the podcast editor cheat sheet to include this
site on all non english podcasts

roger
@porteriffic

**Comment by linamoon** [comment]
Closing this issue due to redundancy- please refer to issue creative disturbance guidelines #342
