### ISSUE TITLE
creative disturbance guidelines on acceptable speech

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#342]
develop acceptable speech guidelines for our podcasts

sound editors would be responsible  for checking this off

at the meeting the idea of getting the utd radio station
and the utd magazine ) lina had contacts

chaz lillu can probably help

roger
@coreysmart92 @linamoon

**Comment by linamoon** [comment]
From issue #341:

for any podcast in a language that the sound editor doestn know
a second person needs to listen to it to validate that it conforms to
our policies on acceptable language etf ( swearing, insults etc)

please modify the podcast editor cheat sheet to include this
site on all non english podcasts

**Comment by linamoon** [comment]
I briefly talked with Anwesha in student media:
- Radio plays just follow the FCC guidelines (which I can look into)
- Print has their own Code of Conduct handbook, and I've asked the EIC to send me a copy that we can reference. Haven't heard back from him yet.

**Comment by linamoon** [comment]
From the Student Media handbook (I can provide a copy for reference):

The Mercury follows the **Associated Press’ guide** to profane word usage. 

Inclusion of profanity and vulgarity is discouraged **if it is used exclusively for humor or shock value** and **lacks any journalistic reasoning** for its use.  Profane or vulgar language may be acceptable in quotations when used by official sources (university faculty, staff or students in positions of authority or elected office) if the language **shows particular relevance in the context of the article** or agate copy. 

Profane or vulgar language should not be used in opinion pieces.

**Comment by porteriffic** [comment]
Created a document under "4.0 Reference Documents" in the Google Drive. [Guideline on Acceptable Speech](https://docs.google.com/document/d/1vgGo9dCR5Xaw22ujymqAx1nXx9Bb2dm-XWDImdklATU/edit).

**Comment by rmalina** [comment]
please add a link to the fcc guidelines
and discuss at a next meeting
roger

On Fri, Oct 23, 2015 at 5:27 PM, porteriffic notifications@github.com
wrote:

> Created a document under "4.0 Reference Documents" in the Google Drive. Guideline
> on Acceptable Speech
> https://docs.google.com/document/d/1vgGo9dCR5Xaw22ujymqAx1nXx9Bb2dm-XWDImdklATU/edit
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/342#issuecomment-150607747
> .

## 

Roger F Malina
is in Spain

**Comment by porteriffic** [comment]
Link to FCC guidelines has been added.
