### ISSUE TITLE
new guest info !!! ?

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#347]
@coreysmart92 @dylanorgeron @cassininazir 
so I've been using the new podcast form for my podcasts but just to make sure you don't bother these guests once again as i asked for their info before we implemented the new versions  -i'm copying below their bios info (attached are the pics)
![jepchumba](https://cloud.githubusercontent.com/assets/10967939/10333920/83414fdc-6cac-11e5-990f-e4fb8de163e4.jpg)
![tegan_wsoa-staff-photo](https://cloud.githubusercontent.com/assets/10967939/10333921/834e1c6c-6cac-11e5-9c46-ab59fc9e34d1.jpg)

= please don't email them again to request these info as they already sent it to me - it would look unprofessional 
also i'm kind of reluctant to share this guest page http://creativedisturbance.org/forms/guest/
because it's currently only accessible to CD members - should a voice need to be a member prior to the podcast release, if ever ? not sure.. as many of them may have not heard about us before the actual interview..
i keep using this one instead https://creativedisturbance.wufoo.com/forms/creative-disturbance-guest-release-form/  but let me know when we should move to the new one !
thanks

---

podcast title : "After Fakugesi. The Post African Futures Labs"
guests : Tegan Bristow and Jepchumba

1/ Jepchumba has been listed by Forbes as one of the 20 Youngest Power Women in Africa 2012 and in theGuardian Africa’s Top 25 Women Achievers. A cultural ambassador, Jepchumba is the Founder and Creative Director of African Digital Art, a collective and creative space where digital artists, enthusiasts and professionals can seek inspiration, showcase their artistry and connect with emerging artists.  Jepchumba is dedicated to promoting the growth of the creative technology in Africa. Originally from Kenya, she has lived, travelled and spoken around the world promoting her commitment to creativity, art and technology. An African digital artist she is passionate about creating unique digital experiences. She loves experimenting with motion, sound and various digital effects and techniques and has an extensive background in digital art, web design and development, audio/visual production and user interface and user experience design.
http://africandigitalart.com
Twitter: http://twitter.com/digitalafrican
Instagram: http://instagram.com/digitalafrican

2 / Tegan Bristow is an interactive media artist and lecturer at the Digital Arts Division of the Wits School of the Arts. Lines of computer code are to her what a golden sunset is to a landscape painter – the stuff of inspiration and the spark of creative potential. Tegan is most interested in the space that digital art affords interaction and engagement, the place where she believes meaning is made. Apart from being involved in the creation of the first digital art festival in Africa, namely the Fakugesi, she is also working towards her PhD and regularly writes and presents papers at interactive technology forums around the world. Tegan is a self-proclaimed geek at heart, curious about how the world around her works, and believes that creative people should challenge technology and how it is used, every day.
http://teganbristow.co.za/

**Comment by yvantina** [comment]
same goes for these ones (below is guest info, attached is the pic)
![morgan trevor](https://cloud.githubusercontent.com/assets/10967939/10333943/a748d9b8-6cac-11e5-8323-007bb445d0a0.JPG)

@coreysmart92 in order to make it more fluid and agreable to hear, can you please remove the silences,  repetitions and noises that appear sometimes in the records ? we had some skype/internet issues that led to few misunderstandings and quiproquos.. thanks

---

podcast title: "A Lovely Weather : Eco-Cancer and Garbage Art" (this is part 1) and "A Lovely Weather : In Defense of Waste !" (this is part 2)

Guest : Morgan Trevor
Trevor Morgan is an artist, writer and researcher at the University of Nigeria, Nsukka where he teaches Visual Communication Design and digital art (3D modelling, animation and web media art). In his recent works, he tried to engage the mediatory role of art in contemporary issues of society such as culture, environment, climate change and so on.

**Comment by amb141330** [comment]
@yvantina we still need the description of the podcasts and keywords

**Comment by coreysmart92** [comment]
I will confirm that all the information published is correct.
Close: After I publish the Lovely Weather podcasts with Morgan Trevor.

**Comment by porteriffic** [comment]
Podcasts have been published
