### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#349]
this was on facebook
i followed the link but the human impacts channel wasnt there
roger
@linamoon @dylanorgeron 

Creative Disturbance
Published by Hootsuite · Yesterday at 8:35am · 
The Human Impacts Institute has been kind enough to share their podcasts on the Creative Disturbance platform starting this week! Head on over to our website to check out The Human Impacts Channel! http://ow.ly/T20s8

**Comment by porteriffic** [comment]
@rmalina It was just supposed to be a link to the website. I was going to replace the link in hopes that the Human Impacts Channel would be up by then. I'll go ahead and remove the tweet since the channel is not up yet.
