### ISSUE TITLE
Do we need an online checklist for CD 2.3.0 and CD 2.2.2.9?

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#35]
Explore what problems this solves: 
- How do we translate improved procedures into improved product.

**Comment by coreysmart92** [comment]
Finish Cheat Sheet First.

**Comment by coreysmart92** [comment]
In house Check List for Sound Editors about the production process. Review [CD 2.2.2.5 Posting a Complete Podcast](https://docs.google.com/document/d/124eiA3g5XaeDlbtN-yrAfTi9yVGz-2DwgWn5s0HqnlY/edit).

**Comment by rmalina** [comment]
thanks for updating- the date on the document still says feb 3 ? is this the latest version

i looked at the instructions for titles of podcasts-it says
Episode = Title of Podcast
If Podcast is in a Non-English Language then add two letter abbreviation of language in parentheses to end of podcast title.

it says nothing about making sure the title is at least a half of full sentence with some
kind of indication of the content and NOT just the name of the person in the podcast-
sound editors should be rejecting podcasts whose title are inadequate and working with the producer to improve the title

roger

**Comment by coreysmart92** [comment]
Nothing new to report. (8/3/15)
