### ISSUE TITLE
Forms for Aesthetics of complexity with M. Tromble

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#350]
@rmalina Can you fill out these forms?

**Comment by rmalina** [comment]
will do in next few days

roger

On Sun, Oct 11, 2015 at 5:54 PM, amb141330 notifications@github.com wrote:

> @rmalina https://github.com/rmalina Can you fill out these forms?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/350.

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
Any update on this?

**Comment by rmalina** [comment]
Will try and do tomorrow

From roger malina

**Comment by rmalina** [comment]
i have uploaded the form for meredith tromble

**Comment by rmalina** [comment]
ashton-i think i submitted for the for for the meredtih tromble-can you confirm you have it ? roger @amb141330  i think i also submitted her voice bio-but cant figure out how to check-roger

**Comment by rmalina** [comment]
ashton can you confirm you have what you need to publish tromble and tell me planned publication date, thanks, roger @amb141330

**Comment by amb141330** [comment]
So, I wasn't getting notifications for this so I just saw it. The guest info is on the site, but not the actual form the the podcast including description and what not.

**Comment by rmalina** [comment]
Ok will do

**Comment by rmalina** [comment]
done except for confusion as to whether there are one or two podcasts

**Comment by rmalina** [comment]
ashton
can we close this one ? @amb141330 
roger

**Comment by amb141330** [comment]
Yes we can close this. Thank you.
