### ISSUE TITLE
Email Announcing New Forms

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#352]
@linamoon I think we were planning on sending this out end of last week but got delayed since I haven't been in. Is it possible to send this email out this week? We already have a blog post on this.

**Comment by linamoon** [comment]
@porteriffic Yes - we should definitely do that. I can do a draft from the blog post and maybe you can look over it? I'll send you something by the end of today.

**Comment by porteriffic** [comment]
@linamoon Sounds good. I'll be in the lab tomorrow morning.
