### ISSUE TITLE
Setup meeting with Roger for COP21 Coordination

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#354]
@porteriffic, @rmalina  

We updated the Feature Day document to include coordinators. I've added you as coordinator for the COP 21 (Art and Climate Change) feature. Can you setup a meeting with Roger to figure out a path forward? 

https://docs.google.com/document/d/1lA0UaMrmaxg-rOLGox4mCvvn_tB3DBqwo5PoWWsPgZA/edit#

**Comment by porteriffic** [comment]
We're meeting Monday, October 19th @ 10am

**Comment by porteriffic** [comment]
Roger and I met and developed an [action plan for Art COP21](https://docs.google.com/document/d/1Cj5yhRLJsWVzmWLsy26_RRqU7uuTc5upaQF-V2PZ-UI/edit#). This action plan will be updated and referred to by the CD Team.

**Comment by rmalina** [comment]
josephine
great
lets make sure we get two human impacts podcasts up a week
only one went up this week
roger

On Thu, Oct 22, 2015 at 5:48 PM, porteriffic notifications@github.com
wrote:

> Roger and I met and developed an action plan for Art COP21
> https://docs.google.com/document/d/1Cj5yhRLJsWVzmWLsy26_RRqU7uuTc5upaQF-V2PZ-UI/edit#.
> This action plan will be updated and referred to by the CD Team.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/354#issuecomment-150268080
> .

## 

Roger F Malina
is in Spain
