### ISSUE TITLE
Work with Hal on theme and design of experimental home page

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#355]
http://x.creativedisturbance.org/ 
- Lead-in content for home page
- ???

**Comment by halclark** [comment]
@linamoon when are you available to meet with me for this?

**Comment by linamoon** [comment]
@halclark I can do next Monday 3-5pm when you have your lab hours.

**Comment by halclark** [comment]
@linamoon Sorry I never saw this. Will talk to you tomorrow during the meeting.

**Comment by halclark** [comment]
This is taken care of.
