### ISSUE TITLE
nowhere else channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#357]
corey
can you assign this new channel to someone
and get the channel up as quickly as possible

roger

Thank you very much ! Mahsoo
Please let me share this with Roger Malina and Cassini Nazir 
for the implementation of this disturbance. No where else ! Yay !
Someone will contact you soon to proceed. 
Very best 

2015-10-13 17:16 GMT-05:00 Mahsoo Salimi salimi@sfu.ca:
Dear Yvan,

I have attached the logo and name (NOWHERE ELSE) for our channel (with Dr Gromala and PianLab at SFU).
Please let me know how we could upload our personal info.

Bests,
Mahsoo

```
Diane Gromala <gromala@sfu.ca>
```

to: Yvan Tina yvantina@gmail.com
cc: "Maryam (Mahsoo) (Mahsoo)" salimi@sfu.ca,
Roger Malina rmalina@alum.mit.edu,
Cassini Nazir cassini@utdallas.edu

**Comment by coreysmart92** [comment]
@halclark I am assigning this channel to you, let me know if you need help.
Close: When the channel is published. (10/15/15)

**Comment by halclark** [comment]
@coreysmart92 let's talk about this tomorrow.

**Comment by porteriffic** [comment]
@yvantina I've emailed Mahsoo and Dr. Gromala. They have instructions how to start their channel and I offered my assistance if they ever need it.

**Comment by yvantina** [comment]
Thanks so much Josephine ! Yes, I think they are eager to start it ! we'll see. more soon

**Comment by yvantina** [comment]
@porteriffic Please let me know how this evolve ! Bon week end

**Comment by porteriffic** [comment]
@yvantina I emailed them but haven't received a response since then. I'll let you know if they respond. I can touch bases with them soon. Maybe not this week because of Thanksgiving but would next Monday work?

**Comment by yvantina** [comment]
Okay

**Comment by coreysmart92** [comment]
@amb141330 are you in charge of this channel or is @halclark?

**Comment by amb141330** [comment]
There is another issue for nowhere else, closing this one.
