### ISSUE TITLE
clean up New Leonardo's channel in drop box

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#358]
corey
can you go through the new leonardos channel drop box and
clean it up 
- some of the podcasts have already been blished and need to be taken out
  of drop box and moved to where you are archiving

-some of the podcasts have not been published yet and you need to assign them
to an editor and move them to editing

roger

**Comment by coreysmart92** [comment]
Closing: I have gone through backed-up and removed all podcasts that were published. (10/15/15)
