### ISSUE TITLE
music rights

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#36]
team
in the first tim perkis podcast -he uses music segments by other famous composers- we need to make sure that when we post a podcast we have the rights for the music covered ( and we need to be careful on the stingers) i think the rights release from needs to be modified to ask the producer/voice that they have the rights to any music used in the podcast
roger

**Comment by coreysmart92** [comment]
Kim Knight Class

**Comment by porteriffic** [comment]
Ask Kim Knight what she has her class uses for them to check the rights for music
