### ISSUE TITLE
Creative disturbance students present at RAW

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#360]
cassini

lets brainstorm how we can use RAW to do some kind of student
presentatins from creative disturbance 

roger

Poe Johnson
11:41 AM (10 minutes ago)

to Cassini, roger 
Not mentioning sound might be something of a self-fulfilling prophecy. Since I've been organizing RAW, we've never had a proposal that dealt with sound design so it's not included  in the CFP, but maybe we've never had a sound design proposal because it's not included in the CFP. That said, we would more than welcome sound design projects. 

Because I will be organizing and running the conference, I can't see myself being a presenter. However, I think it would be great if Creative Disturbance could have a presence there, not just on a panel, but maybe in recording podcasts with panelists and presenters. 

Sent from Outlook

---

From: roger malina rmalina@alum.mit.edu
Sent: Wednesday, October 14, 2015 11:25 AM
Subject: Re: raw
To: Nazir, Cassini cassini@utdallas.edu, Poejohnson poejohnson@gmail.com

cassini
maybe we can organise a small panel where we present
the gender and diversity aspects of creative disturbance
we can discuss later

roger

poe-see cassini's comment about lack of reference to sound !

On Wed, Oct 14, 2015 at 11:21 AM, Nazir, Cassini cassini@utdallas.edu wrote:

> Glad you sent this out. Yes! I can send out to everyone but think the most interested/likely candidates are probably:
> 
> Lina
> Chaz
> Poe
> 
> Encouraging the sound designers to submit their work will be important too. Interesting that anything sound related is not listed in the submission list!
> 
> Cassini Nazir
> 
> Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
> Director of Design and Research, ArtSciLab
> The University of Texas at Dallas
> ---
> 
> From: leonardo.isast@gmail.com [leonardo.isast@gmail.com] on behalf of roger malina [rmalina@alum.mit.edu]
> Sent: Tuesday, October 13, 2015 8:09 PM
> To: Nazir, Cassini
> Subject: raw
> 
> cassini
> why dont we try and organise a strong contingent of
> presentations at RAW this year from art sci lab
> 
> including undergraduate research !
> 
> roger
> 
> Theme: The Humanities and Social Justice
> 
> University of Texas at Dallas
> Arts & Humanities Graduate Student Association
> utd.gsa@gmail.com
> March 4th and March 5th, 2016
> Keynote: Dr. Sandy Stone
> Theme: The Humanities and Social Justice
> Submission Deadline: December 18th, 2015
> The Arts & Humanities Graduate Student Association of the University
> of Texas at Dallas will hold its eighth annual RAW: Research, Art,
> Writing Graduate Symposium on March 4th and 5th at the UT Dallas
> campus in Richardson, TX. Organized by and for graduate students, RAW
> offers students from around the country the opportunity to share their
> work and ideas with peers across the humanistic disciplines.
> Despite a growing rhetoric to the contrary, the humanities have never
> been more important. The perpetuation of systemic oppressions—poverty,
> anti-gay violence and legislation, sexism, police brutality, racism,
> and militarization—has generated social unrest throughout the world.
> The theme of this year’s RAW, “The Humanities and Social Justice,”
> focuses on scholarly efforts in all humanities-related fields to
> address the institutional marginalizations that have inspired activist
> movements. RAW is dedicated to amplifying the voices of all graduate
> students within the humanities; regardless of the theme, we will
> accept papers or panels from any academic focus or discipline as long
> as it connects with the humanities.
> This year we are proud to welcome Dr. Sandy Stone as our keynote
> speaker. For over thirty years, Dr. Stone’s writings on critical
> theory and media, along with art that conceptualizes the relationship
> between technology and identity, have combined the intense rigor of
> academic work with an investment in the lives and well-being of
> marginalized people. In 1979, her foundational text, “The Empire
> Strikes Back: A Post-Transsexual Manifesto,” helped create space for
> Transgendered Studies and other academic fields of inquiry dedicated
> to exploring the realities of marginalized groups from their own
> perspectives. The founding director of the ACTLab at the University of
> Texas at Austin, Dr. Stone exemplifies the interdisciplinary spirit at
> the heart of the A&H program at UT Dallas and the RAW Graduate
> Symposium.
> Each interested participant may submit one 200-word abstract for a
> 15-minute individual presentation and/or one submission of a full
> panel that includes three to four individual presentations. There are
> no limitations on topic, field, genre, or methodology.
> Submissions may include, but are not limited to: • excerpt of an M.A.
> paper or thesis • excerpt of a seminar paper • excerpt from a
> dissertation • animation, video, or film projects • excerpt from a
> novel, play, or short story • M.F.A. final project • selection of
> poetry • dance or other performance piece • art work (paintings,
> ceramics, drawings, etc.) • games
> Proposals are due by December 18, 2015. All proposals must include the
> following: • A complete mailing address, e-mail address, phone number,
> field, and affiliation of participant • An abstract of no more than
> 200 words for the proposed presentation that includes 3 to 5 keywords
> • For creative pieces, the medium and space requirements for the
> work/presentation
> Panel proposals must include a proposal for the panel, a short
> description of each presentation, and the above information for each
> participant. Send submissions and questions to utd.gsa@gmail.com.
> Registration information will follow. For additional information, see
> www.utdgsa.com.
> ## 
> 
> Roger F Malina
> is in Dallas
> 1-510-853-2007
## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by porteriffic** [comment]
RAW Conference updates located in Google Drive [here](https://drive.google.com/drive/u/0/folders/0B47T3_SpQdTWSl9QNmltM3J5NUE)
