### ISSUE TITLE
10 new podcasts !

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#361]
@coreysmart92 @amb141330 @halclark 
There is 7 new meta-life podcast in dropbox
please use them !
But please START with thIS 3 Virtual Africa ones !!!
After Fakugesi, EmoticoneS and the Afro-Renaissance 

Let me know if you need anything from me

**Comment by yvantina** [comment]
@coreysmart92 @amb141330 @halclark 
You will open the new Meta-Life podcast series with 
Information and Power in the Age of Biotechnology

thank you !

**Comment by coreysmart92** [comment]
I have scheduled both the Virtual Africa and the Meta-Life podcast. (11/2/15)
Close: when they are published.

**Comment by yvantina** [comment]
Please let me know which forms you'll need ASAP !

**Comment by yvantina** [comment]
@coreysmart92 @halclark @amb141330 
You should be able to publish those podcasts now that you have everything you need (description + guest forms). Please let me know your schedule so I can close this issue ! Thanks

**Comment by coreysmart92** [comment]
Closing: The last of these new podcasts have been published.
(9/25/16)

**Comment by yvantina** [comment]
Nope. You haven't published Starbeast yet, nor prosthetics organs for Meta-Life !!!

**Comment by yvantina** [comment]
Or maybe I'm mistaken ??

**Comment by coreysmart92** [comment]
Star Beast just published. I fell asleep last night before it published and Prosthetics Organs has been completed and scheduled to publish 2/1/16 at 12:30 am.

**Comment by yvantina** [comment]
We also miss the two podcasts called "De l'amitié" with Dominique Lestel !!!

**Comment by coreysmart92** [comment]
Yes those were the podcast Hal believed had to much background noise. I have scheduled them to be published. I am transferring this to @halclark  .
Close: When the podcasts have been published

**Comment by rmalina** [comment]
Please publish them
