### ISSUE TITLE
missing urls 

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#363]
cd team

there is no url or link to the human impacts page

http://creativedisturbance.org/channel/human-impacts-institute/

PLEASE  can we make sure that all bios  and podcasts have
a URL linking to the person or the project

this is embarassing

can anyone posting a podcast or putting up a new channel
or a voice make sure there are live URLS

i listed to the podcast but could not click through

\can you make sure the appropriate check list you use
when you post a podcast is modified to reflect this
@coreysmart92 @halclark @amb141330 

roger

**Comment by amb141330** [comment]
The channel page now has a link for the website. Also the voices have URLs to their pages by clicking the "learn more about.." link. I think the only issue was on the channel page, not the podcast page itself.

**Comment by porteriffic** [comment]
@rmalina I spoke with Lina to see if there's a way to go to the Human Impacts website by clicking the logo and we couldn't find one.

@dylanorgeron Is there a way for us to do this?

**Comment by rmalina** [comment]
can you show a url just below it ?
roger

On Fri, Oct 23, 2015 at 5:21 PM, porteriffic notifications@github.com
wrote:

> @rmalina https://github.com/rmalina I spoke with Lina to see if there's
> a way to go to the Human Impacts website by clicking the logo and we
> couldn't find one.
> 
> @dylanorgeron https://github.com/dylanorgeron Is there a way for us to
> do this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/363#issuecomment-150606336
> .

## 

Roger F Malina
is in Spain

**Comment by porteriffic** [comment]
@rmalina Yes, there's already a URL in the description for the channel and also in the description for the podcast.

**Comment by porteriffic** [comment]
@rmalina Let me know if the URL in the description of the channel and podcast are okay. If so, I can close this issue.

**Comment by rmalina** [comment]
josephie
all is fixed
thanks\
roger
