### ISSUE TITLE
Draft Social Media Posts for Art COP21

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#366]
According to the Social Media Plan/Table located in the [Art & Climate Change Action Plan](https://docs.google.com/document/d/1Cj5yhRLJsWVzmWLsy26_RRqU7uuTc5upaQF-V2PZ-UI/edit), we'll need posts on social media announcing upcoming content (podcasts, splash page, blog, etc.).

**Comment by porteriffic** [comment]
@amb141330 Any update on these posts? The splash page is supposed to go up today.

**Comment by amb141330** [comment]
There was social media posts scheduled during the release week and following week for Art Cop21. I forgot to comment because I worked with Josephine on drafting those posts.
