### ISSUE TITLE
Send out emails and create blog post for CD successes timeline

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#367]
Have:
- Timeline on Codepen: http://codepen.io/linamoon/full/yYGoVV/
- Document with list of key CD moments: https://docs.google.com/document/d/1kRhmFgRqzBiKmqIfFtVzRPG0rnlncQZk31QgJRdfD5c/edit

Need:
- Content for email
- Any add. graphics 

@porteriffic and I can begin working on content and decide on a date to send these out.

**Comment by porteriffic** [comment]
Will send this out when we hit 20,000 downloads. @linamoon and I will be working on it between now and mid November.

**Comment by linamoon** [comment]
Email has been sent out and blog post has been published.
