### ISSUE TITLE
New Podcast Form Issues....

### ISSUE THREAD

**Issue by kkondas** [creativedisturbance/podcasts#37]
So this has happened to me twice now. I've tried to submit a new podcast info form, but every time it comes back asking me to upload the voice pictures and the Estimated Length of Podcast. I repeatedly enter the information again, but it never submits. I end up having to send the sound team a word document and attach the pics to the e-mail.

**Comment by cassininazir** [comment]
Tried duplicating this, but haven�t been able to. Would like to take a look at this on your computer.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by porteriffic** [comment]
Kyle will test using Chrome.

**Comment by coreysmart92** [comment]
Solved by New Forms
