### ISSUE TITLE
Login information for ArtSciLab computer

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#371]
Computer in the lab froze, had to restart, and I do not know what the login information is. Does anyone know?

**Comment by rmalina** [comment]
all passwords are in the password file in gdocs
roger

On Wed, Oct 28, 2015 at 4:13 PM, halclark notifications@github.com wrote:

> Computer froze and I do not know what the login information is. Does
> anyone know?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/371.

## 

Roger F Malina
is in Dallas

**Comment by coreysmart92** [comment]
The login information is:
           Username - art
           Password - science
Closing: I have added this information onto the password and login information document. (11/2/15)
