### ISSUE TITLE
schedule 2 ellen levy podcasts for new leonardos channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#372]
please schedule the two podcasts with ellen levy
that i put in drop box new leonardods file

roger

**Comment by coreysmart92** [comment]
I have scheduled the podcast for editing.
Close: When the podcasts are published. (11/2/15)

**Comment by coreysmart92** [comment]
The podcasts are edited. Once the forms are complete we can publish. I have scheduled the publishing for Friday 12/4/15.
Close: When the podcasts are published (11/30/15)

**Comment by halclark** [comment]
@rmalina , what is the status on the Ellen Levy forms?

**Comment by halclark** [comment]
Assigning this issue to you Roger, as we talked about at Mondays meeting

**Comment by halclark** [comment]
@rmalina have uploaded Ellen Levy 1 and 2, as well as the Tromble Podcast, to creativedisturbance.org/forms. Let me know if you cannot access them.

**Comment by rmalina** [comment]
found them
roger

On Wed, Feb 17, 2016 at 2:49 PM, halclark notifications@github.com wrote:

> @rmalina https://github.com/rmalina have uploaded Ellen Levy 1 and 2,
> as well as the Tromble Podcast, to creativedisturbance.org/forms. Let me
> know if you cannot access them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/372#issuecomment-185397083
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by rmalina** [comment]
hal
went into the form but the podcast itself is not
there-shouldnt it be already there and i can dowload
to listen ?

or are they in box.com ?

if you send this kind of email to other producers
you need to be explicit !

roger

On Wed, Feb 17, 2016 at 2:49 PM, halclark notifications@github.com wrote:

> @rmalina https://github.com/rmalina have uploaded Ellen Levy 1 and 2,
> as well as the Tromble Podcast, to creativedisturbance.org/forms. Let me
> know if you cannot access them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/372#issuecomment-185397083
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by rmalina** [comment]
hal
i have completed the ellen levy 1 podcast
it is now called

_When the Mind is the Medium; On the new connections between art and
neuroscience_

i have saved the form but it would not let me load the podcast

maybe its too big\

_can YOU try and load it into the form ?_

_i did the ellen levy guest form_

_i think ellen levy 1 is ready to publish but can you do an email_
_to her and ask her to confirm it is ok to publish with any_
_corrections etc_

_roger_

On Wed, Feb 10, 2016 at 5:51 PM, halclark notifications@github.com wrote:

> Assigning this issue to your Roger.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/372#issuecomment-182639599
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by rmalina** [comment]
hal
i did ellen levy 1 but it took me an hour because of the form problems
next time you are in lets do ellen levy 2 together so we can file githubs
on all the problems

go ahead and publish ellen levy 1 after she oks it

roger

**Comment by amb141330** [comment]
both podcasts should have been published.

http://creativedisturbance.org/podcast/disorienting-procedures-teaching-consciousness-through-art-science-practice-eng/

http://creativedisturbance.org/podcast/when-the-mind-is-the-medium-on-the-new-connections-between-art-and-neuroscience-eng/

Closing issue.
