### ISSUE TITLE
Farsi Podcast Text Format

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#373]
@dylanorgeron @cassininazir @yvantina The Farsi Podcast has a formatting error, I am not sure if it is because Farsi is read right to left or if this is because we have combine English with Farsi for the post. Can you check the format we used on the Arabic podcasts and see if you can fix two things:
1. Correctly replace the image of IRCAM with text, without moving its position in the paragraph.
2. Make all of the Farsi text justified, except the bottom line which should be right align.
Let me know if you have any questions. Close when the formatting error has been resolved. (10/29/15)

**Comment by yvantina** [comment]
Corey 
Am not sure where the error comes from but Fatemeh told me it's probably due to the combination of Farsi and English

**Comment by dylanorgeron** [comment]
text now right aligned
