### ISSUE TITLE
roger to do podcast with julian reyes in january

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#375]
From: julian reyes [mailto:jrgcop@gmail.com] 
Sent: Saturday, October 31, 2015 7:23 PM
To: Malina, Roger
Cc: Leonardo (manuscripts)
Subject: Re: leonardo manuscript proposal

Yes, I included the 360 video and the link to findr local but the oculus share page link was only made active yesterday. 

That sounds great! I'd be happy to speak to you whenever the time comes. 

Thank you,

Julian

On Sat, Oct 31, 2015 at 2:39 PM, Malina, Roger rxm116130@utdallas.edu wrote:
Julian
Great ! I assume you added the urls in the text ?

**Comment by amb141330** [comment]
No movement on this issue. Closing and adding to people to contact.
