### ISSUE TITLE
podacst with harrison s for art and climate change

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#378]
josephine
my podcast recorded with newton and helen harrison
should go up in new leonardos and is part of art and climate chante

i think its in the editing queue=i cant remember if i did the forms

 corey-can you work the scheduling so this podcast appears
by december 1 ?

roger

@coreysmart92

**Comment by porteriffic** [comment]
@rmalina There is already a GitHub item for this podcast. Located in #325. Corey is waiting on forms and content check. Last update was Monday 11/2.
