### ISSUE TITLE
Create a Schedule for Group Meetings (Once a Month)

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#381]
ArtSciLab Meetings once a month

**Comment by porteriffic** [comment]
I've scheduled meetings [here](http://teamup.com/ksd6a53f8b03c96dea)

**Comment by cassininazir** [comment]
Thanks. We may forget about these dates from having to use another tool. 

Can you also put the dates in a Google Doc that we can refer to?

**Comment by porteriffic** [comment]
@cassininazir Sure can!

**Comment by porteriffic** [comment]
Schedule located in Google Drive under Project Management [CD 1.2.6](https://docs.google.com/document/d/1o2tKweAWNli3SBrs-vS-2IEKE1WVMpYNEYu7EOx3PEM/edit)
