### ISSUE TITLE
Create link to Experimental space from Creative Disturbance website

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#383]
Would like to have a way for people to access to the experimental space from the CD website. 

Was thinking we could put a link up in the main nav, which would lead to either the website or a page introducing the experimental project (which would then link to the experimental website). Working with @halclark on this.

**Comment by cassininazir** [comment]
Agreed on adding to the main nav. We can remove the "Home" button so long as the text "Creative Disturbance" links to the home page. 

@halclark please also work on a blog post to coincide.

**Comment by amb141330** [comment]
Please set up a meeting with Dylan or find some way to make progress on this. I'd like this done before school starts.
