### ISSUE TITLE
RAW Conference - Creative Disturbance

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#384]
Create a 200 word abstract by November 20th for the RAW conference.

http://utdgsa.com/

**Comment by linamoon** [comment]
CD 5.9.2 RAW Conference folder can be found here (putting this for reference): 
- https://drive.google.com/open?id=0B47T3_SpQdTWSl9QNmltM3J5NUE

**Comment by porteriffic** [comment]
Proposals have been sent. Create new items in the future for next steps.
