### ISSUE TITLE
RAW Conference - Arteca

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#385]
Create a 200 word abstract by November 20th for RAW Conference.

http://utdgsa.com/

**Comment by linamoon** [comment]
CD 5.9.2 RAW Conference folder can be found here: 
- https://drive.google.com/open?id=0B47T3_SpQdTWSl9QNmltM3J5NUE

**Comment by linamoon** [comment]
I've put a draft in the RAW Conference folder - think Chaz might look over it before submission, but it's there if anyone wants to look at it. Think it's pretty much good to go. Link to file:
- https://drive.google.com/open?id=12mgzHuxy7GjT99AbcXwVUsuPPBy_gm5KLO3sqqOIOxA

**Comment by linamoon** [comment]
Conference materials submitted and registered for.
