### ISSUE TITLE
RAW Conference - Xperimental

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#386]
Create a 200 word abstract by November 20th for RAW Conference.

http://utdgsa.com/

**Comment by linamoon** [comment]
CD 5.9.2 RAW Conference folder can be found here: 
- https://drive.google.com/open?id=0B47T3_SpQdTWSl9QNmltM3J5NUE

**Comment by linamoon** [comment]
@halclark I've edited the Experimental abstract a little bit and added some comments that might be helpful - see below. Be aware that submissions are due this Fri Dec 18th!
- https://docs.google.com/document/d/14woBZrNi7nJAxg94XP4iYqZFroH_mtxHJAnziujNRPw/edit

@porteriffic - I guess you will be the one collecting and emailing to utd.gsa@gmail.com?

**Comment by porteriffic** [comment]
Proposals have been sent. Create new item in the future for next steps.
