### ISSUE TITLE
Create an Action Plan for Podcast Awards

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#387]
We need to know important dates, info, etc. Use the Art COP21 Action Plan as a template if needed. Deliver by November 20th.

**Comment by cassininazir** [comment]
Let's not assume that producers will submit to this. Please identify specific channels or podcasts to submit by Nov. 20. Please explain.

Deliverable should be a Google Document with the channel, explanation and any additional information.

**Comment by amb141330** [comment]
Here is the document for the Podcast Awards nomination

https://docs.google.com/document/d/1uss-cg0pycF3EKqfUFsbeGzTmojXrZSE8RoZlWN9etU/edit

**Comment by amb141330** [comment]
Document was created in preparation for the last team meeting. Would you like me to send out an email to each specific eligible producer? Also the producers that are close to being eligible?

**Comment by porteriffic** [comment]
@amb141330 That would be great! Maybe include in the email if they don't respond that you'll enter for them?

**Comment by amb141330** [comment]
This is old and I've already submitted everyone to podcast awards.
