### ISSUE TITLE
Please swap these titles and descriptions !!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#388]
@halclark @coreysmart92 hey guys ! please swap the title and descriptions of those two podcasts
the content don't match with the title nor the description - the audio is ok, just change the texts
http://creativedisturbance.org/podcast/a-lovely-weather-eco-cancer-and-garbage-art-eng/ 
with 
http://creativedisturbance.org/podcast/a-lovely-weather-in-defense-of-waste-eng/

Thank you !

**Comment by porteriffic** [comment]
@yvantina I swapped the descriptions. Do the tags need to be swapped as well?

**Comment by porteriffic** [comment]
@yvantina Can you confirm the descriptions are now correct? I can close this issue if it has been corrected.

**Comment by yvantina** [comment]
Nope. almost.  now just swap the titles. thanks

**Comment by porteriffic** [comment]
@yvantina Wait. I'm confused. I just swapped the descriptions. If I swap the titles it'll go back to what they were before...

**Comment by yvantina** [comment]
That's what I said in the podcast issues. Swap both the title and descriptions because it didn't match with the podcast content. Now that you already swapped the descriptions, you need to swap the titles...

**Comment by porteriffic** [comment]
@yvantina Okay. So "content" means the actual podcast. Gotcha. I think that's what confused me. I didn't know what "content" meant (i.e. description, title, tags, etc.). The titles have been swapped. Let me know if I need to make any more changes.

**Comment by yvantina** [comment]
Perfect ! Thank you - wait ! this was assigned to Hal and Corey - why did you end up doing this ?

**Comment by porteriffic** [comment]
Because no one else did it.

**Comment by yvantina** [comment]
Wow !

**Comment by porteriffic** [comment]
I've also been updating the COP21 splash page. I believe the same thing needs to happen for your podcasts on the page as well. Would you mind taking a look just to make sure?

http://creativedisturbance.org/cop21/

**Comment by yvantina** [comment]
Yes Please !

**Comment by yvantina** [comment]
It seems like the links doesn't link to the right podcast/page.. can you help fix this also?

**Comment by porteriffic** [comment]
Working on it right now...

**Comment by porteriffic** [comment]
@yvantina Okay...

The correct title and descriptions should match the podcast on the Virtual Africa page, the splash page, and on each individual page for the podcast.

Let me know if there's anything I missed.

**Comment by yvantina** [comment]
No, that's it ! you rockk !! thanks
