### ISSUE TITLE
task for corey for weekly podcast schedule email

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#39]
corey

can you set up a system so every monday evening an email is sent to the CD team and all producerswith a list of the podcasts going up that week- and which day it goes up

the email should be a standard email with

Week of April x to Y
The following podcasts are being published this coming week
a) monday midnight; name of podcasts, channel
b) tuesday midnight: name of podcasts, channel
c) wednesday midnight, names, channels
d) thursday
e) friday
f) sat midnight
g) sun midnight

roger

**Comment by coreysmart92** [comment]
@coreysmart92 and @cassininazir have discussed making a email template with images. Plan to proceed along this plan of action in the future.

Close this issue when template is completed and the first email has been sent.

**Comment by coreysmart92** [comment]
For creating template - podcast editors need to send examples of emails between them and producers. See #75 for more detail.

**Comment by rmalina** [comment]
i didnt receive any announcement this week

**Comment by cassininazir** [comment]
@coreysmart92 adding a High Priority tag back to this. Not sure why I took it off originally. Apologies. 

This needs to go out by Wed., May 27.

**Comment by coreysmart92** [comment]
I have sent a version to Roger and Kyle, but I want to improve this to include more detail and all of those involved with podcasts being published in that week.
Close when you have updated the system to include all producers, hosts, and voices of that week.

**Comment by rmalina** [comment]
corey-why dont you send it out as it is- you can improve the format next time
roger

**Comment by coreysmart92** [comment]
I have add to the tracking sheet to improve this. I will walk through the changes in Sound meeting on 6/15/2015.

**Comment by coreysmart92** [comment]
Josephine, will walk me through how to update voices. I will make a new template for weekly podcast schedule. (6/22/15)
Close when template is completed.

**Comment by coreysmart92** [comment]
Nothing new to report. (8/3/15)

**Comment by coreysmart92** [comment]
I am taking this off of hold and will have the template to show in next sound meeting-9/7/15. (9/1/15)

**Comment by porteriffic** [comment]
@coreysmart92 Dylan is working on creating emails for this. Once they are ready to go, you might have to provide content for the email (i.e. upcoming podcasts). I'll update you as soon as this is available to us. (11/4)

**Comment by coreysmart92** [comment]
Closing: @amb141330 will be taking this over. I have sent him my template.
