### ISSUE TITLE
climate change page

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#390]
josephine
the art and climate change podcasts are not being added to the splash page
http://creativedisturbance.org/cop21/
several of yvans's art and climate change podscasts dont appear

roger
can you coordinate with corey ?
@coreysmart92

**Comment by porteriffic** [comment]
@rmalina Which podcasts are you speaking of? I see both "A Lovely Weather" podcasts on the splash page. They're currently at the bottom of the page but I'm working on making the most recent podcasts appear at the top of the page.

**Comment by rmalina** [comment]
yvan's two latest podcasts for sure
ask him
roger

On Tue, Nov 10, 2015 at 9:41 PM, porteriffic notifications@github.com
wrote:

> @rmalina https://github.com/rmalina Which podcasts are you speaking of?
> I see both "A Lovely Weather" podcasts on the splash page. They're
> currently at the bottom of the page but I'm working on making the most
> recent podcasts appear at the top of the page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/390#issuecomment-155653081
> .

## 

Roger F Malina
is in Dallas

**Comment by porteriffic** [comment]
@yvantina Okay then yes those podcasts are already on there. They were just at the bottom of the page. I rearranged everything so that the most recent podcasts appear first.
