### ISSUE TITLE
correction to web site

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#393]
josephine
can you make sure this gets taken care of
thanks

roger

Dhruba Deb
12:15 PM (1 hour ago)

to roger, Yvan, Jamie 
Hi Roger,

I am providing a link to your Creative Disturbance at the LuminArte gallery website showing our "Beauty in the Beast" art show. At the same time, I requested Yvan to put a hyperlink in Elisabeth's podcast description to the LuminArte gallery. In this way, we can push audience at each other. Hope this is ok with you.

Best
Dhru

Dhruba Deb, Ph.D.
Postdoctoral Researcher
Hamon Center for Therapeutic Oncology Research
University of Texas Southwestern Medical Center
Dallas, TX, USA

**Comment by porteriffic** [comment]
@rmalina I went to the website but couldn't find a specific page for the "Beauty in the Beast" exhibition. Would it be okay to just use the link for the gallery website? -----> http://luminartegallery.com/

**Comment by rmalina** [comment]
Yes

**Comment by porteriffic** [comment]
Correction made.
