### ISSUE TITLE
urgent podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#394]
Patrícia Correia
Attachments2:32 PM (2 hours ago)

to roger, Yvan, Lina, Sam, Ana 
Hi Roger,
corey
can we try and publish this podcast before friday
yvan is goingto help me get the forms done

its in new leonardos

roger
@yvantina 

We have been following the news from Paris with extreme sadness. We hope all your friends and family living in France are safe.
From our side all is good.

I want to let you know that we have some podcasts ready (except for the intro music). I wonder if it would be possible to post one of them (at least) before Friday - the book launch? We did this one in particular in Portuguese, with the curator of Roots of Curiosity and it would be great to spread the word!

I'm sending the file, but let us know if you prefer to do it only when we launch the website...

Best regards

**Comment by yvantina** [comment]
@rmalina @coreysmart92 @porteriffic Email sent. Will fill out the description form.

**Comment by porteriffic** [comment]
@yvantina So the podcast is already edited and just needs a bumper, correct?

**Comment by yvantina** [comment]
@porteriffic @coreysmart92 YES: I tried to fill out the podcast form without success: Corey is supposed to have it done. Remember we need to publish it before Cop21 starts.

**Comment by porteriffic** [comment]
@yvantina Okay, go ahead and fill out a form on Wufoo since this is urgent but please let Dylan know what went wrong with the forms. The podcast is in the New Leonardos folder on Dropbox, correct?

**Comment by yvantina** [comment]
@porteriffic @coreysmart92 Corey told me on Tuesday he would take care of this. Corey did you fill out the form or should I go ahead with Wufoo ? Yes the podcast is in the right location

**Comment by porteriffic** [comment]
@yvantina Oh, I see. I just checked both Wufoo and the new forms. No forms have been submitted. I'll contact Corey to get this resolved. It's already Thursday and needs to be fixed by the end of today.

**Comment by yvantina** [comment]
@coreysmart92 @porteriffic Yes it needs to be fixed today !! Corey and I have all information we need: I'm simply going through troubles while using the new forms, that's why Corey said he would take care of this, but I can do Wufoo if needed  !!

**Comment by porteriffic** [comment]
@yvantina I'll help you coordinate with Corey to get the podcast up but you might want to just go ahead and fill out the forms. It'll be one less thing we have to worry about.

**Comment by porteriffic** [comment]
@yvantina The podcast is up on Creative Disturbance with the bumper. If it's all correct, please go ahead and close this issue.
