### ISSUE TITLE
correcton to podcast correa

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#398]
corey

can you correct this error ?

roger

Patricia Correia
2:55 AM (10 hours ago)

to roger, Yvan, Sam, Josephine, Corey 
Hi Roger, 

Our book is lovely! (unfortunately only in Portuguese for now, but we are keeping a copy for you!) 
Yesterday we celebrated our first podcast too! Thanks so much Yvan and Corey!

I have only a small note on the tags.. something went wrong with the words (probably because of our Portuguese characters).. 
It was supposed to be:  Art Science, Curiosity Roots Book
(instead of art, science, curiosity, and, book, reasons)

But I am also thinking if it makes more sense to have the tags in english? if you think it's better, it can be
Arts, Science, Curiosity, Book

Have a great weekend!

**Comment by coreysmart92** [comment]
Closing: I have corrected this. [11/30/15]
