### ISSUE TITLE
urgent re art and climate change podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#399]
corey
PLEASE reply to this email and copy me
roger

Hello Roger and Corey,

I just got s link to an exhibition I am in as part of COP21.
Here it is:
http://www.artcop21.com/events/tipping-points-artists-address-the-climate-crises/

This made me wonder if the podcast that Miriam Seidel and I did has been posted yet??

Thank you. 

Best,
@porteriffic 

Diane Burko
310 South Juniper Street
Philadelphia, PA 1017
cell:215-880-8466home: 215-546-8181 
www.dianeburko.com
www.dianeburkophotography.com

**Comment by coreysmart92** [comment]
Closing: I have responded and everything is ready to go. The podcast will be published 12/1/15 at 12:30 AM.
