### ISSUE TITLE
Submit Bio - Hal

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#4]
We will need short descriptions of your overall background and current majors to put on the team page for CD. 

Basic example: [ Your name ] is currently pursuing her ____ degree at UTD and is focusing on ____. She is interested in ___ with ___ and the effects it has on ___. Current qualifications? Future goals?

**Comment by halclark** [comment]
(Guess I'll just post here?)

Hal Clark is currently an undergraduate student at UTD studying for a degree in Sound Design with a focus on digital composition for film and video games. He has over 10 years of experience in traditional music platforms and 6 years experience producing on digital platforms. He is most interested in the production of music and sound effects for these media platforms and hopes to one day be known for producing sounds that drive plot lines.

**Comment by cassininazir** [comment]
@vivraman Please edit and add to Meet the Team page.
