### ISSUE TITLE
style sheet for bumpers and stingers

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#40]
develop a written style sheet for bumpers and stingers- and includ discussion of how to avoid copyright problems

roger

tim perkis sends us this information:
as far as music rights goes: this is a thorny area, and the not-really-legal practices of many entities now  with 'automated takedowns' is a real problem. The fact is that aside from the theme music(which I created and own), every music clip of my show is a short excerpt of a longer work, which is there as an illustration of our discussion, and is there under "fair use".  In every case the music is created, at least in part, by my guest, but that doesn't necessarily means my guest owns the rights, or is authorized to authorize me to use the music; I can't seek the rights from the owners to use every one of these clips; the only way is to be certain that the way I use it falls under "fair use". 

Automated take-down systems often don't recognize "fair use" situations ... so there are potentially situations where automated systems like those used by soundcloud would demand or just perform a "take-down" of one of my podcasts. I'm not sure what can be done about this, except to try to appeal the case. It will help that the music I'm interested in is usually obscure, and not likely to be in the database of protected songs, although these databases are always getting more extensive, and the recognition algorithms sometimes just make mistakes, as well. 

This is a real societal problem I think – the 'de facto' abolition of the fair use exception by automated systems. Its something to keep an eye on, and something which makes trying to do a podcast on the subject of music a little problematic.

**Comment by cassininazir** [comment]
@amb141330 this should tie in to item #51. Suggest the specs.

**Comment by amb141330** [comment]
Moving this issue to another individual since I am no longer involved with creating stingers.
