### ISSUE TITLE
podcast screwed up - nov 26

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#400]
corey

this podcast is screwed up

http://creativedisturbance.org/podcast/kim-fraczek-artist-and-activist-eng/

it cuts off in mid sentence at 1 m 21 second

i assume you didnt loan up the whole podcast

PLEASE fix this urgently its embarassing

roger
@coreysmart92

**Comment by amb141330** [comment]
It worked fine when I uploadted the file. I'll fix it right now.

**Comment by rmalina** [comment]
thanks !!
happy thanksgiving !

roger

On Thu, Nov 26, 2015 at 10:01 AM, amb141330 notifications@github.com
wrote:

> It worked fine when I uploadted the file. I'll fix it right now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/400#issuecomment-159970224
> .

## 

Roger F Malina
is in california
COME TO OUR DALLAS CHRISTMAS PARTY DEC 6 SUNDAY 4-10pm
If you want to come or know someone who would-contact me
my cell is still 510-853-2007

**Comment by amb141330** [comment]
Should be fixed now. Just skipped to that time in the podcast and had no issue. Happy Thanksgiving!
