### ISSUE TITLE
Helen and Newton Podcast Forms

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#401]
The only podcast I edited that is still waiting on podcast forms from you is the Helen and Newton podcast. I can shift the podcast scheduling depending on how much time you need to complete the forms. Just let me know.
Close: When the podcast has been published.

**Comment by rmalina** [comment]
corey
i have done the forms for the harrisons podcast
please go ahead and publish this week
thanks

roger

**Comment by porteriffic** [comment]
Podcast has been published.
