### ISSUE TITLE
Add feedback@creativedisturbance.org email, social media and Stitcher links to website footer and important pages

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#403]
- I couldn't find a way to contact CD on the website - eventually found an email link on the bottom of the dashboard page, but this needs to be made more visible
- I know there are social media icons at the header of the website, but these need to be made more visible as well

**Comment by cassininazir** [comment]
Let's replace the footer information with what you describe here.

**Comment by linamoon** [comment]
Website footer has been updated with the changes--http://creativedisturbance.org/
