### ISSUE TITLE
Implement logo reciprocity for partner organizations - ideally by end of week

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#407]
For CD partner organizations, we should make sure that they have a link to CD on their site and that we have a logo link to them on our site as well. See example with Audiolats at:

http://www.olats.org/audiolats/audiolats.php

Partner organizations include:
- Human Impacts Institute
- RAMI
- Noisy People
- Meta-Life 

Touch base with @yvantina and @linamoon on this if any questions.

**Comment by dylanorgeron** [comment]
waiting on metalife and noisy people confirmation

**Comment by yvantina** [comment]
thanks ! as for Meta-Life (i.e. Leonardo/OLATS), we'd simply need to put CD's logo-link on the home page of the website  http://synthbioart.texashats.org/

**Comment by linamoon** [comment]
Website has logos implemented (list and info document under 2.3 Community Building): 
- https://docs.google.com/document/d/1VA5jC-Ina-iDM1yrGtna651Ofhwb3ofzKzaSfaW_sDI/edit

I guess next step is to send emails to partners that don't have the CD logo on their website? @yvantina

**Comment by yvantina** [comment]
Yes Thank you. We should do that next week

**Comment by linamoon** [comment]
Link to CD has been made on Meta-Life as well!

**Comment by dylanorgeron** [comment]
What's the status on this issue? I've added the links lina specified to our website, are we waiting on emails still or can I close this issue?
