### ISSUE TITLE
Email Podcast Information to Sound Team

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#408]
Email any information needed for the following podcasts to someone on the sound team:

Information and Power in the Age of Biotechnology
Prosthetics Organs Wearable Art Podcast
On Aliveness with Stelarc
Microbiome Art
De l’Amitie avec Dominique Lestel 1 (Recording Quality)
De l’Amitie avec Dominique Lestel 2 (Recording Quality)
Future of Architecture and Synthetic Biology

**Comment by yvantina** [comment]
DONE  !! They should have enough info to publish now
