### ISSUE TITLE
Create Artwork for Roots of Curiosity Channel

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#409]
See emails between Patricia Correia and myself. You should see an attached image they'd like to use but are open to whatever suites us as well. I'd like to have the channel live before the end of the year.

**Comment by linamoon** [comment]
Logo approved and ready to go - can be found in the Album Artwork folder.
- https://drive.google.com/open?id=0BwvQhnxKj6jFdGN2MVpfYUx5ZHM
