### ISSUE TITLE
Please change podcast voices !!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#410]
@halclark @amb141330 Can you please update this podcast info accordingly ? See below. thanks !

For Clarification. The podcast listing Ryan is actually 3 people:

"with Ryan McMahan, Paul Fishwick, Kang Zhang
EN
December 6, 2014"

Your web site shows only Ryan. This is not a big deal, but I wanted to highlight it
in case this same issue is pervasive across podcasts.
-p

Paul Fishwick, PhD
Chair, ACM SIGSIM
Distinguished University Chair of Arts, Technology, and Emerging Communication
Professor of Computer Science
Director, Creative Automata Laboratory
The University of Texas at Dallas
Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Home: utdallas.edu/atec/fishwick

Blog 1: creative-automata.com 

Blog 2: modelingforeveryone.com 

LinkedIn: metaphorz
Twitter: @representationz

> On Dec 21, 2015, at 1:00 AM, Roger Malina rmalina@alum.mit.edu wrote:
> 
> Roger Malina is thinking aloud, ''
> 
> Thinking Aloud: top 10 creative disturbers of 2015
> http://malina.diatrope.com/2015/12/20/thinking-aloud-top-10-creative-disturbers-of-2015/ 
> 
> Colleagues
> We are delighed with the success of Creative Disturbance and to announce the top
> ten dowloaded podcasts of 2015, http://creativedisturbance.org/ 
> 
> If you havent listed to them- you will be fascinated - and if you want to
> publish a podcast on creative disturbance, contact me
> roger malina
> 
> Arts Activities of Successful Scientists:  Root Bernstein
>   http://creativedisturbance.org/podcast/successful-scientists/ 
> 
> Cancer: Finding Beauty In the Beast [...]
> 
> You may view the latest post at
> 
> You received this e-mail because you asked to be notified when new updates are
> posted.
> Best regards,
> Roger F. Malina
> rmalina@alum.mit.edu

**Comment by rmalina** [comment]
yvan yvan
this was my mistake on my blog
the podcast is fine
roger

On Mon, Dec 21, 2015 at 5:23 PM, yvantina notifications@github.com wrote:

> @halclark https://github.com/halclark @amb141330
> https://github.com/amb141330 Can you please update this podcast info
> accordingly ? See below. thanks !
> 
> For Clarification. The podcast listing Ryan is actually 3 people:
> 
> "with Ryan McMahan, Paul Fishwick, Kang Zhang
> EN
> December 6, 2014"
> 
> Your web site shows only Ryan. This is not a big deal, but I wanted to
> highlight it
> in case this same issue is pervasive across podcasts.
> -p
> 
> Paul Fishwick, PhD
> Chair, ACM SIGSIM
> Distinguished University Chair of Arts, Technology, and Emerging
> Communication
> Professor of Computer Science
> Director, Creative Automata Laboratory
> The University of Texas at Dallas
> Arts & Technology
> 800 West Campbell Road, AT10
> Richardson, TX 75080-3021
> Home: utdallas.edu/atec/fishwick
> 
> Blog 1: creative-automata.com
> 
> Blog 2: modelingforeveryone.com
> 
> LinkedIn: metaphorz
> Twitter: @representationz
> 
> On Dec 21, 2015, at 1:00 AM, Roger Malina rmalina@alum.mit.edu wrote:
> 
> Roger Malina is thinking aloud, ''
> 
> Thinking Aloud: top 10 creative disturbers of 2015
> 
> http://malina.diatrope.com/2015/12/20/thinking-aloud-top-10-creative-disturbers-of-2015/
> 
> Colleagues
> We are delighed with the success of Creative Disturbance and to announce
> the top
> ten dowloaded podcasts of 2015, http://creativedisturbance.org/
> 
> If you havent listed to them- you will be fascinated - and if you want to
> publish a podcast on creative disturbance, contact me
> roger malina
> 
> Arts Activities of Successful Scientists: Root Bernstein
> http://creativedisturbance.org/podcast/successful-scientists/
> 
> Cancer: Finding Beauty In the Beast [...]
> 
> You may view the latest post at
> 
> You received this e-mail because you asked to be notified when new updates
> are
> posted.
> Best regards,
> Roger F. Malina
> rmalina@alum.mit.edu
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/410.

## 

Roger F Malina
is in New York
my cell is still 510-853-2007

**Comment by yvantina** [comment]
Okay okay, My BAD ! I didn't double check as Paul cc-me in your email... I thought our team was involved..
yvan
