### ISSUE TITLE
errors on web site re zhang mcmahan fishwick podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#411]
paul fishwick reports the following errors it would be nice to fix
@halclark @amb141330 

can you someone put this on their to do list

roger

Roger
 Thanks — two minor additions (but no rush):

(1) Kang Zhang’s name is misspelled. “Kang” rather than “Kan” in the main web page.

(2) There should be bio pages to Kang and I. Currently, when clicked, only Ryan’s photo and bio
show. For example (using whatever URL mapping you have for individuals):

http://creativedisturbance.org/people/ryan-mcmahan
http://creativedisturbance.org/people/paul-fishwick
http://creativedisturbance.org/people/kang-zhang

**Comment by amb141330** [comment]
This was fixed already, but I'm not sure when.
