### ISSUE TITLE
follow up with altugy akin for turkish creative fellow

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#412]
altug

Altug Akin altugakin@gmail.com
delighed to hear f
Vrom you !! and best for 2016

the project i mentioned it is Creative Disturbance

http://creativedisturbance.org/

we boadcast podcasts by professionals for professionals
in the broad fields of connecting the arts and emerging technologies
and arts and science

we raised money by crowdfunding to give 1000 dollar speaking 'fellowships)
to students internationally who would agree to publish a few podcasts ( in any
language) with advanced students or professionals in their own community

http://malina.diatrope.com/2015/12/17/disturbing-fellows-and-fellas-in-portugal-on-creative-disturbance/

i would be delighted if you could find a student ( MA or PhD) who
might be interested
in doing this under your supervision in turkey !

we are moving the platform to MIT in the spring -so its great visibility

i am copying this to lina moon who is coordinating who student fellow program

roger

lina i will work with you on this

**Comment by linamoon** [comment]
For reference (below):

Hi Altug,

Happy new year! It's good to (e-)meet you. As Roger mentioned, my name is Lina, and I am coordinating the student grants for Creative Disturbance.

I just wanted to follow up with you and say that we'd be delighted to have a graduate student that would be interested in gaining exposure for their research and producing podcasts on Creative Disturbance, at your recommendation. 

Please feel free to let us know if there's anyone that comes to mind, and we'd be glad to connect.

Best,
Lina Moon
