### ISSUE TITLE
update of job descriptions

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#414]
corey ashton hal meet as a group with cassini
- review job description and goals; do a self assessment of what was done/not done
- update job descriptions, goals for next semester
- organise amont the three of yourselves so that 5 podcasts a week go up
  rain or shine

roger
@cassininazir @halclark @coreysmart92 @amb141330

**Comment by cassininazir** [comment]
Closing this item. Reviewed with all team members.
