### ISSUE TITLE
Update, Print and Post Lab Hours for Spring 2016

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#416]
@amb141330 please review the lab hours document in Google Drive and post in ArtSciLab

**Comment by amb141330** [comment]
Lab hours are updated
https://docs.google.com/document/d/1ndXzEpIHEwShp79lg5f6i8k9U5Bo6kBsgrJOtmhsuOA/edit
Can you print this in your office?

**Comment by cassininazir** [comment]
Printed.

You can access and printer to the printer in the main ATC office by add the printer by IP address:

10.204.40.31

Cassini Nazir

Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
Director of Design and Research, ArtSciLab
The University of Texas at Dallas

**Comment by amb141330** [comment]
Lab hours posted in the lab.
