### ISSUE TITLE
Register CD in Podcast Awards

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#418]
@amb141330 can you register the appropriate channels in the Podcast Awards at
http://www.podcastawards.com/index.php?option=registerpodcast

**Comment by amb141330** [comment]
I have registered several channels including:

Virtual Africa
New Leonardos
Meta-Life
Pioneers and Pathbreakers
The Bold Roast
Voices from the Crowd

I have contacted Tara DePorte of Human Impacts Institute and Tim Perkis of Noisy People to request their permission to submit their podcasts.

**Comment by amb141330** [comment]
I have submitted all of the possible channels for Podcast Awards. I will keep track of feedback on our feedback email.
