### ISSUE TITLE
Make sure sponsors have logo and link to CD on their sites.

### ISSUE THREAD

**Issue by dylanorgeron** [creativedisturbance/podcasts#419]

**Comment by rmalina** [comment]
cassini
i think we need to convert this to a task included in the arteca action
item plan

we should probably contact everyone with their logo on our creative
disturbance site
and confirm the agreement for 2016 including their ok on the move to mit url

roger

On Tue, Jan 12, 2016 at 2:09 PM, Dylan Orgeron notifications@github.com
wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/419.

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by cassininazir** [comment]
@linamoon can you propose a design for the sponsors to implement. Would like to see the first-round design.
