### ISSUE TITLE
please get the portuguese roots of curiosity channel up as soon as possible

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#420]
ashton

can you take this on ? and get this new channel up as soon as possible-
if yiou need help from lina or dylan ask cassini

roger

Patrícia Correia
11:56 AM (2 hours ago)

to Josephine, Corey, Sam, Ana, roger, Lina 
Hi Josephine and colleagues,

Happy 2016! I wish you all a great podcast's year! :)

We are all set and ready to start posting our podcasts in the new channel! I would like to know if there are any news on the logo? I noticed that the "roots of curiosity" isn't yet in the list of existing channels in the submission form, should I just choose "no" for existing channel? I also have a question regarding the voices, do we always have to repeat the info for our own voices? We also plan to add the podcast with Madalena Wallenstein previously published on new Leonardos, so maybe there's no need to repeat the info.
Thanks so much!

Best,
@cassininazir

**Comment by linamoon** [comment]
I saw this, working on the logo - will email them by tonight @rmalina @amb141330

**Comment by amb141330** [comment]
duplicate issue
