### ISSUE TITLE
Podcast schedule

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#421]
@coreysmart92 @amb141330 @halclark 
Please let me know when the two new audiolats podcasts will be up. I can't find them here
https://docs.google.com/spreadsheets/d/1JUtI3ecGsmmmIR9dKtSGxkuNFcKvmzhXc2ND69MSvd4/edit#gid=1552320650 
Also, let me know if there's anything you need from me

**Comment by yvantina** [comment]
@coreysmart92 @halclark Can you please duplicate these two Audiolats podcasts under the Meta-Life channel as well ? Thanks 
Skotopoiesis with Spela Petric and Jurij Krpan

**Comment by yvantina** [comment]
@coreysmart92 Please publish the second Skotopoiesis podcast this week !!!! Transmediale is coming next week.. also please duplicate these two Audiolats podcasts into the Meta-Life channel as well !!! Thank you

**Comment by cassininazir** [comment]
@yvantina this wasn't assigned to anyone. Assigning to @coreysmart92 

@amb141330 can you make sure this also goes on the Podcast Production Sheet?

**Comment by coreysmart92** [comment]
Closing: the podcast tracking sheet has been completely updated. (2/1/16)
