### ISSUE TITLE
Update Job Description with New Responsibilities

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#422]
Update doc in google Drive.

**Comment by amb141330** [comment]
Done most of this, need to review it with you Cassini

**Comment by cassininazir** [comment]
Can you add a link to the updated version to this GitHub item?

Cassini Nazir

Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
Director of Design and Research, ArtSciLab
The University of Texas at Dallas

**Comment by amb141330** [comment]
https://docs.google.com/document/d/1HHe0dq7U69f4perh28GOa3IiUA6pPSAuBuPpZsybmyY/edit

**Comment by amb141330** [comment]
Finished. Document listed above in the link.
