### ISSUE TITLE
lilla podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#424]
please contact this person and tell them when their podcast will be published
this is embarassing
roger

Lilla LoCurto via alum.mit.edu 
3:15 PM (23 hours ago)

to Dylan, roger, Creative, Corey 
Hi Dylan,

We haven’t heard anything since you said you received everything. Can you let us know when we’ll be published? Many thanks. Lilla

**Comment by amb141330** [comment]
Corey can you let me know about this?

**Comment by coreysmart92** [comment]
This has been scheduled to publish. Roger has been updated, but there has been a technical complication with communicating to the producer. I have attempted to contacter her again.
Close: when podcast is published.
(1/25/16)

**Comment by coreysmart92** [comment]
Closing: This podcast has been published and the producer informed.
(2/1/16)
