### ISSUE TITLE
opening roots of curiosity channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#425]
ashton
another example of our brand is suffering from our lack of
reacting to our producers !

can you contact the portuguese team immediately and introduce
yourself and then figure out how to open their channel as soon as 
possihle

as you will see from the email its really embarassing but we have been promising
this for months

roger

Dear Josephine, 

Sorry for insisting, but do you have any news about the logo? 

We are ready to launch our new channel and a series of podcasts, and are just waiting news on the logo and having the channel listed in the form.

Thank you very much! 
Best,

On Tue, Jan 12, 2016 at 5:56 PM, Patrícia Correia patricia.correia@neuro.fchampalimaud.org wrote:
Hi Josephine and colleagues,

Happy 2016! I wish you all a great podcast's year! :)

We are all set and ready to start posting our podcasts in the new channel! I would like to know if there are any news on the logo? I noticed that the "roots of curiosity" isn't yet in the list of existing channels in the submission form, should I just choose "no" for existing channel? I also have a question regarding the voices, do we always have to repeat the info for our own voices? We also plan to add the podcast with Madalena Wallenstein previously published on new Leonardos, so maybe there's no need to repeat the info.
Thanks so much!

Best,

On Thu, Dec 17, 2015 at 12:22 AM, Josephine Porter porteriffic@gmail.com wrote:
Hi Patricia,

That's great! I'll have Lina handle the artwork/logo. She's made some great logos that stay pretty true to the original input/design.

And to answer your question: Yes, you'll want to say the podcast is for an existing channel. We'll get all the new channels listed soon. Our forms are still fairly new (we launched them in October) so there are still a few things here and there that need to be updated. Once you have your podcast ready, you can attach it to the podcast form. 

Hopefully we can get the channel up before the end of the year! 

Best,
Josephine

On Wed, Dec 16, 2015 at 6:08 PM, Patrícia Correia patricia.correia@neuro.fchampalimaud.org wrote:
Hi Josephine,

Thanks for your prompt reply.
I didn't know you have a designer (that's great!), so we talked with a friend and he managed to this image in attachment. (In case you're wondering, it's an image of a brain superimposed with an image of a galaxy and the art&science symbiosis logo we used for the Roots conference). We are obviously open and more than happy to have Lina doing another version. Whatever works better for you!

As for the podcast form, I have only one question: in the "Is this podcast for an exisiting channel?" I should say yes for now and then in the future the Roots channel will be available in the list, correct?
We just have to finish composing the first seconds intro music to add in the podcasts and I guess that's the final editing from our side.

Almost there! :)

Best,

On Wed, Dec 16, 2015 at 11:51 PM, Josephine Porter porteriffic@gmail.com wrote:
Hi Patricia,

Wonderful! I'm happy to hear that the process was painless. 

Obviously the channel is approved so that's out of the way. The next step on our end is to create some kind of channel artwork or logo. I've copied our designer, Lina, to this email so if you have suggestions please let her know. Logos shouldn't take more than a few days but she can give you a more accurate time on how long it will take.

Are your podcasts already edited? If they are, all we'll need is the information for the first podcast to go up with your channel. To do this you'll need to fill out the New Podcast Form. We're currently experiencing some glitches with that specific form on some users, not all. So if you experience a glitch, please let me know and we'll figure something out.

So once we have the information for the podcast, as well as the podcast itself, and the channel logo, we can launch the Roots of Curiosity Channel.

Let me know if you have any questions. I know all this information can be a little overwhelming. I'll be more than happy to help!

Best,
Josephine

On Wed, Dec 16, 2015 at 5:17 PM, Patrícia Correia patricia.correia@neuro.fchampalimaud.org wrote:
Hi Corey, Josephine and Roger,

I hope all is good with you.

I have completed the two first forms - to create the channel and to be a producer. I guess now I have to wait until the channel becomes available, so that I can submit podcasts directly to the Roots of Curiosity channel, correct? Any idea of the timing for this? All the process was very easy, thanks for having it so organized.

We have some podcasts ready in the context of our art&science project, and have some more arranged for January with other art&science people. Also in January, we will release our website, inserted in the Science Communication platform AR and so we'll spread the word to some potential creatively disturbed minds :)

I wish you all great holidays (if that's the case)!

All the best,

On Tue, Nov 17, 2015 at 3:28 AM, Yvan Tina yvantina@gmail.com wrote:
Hi everyone !

Patricia, Sam, Ana

Can you please send me a short description of the podcast ? Maybe 2 or 3 sentences long..
I will fill out the podcast description for you as you already register as CD voices in the platform*
However, as new producers of a channel, you will ultimately have to fill out and send back the forms accessible through the links copied below (this may require each of you to create a user ID and password on the website - see the "join" section)

http://creativedisturbance.org/forms/channel/ (to create your channel)

http://creativedisturbance.org/forms/producer/ (to be a channel producer)

http://creativedisturbance.org/forms/podcast/ (for each podcast you will send/publish)

http://creativedisturbance.org/forms/guest/ (to be filled out by any/each of your guest)
[*For emergency purposes, you can have the curator of your exhibition using this link instead
https://creativedisturbance.wufoo.com/forms/creative-disturbance-guest-release-form/]

May you have any question regarding the procedure, feel free to contact Josephine Porter or Corey Smart copied in this email

But again, as for now, we (i) just need a description (in english or portuguese, if applicable) for this first podcast which will be published on the New Leonardos disturbance pending the creation of your own channel 

"Roots of Curiosity
Exploring arts, science and the brain" 

You will have plenty of time to get familiar with the process later but we're trying to have your podcast published as soon as possible..

All the best

yvan

2015-11-16 17:16 GMT-06:00 roger malina rmalina@alum.mit.edu:
yvan
can you try and help get this posted on creative
disturbance quickly ?

roger

On Mon, Nov 16, 2015 at 2:32 PM, Patrícia Correia
patricia.correia@neuro.fchampalimaud.org wrote:

> Hi Roger,
> 
> We have been following the news from Paris with extreme sadness. We hope all
> your friends and family living in France are safe.
> From our side all is good.
> 
> I want to let you know that we have some podcasts ready (except for the
> intro music). I wonder if it would be possible to post one of them (at
> least) before Friday - the book launch? We did this one in particular in
> Portuguese, with the curator of Roots of Curiosity and it would be great to
> spread the word!
> 
> I'm sending the file, but let us know if you prefer to do it only when we
> launch the website...
> 
> Best regards
> 
> On Wed, Nov 11, 2015 at 1:19 PM, Patrícia Correia
> patricia.correia@neuro.fchampalimaud.org wrote:
> 
> > Hi Roger, Yvan and Lina,
> > 
> > More than busy with the book launch, we have been having fun doing some
> > podcasts!
> > Here are some questions from our side:
> > 
> > 1) Who is the contact person to send the audio files? In some of the
> > podcasts, some editing is needed, like cutting off some mistakes, so we will
> > include also the times to edit. We also want to make sure that the guest
> > releasing forms are all ok.
> > 
> > 2) Any specifics for the image logo? We see from the other examples that
> > it's squared, but let us know if you have suggested dimensions/resolution.
> > We have an idea for ours and are just working on it with a designer friend.
> > 
> > 3) The music for the begging/end - we are working on a composition of
> > music + sounds of neurons from the brain, but we don't have it fully ready
> > yet. Can we send you recorded podcasts without the song and then we
> > integrate, or do you prefer to have the final version of the podcasts final
> > already?
> > 
> > 4) Website - we hope to have it ready at some point in December, but I
> > guess before that the podcasts can be just shared in the Creative
> > Disturbance website, right?
> > 
> > Our channel should be called
> > Roots of Curiosity
> > Exploring arts, science and the brain
> > 
> > As for your questions, please see the answers below.
> > 
> > Thanks Roger!!
> > 
> > On Tue, Nov 10, 2015 at 9:32 PM, roger malina rmalina@alum.mit.edu
> > wrote:
> > 
> > > patricia sam ana rita
> > > 
> > > we hope all is well with you ! we are keen to get going on next steps
> > > for the creative disturbance podcasts !!
> > > 
> > > we are sure you are busy with your november book release ! if you
> > > have any podcasts for this we are happy to publish them
> > > 
> > > a) can you each send me your official legal names, and home addreses
> > > i need this to start setting up sending you each the $1000 for the
> > > creative
> > > disturbance
> > 
> > Ana Rita Secca da Fonseca
> > Rua dos Cordoeiros a Pedrouços, nº19, 3ºandar
> > 1400-071 Lisboa
> > Portugal
> > 
> > Patrícia Marçal Alves Correia
> > Avenida Infante Santo 45 9o esquerdo
> > 1350-177 Lisboa
> > Portugal
> > 
> > Samuel Viana Meyler
> > Rua Cmte Assis Camilo, No 6 R/C Dir,
> > Ajuda 1300-136 Lisboa
> > Portugal
> > 
> > > b) we would like to make a short announcement of the grants
> > > we are not sure what to call them " but we can call them Creative
> > > Disturbance Fellowships ?
> > > so it looks good on your cv ?
> > > 
> > > Lovely :)
> > > 
> > > lina moon here will work with you to put together a short news
> > > announcement ?
> > 
> > Sure! Is there a draft that we can edit or comment?
> > 
> > > c) then we are happy to work with you in any way to make sense so that
> > > we can publish
> > > podcasts that you organise over the coming year
> > 
> > Sounds good.
> > 
> > > roger
> > > 
> > > On Tue, Oct 6, 2015 at 2:26 AM, Patrícia Correia
> > > patricia.correia@neuro.fchampalimaud.org wrote:
> > > 
> > > > Hi Roger,
> > > > 
> > > > Great news there, congrats!
> > > > 
> > > > Here, elections were depressing... let's not even mention it!
> > > > 
> > > > We are with energy to get more disturbed! Rita and Sam did some test
> > > > version
> > > > of podcasts to check how it goes.
> > > > 
> > > > I'm a bit more busy these days, as I will deliver my PhD thesis today
> > > > and
> > > > get married this weekend, so will be off during October ;)
> > > > 
> > > > But we are all set for the book release at the end of November, and to
> > > > do
> > > > podcasts with the team. Then December max we can release our set of
> > > > podcasts! Sounds good?
> > > > 
> > > > On Mon, Oct 5, 2015 at 10:01 PM, roger malina rmalina@alum.mit.edu
> > > > wrote:
> > > > 
> > > > > ana rita sam patricia
> > > > > 
> > > > > how is LIFE after the elections !!
> > > > > 
> > > > > meanwile we would like to send you the small student
> > > > > grants as we discussed and see if we can work with you
> > > > > to get podcasts up on creative disturbance if you are still
> > > > > interested
> > > > > 
> > > > > we are moving  the platform to mit press is january
> > > > > 
> > > > > are you still releasing your book in november !!
> > > > > 
> > > > > what else is new ! we got the funding for the next
> > > > > stage of the fMRI network data project and are porting
> > > > > our system into unity and the oculus !
> > > > > 
> > > > > look forward to heating your news and see if
> > > > > we can make trouble together !
> > > > > 
> > > > > roger
> > > > > 
> > > > > On Sun, Mar 8, 2015 at 11:32 AM, Sam Meyler sam_viana@yahoo.com
> > > > > wrote:
> > > > > 
> > > > > > ok great
> > > > > > don't forget i sent the edits for the portuguese part to Josephine..
> > > > > > Sam
> > > > > > 
> > > > > > On Sunday, March 8, 2015 4:05 PM, roger malina
> > > > > > rmalina@alum.mit.edu
> > > > > > wrote:
> > > > > > 
> > > > > > patricia ana rita sam
> > > > > > 
> > > > > > attached is the podcast edited by corey smart
> > > > > > 
> > > > > > corey= go ahead and put it up- given i dont understand
> > > > > > the portuguese i will let our colleagues listen to it also
> > > > > > and make sure the editing is ok- you can always replace it
> > > > > > if they feel this version has a problem
> > > > > > 
> > > > > > the sound levels, balance and background noise are fine
> > > > > > 
> > > > > > lets get it up for march 8 !
> > > > > > 
> > > > > > also since its in portuguese make sure that
> > > > > > you indicate its in portuguese for people who
> > > > > > visit the web site
> > > > > > 
> > > > > > roger
> > > > > > 
> > > > > > On Sun, Mar 8, 2015 at 1:11 AM, Corey Smart
> > > > > > corey.smart92@gmail.com
> > > > > > wrote:
> > > > > > 
> > > > > > > Thank you very much I look forward to it.  Attached is the Roots of
> > > > > > > Curiosity podcast, if you could give it a content check I will
> > > > > > > upload
> > > > > > > it
> > > > > > > as
> > > > > > > soon as possible on Sunday 3/8/15.  Also for spring break Ashton,
> > > > > > > Hal,
> > > > > > > and
> > > > > > > myself have all expressed interest in working.  I plan to let all
> > > > > > > of us
> > > > > > > work
> > > > > > > given that we have enough podcasts for editing.  Thank you again.
> > > > > > > Corey
> > > > > > > 
> > > > > > > On Sat, Mar 7, 2015 at 9:09 AM, roger malina rmalina@alum.mit.edu
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > Corey ..just listened to your podcast
> > > > > > > > Worked out great
> > > > > > > > Good dialogic style with back
> > > > > > > > And forth
> > > > > > > > 
> > > > > > > > Hope you will do more
> > > > > > > > 
> > > > > > > > roger malina
> > > > > > ## 
> > > > > > 
> > > > > > Roger F Malina
> > > > > > is in texas
> > > > > > 1-510-853-2007
> > > > > ## 
> > > > > 
> > > > > Roger F Malina
> > > > > is in Dallas
> > > > > 1-510-853-2007
> > > > ## 
> > > > 
> > > > Patrícia A. Correia
> > > > Systems Neuroscience Laboratory
> > > > Champalimaud Centre for the Unknown
> > > > Av. Brasília, Doca de Pedrouços
> > > > 1400-038 Lisboa, Portugal
> > > > (+351) 210480116
> > > > www.neuro.fchampalimaud.org
> > > ## 
> > > 
> > > Roger F Malina
> > > is in Dallas
> > ## 
> > 
> > Patrícia A. Correia
> > Systems Neuroscience Laboratory
> > Champalimaud Centre for the Unknown
> > Av. Brasília, Doca de Pedrouços
> > 1400-038 Lisboa, Portugal
> > (+351) 210480116
> > www.neuro.fchampalimaud.org
> ## 
> 
> Patrícia A. Correia
> Systems Neuroscience Laboratory
> Champalimaud Centre for the Unknown
> Av. Brasília, Doca de Pedrouços
> 1400-038 Lisboa, Portugal
> (+351) 210480116
> www.neuro.fchampalimaud.org

**Comment by linamoon** [comment]
@amb141330 I've replied to the email and sent them the logo, but might be good for you to follow up with them.

**Comment by amb141330** [comment]
Just drafted an apology email + introduction of myself to Cassini for review to go to Patricia.

**Comment by amb141330** [comment]
I sent an email to Patricia last week, still waiting on a response from her. Other than that I believe we're ready to go on this channel?

**Comment by cassininazir** [comment]
Thanks. Once scheduled, please send her an email letting her know the day the podcast will be published.

Cassini Nazir

Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
Director of Design and Research, ArtSciLab
The University of Texas at Dallas

**Comment by amb141330** [comment]
Going up on Feb. 5th. Will close when channel is launched.

**Comment by amb141330** [comment]
Channel up and running!
