### ISSUE TITLE
marie pier boucher podcast for yuri's night

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#426]
ashton
who is coordinating the yuris night splash page and podcasts ?

i would like to start working with the person to organise yuri's night

here below are details of one post cast we need to record

roger

Marie-Pier Boucher
9:54 AM (2 minutes ago)

to me 
Dear Roger

Thanks for your message. No worries in regards to MIT. They are offering 2 postdocs and it is unclear who is on the committee since the School of Humanities, Arts and Social Sciences joins several departments. I was just checking in case you knew someone in that School.

Kosmica Montreal would be this coming fall or next winter, depending on our funding possibilities. I am super excited about this. I am especially thrilled to have another opportunity to work with Nahum.

I would love to do a podcast with you! Thanks for the invitation! Would it be possible to record it in March? (after the storm of job applications and articles).

Thanks

Marie-Pier

On Wed, Jan 20, 2016 at 4:05 PM, roger malina leonardo.isast@gmail.com wrote:
Marie pier
I really don’t have these kinds of contacts- the right people
Are the people on the hiring committee
Do you know who they are?

Re kosmica-fantastic-when would it be ?

I am recording podcasts for publication on creative disturbance
For yuris night in april- would you be interested in recording
A podcast with me
roger

**Comment by amb141330** [comment]
Lets get someone assigned to this on Monday during the meeting

**Comment by amb141330** [comment]
Reassigning since Hal is coordinating with Roger on Yuri's night.

**Comment by cassininazir** [comment]
This is up. Closing.

**Comment by cassininazir** [comment]
Oops. This is **not** up. Will create a new issue for all Yuri's Night items.
