### ISSUE TITLE
cd professional development

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#427]
ashton
for our meeting with cassini- do we have on next week
would like to review hte spring goals document
but would also like to flesh out the professional development
one
which includes your all doing public speaking at RAW
but also we want to work with all on you on developing yout resumes
and cv's and provide any help we can on all of your job hunting

lets spend a little time fleshing this out

roger
@cassininazir

**Comment by amb141330** [comment]
Will talk with you during meeting to discuss meeting on Wednesday

**Comment by amb141330** [comment]
Met with you both two Wednesdays in a row. Will schedule next meeting for Feb. 10th

Meeting with Cassini today about my CV. 

Forwarded the registration fee email to both @rmalina and @cassininazir
