### ISSUE TITLE
Andy Gracie for Oceans sci-art podcasts

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#428]
@amb141330 @rmalina 

---------- Forwarded message ----------
From: andy gracie andy@hostprods.net
Date: 2016-01-15 9:02 GMT-06:00
Subject: Re: ocean sci-art
To: roger malina rmalina@alum.mit.edu
Cc: Yvan Tina yvantina@gmail.com

thanks to you too, roger. i was toying with the idea of putting myself forward for a podcast on the space theme. let's see if i can come up with a new and interesting angle…

cheers

andy

---

:: hostprods dot net ::

:: hostdev dot wordpress dot com ::

On 15 Jan 2016, at 15:34, roger malina wrote:

> thanks andy
> yvan can you add this to the compilation
> 
> roger
> 
> andy- leonardo is always available to you for articles
> to document your work !
> 
> yvan can you add andy to the list of possible
> podcasts for this year
> 
> On Fri, Jan 15, 2016 at 6:53 AM, andy gracie andy@hostprods.net wrote:
> 
> > hi roger
> > 
> > hope all is well.
> > 
> > i saw you were asking for examples of art/science projects the focussed on the ocean. did you know about my brief research pilot '200Metros'?
> > 
> > http://hostprods.net/projects/200metros/
> > 
> > maybe it would be of interest to you
> > 
> > best regards
> > 
> > andy
> > ---
> > 
> > :: hostprods dot net ::
> > 
> > :: hostdev dot wordpress dot com ::
> ## 
> 
> Roger F Malina
> is in  Dallas
> 510-853-2007

**Comment by coreysmart92** [comment]
@yvantina could you clarify what action needs to be taken by who for this Github item.

**Comment by rmalina** [comment]
we need to schedule a skype with him to record a podcast before april 13
yuri's night

roger

On Mon, Feb 1, 2016 at 2:03 PM, coreysmart92 notifications@github.com
wrote:

> @yvantina https://github.com/yvantina could you clarify what action
> needs to be taken by who for this Github item.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/428#issuecomment-178163368
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by yvantina** [comment]
we never done this.. closing this issue!
