### ISSUE TITLE
fee fishwick podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#429]
corey

did you load up the forms for the fey broadcast as you said you would yesterday- i didnt get any message? here is a draft description of the podcast. YOU NEED TO GET PAUL FISHWICK TO FINALISE IT-contact him

you have total control over this broadcast-there is no reason you cant finish this up in
the next couple of days and upload it for broadcasting at a later date-like in two or three weeks or whatever since there are other podcasts ahead in the queue

please drive this broadcast to be uploaded as soon as possible- dont publish it before the others in the queue-but this is an example of a podcast where you have total control of what is needed

roger

STEAM:  Bespoke chicken or curated brisket ?
Robert Fee, Paul Fishwick and Roger Malina discuss the current discussion on the need to integrate art and design into science and engineering, STEM to STEAM. In particular the different ways that design is understood , from component design to context design. THey can teach design using different approaches from problem, project, object and topic approaches, but that university curricula are often designed backwards with the integrative approaches only occurring later in the syllabus. The discussion concluded with a nightmare scenario of the museum of the future which anticipates visitor interests and tell them what to experience, and commercial personalization of buyer needs versus customization. Fee contrasted the scenario of going to the restaurant and experiencing the unanticipated offer of a great chef  versus a restaurant algorithm that anticipates what you should eat based on previous behavior 
@amb141330

**Comment by rmalina** [comment]
corey
paul edited the description- i think you have everyting you need to go ahead
and edit, finalise the forms and schedule it for a date in the future

roger

> STEAM:  Bespoke chicken or curated brisket ?
> 
> Robert Fee, Paul Fishwick and Roger Malina discuss the current discussion on the need to integrate art and design into science and engineering, STEM to STEAM. In particular the different ways that design is understood , from component design to context design. They can teach design using different approaches from problem, project, object, and topic approaches, but that university curricula are often designed backwards with the integrative approaches only occurring later in the syllabus. The discussion concluded with a nightmare scenario of the museum of the future which anticipates visitor interests and tell them what to experience, and commercial personalization of buyer needs versus customization. Fee contrasted the scenarios of going to the restaurant and experiencing the unanticipated offer of a great chef, a restaurant algorithm that anticipates what you should eat based on previous behavior, or a made-to-order menu.
> @coreysmart92

**Comment by coreysmart92** [comment]
Closing: Duplicate #441
