### ISSUE TITLE
Podcast with Nora Abushadi

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#430]
@coreysmart92 @amb141330 @halclark Can you please find and publish the podcast with Nora Abushadi for Virtual Africa ? I've submitted a completed form in December, so you should have everything you need.. Hope it's not lost. Thanks !

**Comment by coreysmart92** [comment]
Closing: This podcast as been published "[Being a Young Designer in Cairo [ENG]](http://creativedisturbance.org/podcast/being-a-young-designer-in-cairo-eng/)"
