### ISSUE TITLE
Define Quality Measurements for Podcasts

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#431]
@amb141330, @coreysmart92 and @halclark please meet soon (before end of Jan) to put together a list of measures of quality for podcasts.

**Comment by cassininazir** [comment]
- Measure of quality should also include the quality of contact with the producers.

**Comment by amb141330** [comment]
ashton-
as the team develops criteria for evaluating good podcasts, i suggest you include also the bio and podcast text

here is one that rates LOW for my reading

a) the name of the person in the podcast should be at the START of the text not burried in the text-
you tell me who is being interviewed
b) the name of the producer talking to the voice is not named in the text

anyway-in your criteria -one way is to develop checklists of what you consider 'good" and then score that way
roger

Drawing on the work of Neri Oxman with her use of biomaterials and 3d printing for the design exploration Mushtari, and considering the popular examples of Henri Damon and Oscar Pistorius, Laini Burton investigates the use of prosthetic organs as wearable art in fashion industry and biodesign. From cosmetic surgery and extreme body modification to the design of astrobiological artefacts that could host life, she questions the agentic capacity of synthetic biology in our perception of liveness. The podcast also talks about the ideas of fiction and suspension of disbelief in design from the speculative and the contestable approaches

Posting from other duplicate issue

**Comment by amb141330** [comment]
reassigning to Hal since he is in charge of quality metrics. We can discuss them as a group when they are finished.

**Comment by halclark** [comment]
I have updated 2.2.2.7 with more guidelines on how to spot bad recordings. I would like some help or suggestions on taking these guidelines and turning it into some kind of rating system. Let's talk about this more next Monday 3/28 @cassininazir @rmalina @coreysmart92 @amb141330

**Comment by halclark** [comment]
2.2.2.7 is fully updated with all guidelines I can think of to determine the quality of a podcast. @amb141330 and I are going to work on a number system to go along with this.

**Comment by rmalina** [comment]
hal
does the check list include a task for the sound editor
to give a rating to each podcast-we should do this
then you can do monthly stats and see if we need
to help producers do better quality
roger

Roger F Malina
is in Dallas 1-510-853-2007
To: all family and Leonardo friends- we are having a party to celebrate the
50th
anniversary of the founding of Leonardo on Saturday June 18 in Paris- if
you
are in Paris then and can attend we would be delighted to invite you.
Contact
me.

**Comment by arfaye** [comment]
@cassininazir @ritwikjk @OskarOlssonCD Updated CD 7.0 Metrics with document "Quality Measurements for Podcasts"

Sheet does not yet involve quality of contact with producers

**Comment by arfaye** [comment]
Closing issue; updating the quality measurement sheet will become a new issue when we have more contact with producers.

**Comment by rmalina** [comment]
We are organising a Yuri's night  (see at https://yurisnight.net/ ) a
global space party
in dallas in Saturday April 11 2020 ;4-11pm, at http://mercado369.com/
in Dallas, Texas

Contact me if you would like to help us make trouble or just party

Families with Children welcome at 4pm-7pm

Oh Yes its also my wife Christine and my 70th Birthday party
Reply if you would like an invitation.
ROGER AND CHRISTINE MALINA
