### ISSUE TITLE
make sure CD 2.2.7 is updated

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#436]
ashton
per our discussion your key management tool is making sure
that CD 2.2.7 is regularly updated - all the tabs

make sure this is someones  regular job- just make sure the doc is pulled up every monday
and make sure its updated before the meeting

roger

**Comment by amb141330** [comment]
Corey now knows specifically what he should be updating. Will close once I'm happy with the finished product.

**Comment by amb141330** [comment]
Spreadsheet is more updated than before, I'll leave it to Corey's discretion as to when to close this issue.

**Comment by rmalina** [comment]
corey =please make sure the excel spread sheet is updated BEFORE each monday meting-roger

**Comment by coreysmart92** [comment]
Closing: I have updated the tracking sheet for Monday meeting 2/22/16.
(2/22/16)
