### ISSUE TITLE
stitcher is not being updated

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#437]
ashton for some reason todays podcast on the web site is not showing up on stitcher
please assign to someone to check/fix

roger
@cassininazir

**Comment by amb141330** [comment]
If there's not still a problem I'm guessing it was an issue on Stitcher's side. Roger, if you're not still having issues with stitcher, could you close this?

**Comment by amb141330** [comment]
We were having issues with setting up libsyn properly. It was a user error and checking for these things has become part of the check list.
