### ISSUE TITLE
mistake in starbeast description

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#438]
@coreysmart92 Corey, can you please help me fix this? simply replace
" (Biofilia, Helsinki) " with (organized and produced by the Bioartsociety)"
and adding the link below - keep the other one
http://bioartsociety.fi/making_life/

THANKS

---------- Forwarded message ----------
From: roger malina rmalina@alum.mit.edu
Date: 2016-01-26 19:20 GMT-06:00
Subject: correction
To: Yvan Tina yvantina@gmail.com, Erich Berger erich.berger@bioartsociety.fi

yvan
erick caught an error on the podcast description

hello roger, I just saw the starbeast post on creative disturbance.
the workshops in questions was actually organized and produced by the
Bioartsociety - Biofilia was only the location:
http://bioartsociety.fi/making_life
erich berger
## 

Roger F Malina
is in  Dallas
510-853-2007
## 

check out this website for more information on art, synthetic biology and a-life 
http://synthbioart.texashats.org/
and listen to our podcasts !
http://creativedisturbance.org/

**Comment by cassininazir** [comment]
@yvantina make sure you assign this to @coreysmart92 so it shows up in his list. Seen a few items that mention someone in the content without actually being assigned to an individual.

I've assigned to @coreysmart92 for this one.

**Comment by coreysmart92** [comment]
Thank you Cassini.
Closing: I have made the above updates. Let me know if you need anything else.
(1/27/16)
