### ISSUE TITLE
Nowhere Else Channel !!!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#439]
@amb141330 
---------- Forwarded message ----------
From: Yvan Tina yvantina@gmail.com
Date: 2016-01-26 14:30 GMT-06:00
Subject: Fwd: Creative Disturbance_NoWhere Else
To: Ashton Brillante ashtonbrillante@gmail.com

Can you please follow up on this ?!
We don't want to lose them again
She, and Diane Gromala should be copied in your emails
Much thanks !!

yvan

---------- Forwarded message ----------
From: Mahsoo Salimi salimi@sfu.ca
Date: 2016-01-26 13:28 GMT-06:00
Subject: Creative Disturbance_NoWhere Else
To: Yvan Tina yvantina@gmail.com

Dear Yvan,

Happy new year!

Thanks for your message. we love to continue collaboration with creative disturbance,
I was a bit busy, will post you shortly for our first podcasts,

but please let me know if there is anything else that we need to do in the meantime,
what is the MIT press about? are you going to publish the podcasts?

Bests,
Mahsoo

**Comment by amb141330** [comment]
Will email Yvan about this today and get this going ASAP

**Comment by yvantina** [comment]
FYI 
---------- Forwarded message ----------
From: Mahsoo Salimi salimi@sfu.ca
Date: 2016-02-08 13:48 GMT-06:00
Subject: Re: Creative Disturbance_PainLab Channel (Dr Gromala)
To: Corey Smart corey.smart92@gmail.com
Cc: Yvan Tina yvantina@gmail.com, gromala@sfu.ca

Dear Corey,

I submitted our Channel description and submitted the forms.
Please let us know when it is ready so we could upload our first podcast.

Bests,
Mahsoo

----- Original Message -----
From: "Corey Smart" corey.smart92@gmail.com
To: "Yvan Tina" yvantina@gmail.com, gromala@sfu.ca, salimi@sfu.ca
Sent: Wednesday, November 25, 2015 2:41:31 PM
Subject: Re: Creative Disturbance_PainLab Channel (Dr Gromala)

Dear Mahsoo and Dr. Gromala,
Hello I am Corey, sorry for any delays. Here are the two links: New Channel
form (https://creativedisturbance.wufoo.com/forms/w1brj200mjcrb3/) and the
New Producer form (
https://creativedisturbance.wufoo.com/forms/xzi3tsz1fqp6t7/). These are our
older forms, I am not sure how to share our new forms but the information
is still the same. I will talk with Yvan put together a plan for publishing
this channel as soon as our schedule will allow. Please let me know if you
have any questions, I am here to help.
Corey

**Comment by amb141330** [comment]
Sent an email regarding their first podcast and channel logo. Waiting on response.

**Comment by amb141330** [comment]
Sure. Thanks

**Comment by amb141330** [comment]
Sending them their bumper today. Channel should be up by next week.

**Comment by amb141330** [comment]
I have sent Diane Gromala emails each week asking for her feedback, but have still not gotten any response from her.

**Comment by amb141330** [comment]
This channel is just waiting on a podcast. I received an email from both Mahsoo and Diane about getting podcasts from them shortly and then their channel will be published!

**Comment by yvantina** [comment]
Should we close this issue then ? or wait until the podcast is published ?

**Comment by amb141330** [comment]
I'll leave it open until I publish their first podcast. Just to make sure.

**Comment by amb141330** [comment]
I have emailed them each week for more than the past month and they have still not sent in a podcast. I have offered help each time and done my best to not be pushy. There's nothing I can do about this until they decide to finally send me a podcast.

**Comment by yvantina** [comment]
Yes I know. I don't know what to do neither.. I'll send a private message to Mahsoo on Facebook! stay tuned

**Comment by rmalina** [comment]
ashton
at this point stop pushing
\roger

On Mon, Apr 4, 2016 at 12:20 PM, amb141330 notifications@github.com wrote:

> I have emailed them each week for more than the past month and they have
> still not sent in a podcast. I have offered help each time and done my best
> to not be pushy. There's nothing I can do about this until they decide to
> finally send me a podcast.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/439#issuecomment-205402838

## 

Roger F Malina
is in  Dallas 1-510-853-2007

COME TO OUR CREATIVE DISTURBANCE YURI'S NIGHT PARTY
APRIL 13
FREE TICKETS, BRING YOUR FRIENDS
Wizard's Sports Cafe - 747 S Central Expy, Richardson, TX 75080

https://www.eventbrite.com/e/yuris-night-with-creative-disturbance-tickets-22806282204

**Comment by amb141330** [comment]
Still awaiting information from this group, will just be patient with them and ease into it with summer.

**Comment by rmalina** [comment]
Ashton
Lets discuss strategy face to face

**Comment by amb141330** [comment]
Closing this issue since I've heard nothing from them and Yvan hasn't gotten any progress with them either.

**Comment by yvantina** [comment]
Yes too bad. She (Mahsoo) promised she will come back to us but never did.. 

(Excerpt Facebook) 

Mahsoo
can you just send an email to Ashton and let him know you need more time? they're not aware of our exchanges and are worrying a bit about the next steps since they don't know what to do to help you
thanks

Mahsoo Salimi
21/05/2016 05:58
Mahsoo Salimi
Sure...I will, thanks for all of your help and support 🙂
