### ISSUE TITLE
BIOFICTION - SHAHARATECH

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#440]
@rmalina @cassininazir 

Good Morning every one !
Dear Amal and Markus, this is true synchronicity

Markus met Amal, Amal met Markus

Amal, as you can see below Markus and I talked about the opportunity to tour the BioFiction festival in Africa. Markus is the founder and artistic director, among many other things, of BioFictioin
http://bio-fiction.com/2014/

Markus, Amal is a writer and business entrepreneur heavily involved in cultural activities in the Middle East and Arab spring countries. We met last year through Roger Malina and she is about to set up the 2nd edition of the ShaharaTech Festival in the Tunisian desert, in collaboration with Leonardo.
http://www.sharara.tech/

I think the texts copied below will be self-explanatory so please meet  / talk each other about the possibility of hosting such an interesting event in the Northern Africa area.
We'll be happy to tune in our RAMI's friends as part of a Creative Disturbance partnership with Virtual Africa.
http://ramimed.com/#&panel1-1

Best wishes for this year again, before it's too lat, and let me know if you have any further question !

Thanks

yvan

---------- Forwarded message ----------
From: Markus Schmidt schmidt@biofaction.com
Date: 2016-01-26 9:16 GMT-06:00
Subject: Re: Bio + Pic for Creative Disturbance
To: Yvan Tina yvantina@gmail.com
Cc: Sandra Youssef sandra.youssef@biofaction.com

Dear Yvan

I just saw the blog you published. Thanks again!

Say would you be able and willing to help us bring the BIO·FICTION Festival to Africa? You mentioned a few festivals in Western Africa that would be suitable for the films. We would be happy to get in touch with someone who is seriously interested!
See http://bio-fiction.com/2014/#bio-fiction-on-tour for other stops of the tour.

Many thanks, yours Markus

Dr. Markus Schmidt 
BIOFACTION KG
Kundmanngasse 39/12
1030 Vienna, Austria
www.biofaction.com
schmidt@biofaction.com

2016-01-26 7:32 GMT-06:00 Amal Alayan aalayan@gmail.com:

```
hi Yvan

Just heard your post on META Life film festival etc.

can you please send me their email addresses. Given I am starting to conceptualize the theme of a 2nd ShararaTech Challenge on Sci Fi, it will be worthwhile for me to chat with them

Thanks so much

Amal
```

**Comment by coreysmart92** [comment]
@yvantina could you clarify what action needs to be taken for this Github item.

**Comment by rmalina** [comment]
corey-will discuss with yvan but i suggest we put this on hold for now
roger
@yvantina

On Mon, Feb 1, 2016 at 2:01 PM, coreysmart92 notifications@github.com
wrote:

> @yvantina https://github.com/yvantina could you clarify what action
> needs to be taken for this Github item.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/440#issuecomment-178162344
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by amb141330** [comment]
No action on this issue. Closing
