### ISSUE TITLE
another correction to fee description

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#441]
sorry about this corey but the voice in the fee/fiswick you recorded has edited/corrected
the desicription-pleaes use this version
sorry
roger

> > STEAM:  Bespoke chicken or curated brisket ?
> > 
> > Robert Fee, Paul Fishwick and Roger Malina discuss the current discussion on the need to integrate art and design into science and engineering, STEM to STEAM. In particular the different ways that design is understood , from component design to context design. They can teach design using different approaches from problem, project, object, and topic approaches, but that university curricula are often designed backwards with the integrative approaches only occurring later in the syllabus. The discussion concluded with a nightmare scenario of the museum of the future which anticipates visitor interests and tell them what to experience, and commercial personalization of buyer needs versus customization. Fee contrasted the scenarios of going to the restaurant and experiencing the unanticipated offer of a great chef, a restaurant algorithm that anticipates what you should eat based on previous behavior, or a made-to-order menu
> > Bob: Looks fine. -p

Paul Fishwick, PhD
Chair, ACM SIGSIM
Distinguished University Chair of Arts, Technology, and Emerging Communication Professor of Computer Science Director, Creative Automata Laboratory The University of Texas at Dallas Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Home: utdallas.edu/atec/fishwick
Blog 1: creative-automata.com
Blog 2: modelingforeveryone.com
LinkedIn: metaphorz
Twitter: @representationz

> On Jan 26, 2016, at 12:36 PM, Robert Fee feedesign22@gmail.com wrote:
> 
> Okay, I got a little carried away with the Track Changes feature, but here is a slightly edited version of the Podcast Summary. I like Paul's Comments on Food paragraph a lot.
> 
> bob
> 
> On Sun, Jan 24, 2016 at 12:53 PM, Fishwick, Paul Paul.Fishwick@utdallas.edu wrote:
> Roger:
> 
> Here is a slighty edited version. Thanks for doing! I am editing 
> directly, which seems to not have changed the font so it will look 
> like what you sent, but is actually edited
> 
> > On Jan 22, 2016, at 5:16 PM, Malina, Roger rxm116130@utdallas.edu wrote:
> > 
> > Robert paul
> > 
> > Go to it
> > 
> > Title and abstract need help
> > 
> > STEAM:  Bespoke chicken or curated brisket ?
> > 
> > Robert Fee, Paul Fishwick and Roger Malina discuss the current discussion on the need to integrate art and design into science and engineering, STEM to STEAM. In particular the different ways that design is understood , from component design to context design. They can teach design using different approaches from problem, project, object, and topic approaches, but that university curricula are often designed backwards with the integrative approaches only occurring later in the syllabus. The discussion concluded with a nightmare scenario of the museum of the future which anticipates visitor interests and tell them what to experience, and commercial personalization of buyer needs versus customization. Fee contrasted the scenarios of going to the restaurant and experiencing the unanticipated offer of a great chef, a restaurant algorithm that anticipates what you should eat based on previous behavior, or a made-to-order menu.
> 
> [[COMMENTS on food:
> 
>  Total personalization is they have your food based on your profile 
> (what knowledge they know of you)  Total customization is from the 
> bottom-up, where the client specifies everything  The Chef scenario is different, a a bit like a museum curator, they do not know your profile and do what
>     they feel is best for the client based on their experience
> 
>  So, the Chef scenario isn’t customization or personalization. The curator at the museum has no idea who I am.
>  I get the standard 3 line of text placard regardless
> 
> -p
> 
> <Podcast Description.docx>

**Comment by coreysmart92** [comment]
@rmalina I have created a draft of the Podcast Form. The podcast has been scheduled to publish 4/6/16 I will have it edited and ready to publish as soon as possible if we wish to move up the publishing.
Close: When published.
