### ISSUE TITLE
Update Max Schich's bio and expertise lines

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#442]
@amb141330 you may assign to another team member. 

Please change Max Schich's bio/info online to the following and **email him when complete: Maximilian.Schich@utdallas.edu.**

EXPERTISE:
[please change to...]
History of western art and architecture, complex networks, data science, multidisciplinarity, visualization.

BIO:
[please change to...]
MAXIMILIAN SCHICH is an associate professor for arts and technology at the University of Texas at Dallas and a founding member of the Edith O’Donnell Institute of Art History. His work converges hermeneutics, information visualization, computer science, and physics to understand art, history, and culture. His motivation is to harness and advance expertise in collaboration, to build and lead a group of researchers, to teach students, and to contribute within a team of teams. Maximilian is the first author of A Network Framework of Cultural History (Science Magazine, 2014) and a lead co-author of the animation Charting Culture (Nature video, 2014). He is an editorial advisor at Leonardo Journal, an editorial board member at Palgrave Communications (NPG), and the Journal for Digital Art History. He publishes in multiple disciplines and speaks to translate his ideas to diverse audiences across academia and industry. His work received global press coverage in 28 languages.

---

**Comment by amb141330** [comment]
Changes made and Max has been emailed.
