### ISSUE TITLE
media, arts and communication Turkey channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#444]
ashton
can you assign someone to work with me to set up this new channel

roger

Thanks for your quick response Roger:

Based on your responses and earlier correspondence, here's what I think:

We begin a channel tentatively named "media, arts and communication Turkey" and it covers the intersection of these three domains as well as any possible relevant fields (such as design). We begin with two graduate students, one based in Istanbul the other in Izmir to work under my supervision. 
It works like this: they propose their suggested interviewees and topics to me and then with my approval produce the podcasts. In the first step, they each make 5-7 podcasts, and meanwhile we try to gather some more volunteers or look for other means of funding the new comers. In order to provide them an example and guidelines, I make one or two podcasts, where we establish the format to be followed by them (by the way is there any format requirements, such as using a particular intro music, or labeling the program in any particular way?).
If this framework is fine for you, I'll get in touch with graduate students and then will get back to you.

All the best,

Altug
Altug Akin altugakin@gmail.com

**Comment by cassininazir** [comment]
From the email: 
- Ask @linamoon to develop channel artwork

## \- Work with @halclark for bumper/stinger

absolutely enthusiastic about the proposed media, arts and
communication Turkey channel
you might work with your students to see if we can come up with a catchy name !

this email puts you in touch with ashton brillante, an undergraduate
student who is now
the overall coordinator for creative disturbance

ashton can send you some of our guidelines for recording podcasts- our normal
formal is 15 minutes a bit longer is ok- if its going to be much longer its best
to break it down into several 15 minute podcasts ( our use case is
people listening
while they are doing something else eg commuting or exercising and
longer podcasts
dont work well)

your proposal for the podcast with a test one is fine- ashton will
explain to you
how to deposit a podcast into the system with the descriptive material
and rights release
(these will change a bit soon as we are moving the system to the MIT url soon)

note- we encourage podcasts in different languages than english- we
are trying to be
multiplingual- in some cases people have done one english version and
one other language
versio ( eg aranic)

lina moon can work with you to develop a logo for the channel- unless
one of your
students wants/can do that- lina has great visual graphic skills

for the bumper/stinger- the 10 seconds of music at the beginnign and
end of the podcast
again ashton can have a student here develop one or work with one of
yoru studentts to do this

delighted to partner/help if you know anywhere to go for funding so
you can sustain the effort
yvan tina who runs our Virtual Africa channel is planning to go for
funding for that

once you have selected the students we will need bank information- we send a
1000 $ speaking honorarium- i assume these are not us residents-

**Comment by amb141330** [comment]
Here's the next email. Posting here to keep track:

Dear Roger and rest of the team CreativeDisturbance,

Finally, I got two graduate students who are willing to contribute to Turkish series of CD. Here is the their names and contact information:
Cenk Dereli c.dereli@gmail.com
Sarphan Uzunoglu sarphanuzunoglu@gmail.com

I explained them the project and they're waiting for your emails.
And meanwhile, I'm looking forward to Ashton's guidelines.

Roger, do not worry about the language diversity you want to establish in CD: Our podcasts will be mostly in Turkish, and occasionally, depending on theme and guest, in English.

Best,

Altug

**Comment by amb141330** [comment]
Corey has said that he is in charge of the Turkey Channel

**Comment by rmalina** [comment]
ashton corey
i just put ashton in touch with the turkish team
you need to set up a skype with them next
week

roger

On Mon, Feb 8, 2016 at 1:34 PM, amb141330 notifications@github.com wrote:

> Corey has said that he is in charge of the Turkey Channel
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/444#issuecomment-181477793
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by coreysmart92** [comment]
The Skype meeting went well Wednesday 2/17/16. I will now make individual Github Issues for all task pertaining to the publishing of this channel.
Close: once all Github issues have been created.
(2/22/16)
