### ISSUE TITLE
Creative Disturbance Student Grant Names from Arun Augustine

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#446]
_Email reference below:_

From Roger:

arun
where in india are you moving to ? i was supposed to go to
bangalore in ten days but finally cancelled and will try to go
next summer-it would be great to meet up with you

and what are 'your projects' !!!!!

we are looking for students particularly outside north america
and western europe- we have no leads in india right now

why dont you run the ideas first by us and yvan and lina and
i can interact with you on it

---

From Arun:

One name I would suggest is Sanjukta Krishnagopal, a fellow alumni from BITS Pilani Goa campus, currently a student
in Berlin. She was involved organizing TEDx at our college and is a freelance journalist.

Her LinkedIn Page: https://www.linkedin.com/in/sanjukta-krishnagopal-894b907
On Facebook: https://www.facebook.com/darkangel.sanju?fref=ts

If you are looking for someone currently in India, Ananya is the current sponsorship head of Waves 2015, a widely popular national college cultural festival at BITS Goa.

LinkedIn: https://www.linkedin.com/in/ananya-majumdar-750ba47a

Regards,

Arun

**Comment by linamoon** [comment]
@rmalina Wondering if there was any action I needed to take on this - tagging @yvantina also for reference.

**Comment by yvantina** [comment]
Nope Lina ! Roger, any idea ? I think Ananya may be a better candidate, as she is currently in India and would increase our gender/multilingual stats..just my opinion @linamoon @rmalina

**Comment by rmalina** [comment]
Right now I think we have our hands fill

Getting the first ones going- so I think we should wait

To find other students

roger

**Comment by yvantina** [comment]
Okay
yvan

2016-02-13 15:38 GMT-06:00 rmalina notifications@github.com:

> Right now I think we have our hands fill
> 
> Getting the first ones going- so I think we should wait
> 
> To find other students
> 
> roger
> 
> From: yvantina [mailto:notifications@github.com]
> Sent: Friday, February 12, 2016 7:54 PM
> To: creativedisturbance/podcasts podcasts@noreply.github.com
> Cc: rmalina leonardo.isast@gmail.com
> Subject: Re: [podcasts] Creative Disturbance Student Grant Names from Arun
> Augustine (#446)
> 
> Nope Lina ! Roger, any idea ? I think Ananya may be a better candidate, as
> she is currently in India and would increase our gender/multilingual
> stats..just my opinion @linamoon https://github.com/linamoon @rmalina <
> https://github.com/rmalina>
> 
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/creativedisturbance/podcasts/issues/446#issuecomment-183559498>
> . <
> https://github.com/notifications/beacon/AFjpSVNk4-r2BBbbLEhfj3bRFyohGo7Wks5pjoRDgaJpZM4HPjDr.gif>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/446#issuecomment-183760250
> .

## 

check out this website for more information on art, synthetic biology and
a-life
http://synthbioart.texashats.org/
and listen to our podcasts !
http://creativedisturbance.org/

**Comment by amb141330** [comment]
Closing, but adding to the list to revisit. Think this is a good opportunity if it's not too late.
