### ISSUE TITLE
metrics for good podcasts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#447]
ashton-
as the team develops criteria for evaluating good podcasts, i suggest you include also the bio and podcast text 

here is one that rates LOW for my reading

a) the name of the person in the podcast should be at the START of the text not burried in the text-
you tell me who is being interviewed
b) the name of the producer talking to the voice is not named in the text

anyway-in your criteria -one way is to develop checklists of what you consider 'good" and then score that way
roger

Drawing on the work of Neri Oxman with her use of biomaterials and 3d printing for the design exploration Mushtari, and considering the popular examples of Henri Damon and Oscar Pistorius, Laini Burton investigates the use of prosthetic organs as wearable art in fashion industry and biodesign. From cosmetic surgery and extreme body modification to the design of astrobiological artefacts that could host life, she questions the agentic capacity of synthetic biology in our perception of liveness. The podcast also talks about the ideas of fiction and suspension of disbelief in design from the speculative and the contestable approaches

**Comment by amb141330** [comment]
Will include this example when discussing guidelines with the team

**Comment by amb141330** [comment]
Actually closing because this is a duplicate issue, will copy & paste the text from this issue into the other.
