### ISSUE TITLE
scheduling guidelines

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#448]
ashton
in the last few weeks a couple of weeks you
had more than one podcast from the same channel

i suggest a general policy that in any given week there not
be more than one podcast from the same channel 

unless there is a erally good reason

if i was a producer of another channel that has podcasts waiting
i would be mad that my channel is not getting attention !

roger

**Comment by amb141330** [comment]
Will discuss in today's meeting

**Comment by amb141330** [comment]
Have discussed. Team in agreement, will try and make sure this happens as long as it is possible.
