### ISSUE TITLE
open turkish channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#449]
lina ashton
@cassininazir @yvantina 

can you work with altug to set up the new turkish channel in march ?

roger

Dear Cenk Dereli and Sarphan Uzunoglu

We are delighted that you have agreed to work with Altug Akin to
produce a new channel on the Creative Disturbance platform-
we will be moving this platform to a MIT URL later this spring
so it will have much visibility !

Let me introduce you to the two students here who you
will work with to set up the channel

Lina Moon- she does a lot of our web work, new channels, graphics etc
and development of the platform

Ashton Brillante is the project coordinator and you will work with him
to post podcasts- ashton can you send the team the instructions ?

the idea is that you will work with altug to produce podcasts- normally
under 15 minutes- in any language

when you submit the podcasts we need information like the title,
desiption and short bios and photos of what we call the voices

we have a portuguese channel going up in february- so we
would hope to set yours up in march

the first podcast could be the three of you discussing !
you can record podcasts in person or on skype-ashton will
send instructions

we are pleased to provide you a $1000 US honorarium and
will announce your fellowships -we are now working with students
in south africa, egypt porutgal and are trying to find other students
in other parts of the world- the funds for these awards was raised
through a kickstarter campaign

we do not specify the number of podcasts, but it should be 'several'
each-and altug indicated that we might be able to work with you
to raise additional funds to keep the channel going

if you confirm that you are interested in working with altug=then
i we will need your bank account information

we all look forward to working with you

roger malina

On Mon, Feb 1, 2016 at 9:55 AM, Altug Akin altugakin@gmail.com wrote:

> Dear Roger and rest of the team CreativeDisturbance,
> 
> Finally, I got two graduate students who are willing to contribute to
> Turkish series of CD. Here is the their names and contact information:
> Cenk Dereli c.dereli@gmail.com
> Sarphan Uzunoglu sarphanuzunoglu@gmail.com
> 
> I explained them the project and they're waiting for your emails.
> And meanwhile, I'm looking forward to Ashton's guidelines.
> 
> Roger, do not worry about the language diversity you want to establish in
> CD: Our podcasts will be mostly in Turkish, and occasionally, depending on
> theme and guest, in English.
> 
> Best,
> 
> Altug
> 
> On Wed, Jan 27, 2016 at 5:35 PM, roger malina rmalina@alum.mit.edu wrote:
> 
> > altug
> > 
> > absolutely enthusiastic about the proposed media, arts and
> > communication Turkey channel
> > you might work with your students to see if we can come up with a catchy
> > name !
> > 
> > this email puts you in touch with ashton brillante, an undergraduate
> > student who is now
> > the overall coordinator for creative disturbance
> > 
> > ashton can send you some of our guidelines for recording podcasts- our
> > normal
> > formal is 15 minutes a bit longer is ok- if its going to be much longer
> > its best
> > to break it down into several 15 minute podcasts ( our use case is
> > people listening
> > while they are doing something else eg commuting or exercising and
> > longer podcasts
> > dont work well)
> > 
> > your proposal for the podcast with a test one is fine- ashton will
> > explain to you
> > how to deposit a podcast into the system with the descriptive material
> > and rights release
> > (these will change a bit soon as we are moving the system to the MIT url
> > soon)
> > 
> > note- we encourage podcasts in different languages than english- we
> > are trying to be
> > multiplingual- in some cases people have done one english version and
> > one other language
> > versio ( eg aranic)
> > 
> > lina moon can work with you to develop a logo for the channel- unless
> > one of your
> > students wants/can do that- lina has great visual graphic skills
> > 
> > for the bumper/stinger- the 10 seconds of music at the beginnign and
> > end of the podcast
> > again ashton can have a student here develop one or work with one of
> > yoru studentts to do this
> > 
> > delighted to partner/help if you know anywhere to go for funding so
> > you can sustain the effort
> > yvan tina who runs our Virtual Africa channel is planning to go for
> > funding for that
> > 
> > once you have selected the students we will need bank information- we send
> > a
> > 1000 $ speaking honorarium- i assume these are not us residents-
> > 
> > very excited about this
> > 
> > with the other new channels we have started we know it will take a few
> > weeks to
> > get organised and set up- we have  a new portuguese channel about to go up
> > next
> > week !
> > 
> > i am also copying this to professor cassini nazir who oversees the
> > student team here
> > 
> > roger malina
> > 
> > On Mon, Jan 18, 2016 at 5:23 PM, Altug Akin altugakin@gmail.com wrote:
> > 
> > > Thanks for your quick response Roger:
> > > 
> > > Based on your responses and earlier correspondence, here's what I think:
> > > 
> > > We begin a channel tentatively named "media, arts and communication
> > > Turkey"
> > > and it covers the intersection of these three domains as well as any
> > > possible relevant fields (such as design). We begin with two graduate
> > > students, one based in Istanbul the other in Izmir to work under my
> > > supervision.
> > > It works like this: they propose their suggested interviewees and topics
> > > to
> > > me and then with my approval produce the podcasts. In the first step,
> > > they
> > > each make 5-7 podcasts, and meanwhile we try to gather some more
> > > volunteers
> > > or look for other means of funding the new comers. In order to provide
> > > them
> > > an example and guidelines, I make one or two podcasts, where we
> > > establish
> > > the format to be followed by them (by the way is there any format
> > > requirements, such as using a particular intro music, or labeling the
> > > program in any particular way?).
> > > If this framework is fine for you, I'll get in touch with graduate
> > > students
> > > and then will get back to you.
> > > 
> > > All the best,
> > > 
> > > Altug
> > > 
> > > On Mon, Jan 18, 2016 at 1:40 PM, roger malina rmalina@alum.mit.edu
> > > wrote:
> > > 
> > > > Altug
> > > > 
> > > > some responses
> > > > - we are just getting this initiative going- we raised 20,000$ through
> > > >   kickstarter
> > > >   and are starting by awarding $1000 grants to students internationally
> > > > 
> > > > we could potentially award two grants of $1000 in turkey
> > > > 
> > > > our podcast format is 15 minutes- but one can do several with one guest
> > > > 
> > > > we are totally open to whether the channel is geographic or thematic or
> > > > mixed=
> > > > we are interested in getting podcasts in different languages also = and
> > > > we
> > > > are trying to have good gender balance among our speakers
> > > > 
> > > > we havent set a fixed number of podcasts- as we are experimenting=
> > > > but lets say at least 5 is maybe reasonable
> > > > 
> > > > the podcasts are intended to be professional to professional
> > > > communication
> > > > ie to peers or to graduate students- we hope to help professionals
> > > > develop
> > > > podcast publishing as part of their professional practice- we will be
> > > > moving
> > > > the web site to MIT later this spring
> > > > 
> > > > in terms of follow up beyond the initial grant we are very open to
> > > > ideas-
> > > > for instance yvan tina that runs the virtual africa channel has found
> > > > one
> > > > student in egypt and one in south africa- and we are discussing
> > > > applying
> > > > for project funding that would include the students beyond the initial
> > > > grant
> > > > 
> > > > for instance also the french leonardo non profit is in a number of
> > > > EU grants- and the art and biology channel is being in part funded
> > > > by that EU grant in europe
> > > > 
> > > > in other cases the organisation that has opened the channel ( et
> > > > the Human Impacts Institute) is just including the channel as part
> > > > of their organisations communication strategy and is included
> > > > in their own initiatives and we agree to keep carrying the channel
> > > > 
> > > > finally in terms of editorial scope- we cover the broad intersections
> > > > of arts/design/humanities with science/engineering- but we are finding
> > > > that many of the podcast authors have very diverse professional
> > > > practices so we are happy to have podcasts in other theme areas
> > > > as they make sense
> > > > 
> > > > roger
> > > > 
> > > > On Mon, Jan 18, 2016 at 12:24 PM, Altug Akin altugakin@gmail.com
> > > > wrote:
> > > > 
> > > > > Dear Lina,
> > > > > 
> > > > > Thanks for your email, and I'm very pleased to (e-)meet you as well.
> > > > > 
> > > > > As I've been thinking about possible names of graduate students who
> > > > > might be
> > > > > interested in contributing to CD, I realized that there are some
> > > > > points
> > > > > that
> > > > > I should be more clear about. And I'll be pleased if you or Roger can
> > > > > clarify these, so that we can move forward more efficiently.
> > > > > 
> > > > > As I looked through the podcasts, I realized that there are some
> > > > > country
> > > > > specific ones (for instance Iran) and thematic ones (for example
> > > > > Audiolats).
> > > > > So should I propose you students, in the scope of a Turkey-specific
> > > > > series,
> > > > > or rather as potential contributors to existing thematic series? I
> > > > > think, I
> > > > > would prefer the first one, by the way.
> > > > > 
> > > > > Secondly, the fellowship is 1) For how many podcasts? 2) How long are
> > > > > the
> > > > > podcasts supposed to be? 3) what is the amount of the fellowship? 4)
> > > > > If
> > > > > there is more than one student, do they share the fellowship or each
> > > > > gets
> > > > > the fellowship individually?
> > > > > 
> > > > > Thirdly, how the podcasts series are sustained once the fellowship
> > > > > holders
> > > > > finish their share of podcasts? Voluntarily, or sponsored in other
> > > > > ways
> > > > > like
> > > > > fellowships?
> > > > > 
> > > > > I'm looking forward to your answers, and once we are clear about
> > > > > these,
> > > > > I'll
> > > > > propose you some names for this project which excites me, indeed.
> > > > > 
> > > > > All the Best
> > > > > 
> > > > > Altug Akin
> > > > > 
> > > > > On Thu, Jan 14, 2016 at 3:05 PM, Lina Moon jmoon12@gmail.com wrote:
> > > > > 
> > > > > > Hi Altug,
> > > > > > 
> > > > > > Happy new year! It's good to (e-)meet you. As Roger mentioned, my
> > > > > > name
> > > > > > is
> > > > > > Lina, and I am coordinating the student grants for Creative
> > > > > > Disturbance.
> > > > > > 
> > > > > > I just wanted to follow up with you and say that we'd be delighted
> > > > > > to
> > > > > > have
> > > > > > a graduate student that would be interested in gaining exposure for
> > > > > > their
> > > > > > research and producing podcasts on Creative Disturbance, at your
> > > > > > recommendation.
> > > > > > 
> > > > > > Please feel free to let us know if there's anyone that comes to
> > > > > > mind,
> > > > > > and
> > > > > > we'd be glad to connect.
> > > > > > 
> > > > > > Best,
> > > > > > Lina Moon
> > > > > > 
> > > > > > On Wed, Dec 30, 2015 at 7:43 PM, Altug Akin altugakin@gmail.com
> > > > > > wrote:
> > > > > > 
> > > > > > > Great roger,
> > > > > > > 
> > > > > > > For a week, I'll be on vacation and once I'm back, I'll have a
> > > > > > > think
> > > > > > > about it.
> > > > > > > 
> > > > > > > Best,
> > > > > > > 
> > > > > > > Altug Akin
> > > > > > > 
> > > > > > > On Wed, Dec 30, 2015 at 4:35 AM, roger malina
> > > > > > > rmalina@alum.mit.edu
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > altug
> > > > > > > > delighed to hear f
> > > > > > > > Vrom you !! and best for 2016
> > > > > > > > 
> > > > > > > > the project i mentioned it is Creative Disturbance
> > > > > > > > 
> > > > > > > > http://creativedisturbance.org/
> > > > > > > > 
> > > > > > > > we boadcast podcasts by professionals for professionals
> > > > > > > > in the broad fields of connecting the arts and emerging
> > > > > > > > technologies
> > > > > > > > and arts and science
> > > > > > > > 
> > > > > > > > we raised money by crowdfunding to give 1000 dollar speaking
> > > > > > > > 'fellowships)
> > > > > > > > to students internationally who would agree to publish a few
> > > > > > > > podcasts
> > > > > > > > (
> > > > > > > > in any
> > > > > > > > language) with advanced students or professionals in their own
> > > > > > > > community
> > > > > > > > 
> > > > > > > > http://malina.diatrope.com/2015/12/17/disturbing-fellows-and-fellas-in-portugal-on-creative-disturbance/
> > > > > > > > 
> > > > > > > > i would be delighted if you could find a student ( MA or PhD) who
> > > > > > > > might be interested
> > > > > > > > in doing this under your supervision in turkey !
> > > > > > > > 
> > > > > > > > we are moving the platform to MIT in the spring -so its great
> > > > > > > > visibility
> > > > > > > > 
> > > > > > > > i am copying this to lina moon who is coordinating who student
> > > > > > > > fellow
> > > > > > > > program
> > > > > > > > 
> > > > > > > > roger
> > > > > > > > 
> > > > > > > > On Wed, Dec 30, 2015 at 6:06 AM, Altug Akin altugakin@gmail.com
> > > > > > > > wrote:
> > > > > > > > 
> > > > > > > > > Dear Roger,
> > > > > > > > > 
> > > > > > > > > After the party at Price's house on Saturday evening, I'm
> > > > > > > > > sending
> > > > > > > > > you
> > > > > > > > > this
> > > > > > > > > email, as I promised, with the hope of keeping in touch with
> > > > > > > > > you.
> > > > > > > > > If you inform me about the podcast project you mentioned that
> > > > > > > > > night,
> > > > > > > > > I'll do
> > > > > > > > > my best to find someone who can contribute to tour project, if
> > > > > > > > > it
> > > > > > > > > cannot be
> > > > > > > > > myself.
> > > > > > > > > 
> > > > > > > > > Best Regards and Happy New Year.
> > > > > > > > > 
> > > > > > > > > Altug Akin
> > > > > > > > > ## 
> > > > > > > > > ---
> > > > > > > > > 
> > > > > > > > > Visiting Scholar at Annenberg School for Communication, UPENN
> > > > > > > > > 
> > > > > > > > > Assistant Professor Doctor at Faculty of Communication, Izmir
> > > > > > > > > University of
> > > > > > > > > Economics, Turkey
> > > > > > > > > 
> > > > > > > > > Reporter for BBC World Service, Turkish Section
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > Roger F Malina
> > > > > > > > is in Paris
> > > > > > > > my cell 33-6-80-45-94-47
> > > > > > > ## 
> > > > > > > ---
> > > > > > > 
> > > > > > > Visiting Scholar at Annenberg School for Communication, UPENN
> > > > > > > 
> > > > > > > Assistant Professor Doctor at Faculty of Communication, Izmir
> > > > > > > University
> > > > > > > of Economics, Turkey
> > > > > > > 
> > > > > > > Reporter for BBC World Service, Turkish Section
> > > > > ## 
> > > > > ---
> > > > > 
> > > > > Visiting Scholar at Annenberg School for Communication, UPENN
> > > > > 
> > > > > Assistant Professor Doctor at Faculty of Communication, Izmir
> > > > > University
> > > > > of
> > > > > Economics, Turkey
> > > > > 
> > > > > Reporter for BBC World Service, Turkish Section
> > > > ## 
> > > > 
> > > > Roger F Malina
> > > > is in  Dallas
> > > > 510-853-2007
> > > ## 
> > > ---
> > > 
> > > Visiting Scholar at Annenberg School for Communication, UPENN
> > > 
> > > Assistant Professor Doctor at Faculty of Communication, Izmir University
> > > of
> > > Economics, Turkey
> > > 
> > > Reporter for BBC World Service, Turkish Section
> > ## 
> > 
> > Roger F Malina
> > is in  Dallas
> > 510-853-2007
> ## 
> ---
> 
> Visiting Scholar at Annenberg School for Communication, UPENN
> 
> Assistant Professor Doctor at Faculty of Communication, Izmir University of
> Economics, Turkey
> 
> Reporter for BBC World Service, Turkish Section
## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by rmalina** [comment]
@amb141330 
check out the turkish channel github item

**Comment by coreysmart92** [comment]
@amb141330 Assign/create sub tasks github items then Close.
