### ISSUE TITLE
Tracking of previous Splash Pages

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#450]
Create a sheet tracking for previous splash pages stats.

**Comment by amb141330** [comment]
I'll go through the past splash page dates and look at the statistics for those dates later this week. I have other priorities right now.

**Comment by amb141330** [comment]
I have the info-graphic from the RAW Presentation I did which displays monthly stats in addition to splash page dates

**Comment by amb141330** [comment]
Putting this on a list of tasks to revisit. I think splash pages should be a normal part of our year, but be planned out to do a certain amount over the year.
