### ISSUE TITLE
update bumper schedule in the excel sheet

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#452]
hal

can you update the bumper schedule in the excel sheet
it is way out of date

i assume that all of you are producing bumbers so you
meet the goal for number of bumpers per month

and never change the bumper on a producers channel
without checking and getting it oked by that producer

roger
@amb141330

**Comment by halclark** [comment]
Bumper schedule has been updated, pending approval from producers who aren't in-house.
