### ISSUE TITLE
podcast on hold- bradbury

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#453]
corey
there is a podcast on hold under the tab in the excel sheet called on hold
can you publish that podcast please

you might check all, the tabs and make sure the contents are up to date
i assume hal is updating the bumper tab

roger

**Comment by coreysmart92** [comment]
I will discuss this in the Sound meeting Monday 2/22/16.
(2/22/26)

**Comment by coreysmart92** [comment]
Closing: We discussed this issue and found that we can not publish that podcast because of a voice. I will make a new issue to review and update all tabs on the Tracking Sheet.

**Comment by rmalina** [comment]
judd
just wanted to confirm that we cant publish that podcast
that you recorded with a colleague last year ?

not a problem just wanted to make sure you dont want the
podcast published

roger

On Mon, Mar 7, 2016 at 11:42 AM, coreysmart92 notifications@github.com
wrote:

> Closing: We discussed this issue and found that we can not publish that
> podcast because of a voice. I will make a new issue to review and update
> all tabs on the Tracking Sheet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/453#issuecomment-193365398
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by rmalina** [comment]
It can be posted, we have all the releases. The only thing we do not have is a profile for Billy Lett.

-Judd

From: Roger Malina <rmalina@alum.mit.edu<mailto:rmalina@alum.mit.edu>>
Date: Monday, March 7, 2016 at 4:46 PM
To: creativedisturbance/podcasts <reply@reply.github.com<mailto:reply@reply.github.com>>, Judd Bradbury <jdb101000@utdallas.edu<mailto:jdb101000@utdallas.edu>>, Ashton Brillante <ashtonbrillante@gmail.com<mailto:ashtonbrillante@gmail.com>>
Subject: Re: [podcasts] podcast on hold- bradbury (#453)

judd
just wanted to confirm that we cant publish that podcast
that you recorded with a colleague last year ?

not a problem just wanted to make sure you dont want the
podcast published

roger

On Mon, Mar 7, 2016 at 11:42 AM, coreysmart92 <notifications@github.com<mailto:notifications@github.com>> wrote:

Closing: We discussed this issue and found that we can not publish that podcast because of a voice. I will make a new issue to review and update all tabs on the Tracking Sheet.

## 

Reply to this email directly or view it on GitHubhttps://github.com/creativedisturbance/podcasts/issues/453#issuecomment-193365398.

## 

Roger F Malina
is in  Dallas
510-853-2007
