### ISSUE TITLE
Ideas for Yuri's night

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#455]
----- Forwarded message from frank@pietronigro.com -----
    Date: Mon, 8 Feb 2016 22:33:22 +0000
    From: "Frank Pietronigro, Zero Gravity Arts Consortium, Director" frank@pietronigro.com
Reply-To: "Frank Pietronigro, Zero Gravity Arts Consortium, Director" frank@pietronigro.com
 Subject: Seeking Arts in Space Exploration Videos for the National Space Society's 35th International Space Development Conference
## *\* Mark your calendars and join us for a screening of the latest videos showcasing the arts, humanities and culture in space exploration projects during the proceedings of the

National Space Society’s 35th Annual (http://isdc2016.nss.org/isdc/#/)  International Space Development Conference 2016 (http://isdc2016.nss.org/isdc/#/)
May 18 - 22, 2016, Sherator Puerto Rico Hotel & Casino, San Juan, Puerto Rico

Space arts colleagues, space scientists, engineers, and entrepreneurs from around the globe who are working at the nexus of space arts, culture, science and engineering are invited to submit documentaries showcasing new works to the

2016 Arts in Space Exploration Film Screening
Produced in Collaboration with the
Zero Gravity Arts Consoritum (ZGAC)’s

What are the latest developments in the internatioanl arts and space exploration community responses and contributions to the expansion of the arts, humanities and culture within the context of the space exploration industry? How are the arts impacting space science and engineering and how is sapce science and engineering impacting the arts?  What sublime new works of art, performance and or collaborations have evolved during recent space missions, parabolic flights or collaborations created aboard the International Space Station?

DEADLINE: APRIL 1, 2016

TO PARTICIPATE MAIL NTSC DVDs TO:
Frank Pietronigro, Curator
Zero Gravity Arts Consoritum’s 2016 Arts in Space Exploration Film Screening, P. O. Box 193163, San Francisco, CA 94131, United States

Please include in your package PLUS email the following information to frank@pietronigro.com (mailto:frank@pietronigro.com)
Title
Total Running Time (TRT):
Creators
Description
WEBSITE URL:
Contact Information (Name, Address, City, State, Zip
Image for public relations use (.jpg format 1080 x 1920, 72dpi)

This program will be organized as a part of the ZGAC’s International Conference Program with Frank Pietronigro, Co-Founder and Project Director, ZGAC, serving as curator.  The Space Arts practice is a global, human cultural endeavor that transcends national boundaries.   As artists, artronauts, astronauts, space scientists, engineers and other pioneers we wish to fortify conference participation from people representing the diversity and cultural richness of our global community as reflected in the cultural richness of ISDC2016’s theme:

Space Beyond Borders

As a compliment to the screening ZGAC will faciliate group meetings for artists, artronauts, astronauts, space scientists, engineers and other pioneers whose goal will be to form production teams to collaborate on the conception, scope, theme and focus of the Space Arts Track for the National Space Society’s 36^th International Space Development Confernece Space Arts Track that will take place in St. Louis, MO in May of 2017.

ISDC2016 in San Juan, Puerto Rico will serve as a venue to celebrate a selection of new international video works showcasing the arts in space exploration while our community looking forward to the creation of a much larger Spacse Arts Track that will take place during ISDC 2017 including the long awaited awarding of the 2^nd round of the Leonardo DaVinci Space Arts Awards.

Thank you for your time and consideration.

Sincerely,
Dave Dressler
Chair, 35^th International Space Development Conference 2016

Frank Pietronigro
Artist and Artronaut
Co-Founder and Project Director, Zero Gravity Arts Consortium
Curator, Arts in Space Exploration Film Screening 2016
35^th International Space Development Conference
P. O. Box 193163, San Francisco, CA 94119-3163
415-695-0933
frank@pietronigro.com

ISDC® 2016: Space Beyond Borders celebrates the increasingly collaborative, multinational, multidisciplinary, and interconnected nature of space development in the 21st century. The International Space Development Conference® (ISDC®) is the preeminent gathering place for everyone around the world who seeks to accelerate our pursuits beyond planet Earth and learn about the opportunities the emerging space economy can bring to science, technology and exploration.

The conference brings together aerospace industry leaders, astronauts, newspace startups, space exploration pioneers, academic thought leaders, and space supporters young and old—all united by a common goal to explore and develop space for the benefit of humankind.  We will host various sessions and workshops focused in multiple areas of space development: Moon and Mars exploration and settlement, deep space exploration, innovative technology, science fiction’s influence in today’s technology, collaboration in space, planetary sciences, commercial space, living in space, space-based solar power, space debris, space law and policy, and much more.  The speakers and panelists have key roles in the industry and our interactive discussions during panel sessions will allow you to ask the right questions.

2016 LEONARDO DAVINCI SPACE ARTS AWARDS II

The receipints of the 2^nd Leonardo DaVinci Space Arts Awards will be selected from nominees noted below, during the proceedings of the National Space Society's 35th Annual International Space Development Conference.  The awards ceremony will be held the following year during ISDC2017 in St. Louis, MO.

Nominees Include:
2^nd Artronaut Award
Col. Chris Hadfield
Canada

Arts in Space Life Dedication Award
Lowry Burgess
United States

Arts in Space Life Dedication Award
Kitsou Duboise
France

Arts in Space Life Dedication Award
Tekuro Osaka
Japan

Arts in Space Organization Award
Projekt Atol
Solvenia

Arts in Space Advocate Award
Pete Worden
United States

Arts in Space Advocate Award
Yvonne Clearwater
NASA Art Space
United States

Arts in Space Advocate Award
Adarsh Deepak
United States

Arts in Space Scholastic and Curatorial Awards
Marko Peljhan
Tyler Stallings
United States

Zero Gravity Art Award
Ayako Ono
Japan

Special Arts in Space Award
Trevor Paglen
United States

Special Arts in Space Award (Architecture)
Arturo Vittori
Andreas Vogler
Co-Founders
Architecture and Vision
Germany

Special Arts in Space Award (Zero Gravity Dance)
Setsuko Ishiguro
Japan

Special Arts in Space Award (Performance Collaboration)
Nelly Ben Hayoun
United Kingdom

2016 LEONARDO DAVINCI SPACE ARTS AWARDS II

In honor of the great artist and scientist whose visions of flight inhabits our minds and whose first observations of light reflected from the Moon gave reverberant and reflective deep-space consciousness to us.  These honors were first awarded during the proceedings of the Space Arts Track of the 25th International Space Development Conference that was held in Los Angeles in 2006.  The award sponsors, at that time included: Co-Sponsored by the National Space Society, the Planetary Society, the STUDIO for Creative Inquiry at the College of Fine Arts, Carnegie Mellon University and the Zero Gravity Arts Consortium.

2017 LEONARDO DAVINCI SPACE ARTS AWARDS II
Please contact frank@pietronigro.com (mailto:frank@pietronigro.com)  for sponsorship information.
# 

*\* (http://www.twitter.com/)
*\* (http://www.facebook.com)
*\* (http://mailchimp.com)
Copyright © _2016_ _Frank Pietronigro_, All rights reserved.
 You are receiving this email because of your interest in or having worked with Frank Pietronigro.

Our mailing address is:
Frank Pietronigro Interdisciplinary Artist
P. O. Box 193163
San Francisco, CA 94119-3163
USA
Want to change how you receive these emails?
You can *\* update your preferences (http://pietronigro.us8.list-manage2.com/profile?u=e319bb263d7b19cf1aecca48d&id=25999d2e47&e=580ba0df5b)
or *\* unsubscribe from this list (http://pietronigro.us8.list-manage2.com/unsubscribe?u=e319bb263d7b19cf1aecca48d&id=25999d2e47&e=580ba0df5b&c=516964a89c)

----- End forwarded message -----

**Comment by rmalina** [comment]
@halclark 
hal can you put frank pietronigro on the list of potential yuri's night podcasts to record
roger

**Comment by cassininazir** [comment]
Create a new issue to record with Frank Pietronigro
