### ISSUE TITLE
podcast credentials

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#456]
---------- Forwarded message ----------
From: Yvan Tina yvantina@gmail.com
Date: 2016-02-10 17:41 GMT-06:00
Subject: podcast credientials
To: Hal Clark hclark55@gmail.com, Ashton Brillante ashtonbrillante@gmail.com, Corey Smart corey.smart92@gmail.com

Hey guys !

We need to give full credits to the bumpers my friends in Paris have created
Can you please let me know the numbers of podcasts that have these signatures ?
Once you'll give me these information they will be able to tell us exactly what should be indicated on the web page for their sounds..
they're also willing to work with us on the experimental sound channel and create new bumpers
but first we have to credit them on the podcasts that use their work
Please let me know as soon as possible since they made this request a few months ago now but i can't browse the whole website to figure out which podcasts have these signatures..
​
 Creative Disturbance - Frank Malina - Signature...
​​
 Virtual Africa - Signature 1.wav
​
Thanks
yvan

**Comment by yvantina** [comment]
@halclark any update on this please ??  @amb141330

**Comment by yvantina** [comment]
@amb141330 Ashton, can you assigned this to someone please ? I've been talking about this for months now but nothing happened..

**Comment by amb141330** [comment]
Yes, let me look into this. Just to clarify, this individual participated in both the Frank Malina podcast bumper and the Virtual Africa one?

**Comment by yvantina** [comment]
yes - I think so..though the Frank Malina one has not been that much used compared to Virtual Africa..
but we need to credit them on every podcast they contributed..
https://drive.google.com/drive/folders/0B0RS2YDJUln1fng5aTlnd0tzTXVZamZOeUdHckN0OEJ4RXVDZVFITHlHOTJ4bzdrdjZNNHc

**Comment by cassininazir** [comment]
please give credit on those podcasts within the podcast descriptions

**Comment by yvantina** [comment]
Hal, can you send me the list of the podcasts you have identified please ? I'll ask the authors the necessary description to be added. thanks

**Comment by amb141330** [comment]
Please update this issue or close it.

**Comment by yvantina** [comment]
Haven't received that list yet..

**Comment by ritwikjk** [comment]
Hey @yvantina was this completed?

**Comment by yvantina** [comment]
Nope..

**Comment by ritwikjk** [comment]
@yvantina What was the artist's name?

**Comment by yvantina** [comment]
Ronan Martin http://douxdivorcerecords.com/index.php/ronan-martin/

**Comment by ritwikjk** [comment]
@OskarOlssonCD 
@arfaye can you work on which podcasts have this bumper and give the bumper author name as the above artist?

**Comment by OskarOlssonCD** [comment]
@ritwikjk 
I'll look into this. Is it just for that channel?

**Comment by OskarOlssonCD** [comment]
@ritwikjk Please see the issue posted about the bumpers on google drive. We'll need access to those to identify the bumper by how it sounds.

**Comment by OskarOlssonCD** [comment]
I've added Ronan Martin into the descriptions of each of these podcasts with a hyperlink to his website.

**Comment by yvantina** [comment]
Much thanks Oskar and Ritwik
ps: can you please do the same with the Frank Malina's ones ?
one example https://creativedisturbance.org/podcast/chardronnet-and-lapelletrie-discuss-frank-malina-and-his-circle-of-friends-2/

**Comment by OskarOlssonCD** [comment]
@yvantina Will do! Just for clarity's sake, this podcast bumper was also done by Ronan, correct?

**Comment by yvantina** [comment]
yes

**Comment by OskarOlssonCD** [comment]
@yvantina @ritwikjk  Alright, now all of the podcasts on both channels featuring Ronan Martin's bumper are credited to him. Closing this issue.
