### ISSUE TITLE
splash page for yuri's night

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#457]
hal
here is my proposal for the yuri's night splash page= i assume you will work with lina on this ?

lets do a matrix of images of 'firsts' in space, first man in space, first woman in space, first dog in space ! first chinese in space first plant in space etc etc

just an image with "first x in space' with a link to where the image was
taken from

roger

**Comment by linamoon** [comment]
Reassigning to myself so I will remember - will work with @halclark on this.
