### ISSUE TITLE
broken links to voice images

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#459]
ashton

when there is an image of a voice on the page

http://creativedisturbance.org/channel/femgineers/

the image doesnt link to the bio of the voice ? is that suppoed to be
happening ?

its annoying to see an image of someone and you cant click through
to their voice bio

roger

**Comment by amb141330** [comment]
To my knowledge this has always been the case. I agree with you that they should just be able to click those pictures rather than have to go to the podcast's URL to click those images. 

@cassininazir What's the best way for us to change this?

**Comment by cassininazir** [comment]
Re-assigning to @dylanorgeron to fix. Completely agree, we should make those links.

**Comment by dylanorgeron** [comment]
images now link to the voice's page
