### ISSUE TITLE
register our yuris night on yuris night website

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#461]
read instruciton and register our event

https://yurisnight.net/3-steps/

with party at wizards

roger

**Comment by halclark** [comment]
Yuri's Night has been registered with website. 
https://yurisnight.net/events/creative-disturbance-celebrates-yuris-night/
Closing issue.

**Comment by rmalina** [comment]
great
so thats wednesday evening the 13 ?
thats good

roger

On Thu, Mar 10, 2016 at 4:42 AM, halclark notifications@github.com wrote:

> Yuri's Night has been registered with website.
> https://yurisnight.net/events/creative-disturbance-celebrates-yuris-night/
> Closing issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/461#issuecomment-194647274
> .

## 

Roger F Malina
is in  Paris
06-80-45-94-47
