### ISSUE TITLE
yuris night podcasts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#462]
make a list of podcasts we will feature for yuris night

a) all those already in space and culture channel : 6

b) annick and jean luc said they would try and do ones with kitsou dubois and pierre compte
c)african astronaut: yvan is setting up podcast
d) mike kesden and midori kitagaw on their occulus gravitational waves project
e) moon day guy 

can you keep track and work with me on these

roger

**Comment by halclark** [comment]
Yuri's Night published.

**Comment by rmalina** [comment]
hal
we never did the podast with kesden and midori
needs to be scheduled
roger

**Comment by cassininazir** [comment]
Closing this item. Have opened a new item at #581 with specific details
