### ISSUE TITLE
Add field for language for Podcasts in WP 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#464]
We'd like to track language in our metrics (http://creativedisturbance.org/stats/). Can you add a dropdown for language(s) in the Podcast Episode form in WordPress.

**Comment by cassininazir** [comment]
Connecting issue #466 here.

**Comment by dylanorgeron** [comment]
languages are already being tracked in WP. was this issue resolved already or is there something more to it?

![image](https://cloud.githubusercontent.com/assets/6401465/15152120/ba95b6b6-1699-11e6-832a-011f974a3204.png)

**Comment by cassininazir** [comment]
This field should change from **text input** to **dropdown** menu, if possible. The current text input introduces user error: your example above lists `English` the one below `EN`. I can foresee additional confusion when introducing other languages (e.g. confusion between Mandarin and Cantonese). The solution should minimize garbage-in, garbage-out.

<img width="485" alt="screen shot 2016-05-10 at 1 44 57 pm" src="https://cloud.githubusercontent.com/assets/1661430/15158409/6a480cba-16b5-11e6-8318-a8c12997685a.png">
