### ISSUE TITLE
podcast scheduling with iranian channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#465]
ashton
who is the liaison wiht the iranian channel- the liaison needs to contact
fatemeh and start scheduling these podcasts

they will help in our non english metric !

roger

Tashakori, Fatemeh via cometmail.onmicrosoft.com 
2:34 PM (1 hour ago)

to roger 
Hi Dr.Malina,

Thank you so much for your email. Absolutely, I am gonna publish two podcasts in next few weeks.
I will let you know when they become ready.
Best,
Fatima
Sent from my iPhone

**Comment by amb141330** [comment]
I believe Yvan was the one dealing with this channel. Since he is busy with his own channel and studies, I am happy to contact Fatima about any updates.

**Comment by rmalina** [comment]
no yvan is NOT assigned to this channel
all channels should be assigned to one of the sound editors
roger

On Mon, Feb 22, 2016 at 11:00 AM, amb141330 notifications@github.com
wrote:

> I believe Yvan was the one dealing with this channel. Since he is busy
> with his own channel and studies, I am happy to contact Fatima about any
> updates.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/465#issuecomment-187267503
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by amb141330** [comment]
I'll handle this then.

**Comment by amb141330** [comment]
Already in contact with Fatimeh and we have another issue open about her podcasts, closing this one.
