### ISSUE TITLE
language diversity goal

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#466]
ashton

per the discussion i think we need to develop a metric but also a goal
of what fraction of our podcasts are not in english each month

what do you think would be a reasonable goal as a start as to
what % podcasts each month will be in another language than
english ?

roger

**Comment by cassininazir** [comment]
Connecting issue #464 here.

**Comment by amb141330** [comment]
I'm not sure exactly what our goal should here. My immediate goal would be around 25%, but I'm not sure how reasonable this is. It would be helpful to view past months and see what percentage of them was languages other than english. Then perhaps we push that percentage a bit to make it a "goal."

**Comment by rmalina** [comment]
lets discuss in the meeting

do we have a history of what our stats are on languate and international
diversity ?

roger

On Mon, Feb 22, 2016 at 10:59 AM, amb141330 notifications@github.com
wrote:

> I'm not sure exactly what our goal should here. My immediate goal would be
> around 25%, but I'm not sure how reasonable this is. It would be helpful to
> view past months and see what percentage of them was languages other than
> english. Then perhaps we push that percentage a bit to make it a "goal."
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/466#issuecomment-187267037
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by amb141330** [comment]
I am able to go through and get a list of languages that we have. In terms of tracking actual splash page data, we can view how downloads changed during splash page times. In my RAW presentation I made a diagram of splash pages and their dates. We can refer to that diagram when looking at the stats.

**Comment by amb141330** [comment]
Old issue. Closing, will put on my list of issues to revisit when looking at goals for the fall.
