### ISSUE TITLE
info for collin steinmetz podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#467]
corey
here is url bio and info about the podcast for your
to edit and use for the podcast
@cassininazir 
cassini edit if you want

roger

The Lumen Life - Reexamining the Relationship Between People and Lighting

Collin Steinmetz
Sales & Marketing, ilumi
www.ilumi.co

Light is a powerful force that often seems to fall into the background of our day-to-day lives. It tells us when to wake and when to sleep. It creates atmosphere and mood. It gives focus and function. It entertains and envelops. So why is control of lighting normally limited to on and off? As both the LED lighting and the connect home industries continue to see exponential growth, we find it increasingly important to examine how people interact with light, how light interacts with them, and what can be done to help people think about an ordinary item in an extraordinary way. 
Collin Steinmetz is a recent UT Dallas Alumnus (Bus. Admin/Marketing/Economics, '14) with a knack for problem solving. As a fresh graduate, he craved an opportunity that would allow him to escape the monotony often associated with a 'desk job'. As fate would have it, an opportunity at Plano-based ilumi solutions (founded by two UT Dallas MBA graduates) presented itself a month after graduation where he currently works in sales and marketing role to facilitate and support the company's rapid growth. He is in discussion with ATEC faculty member Cassini Nazir.

ATEC Watering Hole
Friday, February 12, 2016
2:00 – 4:00 pm
ATC 3.209

The Lumen Life - Reexamining the Relationship Between People and Lighting

Collin Steinmetz
Sales & Marketing, ilumi
www.ilumi.co

Light is a powerful force that often seems to fall into the background of our day-to-day lives. It tells us when to wake and when to sleep. It creates atmosphere and mood. It gives focus and function. It entertains and envelops. So why is control of lighting normally limited to on and off? As both the LED lighting and the connect home industries continue to see exponential growth, we find it increasingly important to examine how people interact with light, how light interacts with them, and what can be done to help people think about an ordinary item in an extraordinary way. 
Collin Steinmetz is a recent UT Dallas Alumnus (Bus. Admin/Marketing/Economics, '14) with a knack for problem solving. As a fresh graduate, he craved an opportunity that would allow him to escape the monotony often associated with a 'desk job'. As fate would have it, an opportunity at Plano-based ilumi solutions (founded by two UT Dallas MBA graduates) presented itself a month after graduation where he currently works in sales and marketing role to facilitate and support the company's rapid growth.

Collin Steinmetz is a recent UT Dallas Alumnus (Bus. Admin/Marketing/Economics, '14) with a knack for problem solving. As a fresh graduate, he craved an opportunity that would allow him to escape the monotony often associated with a 'desk job'. As fate would have it, an opportunity at Plano-based ilumi solutions (founded by two UT Dallas MBA graduates) presented itself a month after graduation where he currently works in sales and marketing role to facilitate and support the company's rapid growth.

**Comment by coreysmart92** [comment]
Okay, I will begin the podcast forms.
Close: when podcast forms have been submitted.
(2/22/16)

**Comment by coreysmart92** [comment]
This podcast is scheduled for 4/13/16
Close: When podcast is published

**Comment by cassininazir** [comment]
Scheduled to publish for this week. Closing.
