### ISSUE TITLE
podcast description for second podcast with steinmetz

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#468]
corey-here is the description for the second steinmetz podcast
@cassininazir 

Designing the Mundane, Live Your Light, Chickens Unite !
Collin Steinmetz of the Ilumi lighting company, www.ilumi.com, discusses with Cassini Nazir of the ArtSciLab at UT Dallas the disruptive technologies in the lighting industry. Ilumi uses the motto “Live Your Light” to make the point that we underestimate the impact of lighting design on individuals. Ilumi sells a number of products for consumers and companies that allows individuals to tailor their lighting environment to their own specific biological rhythms and reactions to light. Cassini Nazir brings in the idea of “Designing the Mundane” that points out that many aspects of our life can be designed but are often neglected. Steinmetz ends with the most unexpected customer Ilumi has had: a chicken farmer who wanted to design the lighting to  maximize egg laying --- and indeed the they worked using the ‘sunrise’ bulb to wake the chickens up earlier and the Circadian lightbulb to extend the egg laying period  .

**Comment by coreysmart92** [comment]
Okay. I will begin the forms for that podcast.
Close: when new podcast form is completed and submitted.
(2/22/16)

**Comment by coreysmart92** [comment]
This podcast is scheduled to publish 4/20/16
Close: When published.

**Comment by coreysmart92** [comment]
Closing: the description has been updated and the podcast is scheduled to publish
