### ISSUE TITLE
archive two channels

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#469]
ashton

i have contacted david marlett the producer of the cinemersia and crowdfudning channels

please go ahead and move them to the new archive page of inactive channels
on creative disturbance

we arent expecting any new podcasts for these channels

thanks

roger

**Comment by amb141330** [comment]
Reassigning to Dylan. 

@dylanorgeron You can get to this when you have time, I know you have more important things to work on right now. Put this on hold until you have an opportunity.

**Comment by coreysmart92** [comment]
We need to Archive Old channels so that we know what channels are active or dead. This way we know which producers to ask for podcast submission.

**Comment by cassininazir** [comment]
The channels that need archiving are:
- Adventures in Crowdfunding
- Cinemersia

When a podcast is archived, it should:
1. Say on the webpage that this channel is open for a new producer. Please contact feedback@creativedisturbance.org. 
2. Be featured at the bottom of the [Disturbances](http://creativedisturbance.org/disturbances/) page under the heading "Archived".

**Comment by cassininazir** [comment]
@dylanorgeron raising the priority of this. Please schedule in to fix.

**Comment by dylanorgeron** [comment]
![image](https://cloud.githubusercontent.com/assets/6401465/14446025/5997a948-0017-11e6-92b7-9a2d5da502a7.png)
having issues with accessing the content types

**Comment by cassininazir** [comment]
Login with the main CD password info. Check the main password doc in Google Drive for specifics.

**Comment by dylanorgeron** [comment]
Podcasts can now be archived via the 'archive' checkbox on the channel's page.

![image](https://cloud.githubusercontent.com/assets/6401465/15156093/08de7d56-16ab-11e6-9d86-5acd3b98072c.png)

A list of archived channels can be found from the [Disturbances](http://creativedisturbance.org/disturbances/) page.

![image](https://cloud.githubusercontent.com/assets/6401465/15156128/31bccb38-16ab-11e6-8dd3-022f8054703c.png)

**Comment by rmalina** [comment]
ashton hal
now that dylan has the archiving function going
can you start archiving inactive channels

but on each channel can you get my ok on each
channel individually

and once archived can you make sure the producer of the
archived channel is emailed and told where their archived
channel can now be found
thanks

roger

Roger F Malina
is in  Dallas 1-510-853-2007

**Comment by rmalina** [comment]
Additionally, do let them know that their podcasts will continue to be available on the website and also through iTunes/Stitcher or their favorite podcast app.

Cassini Nazir

Clinical Associate Professor, School of Arts, Technology, and Emerging Communication
Director of Design and Research, ArtSciLab
The University of Texas at Dallas

## 

From: <leonardo.isast@gmail.com<mailto:leonardo.isast@gmail.com>> on behalf of roger malina <rmalina@alum.mit.edu<mailto:rmalina@alum.mit.edu>>
Date: Tuesday, May 10, 2016 at 1:16 PM
To: creativedisturbance/podcasts <reply@reply.github.com<mailto:reply@reply.github.com>>, Ashton Brillante <ashtonbrillante@gmail.com<mailto:ashtonbrillante@gmail.com>>, Hal Clark <hclark55@gmail.com<mailto:hclark55@gmail.com>>, Cassini Nazir <cassini@utdallas.edu<mailto:cassini@utdallas.edu>>
Cc: creativedisturbance/podcasts <podcasts@noreply.github.com<mailto:podcasts@noreply.github.com>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: Re: [creativedisturbance/podcasts] archive two channels (#469)

ashton hal
now that dylan has the archiving function going
can you start archiving inactive channels

but on each channel can you get my ok on each
channel individually

and once archived can you make sure the producer of the
archived channel is emailed and told where their archived
channel can now be found
thanks

roger

Roger F Malina
is in  Dallas 1-510-853-2007

On Tue, May 10, 2016 at 12:32 PM, Dylan Orgeron <notifications@github.com<mailto:notifications@github.com>> wrote:

Podcasts can now be archived via the 'archive' checkbox on the channel's page.

[image]https://cloud.githubusercontent.com/assets/6401465/15156093/08de7d56-16ab-11e6-9d86-5acd3b98072c.png

A list of archived channels can be found from the Disturbanceshttp://creativedisturbance.org/disturbances/ page.

[image]https://cloud.githubusercontent.com/assets/6401465/15156128/31bccb38-16ab-11e6-8dd3-022f8054703c.png
