### ISSUE TITLE
Yvan - Complete Post Mortem by May 8

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#47]
https://docs.google.com/forms/d/1sH6ODmAciiw5xkyFaAKsSxrVpEWTjUNZMPUEfWQGz4w/viewform

**Comment by coreysmart92** [comment]
@yvantina Could you please complete this ASAP.

Close when you have submitted you Post Mortem.

**Comment by yvantina** [comment]
@coreysmart92 Hey Corey I've already competed mine you should have received it..don't know what happened..

**Comment by yvantina** [comment]
Closed
