### ISSUE TITLE
strange downloads-have we been hacked

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#470]
ashton
we just had 300 podcasts downloaded today
and its strange
almost each of our podcasts was downloaded once

none more than 15 

i wonder if we have been hacked or is this a bot
check with cassini

roger

**Comment by amb141330** [comment]
I don't have the slightest clue as to how to check for that. I'm sending @cassininazir an email now.

**Comment by cassininazir** [comment]
This may be related: From the recording Mac station in the lab I subscribed to Creative Disturbance from within iTunes. It downloads a certain amount of recent podcasts but not sure how far back it goes. That's one new "user". 

Also, there may be new subscribers from the Leadership Richardson tour from Friday. A few people were interested in the podcasts and asked for the website before the tour ended. 

![screen shot 2016-02-15 at 12 06 41 pm](https://cloud.githubusercontent.com/assets/1661430/13056644/2b8293c2-d3dc-11e5-9bf5-d58ea3f53657.png)

**Comment by amb141330** [comment]
This is no longer, seemingly, an issue. Closing this.
