### ISSUE TITLE
Future mind podcast

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#471]
Roger, pour rappel
un podcast avec Tom Ray ?

---------- Forwarded message ----------
From: Yvan Tina yvantina@gmail.com
Date: 2016-01-02 16:55 GMT-06:00
Subject: Re: tom ray

2016-01-02 16:38 GMT-06:00 roger malina rmalina@alum.mit.edu:

```
yvan
tu te reapple de tom ray de tierra en a life ?

regarde ce cu'il fait maintenant

http://life.ou.edu/pubs/FutureMinds.pdf

wow

http://life.ou.edu/pubs/#Mind

--
Roger F Malina
is in Paris
my cell 33-6-80-45-94-47 
```

**Comment by amb141330** [comment]
No movement on this issue. Closing to clean up the GitHub
