### ISSUE TITLE
new podcasts for the back log !!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#472]
So i've been trying to submit new forms without success again.. not sure if this has something to do with my computer though.. anyway, i've uploaded some new podcasts on Box.com at this address https://utdallas.app.box.com/files/0/f/6542663709/Yvan_podcasts 
Not all the files are in Box and you may want to check the folder in the ArtSciLab desktop
You will schedule them at your convenience but please respect the following guidelines for order of release, as some topics might seem redundant or anachonic if not put in the right way..

For Meta-Life 
1- starts with "De l'amitié" (French podcasts, episodes 1 and 2 with Dominique Lestel)
2- The Semi-Living Perceptions of life (TC&A) episode 1
3- (untitled TC&A) episode 2, not already in Box but will be uploaded soon
4- A Theater of Cruelty (TC&A) episode 3
5- Adam Zaretsky, episode 1, not already in Box but will be uploaded soon (comes with video)
6- Adam Zaretsky, episode 2,  not already in Box but will be uploaded soon (comes with video)
7- Adam Zaretsky, episode 3,  not already in Box but will be uploaded soon (comes with video)
8- Jens Hauser-Yvan (English), episode 1,  not in Box but you can find them on the ArtSciLab Mac desktop
9- Jens Hauser-Danielle Aviles (English), episode 2,  not in Box but you can find them on the ArtSciLab Mac desktop
10- Jens Hauser-Joshua/Alex-Garcia (English), episode 3,  not in Box but you can find them on the ArtSciLab Mac desktop
11- Jens Hauser-Yvan (French), episode 4,  not in Box but you can find them on the ArtSciLab Mac desktop

For Virtual Africa
1- Being a Young Designer in Cairo (please remove "today" from the title)
2- A conversation on Afrofuturism with Tobias Van Veen (Please change the title)
3- Olenkule podcast, not already in Box but will be uploaded soon

For Sound and Data and the Bold Roast channels, podcast with Sruthi and Anvit (comes with video)
1- Please see the Sonification folder (this may go asap as it goes along with this recent announcement http://www.utdallas.edu/news/2016/2/12-31902_Collaborative-Minds-Bringing-Sounds-to-Brain-Data-_story-wide.html )

For Bold roast and Voices from the Crowd
2- A song for the Absentees

Adjust them to your needs but please again respect the order of publication, as some of them have been recorded in October and should appear before the most recent ones.. More soon
Thank you !

yvan

**Comment by cassininazir** [comment]
@yvantina can you discuss with @dylanorgeron. Will need more details on the issue.

**Comment by yvantina** [comment]
@dylanorgeron Meeting scheduled on Tuesday, Feb 16 12-12pm

**Comment by yvantina** [comment]
Files seem to be heavier than what wordpress can support_ please find them into Box.com
will save the forms without the audio file hoping that our sound team can take it from there and manage with Box

**Comment by yvantina** [comment]
Being a Young Designer in Cairo - forms saved - Please go ahead and publish
Scales of Life (art) uploaded in Box - forms not already submitted

**Comment by amb141330** [comment]
Will continue to leave this open until all podcasts have been dealt with.

**Comment by amb141330** [comment]
Yvan,

We currently have the TC&A podcasts all scheduled to be published, is there any others you'd like to give priority to? Or any of the ones you said are "coming soon" that you have for us?

**Comment by yvantina** [comment]
Will upload 3 new podcasts tonight - all Meta-Life - so am just concerned about your requirements..Ideally I would like those new podcasts (and their videos) to go as soon as possible
These podcasts with Adam Zaretsky have been purposely recorded with a video file cause I thought that would be part of our experiments, but I've been confused with the recent episode with Ashton and Sruthi's podcast..

**Comment by rmalina** [comment]
ashton
per our discussions we do not give priority to podcasts
exct non local produces and new women voices

do not give priority to yvan's

yvan if you have a real deadline thats different

ashton- are you now sending emails out to the producers
the focus needs to be on publishing podcasts from non local
producers-turkish-portuguese etc

roger

On Mon, Apr 4, 2016 at 12:22 PM, yvantina notifications@github.com wrote:

> Will upload 3 new podcasts tonight - all Meta-Life - so am just concerned
> about your requirements..Ideally I would like those new podcasts (and their
> videos) to go as soon as possible
> These podcasts with Adam Zaretsky have been purposely recorded with a
> video file cause I thought that would be part of our experiments, but I've
> been confused with the recent episode with Ashton and Sruthi's podcast..
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/472#issuecomment-205403461

## 

Roger F Malina
is in  Dallas 1-510-853-2007

COME TO OUR CREATIVE DISTURBANCE YURI'S NIGHT PARTY
APRIL 13
FREE TICKETS, BRING YOUR FRIENDS
Wizard's Sports Cafe - 747 S Central Expy, Richardson, TX 75080

https://www.eventbrite.com/e/yuris-night-with-creative-disturbance-tickets-22806282204

**Comment by yvantina** [comment]
@amb141330 The three podcasts with Adam Zaretsky have been uploaded to Box  -seems still unable to correctly proceed on the website -- though the forms are filled out and saved. Just need to be published now.. https://utdallas.app.box.com/files/0/f/8287272293/Yvan__Adam_Zaretsky 
it goes this way -- (1) "what's so sexy...." ; (2) "Curie's children..."; (3) "We are wild poetry..."
they both have their complementary videos to go along with as for http://creativedisturbance.org/podcast/the-willful-marionette-eng/-- will close this issue when the Jens podcast are scheduled and/or published, please let me know  - thank you

**Comment by yvantina** [comment]
@amb141330 
podcasts remaining to be published

8- Jens Hauser-Yvan (English), episode 1, not in Box but you can find them on the ArtSciLab Mac desktop
9- Jens Hauser-Danielle Aviles (English), episode 2, not in Box but you can find them on the ArtSciLab Mac desktop
10- Jens Hauser-Joshua/Alex-Garcia (English), episode 3, not in Box but you can find them on the ArtSciLab Mac desktop
11- Jens Hauser-Yvan (French), episode 4, not in Box but you can find them on the ArtSciLab Mac desktop

**Comment by yvantina** [comment]
@halclark @coreysmart92 @amb141330 see how old is this ! i wrote a note a few months ago and post-it on the desktop. I thought you guys took care of this since then.. now am not sure anymore if they've not been deleted or moved somewhere else by mistake..

**Comment by amb141330** [comment]
We took care of everything on box. It's not wise to leave podcasts laying around on the desktop. We keep them on box so that we have access to them from anywhere. Sticky notes are very easily moved or discarded. I will try to find them regardless and give you an update on Wednesday.

**Comment by yvantina** [comment]
Okay no problem but back in the days (when we just set up the sound station in the lab, that was the way we did) we deleted the dropbox account. Box was a suggestion of mine, or started with my podcasts for metalife and Expucu's roundtables. Anyway. I wrote the sticky notes in March or April after a watering hole session, Corey told me would take care of this so I thought they've been uploaded/edited but never heard from him/you afterwards..

**Comment by amb141330** [comment]
I found them on the desktop. I'm sorry for this happening. If you spoke to Corey about it I wasn't aware. I had dealt with all the ones on the box and didn't realize there was more on the desktop.

I have all 4 Jens hauser ones and will add them to the list.

Again, sorry Yvan.

**Comment by yvantina** [comment]
No worries.. I can't hold you responsible for anything. There's just a need for more communication/coordination between us.. I mean within the lab and between the producers/voices/etc

**Comment by ritwikjk** [comment]
@yvantina we'll handle this. how many of the above have been published?

**Comment by OskarOlssonCD** [comment]
@yvantina Can you upload the ones that aren't published yet to a Box folder so I can get working on them? I'll make this a priority. Thanks for your patience as we get this sorted out!

**Comment by OskarOlssonCD** [comment]
Completed podcasts are in bold. @ritwikjk 

**1- starts with "De l'amitié" (French podcasts, episodes 1 and 2 with Dominique Lestel)**

2- The Semi-Living Perceptions of life (TC&A) episode 1 _???_

3- (untitled TC&A) episode 2, not already in Box but will be uploaded soon _???_

**4- A Theater of Cruelty (TC&A) episode 3**

**5- Adam Zaretsky, episode 1, not already in Box but will be uploaded soon (comes with video)
6- Adam Zaretsky, episode 2, not already in Box but will be uploaded soon (comes with video)
7- Adam Zaretsky, episode 3, not already in Box but will be uploaded soon (comes with video)**
**(_What's so sexy with the biological?_, _Curie’s Children and the Biological Exuberance [ENG]_, _We are Wild Poetry: Hubris, De-Extinction and Speculative Art [ENG]_)**

**8- Jens Hauser-Yvan (English), episode 1, not in Box but you can find them on the ArtSciLab Mac desktop
9- Jens Hauser-Danielle Aviles (English), episode 2, not in Box but you can find them on the ArtSciLab Mac desktop
10- Jens Hauser-Joshua/Alex-Garcia (English), episode 3, not in Box but you can find them on the ArtSciLab Mac desktop
11- Jens Hauser-Yvan (French), episode 4, not in Box but you can find them on the ArtSciLab Mac desktop**

**Comment by yvantina** [comment]
2- The Semi-Living Perceptions of life (TC&A) episode 1 ??? completed
https://creativedisturbance.org/podcast/mechanisms-and-abstractions-of-life-eng/

3- (untitled TC&A) episode 2, not already in Box but will be uploaded soon ??? completed
https://creativedisturbance.org/podcast/scales-of-life-in-art-eng/

**Comment by OskarOlssonCD** [comment]
@ritwikjk The only one of these that isn't uploaded is the Olenkule podcast.

**Comment by yvantina** [comment]
@OskarOlssonCD @ritwikjk I have actually lost this file when I moved from the States.. Please discard this podcast, it wasn't the best interview record anyway in my memories... thanks.
