### ISSUE TITLE
wednesday skype for turkish channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#473]
ashton corey

which one of you will be leading the setting up the turkish channel
we have a skype
17th of February, Wednesday, 1 Pm dallas 2 pm NYC 9pm Istanbul-Izmir, is fine for the Turkish team.
Looking forward to skype-talk!

with the team and you need to sit in the skyp
corey or ashton-whichever one of you is lead on the new turkish channel

and you need to send them instructions on setting up a channel

roger
@coreysmart92

**Comment by coreysmart92** [comment]
Closing: The meeting went well and I will open individual Github issues for all task pertaining to that meeting.
(2/22/26)
