### ISSUE TITLE
Artwork for No Where Else Channel

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#474]
_Reference from Ashton below:_

Hello Mahsoo Salimi,

My name is Ashton Brillante and I am the project manager for Creative Disturbance. I'll be in charge of making sure we get your channel up and running as soon as possible.

It seems you've already filled out all the required forms, now we'll just need to produce a logo for the channel. I've CC'd one of our designers, Lina Moon, on here for you to correspond with her in regards to the artwork.

You're welcome to go ahead and submit your first podcast and we will upload it in conjunction with the channel's publication. 

Do you plan on editing your podcasts before you send them to us? We have three sound designers, including myself, that are able to edit podcasts for you if you send them to us. 

The other thing we like to include is a little "bumper" or "stinger" at the beginning and ends of our podcasts. We are happy to make one of these specifically for your channel, but perhaps you already have one or have input as to what you would like it to sound like?

Let me know!

Thank you and welcome to Creative Disturbance,

Ashton Brillante

**Comment by linamoon** [comment]
@linamoon to reply to Mahsoo once I get channel description for @amb141330.

**Comment by yvantina** [comment]
FYI
---------- Forwarded message ----------
From: Mahsoo Salimi salimi@sfu.ca
Date: 2016-02-15 14:06 GMT-06:00
Subject: Re: No Where Else Channel for Creative Disturbance
To: Ashton Brillante ashtonbrillante@gmail.com
Cc: Yvan Tina yvantina@gmail.com, Lina Moon jmoon12@gmail.com, Diane Gromala gromala@sfu.ca

Dear Ashton,

Thank you very much, I have sent the logo for our channel before,
but also attached it again here.

We would record and edit our podcasts but would be great if you could
make some final edit as it needed.

I need to double check with Dr. Gromala for the "bumper" or "stinger" at the
beginning and ends of podcasts that you mentioned and will post you ASAP.

Thanks again and please let me know if there is anything else.

P.S: our channel name is NOWHERE ELSE (all capital letter).

Bests,
Mahsoo

![nowhere_else_logo](https://cloud.githubusercontent.com/assets/10967939/13063202/2a48cd30-d40b-11e5-8036-b60a27f87a7c.jpg)

**Comment by linamoon** [comment]
Artwork has been received and placed in Google Drive - closing issue.
