### ISSUE TITLE
near term priority= process improvement on meeting goal for 3 podcasts a week

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#477]
folks

ashton-here are the notes from todays meeting=please make sure these are implemented

we failed to meet our schedule for a podcast this morning- very disappointing

given that we failed to meet our goal of three podcasts a week- none went up this morning- we decided that all work will focus on 

a) getting the three up this week 

b)  by next monday have uploaded the podcasts for the forthcoming two weeks -up loaded on libysn before the monday meeting 

c) if future no significant work will be done on any tasks until the next two weeks of podcasts are loaded on libsyn=  so this week the team will focus on getting three up this week and the next six into libsyn

we discussed a number of process improvements

a) change the system so the sound editor and producer can edit the forms- ie the producer submits the podcast with beginning of the forms and the editor can complete the forms
b) sound editors will more all podcasts in drop box and move them into box and start a form on each- and ask the producer to complete the forms-then we close drop box for podcasts
c) experimental is supposed to go up today MAKE SURE IT DOES
d) the turkish skype is wednesday at 1- corey will sit it if felipe oks it

next monday - when we open the monday meeting we expect that the following two weeks of podcasts have been uploaded into libsyn= 

we all agreed on the goals for the semester based on the sound team;s proposal of reducing from 5 a week to 3 podcasts published a week

please make sure that we all meet our commitment to achieve the goals that we set for this semester

and if you have trouble meeting any goal- analyse the problem and suggest improvements to the process

roger
@halclark @coreysmart92 @cassininazir

**Comment by amb141330** [comment]
We have made sure to be ready for this Monday's meeting. Everything else should be sorted out. We did make a post about Experimental on social media and on the blog.
