### ISSUE TITLE
stats about podcasts for producers

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#478]
ashton

can you tell these producers how they access stats about
the podcasts

if these producers dont know -the others probably dont
either ! tell them all

roger

Ana Rita Fonseca
3:17 PM (3 minutes ago)

to roger, Sam, jmoon12, Patrícia, Yvan 
Thanks!!

i can't remember about this
but can we access statistics about the podcasts?

just let us know if you need anything from us

:)

arita

**Comment by amb141330** [comment]
Are you refering to the overall stats at creativedisturbance.org/stats ? or something else. I don't believe we can give them access to the Libsyn stats

**Comment by rmalina** [comment]
i think each producer would like to know the stats on their channel and
podcasts
roger

On Mon, Feb 22, 2016 at 10:54 AM, amb141330 notifications@github.com
wrote:

> Are you refering to the overall stats at creativedisturbance.org/stats ?
> or something else. I don't believe we can give them access to the Libsyn
> stats
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/478#issuecomment-187263776
> .

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by amb141330** [comment]
We're working on making this a possibility since right now channel specific stats are not available for producers to view.

**Comment by amb141330** [comment]
Since there is not currently a way for producers to view channel specific stats I will assign this to @dylanorgeron. I know he's very busy so this is not an immediate priority and he can deal with this when he has an opportunity to do so.

**Comment by dylanorgeron** [comment]
fixed
