### ISSUE TITLE
Website Issue report from Australia

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#479]
@cassininazir @dylanorgeron 
Please read the facebook conversation between Laini Burton and myself below 
- it has to do with the 'Prosthetics Organs' podcast
  Thanks

Début de la conversation:
Hi Yvan, I wanted to say a personal thank you for the interview and for posting it online. However, the link doesn't work émoticône frown Not sure if its me though. Would you mind checking it please? This way I can share it amongst my colleagues and networks. Thanks again! Best wishes, Laini
2 février 19:14
Hi Laini. Thank you very much. Which link ? This one ? http://creativedisturbance.org/podcast/prosthetics-organs-and-wearable-art-eng/
Prosthetics Organs and Wearable Art [ENG]
Drawing on the work of Neri Oxman with her use of biomaterials and 3d printing for the design exploration Mushtari, and considering the popular examples of Henri Damon and Oscar Pistorius, Laini Burton investigates the use of prosthetic organs as wearable art in fashion industry and biodesign. From…
creativedisturbance.org
2 février 20:54
2 février 20:54
When I click the Download - an error comes up. This is the address: http://traffic.libsyn.com/createdisturb/ and the
oops. the Loading button doesn't load. Im no tech guru!? sorry to cause trouble
2 février 21:56
don;t understand.. check your browser or another computer..because it works fine with me 
don't know what to do.. it's the first time I receive an issue like this. never happened before
3 février 00:48
I will check with another browser Yvan. Thanks!
Hi Yvan, I tried Chrome - it said there was no file, Internet Explorer said 'This type of audio isn't supported', Firefox comes up with all the details but you can't listen (it says 0.00 minutes) and Safari doesn't load. Oh NO!
3 février 20:18
hmm.. that sucks ! 
am currently in D.C for a conference but will talk about this tomorrow when I get back to Dallas.. I'm afraid there's nothing I can do before then.. sorry about that, but I still don't understand because it used to work fine for everybody... weeiirdd..
3 février 21:21
Not a problem Yvan. Thanks so much. Looking forward to sharing it once its all up and running. I hope your conference is interesting and goes well!
17:21

Hi Yvan, have you had an opportunity to look at the link from the podcast? I have attached screen shots to show what happens when I click on it. On the hm page it never Loads even though it says Loading. Then when you click Download, the error message comes.
Fin de la conversation
## 

check out this website for more information on art, synthetic biology and a-life 
http://synthbioart.texashats.org/
and listen to our podcasts !
http://creativedisturbance.org/

**Comment by yvantina** [comment]
Hi Dylan
any update on this by chance ?
I need an answer for Laini
thank you

**Comment by dylanorgeron** [comment]
should now be working correctly

heres the link to the podcast file http://traffic.libsyn.com/createdisturb/Prosthetics_Organs_Wearable_Art_Podcast.mp3

**Comment by yvantina** [comment]
Thank you !
