### ISSUE TITLE
update the  Podcast Production Cheat Sheet (For Producers)

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#480]
corey
great that you started updating this
ashton and hal- please can you take an action to work with corey
to do a thorough update of this document

CD 2.2.2.7.2 Podcast Production Cheat Sheet (For Producers)

HAL- this is the place to put your WRITTEN evaluation criteria for evaluating
the quality of a podcast

roger
@halclark @amb141330

**Comment by halclark** [comment]
Roger,

I have began to write down the quality guidelines in 2.2.2.7.2. Ashton,
Corey, and myself will finish these guidelines in our skype meeting on
Sunday.

Thanks,
Hal

**Comment by coreysmart92** [comment]
I revised the Cheat Sheet for the Skype meeting Wednesday 2/17/16. I will now have Ashton and Hal review and suggest any changes.
Close: Once I have made the suggested revisions.
(2/22/16)

**Comment by coreysmart92** [comment]
Closing: [2.2.2.7.2 Podcast Production Cheat Sheet (for Producers)](https://docs.google.com/document/d/1mt7syWGCjQSIAZoBszFEg4Xc_YF3zaQ2o_1aW6dKrlc/edit)  is the up to date version of the podcast production process.
