### ISSUE TITLE
pending guest forms

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#481]
ashton

in the pending forms list there is a long list of guest forms that didnt get completed
can you make sure from now on that for every podcast the new guest from gets
filled out by the guest

roger

**Comment by amb141330** [comment]
We have determined that this will be a part of our process if the guests aren't the ones who fill out their information. We will, at the very least, supply them with that information one week in advance.

**Comment by rmalina** [comment]
please make sure the written document is updated
roger

On Mon, Feb 22, 2016 at 10:53 AM, amb141330 notifications@github.com
wrote:

> We have determined that this will be a part of our process if the guests
> aren't the ones who fill out their information. We will, at the very least,
> supply them with that information one week in advance.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/481#issuecomment-187262601
> .

## 

Roger F Malina
is in  Dallas
510-853-2007
