### ISSUE TITLE
form testing

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#483]
ashton
i had a hell of a time this morning filling in the on line form on a podcast

i think we need to do a quality control and have you and i fill a form out and file githubs on all the problems we run into

roger

**Comment by amb141330** [comment]
We'll begin having to do forms as a part of our new process. During that time we will keep track of bugs, issues, or possible processes that could be simplified.

**Comment by amb141330** [comment]
To my knowledge we haven't continued to run into form issues that haven't already been documented. This is something we'll continue to keep track of as we continue to use them.

So far the issues we were running into are file size, which you've now fixed, and finding a producer's channel in the podcast forms. I've already assigned Dylan a task to add the missing channels to the forms.

**Comment by amb141330** [comment]
Will open up new issues as we find parts of the forms that need adjusting.
