### ISSUE TITLE
second ellen levy podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#484]
hal
i filled out the form for ellen levy 2 -the file is called
Disorienting Procedures: Teaching Consciousness through Art_Science Practice

but now there are TWO files for ellen levy-the one you started and the one i finished
you need to remove i think the one you started

also i tried to add ellen levy as a voice- but it couldnt find her voice info so can YOU
add her as a voice using the guest information that is already on file

note you will need to remove ellen lev 1 as its now an early version of the final form i submitted which is under a different name

i would like to sit down with you and lets the two of us fill out a form completely and list
all the bugs we run into

anyway once you have ellen's ok you can schedule ellen levy 2 for a weeil after ellen levy 1
do not schedule them both in the same week

roger

**Comment by halclark** [comment]
Podcast up.
