### ISSUE TITLE
Create a "Creative Disturbers" Page

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#489]
Create a "Creative Disturbers" Page similar to the "Meet the Team" Page. Where a viewer can go and learn more about the producer and what they are doing.

**Comment by rmalina** [comment]
the page , with all the creative disturbers ,should also be up on the TEAM
page under ABOUT

we now have 7 students that need to be featured
roger

On Wed, Feb 24, 2016 at 11:23 AM, coreysmart92 notifications@github.com
wrote:

> Create a "Creative Disturbers" Page similar to the "Meet the Team" Page.
> Where a viewer can go and learn more about the producer and what they are
> doing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/489.

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by cassininazir** [comment]
@linamoon is implementing this in #492. Draft of page is linked from that item.
