### ISSUE TITLE
marie pier boucher for yuris night

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#490]
hal
can you schedule a skype between
marie pier boucher and me for yuris night

roger

will be glad to schedule a podcast for our uris night events
will contact you again
roger

On Thu, Jan 21, 2016 at 9:54 AM, Marie-Pier Boucher
boucher.mariep@gmail.com wrote:

> Dear Roger
> 
> Thanks for your message. No worries in regards to MIT. They are offering 2
> postdocs and it is unclear who is on the committee since the School of
> Humanities, Arts and Social Sciences joins several departments. I was just
> checking in case you knew someone in that School.
> 
> Kosmica Montreal would be this coming fall or next winter, depending on our
> funding possibilities. I am super excited about this. I am especially
> thrilled to have another opportunity to work with Nahum.
> 
> I would love to do a podcast with you! Thanks for the invitation! Would it
> be possible to record it in March? (after the storm of job applications and
> articles).
> 
> Thanks
> 
> Marie-Pier
> 
> On Wed, Jan 20, 2016 at 4:05 PM, roger malina leonardo.isast@gmail.com
> wrote:
> 
> > Marie pier
> > 
> > I really don’t have these kinds of contacts- the right people
> > 
> > Are the people on the hiring committee
> > 
> > Do you know who they are?
> > 
> > Re kosmica-fantastic-when would it be ?
> > 
> > I am recording podcasts for publication on creative disturbance
> > 
> > For yuris night in april- would you be interested in recording
> > 
> > A podcast with me
> > 
> > roger
> > 
> > From: roger malina [mailto:leonardo.isast@gmail.com]
> > Sent: Wednesday, January 20, 2016 2:57 PM
> > To: roger malina rmalina@alum.mit.edu
> > Subject: FW: question regarding MIT postdoc

**Comment by halclark** [comment]
@rmalina Emailed you and Marie 3/22 at 4:45 pm

**Comment by halclark** [comment]
Yuri's Night published.

**Comment by rmalina** [comment]
hal
this podcast was never recorded-it needs to be scheduled
roger

**Comment by cassininazir** [comment]
Closing this issue. Will open a new issue with all individuals to be contacted for Yuri's night.
