### ISSUE TITLE
Collect all grantees' emails and start email discussion thread

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#492]
- Introduce everyone to each other
- Future Africa and Virtual Africa-related items (talk to @yvantina about this)
- Create a page with everyone's information
  - Name 
  - Institution (if applicable)
  - Location
  - Bio 
  - link to channel(s)

**Comment by yvantina** [comment]
@linamoon @amb141330 Can we meet altogether this week, may 9 - 13 ?

**Comment by linamoon** [comment]
@yvantina yes that'd be a good idea -- what time works for you and
@amb141330? Pretty much free anytime this week.

**Comment by linamoon** [comment]
Meeting with Yvan and Ashton this Thurs 5/12.

**Comment by yvantina** [comment]
@linamoon @amb141330 We said Thursday 2-4 pm.

**Comment by linamoon** [comment]
Created initial page here: http://creativedisturbance.org/fellows/ (not yet shown on live site)

**Comment by cassininazir** [comment]
Excellent. A few changes:
-  Don't include the podcasts via "hardcoded" HTML, instead include via a script. This has the distinct possibility of becoming out of date quickly.
- Create a list with the titles of the locations (Portugal, Egypt, South Africa) and hyperlink them to their respective anchors further down on the page.
- Photos should link to the appropriate profile page, not a larger image. 
- Draft a short blurb inviting people to send an email to feedback@ if they'd like to be considered for an international grant.

**Comment by amb141330** [comment]
Reassigning since Lina is gone.

**Comment by yvantina** [comment]
Okay, please feel free to introduce me to the new design fellow when applicable
