### ISSUE TITLE
goal for monday

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#493]
team

we have a new problem developing
at last mondays meeting we agreed

a) four podcasts would be published this week
only two have been published which means i assume that
two more are going up before next monday
PLEASE MAKE SURE TWO MORE GO UP BEFORE MONDAY

the excel sheet indicates that have no podcasts ready to
be published as of now this week

b) that you would have 4 podcasts edited and loaded up for publication
to cover next week and the week after
THE EXCEL SHEET INDICATES THAT WE DONT HAVE 4 PODCASTS
EDITED AND READY FOR NEXT WEEK OR THE WEEK AFTER

to confirm what we agreed last monday

a) 4 go up this week
b) 4 go up next week
c) 4 go up the week after
d) then you can go back to the three a week

also i tried to look at the archive tab and could not find
the archive of what has been published over january and feb to date
i have been assuming that when a podcast is published its moved
from the to be published tab to the archived tab= please make sure
this is being done

if you need my help on sunday i am available

corey hal ahston- please make sure that the podcasts you are each
responsible for are ready for uploading on sunday to cover the
next two weeks as we agreed- so corey can load them on libsyn
for the next two weeks BEFORE the monday meeting

roger
@halclark @amb141330

**Comment by coreysmart92** [comment]
Closing: This was achieved 2/29/16. Although this is a on going issue we will review occasionally.
