### ISSUE TITLE
farsi podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#494]
ashton
for you to follow up wiht
roger

Tashakori, Fatemeh via cometmail.onmicrosoft.com 
12:19 PM (41 minutes ago)

to roger 
Dear Dr. Malina,

I'm gonna publish my podcast, who is the right person to contact with?
Have you changed previous process and official forms to submit a new podcast?
Best,
Fatima

Sent from my iPhone

**Comment by amb141330** [comment]
I have contacted her about this.

**Comment by amb141330** [comment]
Another issue is open regarding her podcasts, closing this one.
