### ISSUE TITLE
david mcphail podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#495]
corey
i completed the david mcphail guest form but i could not find the podcast or draft podcast form
PLEASE can you upload the podcast immediately and start a form so i can complete it
-please on fridays when we do the recording- lets start a podcast form there and then and put the podcast in it

please upload the podcast this weekend so i can complete the form for you

you can edit it later

roger

**Comment by coreysmart92** [comment]
Closing: I have started the form it is named Watering Hole 2/26/16. The voice form has already been submitted. When I edit the podcast I will make a temp title and description for you to review.

**Comment by rmalina** [comment]
corey
do not close this github item until its published
we have got to streamline the watering hole podcasts
it should be really easy to do this

roger

On Mon, Mar 7, 2016 at 11:32 AM, coreysmart92 notifications@github.com
wrote:

> Closing: I have started the form it is named Watering Hole 2/26/16. The
> voice form has already been submitted. When I edit the podcast I will make
> a temp title and description for you to review.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/495#issuecomment-193362020
> .

## 

Roger F Malina
is in  Dallas
510-853-2007
