### ISSUE TITLE
clean up pending podcast forms

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#496]
corey

the pending podcast forms include podcasts that have already been published
PLEASE try and keep up and when you ;publish a podcast remove the pending form-it makes it really diffifult to work when i go to pending forms to try and complete them and some of the podcasts are already published

do you have a check list for what has to be done when each podcast is published- i hope so-can you add to that check list" remove podcast from pending podcast forms" and move to published

when we do the process improvement review lets review your check list of what must be done when each podcast is loaded into libsyn for publication and lets make sure that check list is complete and being used

maybe you can discuss this at your sunday skype

thanks

roger

@amb141330

**Comment by amb141330** [comment]
duplicate issue. Closing and leaving the other, newer, issue open.
