### ISSUE TITLE
Tromble Podcast Forms

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#497]
@rmalina I have put up the incomplete form for the Tromble Podcast as a draft in creativedisturbance.com/forms . Can you finish this as soon as possible? Thank you!

**Comment by rmalina** [comment]
will do
roger

On Sun, Feb 28, 2016 at 5:12 PM, halclark notifications@github.com wrote:

> @rmalina https://github.com/rmalina I have put up the incomplete form
> for the Tromble Podcast as a draft in creativedisturbance.com/forms . Can
> you finish this as soon as possible? Thank you!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/497.

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by rmalina** [comment]
hal
i think this is a duplicate sound file for the aesthetics of complexity podcast form
i just filled out for ashton
roger
@amb141330

**Comment by halclark** [comment]
verified that it was a duplicate. Closing issue
