### ISSUE TITLE
Submit Bio - Ashton

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#5]
We will need short descriptions of your overall background and current majors to put on the team page for CD. 

Basic example: [ Your name ] is currently pursuing her ____ degree at UTD and is focusing on ____. She is interested in ___ with ___ and the effects it has on ___. Current qualifications? Future goals?

**Comment by amb141330** [comment]
Ashton Brillante is currently persuing his Arts and Technology degree at UTD and is focusing on sound design. He is interested in sound with virtual environments and the effects it has on the growing virtual reality market. His current qualifications are having been an audio and visual technician for two years and studying in the field of sound design. His future goals include becoming a composer, creating soundscapes for virtual environments, and recording music in a professional setting.
