### ISSUE TITLE
Setup instruction sheet for ZOOM recorder in ArtSciLab

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#50]
We should have at least 1 ZOOM recorder handy in the lab for quick podcast. Should have:
- Instruction sheet
- Batteries stocked
- Everything in good working order
- In a location we all know about

**Comment by porteriffic** [comment]
Check every Monday to make sure all equipment is available.

Also add:
- Sign in/out sheet

**Comment by cassininazir** [comment]
Poe Johnson will do podcast for Center for Values this week (beginning May 18).

**Comment by cassininazir** [comment]
@coreysmart92 will email Poe Johnson.

**Comment by coreysmart92** [comment]
@coreysmart92 I have created a newer issue for this problem #56.

Closing this issue for updates refer to #56.
