### ISSUE TITLE
improve instruction sheet for producers deposition podcasts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#502]
ahstpon
producers claerly need a written instruction sheet  not just the
email 

or else on the page with the forms you need instrucitons ?

if fatemeh couldnt figure it out nor can others

roger

From: Tashakori, Fatemeh
Sent: Tuesday, March 1, 2016 10:18 PM
To: Ashton Brillante
Subject: Re: Farsi Podcasts

Dear Ashton,

I have couple of questions about publishing a new podcast. Actually I followed the link that you sent me and I found "Submit a podcast" button, then  I clicked on it and I found one form to fill out.
I- is it the only form that I have to fill out? where I have to write biographical information and picture  of the artist that I have interviewed with? Is there any specific form for artist's information? (because in the old version of the podcast forms in the website there was a specific form for artist information)  

2- I am the producer of  the  Persian channel which is "Artisthinktive Iran: A Forum for Distinctive Thinking on Iranian Arts", but in the form under the title of "primary Channel" I cannot see my channel name, so What should I do? how can I determine that my podcast is for that specific channel?

3-In the form, there is one space to write website address, so  does it belong to the artist's website Address or producer's website address?

Thank you
Fatima

From: Ashton Brillante ashtonbrillante@gmail.com
Sent: Monday, February 29, 2016 11:29 AM
To: Tashakori, Fatemeh
Subject: Farsi Podcasts

Hey Fatemeh, 

My name is Ashton Brillante and I am the project manager for Creative Disturbance now. It's my understanding that you were looking to deposit more podcasts? 

Currently we are having producers submit podcasts along with their forms to this link:

http://creativedisturbance.org/forms/

You can simply click the "Submit a podcast" button and fill out the forms while uploading the podcast.

If the podcast file exceeds 64 mb our forms currently don't allow for anything more so you'll have to submit the podcast itself to the dropbox.

I'll send you an invitation to the dropbox now.

If you have any questions, concerns, or need any help let me know!

Thanks,

Ashton Brillante

**Comment by amb141330** [comment]
Corey can you read over this email and see where we need to make improvements in our forms? Then reassign to Dylan

**Comment by amb141330** [comment]
This issue was taken care of. The forms are now displaying all available channels.
