### ISSUE TITLE
equipment list update

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#503]
Sandy
There is an equipment list for my lab
And we are supposed to have an equipment
Sign out system

The equipment list needs to be put in the three
Ring folder-ashton can you do this ?
And then have a way in the 3 ring note book for
People to sign out equipment

And we need to work with sandy to make sure the
Equipment list is complete and we need to do an
Inventory before the end of the semester

Thanks

Roger

Ashton also please give sandy the current version of
The three ring notebook

**Comment by amb141330** [comment]
Indu is in charge of lab equipment. She has the full list that Sandy and I provided.
