### ISSUE TITLE
list of voices not alpabetical

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#504]
on the form for podcasts where you have to put in the voice the tab with the voices lists them in non alphabetical order, its almost impossible to find the name of the person
can you alphabetise the names
roger

ashton for you to coordinate with cassini/dylan

**Comment by amb141330** [comment]
Reassigning to Dylan for this issue since it has to do with the forms.

**Comment by cassininazir** [comment]
Page at http://creativedisturbance.org/forms/podcast

![screen shot 2016-03-07 at 1 48 54 pm](https://cloud.githubusercontent.com/assets/1661430/13581063/b46edd32-e46a-11e5-900b-2bd82841688d.png)

**Comment by dylanorgeron** [comment]
alphabetized voice list. theres also a search box at the top of the select menu that will autocomplete names for you.
