### ISSUE TITLE
Turkish Channel Art Work

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#505]
Lina could you create the Art Work for the Turkish Channel. We plan to publish this channel on 4/1/16.

**Comment by rmalina** [comment]
lina
consult with the turkish team before you start
roger

On Mon, Mar 7, 2016 at 11:43 AM, coreysmart92 notifications@github.com
wrote:

> Lina could you create the Art Work for the Turkish Channel. We plan to
> publish this channel on 4/1/16.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/505.

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by linamoon** [comment]
Let me know if there are any updates on getting information on what the channel is about @coreysmart92 @amb141330
