### ISSUE TITLE
Clear Podcasts from Dropbox (move to Box.com if needed)

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#507]

**Comment by coreysmart92** [comment]
This is in progress, I will remove each on the remaining audio files as they are published.
Close: When dropbox is cleared.

**Comment by coreysmart92** [comment]
Currently there are 8 podcasts still on Dropbox that still need to be published.
(4/11/16)
Close: When all files have been removed from Dropbox.

**Comment by coreysmart92** [comment]
Currently there are 6 podcast still on Dropbox that still need to be published. (5/16/16)
Close: When all files have been removed from Dropbox.

**Comment by rmalina** [comment]
great progress
when these 6 are edited and posted for subsequent publication
are there ANY other podcastss any where that have not been
edited yet ?

roger

Roger F Malina
is in  Colombia 1-510-853-2007

**Comment by coreysmart92** [comment]
Closing: All podcasts have been moved off of Dropbox and backed up on both Box and the Art Sci Lab computer.
(5/23/16)
