### ISSUE TITLE
Write Blog Post/Announcement for Yuri's Night

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#508]
This should include the invitation on EventBrite

**Comment by halclark** [comment]
@coreysmart92 what is the status on the Eventbrite invitations?

**Comment by rmalina** [comment]
i still havent been invited
roger

On Tue, Mar 22, 2016 at 4:38 PM, halclark notifications@github.com wrote:

> @coreysmart92 https://github.com/coreysmart92 what is the status on the
> Eventbrite invitations?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/508#issuecomment-200040692

## 

Roger F Malina
is in  Dallas
1-510-853-2007

**Comment by halclark** [comment]
Eventbrite invitations have been sent, blog post and splash page are live.
