### ISSUE TITLE
Podcast Research

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#51]
Look at the top 100 podcasts (there was another GitHub task with this open, see if you can find it, @amb141330) and review the stingers for best practices. 

Roger mentioned that Angela Lee (http://www.utdallas.edu/atec/artstechnology/lee/) would have some insight and may be able to help when we do a literature review.

**Comment by cassininazir** [comment]
Created a folder in _Google Drive_ > _Research_ > _Podcast Survey_ > _Literature Review_. I've added research papers that I've found on podcasts. Most of them pertain to podcasts in education. 

We need to conduct a thorough lit review. Let's discuss best ways to accomplish this.

**Comment by cassininazir** [comment]
A list of podcasts similar to the top 100 podcasts. Might be some gems in here:

http://www.producthunt.com/e/podcast-hunt

**Comment by rmalina** [comment]
we should learn from how they write good podast one sentence titles !

**Comment by amb141330** [comment]
Will continue when Cassini is back in Dallas

**Comment by cassininazir** [comment]
Let's get this started again. Can you develop a plan of action for this?

**Comment by cassininazir** [comment]
@amb141330 can you document this in Google Drive to make sure we capture? I think it would be good to do, but probably not until fall. Closing for now.
