### ISSUE TITLE
Add ORCID numbers to user profile pages and podcast guest page

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#510]
Many individuals register an [ORCID number](http://orcid.org/). Add the a field in the user registration field and podcast guest page to obtian this number.

**Comment by dylanorgeron** [comment]
ORCID numbers can now be submitted when registering for an account, creating a producer form, creating a guest form, and adding guests to a podcast on a podcast form.

Fun fact: I misread ORCID as ORCHID and got to do all sorts of fun troubleshooting at the end trying to fix the database.

**Comment by cassininazir** [comment]
Excellent. Let's change ORCHID to ORCID in the WordPress admin -- may also confuse others. 

<img width="482" alt="screen shot 2016-05-10 at 5 08 03 pm" src="https://cloud.githubusercontent.com/assets/1661430/15164048/cd1bb564-16d1-11e6-9416-9b331bb79758.png">

**Comment by dylanorgeron** [comment]
done
