### ISSUE TITLE
duplicate podcast of meredith tromble

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#511]
hal ashton
you need to talk

this morning ashton had asked me to complete the form for the meredith tromble podcast
http://creativedisturbance.org/forms/podcast/?id=188

meanwhile hal asked me to complete a form for the tromble podcast
http://creativedisturbance.org/forms/podcast/?id=180 

i think these two are the same podcast ?

please can you check and if they are the same -just use ashton's form

meanwhile i have completed the voice form for meredith tromble

roger
@halclark

**Comment by rmalina** [comment]
hal
i filled and filed a voice form for meredith tromble

hal ashton please make sure that i was right that there were two
copies of the tromble podcast

check to see if there are supposed to be two different podcasts

roger
@halclark @coreysmart92

**Comment by amb141330** [comment]
They were the same podcast, closing this issue.
