### ISSUE TITLE
improve working with producers

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#512]
hal ashton corey

since you are having trouble getting replies from some producers
please can you copy me on ALL emails to producers that you send ?
then i can apply pressure on the producers

note- I dont think i have ever received an email from any of you related to me channel
please can you treat me like any producer and send me the same kinds of emails you are sending to the other producers

thanks

roger
@coreysmart92 @halclark

**Comment by amb141330** [comment]
@halclark @coreysmart92 

Please make sure you're treating Roger just as you would any other producer in regards to his podcasts. We need to make sure he's being updated just as you would any other producer so the process stays consistent.

**Comment by amb141330** [comment]
As I've told both of you now, please copy Roger on any emails that deal with producers if you find yourself having trouble getting responses. I am closing this issue.
