### ISSUE TITLE
record podcast for yuri;s night

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#513]
ashton
i need someone to help me set up a skype podcast recording for yuri's nigh with 
supriya chakrabarti

can you assign thsi to the right person - 

roger

Dr. Chakrabarti:

It is with great pleasure that I send to you this letter on behalf of our president regarding the 2016 SPIE George W. Goddard Award.

**Comment by amb141330** [comment]
@halclark is in charge of Yuri's Night. Reassigning.

**Comment by halclark** [comment]
Yuri's Night has been published

**Comment by rmalina** [comment]
hal
the podcast with chakrabarti was never scheduled= this podcast still needs to be recorded
roger

**Comment by cassininazir** [comment]
Closing this item. Opening a new issue with all individuals to contact for Yuri's night.
