### ISSUE TITLE
raise money through patreon

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#514]
try raising money via patreon

lets discuss as part of the business plan discussion

Unrelated, but are you familiar with https://www.patreon.com/

I listen to Sam Harris' podcast regularly and he gets support for it through Patreon. Might be worth checking out if you're looking for other forms of support for CD.

Nick

**Comment by amb141330** [comment]
We need to setup a meeting for the business plan and funding. I think we should dedicate a session to this to brainstorm and assign ideas.

**Comment by amb141330** [comment]
We still need to have a meeting on the business plan and this is absolutely a good thing to discuss.

**Comment by amb141330** [comment]
We didn't get to this in our business meeting. We should have a second, follow up, meeting and have this be discussed.
