### ISSUE TITLE
F.U.Q podcast Alex Garcia Topete

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#515]
This podcast needs to be published by March 23rd - at the very latest
The file is currently on Box under ALEX_ROGER's folder. We didn't succeed to upload it with the podcast form. All forms , including the guest one, have been filed. 
Please edit out the moment when Alex couldn't remember Sandra's last name in the middle of the podcast
please assign this podcast to  sound editor
@yvantina

**Comment by amb141330** [comment]
@coreysmart92 Can you handle this one? Make sure it goes up this week since all the forms are filled if it didn't already go up.

**Comment by coreysmart92** [comment]
This podcast is scheduled and will publish 3/30/16.
Close: When published
