### ISSUE TITLE
new roots of curiosity podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#516]
ashton
not sure who is assigned to this podcast but can you have them email patiricia right
away to confirm the podcast arrived safely and will be edited as she requested
roger

Hi Creative Disturbed team,

I just submitted one more podcast (with neuroscientist Gil Costa)! 
If you can please have your sound team look at it, around minute 9 there is a construction noise outside, not sure if you prefer to remove it.

This will probably be the last podcast from the science-art Roots project participants series. Now we'll do more podcasts, with other art-science people, not necessarily involved in our project. And we'll do more advertising too!

Cheers,
## 

Patrícia A. Correia
Systems Neuroscience Laboratory
Champalimaud Centre for the Unknown
Av. Brasília, Doca de Pedrouços
1400-038 Lisboa, Portugal
(+351) 210480116
www.neuro.fchampalimaud.org

**Comment by amb141330** [comment]
I sent that email to Corey and it has been published already.
