### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#517]
there was a twitter today to a broken link

http://creativedisturbance.org/podcast/being-a-young-designer-in-cairo-eng/

roger

**Comment by yvantina** [comment]
Ashton, can you please help fix this issue before spring break ?
Nora is the grant recipient from Egypt and she has been waiting for this publication since November..
Thanks !

**Comment by yvantina** [comment]
Ashton, we're unable to publicize this on Facebook. It says the link is broken, even though the podcast works on the website but can't be redirected from social media. Nora just announced her collaboration with CD so it would have been nice to feature the podcast along with her post. Please Help ! Maybe Dylan can assist?

**Comment by amb141330** [comment]
I'm not sure how to fix this issue. Currently the link at the top of the page is working. Does this still need to be taken care of @yvantina ? 

The only issue I can imagine is if for some reason the link had a special character or accent over one of the letters. Those don't always translate to the link and causes those things to break.

**Comment by yvantina** [comment]
I mysteriously succeeded to post it on facebook two days ago - I close this issue
