### ISSUE TITLE
announce yuri's night party

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#518]
hey team
you have got to get the invitation out for the yuri's night party 
in the next couple of days- its a month to the party

PLEASE get the invite and eventbrite set up in next couple of days
roger
@halclark @coreysmart92

**Comment by rmalina** [comment]
the party is still not on the yuri nights web site
https://yurisnight.net/events/worldmap-2/
roger

**Comment by amb141330** [comment]
The party is on the website. I am waiting on the email list from Dylan to send out the email to everyone, including Kickstarter donors.

**Comment by cassininazir** [comment]
@amb141330 we'll need to do an announcement on our own blog as well about Yuri's night. 

Possible to send the email list in two sets (to give @dylanorgeron some time to get to you)?

**Comment by amb141330** [comment]
Email was sent out before April 1st.

**Comment by rmalina** [comment]
you need to keep pushing daily if you really want us to have a crowd
roger

On Mon, Apr 4, 2016 at 12:11 PM, amb141330 notifications@github.com wrote:

> Email was sent out before April 1st.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/518#issuecomment-205398362

## 

Roger F Malina
is in  Dallas 1-510-853-2007

COME TO OUR CREATIVE DISTURBANCE YURI'S NIGHT PARTY
APRIL 13
FREE TICKETS, BRING YOUR FRIENDS
Wizard's Sports Cafe - 747 S Central Expy, Richardson, TX 75080

https://www.eventbrite.com/e/yuris-night-with-creative-disturbance-tickets-22806282204

**Comment by amb141330** [comment]
Party happened already. Closing this issue.
