### ISSUE TITLE
Sonification podcast form

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#519]
The form for this podcast has been filled and saved
Please publish asap - the files are on Box.com - and do not forget to use the video that serves as a visualization of the experiment as Sruthi and Anvit kindly recorded it for us.
please assign to a sound editor
thanks

**Comment by amb141330** [comment]
Pretty sure this one was on the tracking sheet to be published, @coreysmart92 can you make sure this is taken care of properly? Or close it if it's no longer an issue?

**Comment by yvantina** [comment]
It has not been published already !! everything is on box.com - please include the video !!

**Comment by yvantina** [comment]
@coreysmart92  @amb141330 The video is missing !! Sruthi and Anvit have been asked to illustrate the podcast with a video they kindly sent us but which is not on the website.. Please share it ! Thanks

http://creativedisturbance.org/podcast/insight-into-the-sonification-projects-at-the-artscilab-eng/

**Comment by coreysmart92** [comment]
@yvantina previously the only way we have include a video is in the description is that acceptable?

**Comment by yvantina** [comment]
@coreysmart92 I don't understand. There's no link to the video so I don't see how it fits in the description. A few weeks ago we did this http://creativedisturbance.org/podcast/the-willful-marionette-eng/ and I thought this is the way we'll start experimenting new podcasts - if it is what is meant by included in the description then yes !!

**Comment by cassininazir** [comment]
@coreysmart92 if the video is hosted on YouTube or Vimeo you can copy the embed code into WordPress. If it's not hosted, I can upload for you to the main ATEC vimeo account.

**Comment by rmalina** [comment]
agreed
we do NOT host videos on creative disturbance
just link to where they are on vimeo or youtube
roger

On Mon, Mar 28, 2016 at 9:50 AM, Cassini Nazir notifications@github.com
wrote:

> @coreysmart92 https://github.com/coreysmart92 if the video is hosted on
> YouTube or Vimeo you can copy the embed code into WordPress. If it's not
> hosted, I can upload for you to the main ATEC vimeo account.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/519#issuecomment-202424632

## 

Roger F Malina
is in  Dallas
1-510-853-2007

**Comment by cassininazir** [comment]
@halclark can you please add the video to the page and close?

Its been uploaded to https://vimeo.com/165926172

**Comment by yvantina** [comment]
@cassininazir Cassini here's what the web page shows when you click the link : 
"Sorry, we couldn’t find that page. Sorry, there is no video here. Either it was deleted or it never existed in the first place. Such are the mysteries of the Internet."

**Comment by cassininazir** [comment]
Privacy settings were incorrect. Now fixed.

**Comment by yvantina** [comment]
thank you Cassini ! @halclark can you implement this on the podcast page ? Also there was another file that was the audio description of the video which was supposed to go along with it..

**Comment by halclark** [comment]
Video is linked on the podcast page, however, the video is not embedded onto the page. From my understanding, the link needs to be in a format like "https://player.vimeo.com/video/xxxx", for it to be embedded. Attempting to convert the given link to this format did not work.

**Comment by cassininazir** [comment]
Hit the share button on the video link (the paper airplane). It will give you the embed code.

**Comment by halclark** [comment]
Embed code not working for some reason. Neither is the format I used for
the last video that was embedded on "A 9 Year Old Dreams of Space" (
http://creativedisturbance.org/podcast/a-9-year-old-dreams-of-space/)

**Comment by yvantina** [comment]
closing this issue.. let us know if further information is needed !
