### ISSUE TITLE
Train Podcast Team on Website Functionality and Podcast Process

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#52]
@porteriffic, @kkondas making sure you're in on this. Let's setup time over the summer to get everyone trained on this. 
- Blog posts
- Create new channels
- Dropbox - create new folders, invite others
- Anything additional

**Comment by porteriffic** [comment]
Let's add this to the agenda for Monday's meeting @coreysmart92

**Comment by cassininazir** [comment]
Discuss with @anvit and @sayloo about this. Let's include @linamoon as well to bring her into loop.

**Comment by cassininazir** [comment]
@halclark, @coreysmart92 please make sure you do this by next meeting, May 25.

**Comment by coreysmart92** [comment]
Next Sound meeting have a tutorial. May 25

**Comment by cassininazir** [comment]
Who needs to be at this meeting @coreysmart92?

**Comment by coreysmart92** [comment]
@coreysmart92 @halclark @porteriffic @amb141330 @kkondas @cassininazir Need to be at the Sound team meeting Monday May 25, 2015.

**Comment by coreysmart92** [comment]
Due to weather. Tech tutorial is moved to 6/1/15.

**Comment by cassininazir** [comment]
This has happened, I believe. Can this be closed?

**Comment by cassininazir** [comment]
Checking in on this again, @halclark: can this be closed?
