### ISSUE TITLE
Aggregating Future Lab Africa

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#520]
@amb141330 @linamoon @rmalina @cassininazir 
Can you please work with Roger, Lina and myself for the aggregation of the Future Lab Africa project runs by Tegan Bristow and Jepchumba II - two recipients of the international grants ?
http://futurelabafrica.org/
If we succeed, this channel will be one of the Virtual Africa 'network of networks' as part of a syndication strategy (cf. Audiolats), meaning that to a certain extent I  may need to rename my own channel into something else - to avoid any confusion between the podcast channel and the whole project.. 
Please see with Roger whether or not we should contact them before they receive the money - which may help facilitate the process. Thanks !
Tegan - teganbristow@gmail.com  
Jepchumba - contact@jepchumba.com

**Comment by rmalina** [comment]
ashton
can you put this on your planning list for new channels-
i think thats the way to plan it

when is the next month with no new channel planned yet

roger

On Tue, Mar 8, 2016 at 6:02 PM, yvantina notifications@github.com wrote:

> @amb141330 https://github.com/amb141330 @linamoon
> https://github.com/linamoon @rmalina https://github.com/rmalina
> @cassininazir https://github.com/cassininazir
> Can you please work with Roger, Lina and myself for the aggregation of the
> Future Lab Africa project runs by Tegan Bristow and Jepchumba II - two
> recipients of the international grants ?
> http://futurelabafrica.org/
> If we succeed, this channel will be one of the Virtual Africa 'network of
> networks' as part of a syndication strategy (cf. Audiolats), meaning that
> to a certain extent I may need to rename my own channel into something else
> - to avoid any confusion between the podcast channel and the whole
>   project..
>   Please see with Roger whether or not we should contact them before they
>   receive the money - which may help facilitate the process. Thanks !
>   Tegan - teganbristow@gmail.com
> 
> Jepchumba - contact@jepchumba.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/520.

## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by amb141330** [comment]
I will start to work on this next week. I'll work with Yvan in contacting Jepchumba II and getting their podcasts up for collaboration in the way that we did for Human Impacts Institute

**Comment by amb141330** [comment]
Sending Yvan an email about this now so we can get this process started. Based on the channels we have in the works this one would be scheduled to go up in June.

**Comment by yvantina** [comment]
@amb141330 Ashton, can we work on that this week?

**Comment by yvantina** [comment]
@amb141330 How are we doing with these people?

**Comment by amb141330** [comment]
I just recently received a completed collaboration agreement from Jepchumba. Will start the process of uploading their podcasts to the website.

**Comment by amb141330** [comment]
https://creativedisturbance.wufoo.com/entries/creative-disturbance-collaboration-agreement/

**Comment by rmalina** [comment]
ashton
we need to modify these collaboration agreemens so
mit press has the rights to publish the podcasts on arteca
roger

Roger F Malina
is in Dallas
5108532007

**Comment by amb141330** [comment]
I know about this. I'm not sure who to get a modified agreement. Would you like me to email Chaz the current form and let him know what permissions we need so that he's able to adjust the forms?

Yvan had just asked that it get done soon and I met with Cassini about what to do. We decided to use the old forms for now.
