### ISSUE TITLE
broken links for voices

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#522]
broken links

when you click on the images of the voice in this channel
http://creativedisturbance.org/channel/virtual-africa/
the image doesnt link to the bio of the voice

ashton can you add this to the process improvement review

roger

**Comment by amb141330** [comment]
This is a part of the website improvement and absolutely a feature we should implement. Lets discuss today at the meeting.

**Comment by amb141330** [comment]
Talked to Dylan about this, he will take care of this ASAP
