### ISSUE TITLE
send apologies to unhappy voice paul vickers

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#523]
ashton
could you send an email of apologies to this podcast voice and
make sure the podcast is scheduled shortly

roger

On Wed, Mar 9, 2016 at 7:09 PM, Scot Gresham-Lancaster scotgl@gmail.com wrote:
So sorry for the delay. I submitted it to the creative disturbance team the day after we recorded it in early December and expected a much more immediate release. Let me talk to the team and get back to you. 
It really has been a while and it should have been online over a month ago.
rrr...

Scot Gresham-Lancaster ph +1 510-512-8344 ◯◦ ◦◯⃝⃝ ⃝ ◌◌⃝ ⃝ ◌⃝ ◌⃝ ◯○ ◦◌ ◌ ○ ◯◦ ◦◯⃝⃝ ⃝ ◌◌⃝ ⃝ ◌⃝ ◌⃝ ◯○ ◦◌ ◌ ○ ◦◌ ◌ ○ ◯◦ ◦◯⃝⃝ ⃝ ◌◌⃝ ⃝ ◌⃝ ◌⃝ ◯○ ◦ 
http://about.me/scotgl

CONFIDENTIALITY NOTICE: This electronic mail message and any attached files contain information intended for the exclusive use of the individual or entity to whom it is addressed and may contain information that is proprietary, privileged, confidential and/or exempt from disclosure under applicable law.  If you are not the intended recipient, you are hereby notified that any viewing, copying, disclosure or distribution of this information may be subject to legal restriction or sanction.  Please notify the sender, by electronic mail or telephone, of any unintended recipient and delete the original message without making any copies.

On Wed, Mar 9, 2016 at 9:33 AM, Paul Vickers paul.vickers@northumbria.ac.uk wrote:
Hi Scot

Any news on when the podcast is going live?

Cheers
## paul

Dr Paul Vickers BSc PhD CEng MIET FHEA CEH
Reader in Computer Science, Department of Computer Science & Digital Technologies

T:   +44 (0)191 243 7614
E:   paul.vickers@northumbria.ac.uk

Room 2.14, Pandon Building, Northumbria University, Newcastle upon Tyne, NE1 8ST, United Kingdom

Personal Profile: https://www.northumbria.ac.uk/about-us/our-staff/v/dr-paul-vickers/
Research:           http://computing.unn.ac.uk/staff/cgpv1
LinkedIn:             http://uk.linkedin.com/in/drpaulvickers
Twitter:                http://www.twitter.com/DrPaulVickers
Orcid:                  http://orcid.org/0000-0003-0963-5005 
EngCouncil/CharteredEngineerC.pdf ../Dropbox/CEH/CEH-LogoCropped.pdf

From: Scot Gresham-Lancaster scotgl@gmail.com
Date: Thursday, 17 December 2015 at 17:00
To: Paul Vickers paul.vickers@northumbria.ac.uk
Subject: Fwd: data art and data vis Fwd: Lisa Charlotte Rost · A world view

Begin forwarded message:

From: tim perkis tim@perkis.com
Subject: data art and data vis Fwd: Lisa Charlotte Rost · A world view
Date: December 17, 2015 at 1:12:33 AM CST
To: Scot Gresham-Lancaster scotgl@gmail.com, roger malina rmalina@alum.mit.edu
Paul,
Great talking with you. Let’s do part 2 soon. I will see if I can get on the other side of the 30 minute leash they have me on.

Thought you might find this link below of interest.

Have a great Holiday,
Scot

http://lisacharlotterost.github.io/
## 

Roger F Malina
is in  Dallas
510-853-2007

**Comment by amb141330** [comment]
We haven't seen this podcast from Scot, so I'm not sure what he's referring to. Will reassign to Hal to find this podcast and then will send apology email accordingly.

**Comment by cassininazir** [comment]
@coreysmart92 has forwarded @halclark the email. @halclark could please respond?

**Comment by halclark** [comment]
Have not been forwarded the email. Emailed Scot to check the status.

**Comment by halclark** [comment]
Podcast published.
