### ISSUE TITLE
voice names in excel tracking process improvement

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#524]
corey
i tried to see when some of the watering hole podcasts were scheduled but couldnt figure out which podcasts were there

can you always indicate int he form the name of the voice ?

i have added a row for the name of the voice to the excel sheet

meanwhile can you tell me when this one is scheduled

roger

corey
this is one you recorded
when do you think it can go up ?

roger

---------- Forwarded message ----------
From: Collin Steinmetz collin@ilumi.co
Date: Wed, Feb 24, 2016 at 6:17 PM
Subject: Re: thanks
To: Scot Gresham-Lancaster scotgl@gmail.com
Cc: roger malina rmalina@alum.mit.edu

Thanks for the opportunity gentlemen! It was a great experience and I'm looking forward to hearing the podcast!

Best, 

Collin Steinmetz
Sales & Marketing, ilumi
collin@ilumi.co - (469) 751-7501

Live your light! - www.ilumi.co

**Comment by coreysmart92** [comment]
I understand and am in the process of updating the tracking sheet. The podcast with Collin Steinmetz is scheduled for 4/13/16.
Close: when "The Lumen Life - Reexamining the Relationship Between People and Lighting Part 1 [ENG]" is published.
