### ISSUE TITLE
set up recording of yuri;s night podcast recording with clea waite

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#525]
ashton
can you track this in the weekly meetings
hal- would you be available to set this up and record it ?
roger
@halclark 
Clea T. Waite via alum.mit.edu 
8:45 PM (53 minutes ago)

to roger 
Hello Roger,

I would like to do a lunar podcast with you for Yuri's night. Can you give me
an idea of the length you want to do and perhaps some questions or what
you'd like to focus on so I can prepare?

Yesterday I discovered that they have fabulous studios over at the communication
school for doing podcasts, so I'd like to see if I can get in there to do the recording.
Great mics, quiet rooms. If we make a date, I'll see if I can reserve a room.

I look forward to it!

skype: cleawaite
phone: 917-952-6577 in Los Angeles

Best,

Clea

---

www.clea-t.de

> Date: Thu, 21 Jan 2016 21:32:44 -0600
> Subject: moon
> From: rmalina@alum.mit.edu
> To: cleawaite@hotmail.com; ctw@clea-t.de
> 
> clea
> just saw your posting of
> A Selenological History of Lunar Poetics
> 
> i am organising some podcasts in preparation for
> yuri's night on our creativedisturbance.org podcast
> platform with mit press
> 
> might you be willing to do a phone or skyped
> podcast recording with me ?

**Comment by amb141330** [comment]
Reassigned to @halclark since he is in charge of Yuri's Night

**Comment by halclark** [comment]
Yuri's Night published.

**Comment by rmalina** [comment]
hal
we need to re open this
no pocast was recorded with clea waite to my knowledge
roger

On Wed, Apr 13, 2016 at 2:23 PM, halclark notifications@github.com wrote:

> Yuri's Night published.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/525#issuecomment-209607875

## 

Roger F Malina
is in  Dallas 1-510-853-2007

**Comment by cassininazir** [comment]
Closing this item. Will open a new task with all of these individuals listed.
