### ISSUE TITLE
set up yuri's night recording with michael cicciardi

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#526]
hal
another podacst hal
another podcast to record and we can post the video on experimental "

roger

HI Roger!

Hope you are doing well. I have a short (8 minute 'biographical video poem') on the theme of 'The Future of Space Exploration' featuring a 9 year old boy named Jack that I (and he) would love to see be a part of Yuri's Night in Dallas (note: the video incorporates NASA/ESA/JPL/GSFC archival imagery)...and can be found here:
https://vimeo.com/135078384
A Dream of Space

image

A Dream of Space
View on vimeo.com
Preview by Yahoo

There is also a 2 min 30 second version of the video (submitted to/made for the upcoming OSIRIS-REX mission to Bennu), found here:
https://vimeo.com/157067014
A dream of space (version2)

image

 hal
another podcast to record and we can post the video on experimental "

roger
@amb141330 @coreysmart92 

A dream of space (version2)
View on vimeo.com
Preview by Yahoo

Both videos are as is (no HD versions due to issues with editing, sorry) but should look fine in a web stream.

Let me know if either fits your programming needs.

Thanks, Michael Ricciardi

**Comment by halclark** [comment]
@rmalina  Emailed you and Michael 3/22 at 4:30 pm.

**Comment by halclark** [comment]
Set up, recorded, and published.
