### ISSUE TITLE
set up new channel with celestia jo ann koh

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#527]
@linamoon 
ashton
i had a good skype with celestia- i think she is going to be great to work with- can you go ahead and coordinate with her to set up her channel and help train her to do the first podcasts ? 
will leave it to you- can you copy me on important emails

she will do podcasts in mandarin and english for sure

lina- maybe you can work with her for her logo ?

roger

**Comment by amb141330** [comment]
I've been in constant contact with Celestia. She has submitted her channel form and I am working on getting an email from her with ideas for a logo for Lina to take care of. Will close this issue because I have taken care of this process and talk to her regularly.
