### ISSUE TITLE
turkish team needs the several proposed stingers and bumpers

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#528]
corey
the turkish team are waiting for the several bumpers and stingers you were 
going to send theim

is hal makng them

have you been in touch with them for ideas of how the bumpers/stingers could
be made relevant to their channel ?

roger
@halclark 

Altug Akin
3:05 PM (7 minutes ago)

to Corey, roger, Charlotte 
Hey Roger,

Yes, they both have received the transfer.
And they have done their first interviews yesterday. 
I think what we need now is the music-sound pool from Corey, so that we can chose which ones to use in our series. Then, we will be able to put the pieces together.

Best,

altug

**Comment by coreysmart92** [comment]
Closing: I have sent them all perspective bumpers and the team has chosen a bumper for their channel.

**Comment by rmalina** [comment]
please confirm the channel will b e up by april 15
and please copy me on all emails to them

roger

On Mon, Apr 11, 2016 at 9:07 AM, coreysmart92 notifications@github.com
wrote:

> Closing: I have sent them all perspective bumpers and the team has chosen
> a bumper for their channel.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/528#issuecomment-208364380

## 

Roger F Malina
is in  Dallas 1-510-853-2007

COME TO OUR CREATIVE DISTURBANCE YURI'S NIGHT PARTY
APRIL 13
FREE TICKETS, BRING YOUR FRIENDS
Wizard's Sports Cafe - 747 S Central Expy, Richardson, TX 75080

https://www.eventbrite.com/e/yuris-night-with-creative-disturbance-tickets-22806282204
