### ISSUE TITLE
Setup Jabber

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#53]
From Brian's document:

After running the installer click the wrench icon and select "sign-on settings" and enter the following…

Internal Server vcsctl.utdallas.edu 
External Server: vcsxway.utdallas.edu
SIP Domain: vc.utdallas.edu

**Comment by cassininazir** [comment]
I haven't been able to get Jabber to work from my computer (with the settings and my NetID). Spoke with Brian Merlo briefly about this and we will test. Roll this out to the rest of the team before semester ends!

**Comment by cassininazir** [comment]
Sent Brian NetIDs for everyone on the ArtSciLab team. Will do another test run after we have access.

**Comment by porteriffic** [comment]
Go here to download: http://www.utdallas.edu/ir/downloads/

Go to Video Conferencing and select your OS.

**Comment by porteriffic** [comment]
Train members on how to use Jabber.

**Comment by coreysmart92** [comment]
How to get people accounts.

**Comment by coreysmart92** [comment]
This week everyone at least login.

**Comment by heiwanalady** [comment]
I was able to login!

**Comment by cassininazir** [comment]
Have written up a short doc, [CD 1.3 Working Remotely](https://docs.google.com/document/d/1NP-TLJ38swdwy3bZrvcW4umn3Dmy1q5y8RrTfkkNbuE/edit) that we can add to.
