### ISSUE TITLE
meeting this monday march 21 with roger ?

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#530]
hal
are you available to meet with me ahead of the creative disturbance meeting
this monday to go over our stuff that you are working on with me ?

roger

**Comment by halclark** [comment]
@rmalina , sorry I did not see this sooner. I am happy to meet with you this week or next week. Maybe before the Friday meeting? Or before next Mondays meeting? Let me know.

**Comment by halclark** [comment]
Met. Old issue.
