### ISSUE TITLE
yuri's night podcast recording on april 1 with murphy and marshall

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#532]
hal
you never replied to this email
back in february
these two speakers are available to do podcasts for
yuri's night on friday april 1- when they will be
speakers at our 2-4pm watering hole
maybe you can coordinate with corey
so we can get the two podcasts done and the
forms completed on april 1
@coreysmart92 @amb141330 

HAL please confirm you can organise these two podcasts for yuris night

roger
---------- Forwarded message ----------
From: roger malina leonardo.isast@gmail.com
Date: Sat, Feb 13, 2016 at 3:38 PM
Subject: RE: Moon Day celebration in DFW
To: Kenneth Murphy murphydyne@hotmail.com
Cc: "Clark, Theodore" thc140130@utdallas.edu

Hal

Can you help schedule a skype podcast recording

After mid march

roger

From: Kenneth Murphy [mailto:murphydyne@hotmail.com]
Sent: Friday, February 12, 2016 7:19 PM
To: roger malina rmalina@alum.mit.edu
Subject: RE: Moon Day celebration in DFW

Roger,

Je crois que je peux faire ça.  Je n'ai pas beaucoup d'experience avec Skype, mais j'apprends vite.

Ce qui est interessante, c'est que j'etais un des volontiers en 2001 en LA, la premiere annee de ces fetes, au centre des efforts.  Beaucoup du media visuel pour la piste de danse venait de ma collection.  Loretta (la creatrice de l'evenement) et moi, nous avons cree un Medaille du Dancing Snoopy pour les volontiers de qualite, une tradition qu'existe toujours.  C'etait un tel experience, et le capstone de mon stage ISU a Boeing Human Spaceflight & Engineering.

Quel date preferez-vous?  Le plus tard, le plus de details que j'aurais pour Moon Day 2016.

Ken

> Date: Thu, 11 Feb 2016 17:12:19 -0600
> Subject: Re: Moon Day celebration in DFW
> From: rmalina@alum.mit.edu
> To: murphydyne@hotmail.com; hclark55@gmail.com
> 
> ken
> 
> would you be willing to record a podcast with me over
> skype before yuris night april 13
> 
> we will publish it on our podcast platform creative disturbance
> www.creativedisturbance.org
> 
> they are 15 minutes long and we can talk about and publicise
> your moon day event
> 
> hal clarke is the sound producer would would record this with
> us over skyp and can give you more details
> 
> it would take about 30 minutes total over skype
> 
> roger
> 
> ---------- Forwarded message ----------
> From: Kenneth Murphy murphydyne@hotmail.com
> Date: Tue, Feb 2, 2016 at 12:15 PM
> Subject: Moon Day celebration in DFW
> To: roger malina rmalina@alum.mit.edu
> 
> Dear Judge Marshall,
> 
> Salut! I was referred to you by Professor Roger Malina over at UTD
> during a recent conversation we had (partially en français) regarding
> the annual Moon Day event at the Frontiers of Flight Museum at Love
> Field in Dallas.
> 
> Moon Day is an annual event that celebrates space exploration (and
> STEM topics) on or about the anniversary of the first Moon landing.
> This year's event will be Saturday, July 16th at Frontiers of Flight.
> Notably, we have received approval for another live Uplink with the
> International Space Station this year.
> 
> Professor Malina suggested that you might have some interesting ideas
> for the event, given your association with IAA, and/or might have some
> useful local contacts. As the event organizer, I'm always looking for
> new content for the event, from speakers to exhibitors to
> informational materials about space topics. Our 1,600 visitors last
> year included lots of Girl Scouts and Boy Scouts, local engineers, and
> folks from as far away as Montana and Mexico. One of our ISS
> questioners even flew in from California for the opportunity to pose
> his question to an astronaut on orbit.
> 
> If you'd like to learn more about the event, I prepared a backgrounder
> that can be found at:
> http://thespacereview.com/article/2897/1 (which is how Professor
> Malina found me)
> 
> The Dallas Morning News coverage of last year's event can be found at:
> http://www.dallasnews.com/news/metro/20150718-at-frontiers-of-flight-museum-kids-reach-out-touch-space-station-crew.ece
> 
> And the local TV channel CW33 provided some coverage:
> http://cw33.com/2015/07/18/moon-walkers-moon-day-at-frontiers-of-flight-museum/
> 
> The museum's webpage for the event, which includes a list of our 3
> dozen exhibitors, can be found at:
> http://www.flightmuseum.com/moon-day-2015/
> 
> In my view it's pretty cool that Dallas is the city that hosts Texas'
> largest annual space-themed event. As the creator and organizer of
> Moon Day, the museum gives me broad latitude in putting together the
> program each year, so any ideas you might have are likely to be
> useful.
> 
> I hope you find the event of interest, and look forward to speaking
> further with you on the topic.
> 
> Thank you for your consideration,
> 
> Ken Murphy
> Moon Day Organizer
> NASA Academy 2002
> ISU MSS 2001
## 

Roger F Malina
is in  Dallas
1-51-853-2007

**Comment by halclark** [comment]
@rmalina Emailed you and Kenneth 3/22 at 4:15 pm

**Comment by halclark** [comment]
There is another thread for this issue.
