### ISSUE TITLE
Email List

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#534]
@dylanorgeron 

Can you get me an email list for all the voices/producers on Creative Disturbance? We'll need this list for announcing Yuri's night and also looking into the future for other event announcements.

**Comment by amb141330** [comment]
Can you get this to me by the end of the weekend? I want to be able to notify everyone about Yuri's night with at least two weeks before the event.

**Comment by rmalina** [comment]
Ashton

where is party invite

roger

**Comment by amb141330** [comment]
Got the list and the party invites went out.
