### ISSUE TITLE
fatemeh's podcassts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#535]
please reply to fatemeh
it is a priority to publish her podcasts
please assign to right person

roger
 @amb141330 
Tashakori, Fatemeh via cometmail.onmicrosoft.com 
2:06 PM (2 hours ago)

to Ashton, roger 
 Dear Ashton,

Have you received my email?

Best, 
Fatima
<biography in English.docx>
<Biography in Farsi .docx>
<podcast describtion Kiomars, word.docx>
<كيومرث.m4a>
<Kiomars Moradi 1.JPG>

On Mar 13, 2016, at 7:10 PM, Ashton Brillante ashtonbrillante@gmail.com wrote:

Hey Fatemeh,

Just following up. Since you're having trouble uploading the podcasts to the forms, can you just send me the podcasts with their information through email?

Thanks,

Ashton

On Wed, Mar 9, 2016 at 11:41 AM, Ashton Brillante ashtonbrillante@gmail.com wrote:
Hey Fatemeh,

I'm working on getting your channel added to the forms. In the mean time you're welcome to just send the information and podcasts directly to me and I will get them published asap!

Once your channel is added to the forms I'd be happy to meet with you and go through the process.

Thanks,

Ashton

**Comment by amb141330** [comment]
I've already been in contact with Fatemeh and her podcast should be going up within the week. She said the second podcast wasn't quite ready but we are in constant contact.
