### ISSUE TITLE
urvi bhandari podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#539]
corey
i completed the podcast for today with urvi bandhari
a) you need to add the audio file
b) you need to complete with urvi her voice form with photo and also add it to the podcast form
c) contact her via lindked in as part of your job search

you have everything you need from me for this so please complete the process and schedule for publication as soon as possible-give it priority as a female voice
roger

**Comment by coreysmart92** [comment]
This podcast has been scheduled for 4/25/16.
Close: When podcast is published.

**Comment by rmalina** [comment]
please can you inform the voice of this
roger

On Mon, Apr 18, 2016 at 11:30 AM, coreysmart92 notifications@github.com
wrote:

> This podcast has been scheduled for 4/25/16.
> Close: When podcast is published.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/539#issuecomment-211459500

## 

Roger F Malina
is in  Dallas 1-510-853-2007
