### ISSUE TITLE
Marco Buongiorno Nardelli Podcast

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#54]
Quick-turnaround request from SGL (copied from email)

"I have uploaded Marco_Buongiorno_Nardelli.mp3 to the "needs editing" on dropbox for the "Sound and Data" channel on Creative Disturbance. Could you or someone on the team put the stinger that I made for my channel on the front of it and push it up to libsyn and CD fairly quickly. We have a request into IRCAM for a collaboration and need to get this podcast up right away if possible"

**Comment by porteriffic** [comment]
Already discussed at Monday's meeting. Roger doesn't want to push back other podcasts. Will discuss again on Monday.

**Comment by porteriffic** [comment]
Corey, did you email Scot about this?
