### ISSUE TITLE
error in publishing the same podcast twice

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#540]
corey
this is really not good

i think you have published the SAME PODCAST TWICE

please listen to these and tell me

http://creativedisturbance.org/podcast/helen-and-newton-eng/

http://creativedisturbance.org/podcast/helen-and-newton-harrison-on-the-role-of-artists-in-mitigating-climate-change-eng/ 

COREY if they are both the same =then replace the one this week with a different new podcast
and this does not count towards the 3 being published this week

ashton- please add this to the process improvement documents- here is an example of an error of publishing the same podcast twice- work with cassini and dylan to make sure this kind
of error doesnt happen again

if i am wrong and they are different apologies but i listed to the first few minutes of each
and they were identical

to all sound editors- when editing a podcast please double check the podcast has not already been published- all that takes is searching on the site with the name of the voice

roger
@amb141330 @dylanorgeron @halclark

**Comment by coreysmart92** [comment]
Closing: This has been fixed. The podcast was a duplicate and has been removed and replaced in the schedule.
