### ISSUE TITLE
turkish channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#542]
corey
please can you send a reply to this email with your responses to his questions
roger
@linamoon @amb141330 
Altug Akin
3:02 PM (21 minutes ago)

to roger, Lina, cenk, Sarphan, Corey 
Hey Roger and rest of the CD team in the US,

Today we recorded our first program, three of us talking about the series and our focus. It went really well, and it only needs to be final edited with bumper-stringers that we will received from Corey. 

Regarding the sound motifs or aspects that we can propose to Corey: Well, I really have difficulty in putting this in words, but maybe the name of the series (Key Words), our thematic areas (culture, arts, technology) and our key words (creativity, possibilities and Turkey) may give an idea. The tone of the series is rather casual, not a serious, cold, formal NPR style. Let me know if these help. 

To Lina, Cenk will provide a reply regarding the design aspects of the logo.

And if we can manage to put these all together, we're going to have first three to four episodes ready until Friday, the 1st of April.

Meanwhile, you can let us know, is there anything else we should consider (for instance, sth else for the series page?).

All the best,

Altug

**Comment by linamoon** [comment]
@rmalina Cenk contacted me today regarding the logo, and I'm planning to send him drafts in a few days. Letting you know @coreysmart92 and @amb141330 know.

**Comment by linamoon** [comment]
@linamoon has sent the turkish students the artwork draft -- waiting for response and approval.

**Comment by cassininazir** [comment]
Can you send me a copy.

**Comment by rmalina** [comment]
corey its really unacceptable the way you are working-i have asked you to copy me on your emails to the turkish team? have you replied to them-please copy me on all emails you send the turkish team
roger

**Comment by rmalina** [comment]
corey
this is really getting ridiculous and embarassing -please reply immediately to altug
have you done the bumpers
please start replying to altug's emails
and copy me
roger

---------- Forwarded message ----------
From: Altug Akin altugakin@gmail.com
Date: Fri, Apr 8, 2016 at 2:56 PM
Subject: Re: [OlatsNewsEnglish] FEAT/Future Emerging Art & Technology - Leonardo/Olats as outreach partner
To: roger malina rmalina@alum.mit.edu

good news roger, I'll have a look at it. Thanks for letting me know.

By the way, we're on hold as we're waiting for the bumpers-stringers from Corey. Can you please make sure he knows that we need them for making our podcasts ready? Otherwise, we'll have to postpone the launching date again.

And sorry for pushing this Roger.

best,

aa.

On Fri, Apr 8, 2016 at 4:12 PM, roger malina rmalina@alum.mit.edu wrote:

> altug
> FYI
> we have a turkish artist involved in a leonardo project
> roger
> 
> ---------- Forwarded message ----------
> From: Annick Bureaud abureaud@gmail.com
> Date: Fri, Apr 8, 2016 at 7:50 AM
> Subject: [OlatsNewsEnglish] FEAT/Future Emerging Art & Technology -
> Leonardo/Olats as outreach partner
> To: abureaud@gmail.com
> 
> Dear Friends,
> 
> Springs starts with a new project for Leonardo/Olats. We are
> thrilled to be the "Outreach Partner" of the FEAT project.
> 
> FEAT stands for Future Emerging Art & Technology. Co-funded
> by the Horizon 2020 Framework Programme of the European
> Union, it is lead by The Waag Society, Eutema and Youris.com
> and its aim is to bring together artists and FET/Future
> Emerging Technology projects.
> 
> Six artists and artist's teams have been chosen for
> residencies and paired with leading scientific research
> projects.
> The six funded artists and artist's teams in residence are
> Anna Dumitriu (UK), Ruth Jarman and Joe Gerhardt
> (Semiconductor, UK) Evelina Domnitch & Dimitry Gelfand
> (Belarus/Russia), Pinar Yoldas (Turkey), Špela Petrič & Miha
> Turšič (Slovenia) and Vicky Isley & Paul Smith
> (boredomeresearch, UK).
> 
> The paired teams are :
> 1.  Anna Dumitriu (UK) and MRG-Grammar – new strategies for
> deciphering gene regulation [http://www.mrg-grammar.eu]
> 2. Ruth Jarman & Joe Gerhardt (Semiconductor, UK) and
> QuProCS – quantum simulations and quantum computing
> [http://www.quprocs.eu/]
> 3. Evelina Domnitch & Dimitry Gelfand (Belarus/Russia) and
> RySQ – developing quantum simulators with Rydberg atoms
> [http://cordis.europa.eu/project/rcn/193719_en.html]
> 4. Pinar Yoldas (Turkey) and DIACAT – novel ways of
> catalytic CO2 conversion [http://www.diacat.eu/]
> 5. Špela Petrič & MihaTuršič (Slovenia) and INTERTWINE &
> Mango – future high power Exascale computing systems
> [http://www.intertwine-project.eu/]
> [http://www.mango-project.eu/]
> 6. Vicky Isley & Paul Smith (boredomeresearch, UK) and
> subcultron – underwater, self-learning swarm robotics
> [http://www.subcultron.eu/]
> 
> Full info on the project website:
> http://featart.eu/
> 
> Media contact: ester@waag.org | giuseppe.saija@youris.com |
> berghuber@eutema.com
> 
> ## 
> 
> ---
> 
> Annick Bureaud (abureaud@gmail.com)
> Tel mobile/cell : 33/(0)6 86 77 65 76
> Leonardo/Olats : http://www.olats.org
> Web : http://www.annickbureaud.net
> 
> ## Collectif Nunc : http://www.nunc.com
> 
> ---
> 
> Olatsnewse mailing list
> Olatsnewse@mit.edu
> http://mailman.mit.edu/mailman/listinfo/olatsnewse
> 
> ## 
> 
> Roger F Malina
> is in  Dallas 1-510-853-2007
> 
> COME TO OUR CREATIVE DISTURBANCE YURI'S NIGHT PARTY
> APRIL 13
> FREE TICKETS, BRING YOUR FRIENDS
> Wizard's Sports Cafe - 747 S Central Expy, Richardson, TX 75080
> 
> https://www.eventbrite.com/e/yuris-night-with-creative-disturbance-tickets-22806282204

## 

---

Visiting Scholar at Annenberg School for Communication, UPENN

Assistant Professor Doctor at Faculty of Communication, Izmir University of Economics, Turkey

Reporter for BBC World Service, Turkish Section

## 

Roger F Malina
is in  Dallas 1-510-853-2007

COME TO OUR CREATIVE DISTURBANCE YURI'S NIGHT PARTY
APRIL 13
FREE TICKETS, BRING YOUR FRIENDS
Wizard's Sports Cafe - 747 S Central Expy, Richardson, TX 75080

https://www.eventbrite.com/e/yuris-night-with-creative-disturbance-tickets-22806282204

**Comment by coreysmart92** [comment]
The wordpress channel page has been made, and the first podcast is currently being prepared to publish. This channel will publish 4/15/16.
Close: When channel has been published.
