### ISSUE TITLE
bacground noise on podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#544]
hi

we recorded this podcast in the booth in the artscilab but there is a lot
of background
what caused this ?
and how can i avoid this in the future when recording with the booth

and is it not possinle to filter out that kind of background noise ?

for the quality evaluation work

roger
@coreysmart92 @amb141330

**Comment by halclark** [comment]
Hello Roger,

There is a multitude of things that could have made your recording sound like that. I have given instructions in the quality assessment section of the producer cheat sheet, but I know that one of the microphones at the station has been acting up. If the noise is not too prominent, it will be possible to filter it out. I'll have to look at it.
- Hal

**Comment by rmalina** [comment]
hal
can you do some test sessions at the sound station
and make sure this problem is solved
roger

On Wed, Mar 30, 2016 at 3:46 PM, halclark notifications@github.com wrote:

> Hello Roger,
> 
> There is a multitude of things that could have made your recording sound
> like that. I have given instructions in the quality assessment section of
> the producer cheat sheet, but I know that one of the microphones at the
> station has been acting up. If the noise is not too prominent, it will be
> possible to filter it out. I'll have to look at it.
> - Hal
> 
> Sent from my iPhone
> 
> > On Mar 30, 2016, at 7:47 AM, rmalina notifications@github.com wrote:
> > 
> > hi
> > 
> > we recorded this podcast in the booth in the artscilab but there is a lot
> > of background
> > what caused this ?
> > and how can i avoid this in the future when recording with the booth
> > 
> > and is it not possinle to filter out that kind of background noise ?
> > 
> > for the quality evaluation work
> > 
> > roger
> > @coreysmart92 @amb141330
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/544#issuecomment-203629954

## 

Roger F Malina
is in  Dallas 1-510-853-2007

COME TO OUR CREATIVE DISTURBANCE YURI'S NIGHT PARTY
APRIL 13
FREE TICKETS, BRING YOUR FRIENDS
Wizard's Sports Cafe - 747 S Central Expy, Richardson, TX 75080

https://www.eventbrite.com/e/yuris-night-with-creative-disturbance-tickets-22806282204

**Comment by halclark** [comment]
Roger

Yes I can, will keep you updated.
- Hal

**Comment by cassininazir** [comment]
@halclark can you discuss replacing the mic with Brian Merlo? Email him directly and cc @cassininazir

**Comment by amb141330** [comment]
Please update this issue. Make sure the mics are both working before you close it.
