### ISSUE TITLE
missing sd cards in zooms

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#545]
ashton
can you check all the zooms and make sure they
all have sd cards ?

we tried to use the zoom but there was no sd card
in it so had to use scot's

roger

Corey
Can you please remove the sd card from the zoom 
we used for the watering hole podcast last friday and give it back to Scot ?
He told me you have a class on Thursday..
Thanks
yvan

**Comment by amb141330** [comment]
Will go through the zooms this week and make sure they have their SD cards.

**Comment by amb141330** [comment]
We had found one card in Cassini's possession by accident. I am meeting with Indu tomorrow. I'll go over this as some of the things to check for.

**Comment by rmalina** [comment]
i have a zoom with me and a card in it
will return may 22
roger

Roger F Malina
is in  Colombia 1-510-853-2007
