### ISSUE TITLE
yuri's night podcasts with judge marshall and ken murphy

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#546]
hal
ok so we have two first podcats for yuri's night
can you work with ashton to get them up'
for uyuri's night in the space and culture channel

note- they are both legally mind so PLEASE send them
the podcast to aprove BEFORE you publish it

and hope you will have some fund bumpers !

roger
@coreysmart92

**Comment by cassininazir** [comment]
Closing this item. It's referenced in #564
