### ISSUE TITLE
Credits for Virtual Africa & Frank Malina podcast bumper

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#547]
@halclark 

Can you let me know how many podcasts have used the newer Virtual Africa podcast bumper?

Same with Frank Malina, but I'm not sure if we ever used it.

We need to go back and give credit to Yvan's friend on all of those podcasts once we identify them.

**Comment by halclark** [comment]
8 podcasts, starting with "Making Africa, Afropolis and the African
Renaissance [ENG].
- Hal

**Comment by amb141330** [comment]
Please go through those podcasts and add credits into the description

**Comment by OskarOlssonCD** [comment]
I've added Ronan Martin as the bumper author for the following podcasts:

Introducing Kapital Movie Industry Corporation [ENG]
Being a Young Designer in Cairo [ENG]
Announcing an Afrofuturism Podcast Series [ENG]
African Robots [ENG]
A Lovely Weather: In Defense of Waste! [ENG]
A Lovely Weather: Eco-Cancer and Garbage Art [ENG]
Émoticônes et Diversité Culturelle [FR]
Creative Technology and Soft Power [ENG]
Making Africa, Afropolis and the African Renaissance [ENG]
A Bid for ISEA 2018 in Durban [ENG]
