### ISSUE TITLE
Introducing Kapital Movie Industry Corporation

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#550]
@amb141330 Ashton, a new podcast has been recorded for Virtual Africa
the file is on Box.com and a form has been saved (file too heavy to be processed)- please assign, edit, submit and publish
thanks

**Comment by amb141330** [comment]
Hal has volunteered to take charge for this channel so I am reassigning.

**Comment by halclark** [comment]
Ashton has volunteered to take care of this. More than happy to help in any way I can. @amb141330

**Comment by amb141330** [comment]
this podcast is on the tracking sheet and assigned to an editor
