### ISSUE TITLE
Process Update: Description Length and Voices

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#556]
@amb141330 not sure the proper document to put this. 
1. Please limit podcast descriptions to 100 words.
2. Voices' names should be in the podcast description.

**Comment by amb141330** [comment]
Should this be something that we have on the forms? Somehow implement a character limit on the podcast description. Perhaps with a note describing the elements of a good description?

-Who's featured in the podcast
-Main topics covered
-Associated with different businesses or institutions
etc.

**Comment by rmalina** [comment]
Good idea
Have this added to the form

**Comment by cassininazir** [comment]
@dylanorgeron please take a look at this issue.
