### ISSUE TITLE
weekly report

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#557]
corey
can you develop a standard format for each week
with both the list of one time things
and the regular things you must do each week

roger
@cassininazir

**Comment by coreysmart92** [comment]
I have implemented the "One Time Task" and "Repeating Tasks" into my weekly reports. Please inform me if this is effective or if there is anything else I should implement.
(5/16/16)

**Comment by rmalina** [comment]
corey
see you monday ?
yes add to the weekly report " stuck items' where producers or voices or
someone
else is not responding and i get help unstick
roger

Roger F Malina
is in Dallas 1-510-853-2007
To: all family and Leonardo friends- we are having a party to celebrate the
50th
anniversary of the founding of Leonardo on Saturday June 18 in Paris- if
you
are in Paris then and can attend we would be delighted to invite you.
Contact
me.

**Comment by coreysmart92** [comment]
I will review my weekly report template and make any necessary changes before next meeting on 6/13/16.
Close: After all necessary changes have been implemented.
(6/6/16)
