### ISSUE TITLE
clean up forms in progress

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#558]
there are forms in progress/pending

http://creativedisturbance.org/forms/pending/#saved

for podcasts that have already been published

please clear out all the pending forms for piodcasts that are alraedy published

roger
@coreysmart92

**Comment by amb141330** [comment]
Corey is in charge of cleaning up the forms, reassigning.

**Comment by coreysmart92** [comment]
I have begun to clean up the forms, I have noting notable at this time. I will focus on this task during the  week of 5/16-5/22.
Close: When all form pages have been completely updated.
(5/16/16)

**Comment by coreysmart92** [comment]
I have archived all published podcast in the "Submitted Forms" tab. Next I will focus on the "Saved Forms" tab.
Close: When forms are completely up to date
(5/23/16)

**Comment by coreysmart92** [comment]
I have reviewed, published, and archived all old podcast forms in the "Saved Forms Tab". Next I will focus on the voice forms in the "Saved Forms Tab".
Close: When forms are completely up to date
(6/6/16)
