### ISSUE TITLE
Weekly Report Template

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#559]
Come up with a template for weekly reports that aligns with individual goals and job description and also topic discussions

**Comment by amb141330** [comment]
Going to revise this and make a template for every student worker to be able to use. In my opinion this should be on an "as needed" basis. Some students, in my opinion, don't need this kind of structure and are clearly working constantly.

**Comment by cassininazir** [comment]
Let's work on this together.

**Comment by amb141330** [comment]
This is going to be a part of our OKRs that we work on with Cassini starting next week.

**Comment by cassininazir** [comment]
Take a look at the video I sent to you prior to our meeting. It provides a good background to the process.

Sent from my iPhone

On May 15, 2016, at 1:49 AM, amb141330 <notifications@github.com<mailto:notifications@github.com>> wrote:

This is going to be a part of our OKRs that we work on with Cassini starting next week.

##
