### ISSUE TITLE
Develop cheat sheet for use of the ArtSciLab

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#56]
Keep in Google Drive and print copies for the lab

**Comment by coreysmart92** [comment]
@amb141330 Could you please have an update ready to present by next meeting. Does not have to be completed, but we would like to see where you are at and assist where we can.

**Comment by coreysmart92** [comment]
Cheat Sheet needs to be reviewed and transferred to Creative Disturbance drive.

**Comment by cassininazir** [comment]
@coreysmart92 please add a link to the file on Google Drive.

**Comment by cassininazir** [comment]
This should include:
- How to use Jabber (use the [CD 1.3 Working Remotely](https://docs.google.com/document/d/1NP-TLJ38swdwy3bZrvcW4umn3Dmy1q5y8RrTfkkNbuE/edit) document) as a start. Add on as needed. 
- How to setup and change the four projectors 
- Equipment check-in/check-out
- How to make a coffee

**Comment by amb141330** [comment]
The document for using the four projects is almost finished and will include how to change the inputs and use the audio station we are setting up once it is finished.

Still working on a good equipment check-in/check-out system

I don't drink coffee... Coffee machines are scary.

**Comment by cassininazir** [comment]
I'd like you to have a draft document in the shared Google Drive by Nov. 20 that lists how to use the XOOM recorder and the Blue mics. This should be easy to read and review from the perspective of a producer.

**Comment by cassininazir** [comment]
Please provide a link to the instructions for the Crestron you've created here.

**Comment by amb141330** [comment]
The Jabber section of this document
https://docs.google.com/document/d/1NP-TLJ38swdwy3bZrvcW4umn3Dmy1q5y8RrTfkkNbuE/edit#
is fine for setting up jabber. I need to take that section and add it to its own document just for jabber. I need to add how to call into the conference from the jabber system in the room.

This is the document for the projector walkthrough with the Cisco wall device
https://docs.google.com/document/d/1u77D-CZA8WUexJZy5BAKulBAa9HWw0b2-yCO9cna6_M/edit
the setup may change when we setup the audio booth and hopefully and audio-switch issues we have will be fixed.

I am working with @coreysmart92 this week on getting a better talkthrough for the zoom recorders

**Comment by cassininazir** [comment]
The Jabber section needs to be updated. The email address/number to dial into has been changed. 

I made comments on the Google drive document.

**Comment by amb141330** [comment]
Zoom Recorder walkthrough started. Might need to be tweaked, but I followed this setup for a podcast I helped Yvan record on Friday and it worked great.

https://docs.google.com/document/d/1k0K5TlQClR7S7rSVGLsQaiVNS3JE9fkIaZ6RfW3PIaw/edit

**Comment by amb141330** [comment]
Printing this out after review with the rest of the sound team today.

**Comment by amb141330** [comment]
This has been finished and sheets have been, or will be printed, by Brian and put into a three ring binder. There will be two binders, one for the ArtSciLab, and one for the  Lab techs
