### ISSUE TITLE
review podcast check list and start using it

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#561]
review check list april 25 monday meeting
make sure that every podcast editor is following the check list
add quality rating to the checklist
monday review the ratings for this weeks podcast
assigned to hal
roger

**Comment by halclark** [comment]
Created a new check list to be filled out with every podcast. Will go live ASAP.

**Comment by cassininazir** [comment]
Thanks for the quick response @halclark. Could you also provide a link here?
