### ISSUE TITLE
please tell voice neil rodnick when his second podcast is going uo

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#562]
ashton
can you do this or assign it to someone
roger
 Hi Roger & Nick,

I’m updating my web site, and wanted to provide links to both podcasts and the online version of the article from last year.  I have the link Roger sent, below, to the first of the podcasts.  I wonder if the 2nd podcast ever went up, and if the article is up on line in the Just Accepted catalog?  I wasn’t able to locate either in a google search.  If they are up, can you send me links to them?

Thanks,Hi Roger & Nick,

I’m updating my web site, and wanted to provide links to both podcasts and the online version of the article from last year.  I have the link Roger sent, below, to the first of the podcasts.  I wonder if the 2nd podcast ever went up, and if the article is up on line in the Just Accepted catalog?  I wasn’t able to locate either in a google search.  If they are up, can you send me links to them?

Thanks,
— Neil
Neil Rolnick neil@neilrolnick.com

On Aug 7, 2015, at 9:01 PM, roger malina rmalina@alum.mit.edu wrote:

neil
our first podcast is up
## http://creativedisturbance.org/podcast/neil-rodnick-remembers-ircam-iear-and-early-days-in-arttechnology-eng/

Roger F Malina
is in Dallas
1-510-853-2007Hi Roger & Nick,

I’m updating my web site, and wanted to provide links to both podcasts and the online version of the article from last year.  I have the link Roger sent, below, to the first of the podcasts.  I wonder if the 2nd podcast ever went up, and if the article is up on line in the Just Accepted catalog?  I wasn’t able to locate either in a google search.  If they are up, can you send me links to them?

Thanks,
— Neil

On Aug 7, 2015, at 9:01 PM, roger malina rmalina@alum.mit.edu wrote:

neil ( Neil Rolnick neil@neilrolnick.com )
our first podcast is up
## http://creativedisturbance.org/podcast/neil-rodnick-remembers-ircam-iear-and-early-days-in-arttechnology-eng/

Roger F Malina
is in Dallas
1-510-853-2007
— Neil

On Aug 7, 2015, at 9:01 PM, roger malina rmalina@alum.mit.edu wrote:

neil
our first podcast is up
## http://creativedisturbance.org/podcast/neil-rodnick-remembers-ircam-iear-and-early-days-in-arttechnology-eng/

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by amb141330** [comment]
notified him weeks ago, he was able to find his podcast.
