### ISSUE TITLE
apologies to judge marshall and ken murphy

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#564]
corey please send an apology to the judge and ken
and tell them when their podcasts are now scheduled to go up
roger

judge marshall, ken
i want to give you our apologies for not getting
up the podcasts we did up for yuri's night
corey who is responsible for the scheduling
will tell you when the podcasts will now go up

ken-thanks for coming to the party !
## 

Roger F Malina
is in  Dallas 1-510-853-2007

**Comment by cassininazir** [comment]
@coreysmart92 please send out this email this week and let him know when to expect this.

**Comment by coreysmart92** [comment]
Closing: I emailed on May 11 both an apology and all the information about their podcast publishing.
(5/16/16)
