### ISSUE TITLE
Training Video section on dashboard

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#565]
Cassini

We have a video on how to record and upload a podcast to the site. If we could get a section on the dashboard to put this, Vimeo has proved to embed very nicely into wordpress.

**Comment by cassininazir** [comment]
Can you put a link to the video here?

**Comment by cassininazir** [comment]
@halclark can you point me to the location of the video?

**Comment by halclark** [comment]
@cassininazir sent an email to your gmail with the link.

**Comment by cassininazir** [comment]
Uploaded to Vimeo. Closing this item.@halclark reopen if incopmlete.
