### ISSUE TITLE
Make existing voices more visible in forms

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#566]
Cassini

When someone goes to fill out a new form with us, and the voices in the new podcast are already registered with the website, the drop down menu to find existing voices is not as apparent as it should be. I'm having trouble wording this, but I am sure you know what I am talking about.

**Comment by dylanorgeron** [comment]
How could I improve this? There is already a search bar in the drop down allowing you to search for a voice.

**Comment by dylanorgeron** [comment]
read first + last or email to autocomplete form
