### ISSUE TITLE
Make edits to existing voices

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#567]
Cassini

Edits to existing voices need to be updated if we needed. For example, every time I select Roger Malina from the dropdown menu in the forms, his email does not show up. When I update it with the email and submit it, it does not make that edit to the voice. I'm not sure, but it may even treat it is a new voice whenever I submit it with edits.

**Comment by cassininazir** [comment]
@dylanorgeron assigning this and a related task to you. Essentially, this issue causes duplication of individuals. 

We may need to go through and manually add in email addresses for some individuals (the email field was added some time after launch, hence the number of individuals who don't have it). Should be a one-time fix.

**Comment by dylanorgeron** [comment]
@halclark are you making changes in the wordpress ui or on the forms page?

**Comment by halclark** [comment]
The forms page.

**Comment by dylanorgeron** [comment]
the list of voices is pulled directly from wordpress. until you update a voice in wordpress, its going to keep the old info in the forms. update the email through the wordpress ui and it will update in the forms
