### ISSUE TITLE
community building with the student creative disturbers

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#569]
roger is working with ashton to start community building between the students who go the kick starter grants

as a first step ashton is going to send an email to all the students in an open email
announcing the list of current students, appointment of celestia and launch of the turkish channel

he will send a open email and copy roger, cassini and yvan

we will then work with the students to help them network between each other

he will create a page on a tab on the about button w-th a meet the creative disturbers' page
with a brief description and then the list of students and their voice info

once this is done we will discuss longer range plans and this could be on the task list
of thew new student hire

roger

**Comment by amb141330** [comment]
I can get this email sent out, and all of the content for the page, this week.
