### ISSUE TITLE
new channel: DALA Digital Arts and Latin America

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#570]
ashton
can you work with poe johnson to set up the new DALA channel
on digital arts in latin america this summer
@poejohnson@gmail.com 

roger

Reynaldo
Cc frank dufour
Cc ricardo dal farra , max schich

I am pleased you were able to meet with poe – and delighted with the idea
That we would start a DALA channel on creative disturbance with podcasts
organized by you with Mexican and latin American pioneers in digital arts

As poe said in this email if we can put together a plan where you organize
The recording of one podcast a month ? does that sound reasonable ?
We can commit to publish one a month= we are moving the platform to MIT
This summer so the podcasts should get a lot of audience

I think poe gave you the forms for the opening of a new channel and depositing
Podcasts for publication

If you need any help or advice feel free to contact poe and myself

roger

From: Poe Johnson [mailto:poejohnson@gmail.com] 
Sent: Thursday, April 21, 2016 1:30 PM
To: Reynaldo Thompson
Cc: Malina, Roger
Subject: Upcoming Podcasts

Reynaldo,

Is there any update on when you might be able to record the podcasts that we spoke about during our last meeting? Have you begun contacting those people you planned on interviewing? 

Ideally, we would like to publish one podcast a month throughout the summer. 

Also, could you provide me with a list of the people you're planning on contacting so that I note our development with this project?

Thanks,
Poe

**Comment by amb141330** [comment]
Sent Poe an email about Within the Margins and this channel

**Comment by amb141330** [comment]
Poe said nothing about the DALA channel. Would you like me to contact them on my own and CC yourself and Poe?

**Comment by rmalina** [comment]
No
Poe is contact to dala

**Comment by amb141330** [comment]
I'll close this issue and follow up with Poe later in the summer since he is the contact for DALA
