### ISSUE TITLE
scheduling of autiolats podcasts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#571]
ashton corey
annick is waiting to be contacted to be asked what podcasts she will be submitting
and when they need to be scheduled by
please could the person who is her liaison make sure that
this is done and hte podcasts are scheduled as requested
@coreysmart92 

roger

ashton
i am not sure who is the liaison for the audiolats
channels but annick bureaud can tell you now
what podcasts she will be sending them in the coming weeks
and the dates they need to be scheduled
## 

Roger F Malina
is in  Dallas 1-510-853-2007

**Comment by amb141330** [comment]
Already taken care of. Podcasts scheduled to be published on wordpress and libsyn
