### ISSUE TITLE
podcast not on stitcher

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#572]
todays podcast appears on the web site but not on stitcher

http://app.stitcher.com/mystations/27121188/63422/episodes

PLEASE add to the check list that every morning you check that the podcasts
is properly loaded on website, stitcher, itunes

and talk to cassini about fixing hte problem

roger

**Comment by rmalina** [comment]
podcasts not appearing on stitcher, are they appearing on itunes ?
roger
@cassininazir @dylanorgeron

**Comment by cassininazir** [comment]
Confirmed the feed is [valid XML/RSS](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fcreatedisturb.libsyn.com%2Ffeed) -- however, the podcasts missing on iTunes and Stitcher have no sound files in LibSyn! 

@coreysmart92 
Scales of Life (25 April)
Crushing Conventions (22 April)

Have no **master file** (sound file) associated with them. Can you upload to LibSyn? 

![screen shot 2016-04-26 at 9 39 13 am](https://cloud.githubusercontent.com/assets/1661430/14822101/cd607798-0b92-11e6-9389-ce5734d2fe6e.png)

![screen shot 2016-04-26 at 9 37 58 am](https://cloud.githubusercontent.com/assets/1661430/14822040/952e2af0-0b92-11e6-814a-06f5679882d3.png)

**Comment by rmalina** [comment]
@halclark 

hal can you take care of this

roger

urvi
i want to give you our deep apologies for this problem
the students are in final week

I have asked hal clarke to work with you to get the problem fixed
i also noticed that your picture isnt up

sorry again

roger
Roger F Malina
is in  Dallas 1-510-853-2007
