### ISSUE TITLE
turkish channel liaison assigned to hal

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#574]
hal;
per the discussion today we are assigning the liaison/responsibility for the turkish
channel to you 

also we are working with everyone to update their job descriptions to correspond
to what they will actually be doing during the summer

also- as part of taking over the turkish channel can you work with cassini ashton and corey
to update develop a 'new channel checklist' just like we have a podcast publishing check list

roger
@cassininazir @coreysmart92 @amb141330

**Comment by halclark** [comment]
Sent a email to the turkish producers with my introductions and reassurance that they would have their second podcast up ASAP. Waiting on Corey to send me more information before I go any further.

**Comment by halclark** [comment]
As far as I know, Altug/Sarphan are still on vacation. Waiting on forms to publish episode 2. Will send another follow up email sometime this week.

**Comment by amb141330** [comment]
I know @halclark has gotten the podcasts up so this issue can be closed.
