### ISSUE TITLE
404 Page not Found podcast audio file

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#576]
Podcast forms are not correctly linking to the audio files. When I click on the audio file hyper link in the form that is submitted I get a gateway error.

**Comment by amb141330** [comment]
Tagging @cassininazir so he can see this issue.

**Comment by dylanorgeron** [comment]
can you confirm this is still an issue?

**Comment by amb141330** [comment]
I did it just now to double check.

**Comment by dylanorgeron** [comment]
which page and link are you trying to use? 

![image](https://cloud.githubusercontent.com/assets/6401465/14994664/c47768a4-1136-11e6-9660-232ffc9a2f5f.png)

the podcast link here seems to work fine for me.

**Comment by amb141330** [comment]
The two I was looking at were the most recent ones from annick and both of them had that error

**Comment by dylanorgeron** [comment]
both links should now be working

**Comment by amb141330** [comment]
They are. Thank you.
