### ISSUE TITLE
archiving of indie game nation

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#579]
ashton
i have hear from kyle kondras and he doesnt plan to keep the indie game nation
channel going

so you have my approval to 'archive it' it should appear on the list of of archvied station
on the disturbance page-you could even put a call for interest saying we are looking for
someone to relaunch it

hopefully this summer you can work with cassini and the new students to create the archive
of inactive channels

roger
@cassininazir

**Comment by amb141330** [comment]
Sounds good. Will look into implementing this feature with Cassini. Will also touch base with other producers in a similar situation.

**Comment by amb141330** [comment]
redirecting to issue #554
