### ISSUE TITLE
Yuri's Night Follow Items

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#582]
@halclark please follow up with the following individuals for Yuri's Night. I've linked the threads as well so that you find their contact info: 
- [Marie-Pier Boucher](https://github.com/creativedisturbance/podcasts/issues/426) 
- [Clea Waite](https://github.com/creativedisturbance/podcasts/issues/525) 
- [supriya Chakrabarti](https://github.com/creativedisturbance/podcasts/issues/513)
- [Frank Pietronigro](https://github.com/creativedisturbance/podcasts/issues/455)

@rmalina cc'ing you on this item.

**Comment by halclark** [comment]
Will use this as main thread for post Yuri's Night coordination. @rmalina you are still wanting to record podcasts with these individuals, correct?

**Comment by rmalina** [comment]
Yes!!

**Comment by amb141330** [comment]
Do we have an update on this @halclark ?
