### ISSUE TITLE
Redirect Legacy Forms Page

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#583]
@dylanorgeron can you setup a redirect 301 for 

`creativedisturbance.org/forms` to `creativedisturbance.org/dashboard`
`creativedisturbance.org/formslegacy` to `creativedisturbance.org/dashboard`

Note that `creativedisturbance.org/forms` currently redirects to `creativedisturbance.org/formslegacy`. Both should point to the Dashboard. 

The redirect may be setup in the `.htaccess` file.

**Comment by cassininazir** [comment]
@halclark cc'ing you to keep you informed. When the redirect is setup, you send any of the above links.

**Comment by dylanorgeron** [comment]
.htaccess has been updated
