### ISSUE TITLE
Molding the signifier description

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#584]
@amb141330 Can you please assign someone to change the description of the podcast ?
It looks better this way, as for the other podcasts of the channel (description first, then credentials)  >>
"The curator Ondrej Cakl discusses his approach to the biocybernetic installation Molding the Signifier by Ivor Diosi that he showned at the Ex Post cultural center in Prague in november 2015 as part of the EU Creative Europe funded Trust Me, I’m An Artist project. This podcast is linked to the one with Ivor Diosi discussing the same artwork.
Enregistré par Annick Bureaud le 20 novembre 2015 à Prague dans le cadre du projet Trust Me, I’m An Artist [http://olats.org/trustme/trustme.php] Jingles et habillage sonore Jean-Yves Leloup, musiques Carl Harms, David James Elliott “The Wire”, Sergey Lopoukha “Lull” (Universal Production Music Publishing), Stefanski “Last Light Lament” (Atmos Production Music/UNIPPM). Montage : Thibaud Marty. "
http://creativedisturbance.org/podcast/molding-the-signifier-as-seen-by-the-curator-ondrej-cakl/

**Comment by amb141330** [comment]
done
