### ISSUE TITLE
Problem with user information

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#585]
Dylan, got an email from Roger this morning. Contents below. Some kind of error with the registration system. Can you help resolve?

---

eliahu
i am sending this to the student who tracks the registation problem
on creative disturbance to see if he can help you re register 
on the cd site 
i dont know what the problem is
roger

Roger F Malina
is in  Dallas 1-510-853-2007

On Wed, May 11, 2016 at 12:53 AM, Eliahu Gal-Or pizzarebbe@gmail.com wrote:
Hi Roger,

I just read your piece on BunB2016 and looked at the CD site.

I tried registering on it, but was told that the user name Pizzarebbe is already taken.

So I tried Lightwave; ditto. 

Then it said that this e-mail address is already taken.

At this point the only logical assumpion was that I must have already registered while tired and drowsy, hence forgot about it, so I tried the lost password option; surprise: now it says that the address does not exist in their records.

A software glitch? Who knows...

The CD idea really turns me on; may I trouble you by asking if you could look into this or inform the relevant party so the glitch may be fixed?

I also wrote to BunB to ask if there is or can be some activity in Israel; thanks to collateral damage from my divorce I am still barred from leaving the country.

BTW: will you ever come to visit Israel? I'd love to meet you if you do.

Thanks in advance and all the best,

EGO +972586272388

**Comment by dylanorgeron** [comment]
she had already registered with the email she was trying to use. the 'forgot username' email was never configured in WP so it was sending out blank emails. i've configured it so that it will now return your username properly. you can tell her to retrieve her username via the prompt on the login page and things should work correctly.
