### ISSUE TITLE
correct title of podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#587]
not sure why the title of the podcast appears as
Shipping Dirt from the Moon with Ken Murphy==ther eare two guests
it should be
/shipping-dirt-from-the-moon-with-ken-murphy-and-judge-john-marshall

or was that too long

then

/shipping-dirt-from-the-moon-with-murphy-judge-marshall

http://creativedisturbance.org/podcast/shipping-dirt-from-the-moon-with-ken-murphy-and-judge-john-marshall-eng/

**Comment by amb141330** [comment]
You're right. I've made the changes.

Do you want this done for all watering hole podcasts? It's hard to say that all podcasts should include every guests' name in the titles, but I do think it makes sense for watering hole podcasts. 

Is there a reason you publish watering hole to New Leonardos Channel? Would it make sense to release them as their own series?

**Comment by rmalina** [comment]
so lets be consistent ?

and not have the voice names in the tiles of the podcasts ?
anotherthing to specific on the form ?

in any case if one voice is in the title the other one should be
otherwise one will be mad !

i should never be int he title of a podcast

roger

roger

Roger F Malina
is in  Colombia 1-510-853-2007

**Comment by amb141330** [comment]
I agree. Closing this issue. I think it's fine to have their names in the podcast, I was just stating not all podcasts need the guests names.
