### ISSUE TITLE
Publishing Podcast

### ISSUE THREAD

**Issue by kkondas** [creativedisturbance/podcasts#59]
I know that the podcasts were already up on Libsyn, and that we scheduled each of them to go live this week in Monday's meeting, but we had a hicup and today's podcast didn't get published to the site. I've been in touch with Corey and the problem is fixed now, but in the next meeting when we schedule the next batch of podcasts, we need to make sure all of the settings are correct so that we don't have that problem again.

**Comment by porteriffic** [comment]
Which podcast was it?
