### ISSUE TITLE
Add CD to Google Play

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#591]
---------- Forwarded message ----------
From: Jon V sito.org@gmail.com
Date: Sat, Apr 23, 2016 at 11:24 PM
Subject: podcasts now on google play
To: feedback@creativedisturbance.org

wondering if you would considering putting creative disturbance podcasts up on google play?   not sure how big that audience is (they just announced it), but at least you would get one more subscriber there.... me.  :)

https://play.google.com/music/podcasts/publish

best,
-jon

**Comment by rmalina** [comment]
sounds like a good idea to me
can we do it
roger

Roger F Malina
is in  Colombia 1-510-853-2007

**Comment by amb141330** [comment]
done, CD is on google play. Will do blog post.
