### ISSUE TITLE
podcast with sharath chandra ram

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#595]
ashton
to be assigned
i just loaded up a podcast with sharath chandra ram
its in drop box but i think i successfully attached it to the form
he is a new voice and may need help getting his form in
his email address is
looplogic@gmail.com

roger

**Comment by amb141330** [comment]
Reassigned to @coreysmart92

**Comment by coreysmart92** [comment]
Understood, I will comment when I have begun the editing process.
Close: When podcast is scheduled to publish.
(5/23/16)

**Comment by coreysmart92** [comment]
The tracking sheet shows that this podcast has been assigned to Hal. Please inform me if I am to edit/publish this podcast.
(6/6/16)

**Comment by halclark** [comment]
Podcast published.

**Comment by rmalina** [comment]
You need to correct them errors he found
