### ISSUE TITLE
forms in creativedisturbance site

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#596]
ashton
i am just uploading some new podcat forms into the forms section of creative disturbance
there seems to be a whole bunch of forms on published podcasts that have not been
moved to the archived section
it makes it really confusing to track

maybe on the check list when the podcast is published you should move
the form from submitted to archived ?

anyway some clean up is needed

roger

**Comment by amb141330** [comment]
I'll work on the clean up this week.

**Comment by amb141330** [comment]
@coreysmart92 were you working on this?

**Comment by coreysmart92** [comment]
Yes, previously I cleaned up the submitted tab. This week I published and archived the podcast forms in the saved tab. Next I will be focusing on the voices forms in the saved tab.
Close: When all tabs have been reviewed.
(6/6/16)

**Comment by coreysmart92** [comment]
This Github issue is now for the review and completion of all voice information on Wordpress. I will be review and completing all possible voice information on Wordpress voice page. I will also create a list of all voices with missing emails. For Creative Disturbance Form review and clean-up see issue #558.
Close: I will close this issue when all voices have been reviewed, edited, and a list of missing information is created.
(6/6/16)

**Comment by coreysmart92** [comment]
I have begun reviewing all voice emails and created the document "Missing Voice Email". This coming week I will finish reviewing and complete "Missing Voice Email".
Close: When all voices have emails.
(6/13/16)

**Comment by amb141330** [comment]
What's the progress on the emails in the voice section? Have you completed the list? 

Do I need to take over archiving the forms?
