### ISSUE TITLE
podcast with experimental publishign students

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#597]
ashton
to be assigned
i uploaded an experimental publishing podcast with chaz lilly, yvan tina, alex topete, josh brumett
i couldnt figure out how to upload the podcast in the form so the podcast file is in drop box
under voices from the crowd

it may be a bit confusing so i can work it with whoever you assign it to

roger

**Comment by amb141330** [comment]
Assigning to @halclark to work with you on this

**Comment by halclark** [comment]
Published.
