### ISSUE TITLE
Chess channel proposal with Zura

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#598]
Zura will have a google document for his channel proposal completed by 06/10/16

**Comment by rmalina** [comment]
zura- i alerted jim stallings of your proposed chess and technology podcast channel-
once you have written up a proposal- that ashton is ok with- you should show it to
stallings and see if he has comments-roger
@amb141330

**Comment by amb141330** [comment]
@ZuraJavakhadze do you have any updates? Is there anything I can do to help you out and get the ball rolling on this for you?
