### ISSUE TITLE
Podcast Chafchaouni part 2

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#60]
@halclark @coreysmart92 @kkondas 
hey guys ! couldn't find chafchaouni podcast on the production tracking sheet
https://docs.google.com/spreadsheets/d/1JUtI3ecGsmmmIR9dKtSGxkuNFcKvmzhXc2ND69MSvd4/edit#gid=1552320650
since the first part has been published a month ago, was wondering if it has been edited or lost ?
if you find it please be kind enough to add to our schedule
have a good week end !
y

**Comment by coreysmart92** [comment]
Completed first part, but not sure about a second part.

**Comment by coreysmart92** [comment]
Published already.

**Comment by yvantina** [comment]
@coreysmart92  @halclark  can you please shorten the title to "Faire palpiter les sens" ?  thank you

**Comment by halclark** [comment]
Updated to shortened title. http://creativedisturbance.org/podcast/faire-palpiter-les-sens-et-retrouver-lintemporel-2/

**Comment by cassininazir** [comment]
Two things:
- First and last words in a title should always be capitalized. 
- Don't forget should be fixed in LibSyn as well. http://createdisturb.libsyn.com/webpage?search=palpiter&Submit=Search 

Guidelines:
1. Capitalize the first and the last word.
2. Capitalize nouns, pronouns, adjectives, verbs, adverbs, and subordinate conjunctions.
3. Lowercase articles (a, an, the), coordinating conjunctions, and prepositions.
4. Lowercase the "to" in an infinitive (I want to play guitar).

@halclark, please add these guidelines to the appropriate Google Doc.

**Comment by coreysmart92** [comment]
@halclark Have you been able to get to this? If not could you please look at and try to have this at latest May 25, 2015. This is a High Priority Issue and needs to be handled ASAP.

**Comment by halclark** [comment]
Fixed the title. However, I do not know where to add those guidelines in
Google docs. @coreysmart92 could you add it and then link it to me? Thanks

**Comment by cassininazir** [comment]
Please review the production process files. There is a style guide somewhere which is probably a good spot for it.

Sent from my iPhone

On May 21, 2015, at 3:59 PM, halclark <notifications@github.com<mailto:notifications@github.com>> wrote:

Fixed the title. However, I do not know where to add those guidelines in
Google docs. @coreysmart92 could you add it and then link it to me? Thanks

On Thu, May 21, 2015 at 4:37 PM, coreysmart92 <notifications@github.com<mailto:notifications@github.com>>
wrote:

> @halclark https://github.com/halclark Have you been able to get to
> this? If not could you please look at and try to have this at latest May
> 25, 2015. This is a High Priority Issue and needs to be handled ASAP.
> 
> �
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/60#issuecomment-104427320
> .

�
