### ISSUE TITLE
Tobias picture missing

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#600]
@amb141330 Hi, Tobias Van Veen picture is missing from these pages - can you please help fix it ? thanks
http://creativedisturbance.org/podcast/announcing-an-afrofuturism-podcast-series-eng/ 
http://creativedisturbance.org/channel/virtual-africa/

**Comment by yvantina** [comment]
@amb141330 RE ?

**Comment by amb141330** [comment]
taken care of

It was also missing on the bold roast channel. I've fixed that as well.

**Comment by yvantina** [comment]
thanks !!
