### ISSUE TITLE
Duplicating Audiolats podcasts to Meta-Life

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#601]
@amb141330 @halclark @coreysmart92 
hey Team, whenever you publish a new audiolats podcast, can you make sure it is also duplicated on the Meta-Life channel if you see the topics are related ? as a reminder, and as you can see on the logo, Meta-Life is actually part of the Audiolats syndication strategy.. so please duplicate move the two 'molding the signifier' podcast on the art and biology channel as well.. thank you !

**Comment by yvantina** [comment]
@amb141330 @halclark @coreysmart92 RE ?

**Comment by yvantina** [comment]
@amb141330 @halclark RE?

**Comment by yvantina** [comment]
@amb141330 @halclark  Is this issue fixed already ? Please do as I have to provide a report for the audiolats podcasts published this year.. thanks

**Comment by halclark** [comment]
Duplicated and published.

**Comment by yvantina** [comment]
Thank you Hal
