### ISSUE TITLE
Molding the signifier description

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#602]
@amb141330 Ashton, same issue with part 2...
here's the right way of putting the description, thanks for assigning someone to help
"The artist Ivor Diosi discusses his biocybernetic installation Molding the Signifier that he exhibited at the Ex Post cultural center in Prague in november 2015 as part of the EU Creative Europe funded Trust Me, I’m An Artist project. This podcast is linked to the one with Ondrej Cakl who discusses the same work from the point of view of the curator.
Enregistré par Annick Bureaud le 20 novembre 2015 à Prague dans le cadre du projet Trust Me, I’m An Artist [http://olats.org/trustme/trustme.php] soutenu financièrement par le programme Creative Europe de l’Union Européenne, Jingles et habillage sonore Jean-Yves Leloup, musiques Carl Harms, David James Elliott “The Wire”, Sergey Lopoukha “Lull” (Universal Production Music Publishing), Stefanski “Last Light Lament” (Atmos Production Music/UNIPPM) and extracts of Molding the Signifier sound track. Montage : Thibaud Marty."
http://creativedisturbance.org/podcast/molding-the-signifier-as-seen-by-the-artist-ivor-diosi/

**Comment by yvantina** [comment]
@amb141330 RE ?

**Comment by amb141330** [comment]
taken care of, sorry for the late response.

**Comment by yvantina** [comment]
@amb141330 please remove the quotation marks... thanks !
