### ISSUE TITLE
Thanks for the Afrofuturism podcast and logo

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#605]
@amb141330 @linamoon Congrats for the opening of the Afrofuturism channel ! this is a great podcast and logo.. Ashton, the guest pic and bio still missing though http://creativedisturbance.org/podcast/other-planes-01-ytasha-womack-author-filmmaker-innovator/ much thanks !!

**Comment by amb141330** [comment]
already have another issue for this, and I was already aware the guest didn't have information.
