### ISSUE TITLE
frozen stats

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#606]
the stats are frozen
http://creativedisturbance.org/stats/

havent been updated since april 24

roger

**Comment by amb141330** [comment]
handing over to @dylanorgeron since he knows more about how it works

**Comment by dylanorgeron** [comment]
stats wont work again until we move to a vps. last i heard hostgator charged us for the move but havent moved us yet. brett was handling it as far as i know.

**Comment by rmalina** [comment]
http://creativedisturbance.org/stats/
stats are still frozen on cd
where are we on the hostgagor move
roger
@cassininazir @amb141330

**Comment by cassininazir** [comment]
I contacted HostGator earlier in the week. They response indicates that they think they've upgraded us to the correct plan but that's not indicated in our control panel (screenshot below). I responded back with the screenshot. Will close when complete. 

![screen shot 2016-06-16 at 6 31 27 pm](https://cloud.githubusercontent.com/assets/1661430/16136523/ccc560f6-33f0-11e6-9576-a2a723bf6282.png)
