### ISSUE TITLE
screw up in email system

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#61]
corey
i got this email but when i tried to reply it started sending my
reply to david marlett's email address
you need to check with cassinin whats going on
roger

From: CREATIVE DISTURBANCE [mailto:no-reply@wufoo.com] 
Sent: Tuesday, May 12, 2015 5:23 PM
To: Malina, Roger
Subject: CREATIVE DISTURBANCE - New Podcast Info Form

This is confirmation that you have uploaded a new Podcast for you Creative Disturbance Channel.

CREATIVE DISTURBANCE - New Podcast Info Form 
Channel Name \*  Voices in the Crowd
Producer's Name \*   Roger Malina 
Producer's Email \*  rxm116130@utdallas.edu 

Podcast Title \*     Nobel Prize Winner Amartya Sen 
Short Description of this Podcast \*     In this podcast, Amartya Sen talks with UT Dallas doctoral student Anwesha Bhattacharjee. Sen shares his thoughts and works on preferential sex selection and gendercide. Sen’s research delves deeper into the realm of culture, socio-economic structures and policy making as he endeavors to search for plausible causes and remedies for “the missing women,” as he calls them, in governance.
Key Words for this Podcast \*    nobel prize, economist, gendercide, sex selection
Date of Recording \*     Thursday, April 23, 2015 
Has the sound file been uploaded to CD Google Docs under "Podcasts-Need Editing"? \*     • Yes
Method of Recording this Podcast \*  In Person
Primary Language of this Podcast \*  English
Image for this Podcast (preferably square and no less than 600 x 600 pixels)     senamartya4902015046.jpg 39.33 KB • JPG 

Host (if not Producer)  UT Dallas doctoral student Anwesha Bhattacharjee
Photo of Host (if not Producer) (preferably square and no less than 400 x 400 pixels)    anwesha_bhattacharjee.jpg 50.78 KB • JPG 

Did the Host (if not Producer) complete a Guest Release Form(s)?    • Yes
Guest \*     Amartya Sen
Short Bio of Guest \* 
Amartya Sen, recipient of the 1998 Nobel Prize in economics, came to the UT Dallas campus as the first speaker in the newly formed Jaya Lectures Series, which was organized by the University's Asia Center. 

Sen is a highly acclaimed economist, writer and philosopher who won the Nobel Prize for his contributions to welfare economics. Regarded as one of the world's foremost thinkers, Sen was featured on Time magazine’s list of “World's 50 Most Influential People Who Matter” and was named the “Third Most Influential Thought Leader of 2014” by Gottlieb Duttweiler Institute.

Sen helped create the United Nations Human Development Index and is best known for his work on famine, poverty and the role of freedom as a means for development. He was the first person to measure gendercide. In 1990, he determined that 100 million women were demographically “missing” in the world due to vicious discriminatory practices. He has long championed education for girls and economic empowerment of women — as both a moral right and a tool for development.
Photo of Guest (preferably square and no less than 400 x 400 pixels)     senamartya4902015047.jpg 39.33 KB • JPG 

Email of Guest \*    mmw110030@utdallas.edu 

Did the Guest(s) complete a Guest Release Form(s)? \*    • Yes
Guest's Website (if any)    http://scholar.harvard.edu/sen/home 

May CD publish Guest's website (if any)?    • Yes

---

This email notification is powered by Wufoo, the free online form builder. 
Make your own HTML forms for free at wufoo.com
GET STARTED!

**Comment by porteriffic** [comment]
Roger,

It probably started to reply to David's email because the Wufoo Forms are under David's account. Sruthi is almost done with the Google Forms so this shouldn't be an issue in the future. @cassininazir Correct me if I'm wrong.

**Comment by cassininazir** [comment]
Glad you emailed that. Yes, you are correct.

**Comment by rmalina** [comment]
cassini
once the new forms are up- can you tell david copy me that he can close down wufoo forms
as we dont need it any more
roger
