### ISSUE TITLE
crediting bumper and stinger creator

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#610]
ashton
we agree a while back to start crediting the creator of the bumpers and stingers

for instance i was interested in who created this bumper/stinger !

http://creativedisturbance.org/podcast/other-planes-01-ytasha-womack-author-filmmaker-innovator/

roger

**Comment by amb141330** [comment]
Tobias made that bumper himself. Since it's also his podcast there isn't any need to credit him explicitly for the whole podcast.

**Comment by rmalina** [comment]
hmm
i think it would be good on all podcasts to credit\
the composer/creator !
even if produced by the producer
roger

Roger F Malina
is in Paris 33(0)6-80-45-94-47
To: all family and Leonardo friends- we are having a party to celebrate the
50th
anniversary of the founding of Leonardo on Saturday June 18 in Paris from
15h-24h !- if you are in Paris then and can attend we would be delighted to
invite you. Contactme.

**Comment by amb141330** [comment]
WordPress forms now allows for a bumper author section. I'll make sure that's being filled out from now on.
