### ISSUE TITLE
Allow users to edit their voice profile

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#613]
"Awesome.!! Last but not least, just need to change the “Expertise” tags to super please read:

“Critical Theory, Media Arts, and Tactical Turntablism”

(Sorry, this request was sent earlier probably got lost in the shuffle… thanks!!)

best, tobias

ps. Mentioned this before — feel free to pass along — it would be wonderful if the website redesign allowed for Users to update their Voices profile page … :D"

I did the first part, but as you can see he mentioned the desire to edit his own voice profile. Thought that might be a good idea so that voices can update their voice pages to link to their current work.

**Comment by dylanorgeron** [comment]
discussed with cassini, people page will be dependent on user's profile page. if user is not a guest, a guest page will not be created for them unless the do it themselves

**Comment by cassininazir** [comment]
@colin-c had a few thoughts on this. Connect with him when you have a mo.

**Comment by amb141330** [comment]
Dylan and I have discussed this plenty. He knows what is best for our current design.
