### ISSUE TITLE
Bakahika's podcast missing in the channel

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#614]
@amb141330 Ashton, just noticed the podcast with Bruno Bakahika was missing from the channel page.. weird !! http://creativedisturbance.org/channel/virtual-africa/

http://creativedisturbance.org/podcast/introducing-kapital-movie-industry-corporation-en/

**Comment by halclark** [comment]
@dylanorgeron not sure why this is happening. Everything seems to be in order in wordpress, but the podcast is not showing up on the Virtual Africa page

**Comment by dylanorgeron** [comment]
you spelled virtual with a capital I.

**Comment by cassininazir** [comment]
A further note on Dylan's statement: The channel names must match exactly what the official channel title is (e.g. **Sound & Data** is correct, **Sound and** Data is incorrect).

**Comment by halclark** [comment]
Derp, haha thanks guys. Overlooked that!

**Comment by yvantina** [comment]
Thank you guys ! closed
