### ISSUE TITLE
linsyn stats broken

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#616]
tnere is a problem in the libsyn stats

https://four.libsyn.com/stats/general/target/show/id/56517

several of tje recent podcasts arent in the list-only some podcasts are being tracked

roger

**Comment by amb141330** [comment]
I'm not sure what to do about this, Dylan do you have any knowledge about this?

**Comment by dylanorgeron** [comment]
![image](https://cloud.githubusercontent.com/assets/6401465/15982417/3babb4c4-2f4c-11e6-9bad-f5696f9bac1d.png)

**Comment by rmalina** [comment]
Was this solved
