### ISSUE TITLE
set up DALA channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#617]
ashton
we need to start setting up the DALA channel as a sub channel to the poineers and pathbreakers channel
DALA is digital arts in latin america

the producers will be reynaldo thompson in mexico and poe johnson here- you can work
through poe

we want to get up a first podcast this summer

roger

Dear All,

I think it is very important to have the Latin American pioneers in the P&P channel. This has been the dream from the very beginning of the Pioneers project and I am thrilled to see that this is happening now, after all those years. So, even if you open a DALA channel, please make sure that the podcasts relating to pioneers go also in the P&P channel.

Looking forward to great work together !

Best
Annick

**Comment by amb141330** [comment]
replied to that email addressing poe and telling him which forms are needed to get it up and running

**Comment by amb141330** [comment]
Have all the information, have the draft started and a preliminary logo. Will assign sound designer to do the bumper and ask if the logo can be adjusted.

**Comment by amb141330** [comment]
Paddy is making adjustments to the logo. I have been in contact with Reynaldo, he's happy to have modifications to the logo. Should be receiving podcasts from him soon.
