### ISSUE TITLE
Problems with the forms. Missing information

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#618]
See below. I ended up sending an email to this producer asking for forms which she has apparently already submitted.

I checked all the different forms sections and see nothing. If she did submit the forms on the CD website then we have some kind of problem and I'm a bit embarrassed for sending out an email.

---

So my bad for sending that stuff, but I really don't see that information anywhere on the website in our forms section. I checked submitted, archived, and saved. I see nothing.

On Sat, Jun 11, 2016 at 12:48 PM, Ashton Brillante ashtonbrillante@gmail.com wrote:
Yeah there's no forms on the Creative Disturbance page. I'm not sure what she did or where she submitted forms, but I don't see them on the page.

On Sat, Jun 11, 2016 at 12:46 PM, Yvan Tina yvantina@gmail.com wrote:
Ashton 
Here's again what she sent me..

---------- Message transféré ----------
De : "Janeil Engelstad" janeil@mac.com
Date : 8 juin 2016 17:16
Objet : Re: connecting with Matthew Horton for M.A.P. radio hour channel
À : "Yvan Tina" yvantina@gmail.com
Cc : 

Hello again I have filled out the forms on the Creative Disturbance page.
Please let me know if you need anything else rom me to launch our channel.

Thank you -

Janeil

On Jun 5, 2016, at 3:35 PM, Yvan Tina yvantina@gmail.com wrote:

Hi everyone !

Ashton, Corey
this is to put you in touch with Matthew Horton, from Make Art with Purpose (M.A.P); I understand he will be responsible for the implementation of the Virtual Africa and CD's logos on M.A.P's website - we should also integrate their logo in our home page (//Human Impact) - as well as for any work related to their web design and podcast production  . Matthew is also a former utd student and i assume he is familiar with our work environment..

Matthew, 
I think you met Corey last time -I called him to help us record the podcast with Janeil- and Ashton is our coordinator manager - may you have any question please let him know, he will forward it to the right person

Below is copied an email I sent to Janeil last week regarding the creation of the M.A.P channel
All, please make sure to copy her in every email, as she is the director and producer of M.A.P, and will be overviewing the whole project

Okay, the ball is in your court now
Thank you and have a good sunday !!

yvan

---------- Forwarded message ----------
From: Yvan Tina yvantina@gmail.com
Date: 2016-05-30 14:43 GMT-05:00
Subject: Re: delighted
To: Janeil Engelstad janeil@mac.com
Cc: Ashton Brillante ashtonbrillante@gmail.com, Corey Smart corey.smart92@gmail.com

Janeil,

just realized I never sent the information related to the creation of your channel
am also copying Corey Smart who recorded the podcast last week and Ashton Brillante our management coordinator
if you have any question please ask them

as of now, you can create your own login information here http://creativedisturbance.org/registration/ 
in order to fill out your producer and channel forms
once you're logged in click the dashboard link - you should be able to see the forms tab on the top and you can go from there

> channel and producer forms (for your channel to go live)
> podcast form (for each podcast you submit)
> guest form (for any new voice in the podcast)

Ashton will be able to connect you with our web and sound design teams to create your logo and sound signatures
if you already have any of these, please feel free to share them with us at your best convenience

Hope this finds you well

yvan

---------- Forwarded message ----------
From: Yvan Tina yvantina@gmail.com
Date: 2016-06-02 23:43 GMT-05:00
Subject: Re: email test for creative disturbance
To: Matthew Horton mrh120030@gmail.com

Not to worry and thanks for the quick reply. Hope everything is well. Looking forward

yvan

Le 2 juin 2016 22:55, "Matthew Horton" mrh120030@gmail.com a écrit :
Hi Yvan, 

Yes, this is the correct email. 

Apologies again for having to leave so abruptly during recording, but I heard from Janeil that it went really well. 

I'm looking forward to hearing it. 

Matthew

On Thu, Jun 2, 2016 at 9:06 PM, Yvan Tina yvantina@gmail.com wrote:
hey there

this is yvan tina to double check if the email address i have is correct

i think we met last week to record a podcast with janeil for map on creative disturbance

if correct please confirm by replying back to this email
thank you

yvan
## 

check out this website for more information on art, synthetic biology and a-life 
http://synthbioart.texashats.org/
and listen to our podcasts !
http://creativedisturbance.org/
## 

check out this website for more information on art, synthetic biology and a-life 
http://synthbioart.texashats.org/
and listen to our podcasts !
http://creativedisturbance.org/

2016: USE YOUR VOICE

Janeil Engelstad
Founding Director
Make Art with Purpose
www.makeartwithpurpose.net
www.janeilengelstad.net
phone 323-309-4837

**Comment by dylanorgeron** [comment]
@cassininazir databse doesnt seem to have the forms, and i never got an email of a sql error. not sure what happened.

**Comment by amb141330** [comment]
I suppose she didn't submit, there's no record of her doing so. Asked her to resubmit and she did so this is taken care of.
