### ISSUE TITLE
picture of voice missing

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#62]
corey
can you make sure the voices picture always goes up
when the podcast goes up
roger
sounds reasonable to titrate them, rather than dumping them all out in one big lump! I see episode 2 has been added, thank you!

One thing I noticed that on the Noisy People channel summary page, for episode 2 (Joëlle Léandre), her picture did not get added... whether this is my fault – that somehow the pic didnt get properly attached to episode submission form – I don't know... but the image of her did get sent as the 'episode image', and in fact the 'episode image' for each episode is a square portrait of the guest interview subject... (These images are also all easily grabbable from the main page of noisypeople.net if they somehow are failing to be attached properly to the form submission)

thanks again

Tim

**Comment by amb141330** [comment]
Josephine fixed this issue. Don't worry about it Corey.
