### ISSUE TITLE
duplicating the new afronaut podcast 

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#621]
@amb141330 @halclark hey guys ! can you please duplicate the new afronaut podcast (virtual africa) into space art and culture ? thanks  http://creativedisturbance.org/podcast/the-new-afronaut-2/

**Comment by amb141330** [comment]
I've taken care of this. Waiting for it to show up after publication. Usually takes a few minutes but it isn't showing up. I'll leave open until I see it on the website.

**Comment by cassininazir** [comment]
Appears to be fixed 
<img width="1254" alt="screen shot 2016-06-20 at 6 45 55 pm" src="https://cloud.githubusercontent.com/assets/1661430/16213724/40dd4d40-3717-11e6-8178-fbafa16c3567.png">

**Comment by yvantina** [comment]
yes, thanks
