### ISSUE TITLE
Unable to add to experimental space

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#623]
@cassininazir @dylanorgeron in the portfolio section of the experimental websites wordpress, the visual editor (where I add soundcloud links) is not loading. Not sure what to do. Have tried on both my laptop and my desktop.

**Comment by cassininazir** [comment]
Try editing without visual composer. You can add to the Audio Embed section in WordPress. Here's a link on where to find the embed code in SoundCloud:

http://shareandembed.help.soundcloud.com/customer/portal/articles/2167182-embedding-a-track-or-playlist-on-wordpress

**Comment by halclark** [comment]
Not sure how to embed without the visual composer (while sticking to the current format). I have tried on 3 different computers now to no avail. Not sure if I am doing something wrong or not.

**Comment by dylanorgeron** [comment]
drop a link to the experimental site and point me to the login credentials. ill take a look if youre still having issues

**Comment by halclark** [comment]
http://x.creativedisturbance.org/wp-admin

Login doc:
https://docs.google.com/document/d/1ipNxXHlGpEPgllR6QBQ2HF6vrOWRgLuhnngcUIqClxU/edit

Thanks!

**Comment by dylanorgeron** [comment]
did you ever pay for the visual composer plugin on this account?

**Comment by cassininazir** [comment]
I believe it came with the theme. Will have to uncover the history on this one. @ZuraJavakhadze could you assist with this?

**Comment by amb141330** [comment]
I'd like this to go up before the start of the semester if at all possible.

Perhaps @halclark should meet with @ZuraJavakhadze

**Comment by halclark** [comment]
@cassininazir @dylanorgeron @ZuraJavakhadze  still not working. Neither frontend editor or the portfolio page editing section.
