### ISSUE TITLE
Podcast link displays on Facebook

### ISSUE THREAD

**Issue by linamoon** [creativedisturbance/podcasts#624]
@yvantina informed me of this--on Facebook, some link cards show larger album art (below):

![screen shot 2016-06-20 at 4 22 39 pm](https://cloud.githubusercontent.com/assets/10729556/16210744/3bca4bb4-3703-11e6-8238-06dca2a65e5b.png)

The link cards should show smaller album art (below):

![screen shot 2016-06-20 at 4 19 32 pm](https://cloud.githubusercontent.com/assets/10729556/16210726/189ebada-3703-11e6-87a8-6508a7b9ab41.png)

Think this might be because sound team is uploading the larger artwork rather than the smaller artwork to the site. Compare below:

![screen shot 2016-06-20 at 4 24 07 pm](https://cloud.githubusercontent.com/assets/10729556/16210779/7537374a-3703-11e6-9571-3b74d2827b28.png)

Please take note and remember to upload the smaller artwork to site. Thanks!

**Comment by amb141330** [comment]
I've emailed the rest of the sound team about this. I'll have them go back and correct that Turkish podcast and also have them double check in the future

**Comment by yvantina** [comment]
It actually applies to the Afrofuturism channel as well..

**Comment by amb141330** [comment]
I fixed that too

**Comment by yvantina** [comment]
cool ! thanks

**Comment by cassininazir** [comment]
The smaller images aren't optimized for retina displays. See https://www.facebook.com/notes/facebook-engineering/optimizing-for-the-macbook-pro-with-retina-display/10151074971833920/
