### ISSUE TITLE
How to add channels to the forms?

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#625]
Once a new channel is published, I'm not sure how to go about adding it to our podcast forms so that it may be selected from the drop down menu when choosing a channel. Can we meet and you show me how to do this or explain it to me?

**Comment by dylanorgeron** [comment]
Currently they are hardcoded, meaning we have to manually update the list. I can show you how to do this once the forms are stable again and changes wont break things as much.

**Comment by amb141330** [comment]
Can you go ahead and ahead "Other Planes | Afrofuturism Podcast" to the drop down list?

**Comment by dylanorgeron** [comment]
added
