### ISSUE TITLE
Podcast with Joel before start of the semester

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#629]
Set up a time after August 5th to meet with Joel and instruct him on how to record a podcast.

joel
as we discussed i would like to record a podcast with
you - after you present your aug 5 poster

after that can you talk to indu and ashton about getting
training on how to record a podcast- and we can do
one practice podcast and then a real one to publish
on creative disturbance

just need to work this in before the start of the semester

**Comment by cassininazir** [comment]
@physicsshark not sure if you saw this. Please add the podcast to your list of deliverables -- it can of course, be done after Aug 5.

**Comment by joelewing** [comment]
Yes, I've seen this.  I'm leaving on the evening of August 6 and and I will be coming back on the 17.

**Comment by amb141330** [comment]
Let me know when you'd like to schedule this Joel, we can setup a time after you're back on the 17th to go through how to record a podcast

**Comment by joelewing** [comment]
Are we still planning to do this at some point?
