### ISSUE TITLE
Poe Johnson Needs a Zoom Recorder

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#63]
Have Instruction sheet done by 5/21/15

**Comment by cassininazir** [comment]
Please do not write on Microsoft Word, but instead create the document on Google Drive in the appropriate folder. Please update this GitHub issue with the link when you have it.

**Comment by coreysmart92** [comment]
Issues were who had the right to use the zoom recorder and files left on the sd card in zoom recorder.

@coreysmart92 complete Zoom Recorder Instruction sheet and begin making process for checking out zoom recorders by May 25, 2015.

Close when Instruction sheet is completed. But make new issue if zoom recorder process has not been completed.

**Comment by coreysmart92** [comment]
Poe Johnson has the recorder.
Close when returned.
