### ISSUE TITLE
record podcast with lasbouygues

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#631]
podcast with claire serres and
Bonjour Roger, merci pour ton mail, je l'ai transféré à Claire ! J'ai également passé un moment très intéressant, riche en discutions, c'était un plaisir de te montrer le parcours, 
je reste à ta disposition pour l'enregistrement de ce podcast avec Claire,
j’attends de tes nouvelles, je te souhaite un bel été

thomas Lasbouygues

**Comment by rmalina** [comment]
on hold but will do

**Comment by ritwikjk** [comment]
@rmalina 
is this podcast stilll on hold?

**Comment by rmalina** [comment]
roger is keeping this active and will follow up
