### ISSUE TITLE
Podcast for Charissa N. Terranova with Arthur Miller

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#632]
Hey Roger,

I am available for coffee next week -- Tuesday or Thursday afternoon would be great.

Would you be interested in doing a podcast conversation with me at Creative Disturbances about my research -- Wad, Joseph Needham, your dad, Leonardo, LL Whyte, Bronowski, etc.? I am working on a cast of characters -- modernists -- that seem lost to the world.

I also need to arrange a podcast with Arthur I Miller who wrote this: 
https://www.amazon.com/Colliding-Worlds-Cutting-Edge-Redefining-Contemporary/dp/0393083365/ref=sr_1_1?ie=UTF8&qid=1468976520&sr=8-1&keywords=arthur+i+miller

I met him him in Plymouth earlier this month and he wants to chat at this outlet.

We have lots of work to do! &#X1f60a

**Comment by amb141330** [comment]
Do you have an update on when you'll be meeting with Charissa for coffee and to record this podcast?

**Comment by rmalina** [comment]
this is on hold for now but will keep active

**Comment by rmalina** [comment]
will close now
