### ISSUE TITLE
Podcast for Charissa Terranova with Daniel Jardine

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#633]
From Charissa:

I am gobsmacked. I met Jacob Bronowski's grandson, Daniel Jardine, at an opening tonight. He is married to Alison Jardine, an artist represented by Erin Cluley Gallery. They are both Brits, she from Yorkshire, he was a Fellow at Jesus College in Cambridge. She teaches art here, and he...not sure what... a materials scientist and more.

I just did research in his archive at Jesus College Cambridge. He was part of the Kepes scene -- published in the Vision + Values Series.

Brownowski co-founded the Salk Institute with Jonas. He was a mathematician, communist-socialist scientist, holistic, art-sci advocate thinker -- one of my constellation. 

He did this at the end of his life, after many other things:
https://en.wikipedia.org/wiki/The_Ascent_of_Man
The Ascent of Man
The Ascent of Man is a 13-part documentary television series produced by the BBC and Time-Life Films first transmitted in 1973, written and presented by...
Read more...

Would love to do a podcast with the grandson Roger. And we need to one about the greater picture I am painting -- or repainting. WOW!

**Comment by amb141330** [comment]
Asked how I can be of assistance in getting this setup. Will find out when everyone is available and help with the recording.

**Comment by ritwikjk** [comment]
Emailed Charissa regarding this.
