### ISSUE TITLE
Problem with saving and submitting podcast forms

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#638]
Both Yvan and Annick have expressed trouble yesterday with being able to submit and save their podcast forms. As a result they had to just email me all the information. I'm unaware as to if this applies to guest forms as well.

**Comment by dylanorgeron** [comment]
Likely something got missed during the server transfer. Im looking into it.

**Comment by dylanorgeron** [comment]
I've fixed two bugs. One was preventing certain forms from entering the database. Unfortunately, this means that their forms will need to be resubmitted. Second, I've disabled a caching plugin that was preventing new forms from being visible on the pending page. This should resolve the issue Yvan and Annick were having.

**Comment by cassininazir** [comment]
Thanks, @dylanorgeron. @amb141330 can you confirm that it's working on your end?
