### ISSUE TITLE
New Podcast Channel Cover Art

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#642]
@amb141330 (Ashton) please work with @scolecite (Yana) regarding new channels that need artwork. 

Reminder that the producers should have approval at draft stage and final stage.

**Comment by cassininazir** [comment]
Review the [Album Artwork guidelines](https://docs.google.com/document/d/1rF5ZSlPwMFK9gTTlXywviDQlCNnZkFbMGvJxORMwIyw/edit) and the [Brand Guidelines](https://docs.google.com/document/d/1I7wcy-BkpTK5QDva5prW8ZCNboTlYaNF2nq0uY0FQEk/edit)

**Comment by amb141330** [comment]
**SRS BSNS**
This channel needs a logo and doesn't have anything of substance at the moment. The last line of this has what she's looking for.

"Thanks to de-individuation and avatars to represent ourselves on the internet, deception is a core feature. From the 18-year old female could really be a 46 year-old man, to toxic trolls with anger management issues who might even be teachers to pre-schoolers, Individuals who are introverted in person, who have large voices online. A large portion of us on the internet like to think we are more intelligent than our oppose when arguing a point on the internet, so much that maybe we even delude ourselves (where do you think the term mansplaining went viral?).  In other words, the internet has the power to make something out to be that is not.
Ultimately, no one in our modern society has ever seen a unicorn, as this is the generally accepted consensus. The internet has so much power to make things exist out of nothing (viral memes, the fact the interaction of the human with the internet is just a lot of pixels on a screen) and even more power to take things away (the internet is the voice of the world, cmon).
It doesn’t matter that we’ve never seen one. The unicorn represents something very real to internet culture. As such, a unicorn that is represented by a cute, happy and very fat rhinoceros is a reflection of the tone from two voices speaking about internet culture and the sarcastic nature serious topics relating to internet culture bring, that are matters of ‘Srs Business’."

**Dark Culture**
This one has a reference image in the channel form, but I'm unable to find whether or not this is the actual logo they want or just an idea that we base it off of. I'll get him an email about that right now. The reference image can be found on the Creative Disturbance forms. I'm not sure if you have access so I will screenshot the [image](https://gyazo.com/f45f408d2adf9b771d5e936596ce28f1) for you.  

**Digital Arts Latin America** (needs an adjustment)
For this one, there's already an [image on WordPress](http://creativedisturbance.org/wp-content/uploads/2016/10/DalaLogo300.jpg). I have the illustrator file of that image if you would like it. What they want is something with a similar style that includes Mexico and the Carribean countries. Feel free to make adjustments that you feel works better for the channel. If you would like the illustrator file, let me know. 

**Chess and Technology**
Channel will concentrate on chess and importance of technologies in the modern chess world.

This is the only description we have of the channel at the moment. I am meeting with him tomorrow and will ask him for any ideas he has.

**Parsecs, Phasers & Cyborgs**
Representations of Science in Art and Fiction. 

This is the only description for this. They did include a reference image, but again I'm not clear if that's what they want to use. I imagine they would be very open to another interpretation of [this](https://gyazo.com/4947989551a56110e7de12d8564e3983).

**My Suggestion**

I would start with Digital Arts in Latin America or SRS BSNS (which is how they want the channel name to look).

Sorry it took so long, trying to format this into a readable object.

**Comment by ygev** [comment]
**SRS BSNS**
![image](https://cloud.githubusercontent.com/assets/1816215/20064057/f9e9b330-a4ce-11e6-8184-eed64d020b6b.png)

**DALA**
![image](https://cloud.githubusercontent.com/assets/1816215/20069563/ba10e224-a4e2-11e6-919e-79a87f68a23e.png)

**Dark Arts**
_Image is copyrighted by [John Jennings](https://news.illinois.edu/blog/view/6367/210109#image-1); it's his original art. Please verify they have copyrights to the image._ 

**Chess and Technology**
Waiting on @amb141330 to get me more info.

**PP&C**
![image](https://cloud.githubusercontent.com/assets/1816215/20069474/5c805a04-a4e2-11e6-8723-f793b252957e.png)

**Comment by cassininazir** [comment]
Love these. @amb141330 please share and solicit feecback from the respective channel owners. 

On DALA album artwork, please remove the white border.

**Comment by cassininazir** [comment]
Also, the edges on PP&C have a great deal of artefacting, please clean up before final. 
E.g. 
<img width="346" alt="screen shot 2016-11-07 at 11 04 24 am" src="https://cloud.githubusercontent.com/assets/1661430/20067235/f5af530a-a4d9-11e6-8777-7aafc18210d8.png">

**Comment by ygev** [comment]
Edited & cleaned up; added to original comment.

**Comment by cassininazir** [comment]
Thanks, let's review together. I'm still seeing some smaller  throughout.

**Comment by ygev** [comment]
If you mean the pale blue lines, I added them on purpose. I can remove them like so, because I don't think they add much to the composition:

![image](https://cloud.githubusercontent.com/assets/1816215/20071278/71ff02ac-a4e9-11e6-8624-d0e4c8150469.png)

**Comment by amb141330** [comment]
Emails have all gone out. Will update as responses come in.

**Comment by amb141330** [comment]
Poe Johnson said that the Dark Culture image from John Jennings is just a reference image. Not to use that one for his album, but something to work based off of.

**Comment by amb141330** [comment]
Received positive feedback from Alex Garcia Topete (Parsecs, Phasers & Cyborgs) and Celestia (SRS BSNS). Both are happy with the product. Have not yet heard from Reynaldo Thompson.

Will have another channel artwork needed from Zura for his Chess and Technology channel. I am meeting with him tomorrow about that. You can also begin working on the Dark Culture logo whenever you are ready.

**Comment by ygev** [comment]
**Dark Culture**
![image](https://cloud.githubusercontent.com/assets/1816215/20426279/12118370-ad44-11e6-9878-d6f05dc23464.png)

Will upload Zura's in the morning.

**Comment by cassininazir** [comment]
Please make sure Poe and I have an opportunity to review. A few thoughts:
- Overall a good composition. Strong contrast between the colours. 
- The words should be larger. 
- The dots making up the work "DARK" should be larger. Try previewing this at a very small size with the low-brightness on a phone and the word "DARK" gets lost. 
- I recommend removing the lights at top. They look great when large but are indistinguishable when small. 
- No rounded corners on these album artwork. Some podcast apps will round album artwork automatically and you can't guarantee that your roudned corners will match theirs.

**Comment by ygev** [comment]
**Dark Culture ver2**

![image](https://cloud.githubusercontent.com/assets/1816215/20435624/6723eab4-ad72-11e6-8c7e-798ca13c4ed5.png)

**Comment by cassininazir** [comment]
Looks good. The front-facing ribbon on the `r` is misaligned. Needs to move left slightly

**Comment by ygev** [comment]
Fixed **Dark Culture.**
![image](https://cloud.githubusercontent.com/assets/1816215/20614587/cc5c606e-b295-11e6-97f5-2b75d4cf3c32.png)


Talked to Zura and we came up with this design for **Chess & Technology**. He is very pleased with it.
![image](https://cloud.githubusercontent.com/assets/1816215/20614607/0f7f4f78-b296-11e6-872a-951996d28dae.png)


I think we are done here?

**Comment by rmalina** [comment]
looks great to me
roger

Roger F Malina
is in Dallas
1-510-853-2007
malina.diatrope.com
