### ISSUE TITLE
Podcast Forms section not working

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#643]
Hey Dylan, 

I've had three people now submit podcasts and the forms are not showing up on the website. I, myself, just submitted a test form with an mp3 file less than 60 mb and the form is not there. Perhaps it will take some time for mine to show up, but right now we're missing podcasts from people because they've submitted them and I'm not able to see them. 

Not sure if the form is being saved at all. I did get [this screen](https://gyazo.com/3f83d81fba332ed411a69bd1f08c00e0) saying it is, but I'm not able to find it anywhere.

**Comment by amb141330** [comment]
Should we have some sort of email confirmation that allows users to see the information they have submitted in their form? That way if something like this happens, they at least don't have to write everything down again.

**Comment by dylanorgeron** [comment]
Do you recall what time/day you tested this? I'm trying to reproduce it and I can't. I haven't received an email saying a form couldn't be saved to the database, however the logs show that for a certain time the database was unreachable. If a form was submitted during this time, it wouldn't have sent me an email saying it couldn't be submitted. 

UPDATE:
I've increased the maximum packet size for mysql, meaning that verbose forms shouldn't get cut off due to server settings. I'll continue to keep an eye on things.

**Comment by dylanorgeron** [comment]
Lets sit down at some point and try and reproduce this issue on your machine. What time works for you?

**Comment by cassininazir** [comment]
@amb141330 I've asked @dylanorgeron to work with you on this. Please schedule a time to meet. Were you one of the three people who had trouble submitting?

**Comment by amb141330** [comment]
I was not. Including myself would make 4. The people who have experienced issues are Poe Johnson for Dark Culture, Ana Rita Fonseca from Roots of Curiosity, and Fatimeh from Artisthinktive. 

All three of them have tried to submit forms and when I've checked the submitted section they are nowhere to be found. I personally tested this on Friday right before I made the issue. 

Fatimeh was able to save forms, but nothing she submitted went through. I will contact Dylan for a time to meet.

**Comment by dylanorgeron** [comment]
A setting in the php config file was limiting the size of the POST to 8mb and had to be adjusted in addition to the setting for maximum file size. Form should now be working with large files. Sorry for the interruption.  @amb141330 confirm this is working with a test on your end. If so, please close out the issue.

**Comment by amb141330** [comment]
The issue has been fixed. Closing the issue.
