### ISSUE TITLE
MIT Forms for Future Labs Africa Channel- BETA access

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#647]
Creating an issue to document processes needed for Future Labs Africa to publish their podcasts on ARTECA.

-New Collaboration Agreement
-MIT Podcast form

Getting Teagan Bristow and Jepchumba II free beta access to ARTECA

**Comment by ritwikjk** [comment]
@cassininazir  does Future labs africa have beta access to arteca?

**Comment by cassininazir** [comment]
Not sure. Get me the names of the individuals and we can look them up.

**Comment by ritwikjk** [comment]
@cassininazir  Teagan Bristow , Jepchumba II

**Comment by cassininazir** [comment]
Teagan does. Jepcumba may ... can you tell me her email addres?

**Comment by ritwikjk** [comment]
contact@jepchumba.com

**Comment by cassininazir** [comment]
Thanks. I've added her. It will send an email to her directly, but sometimes gets caught in spam. You might also email her.
