### ISSUE TITLE
info card

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#649]
As everyone asks what Creative Disturbance is we need to have like a small info card (the size of a visiting card without any name. just CD and then the website link) or something with just 

"Creative Disturbance 
 an international, multilingual network and podcast platform supporting collaboration among the arts, sciences, and new technologies communities.

www.creativedisturbance.org"

this way people know what it is and access it

@cassininazir @rmalina @amb141330

**Comment by ygev** [comment]
How is this for an info card?

front ![image](https://cloud.githubusercontent.com/assets/1816215/21059269/33abfeba-be07-11e6-98ae-6f027a11392e.png)
back ![image](https://cloud.githubusercontent.com/assets/1816215/21059273/36f5c510-be07-11e6-8753-ce238f4edf30.png)
