### ISSUE TITLE
Agendas on Google Drive 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#65]
Please make sure Monday agenda lists are on Google Drive. Helps for remote team members to be able to follow along.

Please have this ready by next meeting Monday, May 25.

**Comment by coreysmart92** [comment]
@coreysmart92 - I have placed the [older agendas](https://drive.google.com/drive/folders/0B5c7wZNmEjILVE5tRWhsQU9TcGc/0BwvQhnxKj6jFVVV3U3pvMEstN1E/0B0RS2YDJUln1fjdaRWg5dmo0TEk5MGI3Qjd4ckNjLUQ3dEVWbm9STG9TeEp2YVlGYkVkZkE/0B0RS2YDJUln1fllNZTNxWkN3alRHRWI0QlR0aEdTMkg1b2trY1NSd2YzcEtKMXJkaFNaLUE) online and created a new template for [future agendas](https://docs.google.com/document/d/14uSZ_Sp2ONNxYLJZ4iFj688cnubtEPOAc6Re92S_XwU/edit), with the help of Kyle and Cassini.
Now closing this item.
