### ISSUE TITLE
creative disturbance page not loading

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#653]
The CD webpage hasn't been loading since a couple of days. This needs to be addressed asap as I need to upload a lot of recent podcasts.
@dylanorgeron @amb141330 @rmalina

**Comment by cassininazir** [comment]
I've made a temporary fix for those visiting the site (without logging into the WordPress backend). Exploring a more permanent fix for those of us logged in. 

A few things that will help in the meantime @ritwikjk:

- Login using Chrome's Incognito mode 
- Note that we've enabled SuperCache - this caches (stores locally) pages. As you editing previously published pages, you may need to empty the cache for that page

**Comment by cassininazir** [comment]
I've updated the WordPress core to 4.7, deleted never- or seldom-used plugins (6) and de-activated those not in use. 

Need to explore server changes in more detail as these affect *all* our sites.

**Comment by ritwikjk** [comment]
I tried it using incognito mode in google chrome and deleting all cache files. It still is not loading. Maybe I should use a different browser.
@cassininazir

**Comment by magicspacekiwi** [comment]
Creative Disturbance is on a new, much more reliable server now.
However, performance is still an issue so I've created #658 to continue that discussion.
