### ISSUE TITLE
add to podcast procedure putting name of new voices into the communities contact list

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#669]
Ritwik and team
Emma and i just worked on the database of communities members email addresses

We need to make sure that when you publish a podcast from now on
(congrats on the two podcasts this morning) that the info on the voice
Gets added to the data

Ritwik maybe you can point us to the procedure that you are using for
Each podcast so we can add an item- to put the voices email and info
Into the database

roger

**Comment by OskarOlssonCD** [comment]
@ritwikjk Please send me a link to our current podcast process document so I can add a step to give the voices and producers beta access to ARTECA

**Comment by OskarOlssonCD** [comment]
@ritwikjk I think we can close this one
