### ISSUE TITLE
Corey - Setup Jabber 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#67]
Please confirm that you are able to use Jabber. Review the document at [CD 1.3 Working Remotely](https://docs.google.com/document/d/1NP-TLJ38swdwy3bZrvcW4umn3Dmy1q5y8RrTfkkNbuE/edit) for instructions.

**Complete by Monday, May 25**

**Comment by coreysmart92** [comment]
@coreysmart92 Please do this before Monday, and post any issues here. Thank you

**Comment by coreysmart92** [comment]
Closing: Completed Signing in and Downloading, as well as basic use.
