### ISSUE TITLE
Bumpers inaccessible on Google Drive

### ISSUE THREAD

**Issue by OskarOlssonCD** [creativedisturbance/podcasts#670]
@ritwikjk @EmmaNewkirk 
The channel bumpers stored on the Creative Disturbance google drive are creating the 'forbidden' error message upon attempting to download them, and they also are not generating previews. 

The bumpers are located at [https://drive.google.com/drive/u/1/folders/0B0RS2YDJUln1fng5aTlnd0tzTXVZamZOeUdHckN0OEJ4RXVDZVFITHlHOTJ4bzdrdjZNNHc](url)

**Comment by OskarOlssonCD** [comment]
@cassininazir Is it possible my access to these files was restricted along with the previous staff members?

**Comment by cassininazir** [comment]
I've added you. Not sure why that happened.
