### ISSUE TITLE
Upload a podcast to Beta ARTECA site

### ISSUE THREAD

**Issue by OskarOlssonCD** [creativedisturbance/podcasts#673]
@joelewing @ritwikjk 
One Sound & Data podcast, Some Thoughts on Sonification, has been uploaded to the beta version of the ARTECA website. Our next step is to move the podcast to the official ARTECA site as soon as possible. 
Joel, how do we assign a DOI to the podcast?

**Comment by ritwikjk** [comment]
@OskarOlssonCD has uploaded to beta.
