### ISSUE TITLE
Upload podcast from beta to Official Arteca Website

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#678]
Upload podcast from beta to Official Arteca Website. 
work with joel on the process

**Comment by cassininazir** [comment]
@ritwikjk please add here the list of podcasts that are going into ARTECA.

**Comment by cassininazir** [comment]
@ritwikjk can you point me to the list of podcasts?

**Comment by ritwikjk** [comment]
https://drive.google.com/drive/folders/0B36xYmO3PgTEZjExbmdHYldfTEU?usp=sharing

@cassininazir

**Comment by arfaye** [comment]
@ritwikjk or @cassininazir is an account on arteca.mit required independently of the account on the arteca.atec.io site in order to publish things to the MIT site itself?

**Comment by OskarOlssonCD** [comment]
@ritwikjk @cassininazir I've just uploaded Scot's podcast to the live site after creating the show.  

Show:
http://arteca.mit.edu/sound-data

Episode:
http://arteca.mit.edu/pauline-oliveros-%E2%80%93-some-thoughts-sonification

The limit for archiving is 2gb on the live site, so the file has been uploaded as well and will be preserved for the next 50 years. 

The only issue I've noticed is that it doesn't show up on the 'Recent Podcasts' section of the podcasts page. I've created a new issue for this and assigned Joel.

**Comment by cassininazir** [comment]
Excellent. The URL for the episode will need to be shortened. A few things:

- Remove the %E2%80%93 from the URL. 
- On the podcast page, the link http://oxfordindex.oup.com/view/10.1525/california/9780520257801.003.0014 needs to be hot.
- A period is missing on the  end of the sentence.

**Comment by OskarOlssonCD** [comment]
@Cassininazir 
-Added HTML tags to make the link hot
-Added the period, will do the same on the CD page for the podcast
-New URL alias is http://arteca.mit.edu/pauline-oliveros-some-thoughts-on-sonification
