### ISSUE TITLE
Archive unwanted items on CD gdrive

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#679]
Archive unwanted items, drafts in Forms Folder to  a separate folder on CD Gdrive

**Comment by OskarOlssonCD** [comment]
@ritwikjk I can make a physical backup of anything we don't need. Externals are getting cheaper and cheaper.

**Comment by arfaye** [comment]
Oskar if you want to sift through it I’ll be in the lab tomorrow 11-2

**Comment by arfaye** [comment]
Downloaded a copy of the entire CD drive as is to the main computer in the Lab
