### ISSUE TITLE
Josephine - Setup Jabber 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#68]
Please confirm that you are able to use Jabber. Review the document at [CD 1.3 Working Remotely](https://docs.google.com/document/d/1NP-TLJ38swdwy3bZrvcW4umn3Dmy1q5y8RrTfkkNbuE/edit) for instructions.

**Complete by Monday, May 25**

**Comment by porteriffic** [comment]
I've logged in to Jabber on my laptop remotely and it worked. I have not tried to call or anything yet.
