### ISSUE TITLE
Lynx Academy Workshop

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#682]
Oskar, Yusra and Arael to work on putting together material for Lynx Academy workshop.
How to make a podcast? 
What is a podcast?
What is Creative Disturbance?
How to train the students to make sure podcasts are more of a conversation than a presentation?

**Comment by OskarOlssonCD** [comment]
Podcast: A recorded conversation that informs listeners about a subject over the course of 10-15 minutes on average.
"Creative Disturbance is an international platform supporting collaboration among the arts, sciences, and new technologies communities."-CD Kickstarter mission statement

**Comment by arfaye** [comment]
I'm going to sift through the drive and see what documents we have that we can put to use for this with some molding and shaping; I believe there is a document about how to make a podcast as well as how to make sure the podcasts are more conversational

**Comment by arfaye** [comment]
Made a copy of an already existing podcast production "cheat sheet" and published in CD 4.0 Reference Docs. @OskarOlssonCD I'd like to look through it with you and make the necessary changes to make it work for Lynx Academy

**Comment by OskarOlssonCD** [comment]
@arfaye I went ahead and added a brief note about cell phone use and wireless audio equipment. It's under section 2.

**Comment by arfaye** [comment]
So far what we've got done is: 

- [x] How to make a podcast?

- [x] What is a podcast?

- [x] What is Creative Disturbance?

- [x] How to train the students to make sure podcasts are more of a conversation than a presentation?

To the above point, the podcast making and rating sheet both help those making the podcasts to understand that the direction they should be going in when recording their podcasts is more conversational. I wouldn't say another document is entirely necessary. 

After we're done with answering these questions, are we making a presentation on the subject or is it more geared toward the documents? 
@ritwikjk

**Comment by OskarOlssonCD** [comment]
@arfaye, I think what I want to go for with this is a presentation and then distributing the documents to the LYNX students. I'm working on a short document of tips for conversational recording.

**Comment by OskarOlssonCD** [comment]
I'll have to ask Jason about a date for this, but I also want to demonstrate the proper use of a ZOOM recorder for these students, as that's the gear that they use. I'm also including a copy of the ZOOM H6 Handy user manual.

**Comment by arfaye** [comment]
I think there’s also a document in the CD drive about using the Zoom recorder

**Comment by ritwikjk** [comment]
@arfaye  whats the stat on this? We need to review this in the coming tuesday(oct 17th) meeting.

**Comment by arfaye** [comment]
Updated CD 4.0 Reference Docs with Lynx Academy Workshop slides presentation - not completely finished but a start

**Comment by OskarOlssonCD** [comment]
Started also working on the presentation

**Comment by OskarOlssonCD** [comment]
@ritwikjk @arfaye  I've finished the workshop presentation slides
[https://docs.google.com/presentation/d/1LUZBKfZyG6cL8LCg2Oecyc1yShY8oFMzTIjuQYzg8Js/edit#slide=id.p](url)

**Comment by OskarOlssonCD** [comment]
Workshop materials finished, workshop scheduled for November 16th at 3:00pm
