### ISSUE TITLE
Podcast recording for Charissa terranova

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#684]
Charissa terranova (terranova@utdallas.edu) to interview 3 people.
Nov - Patricia Olynyk 
Dec/Jan - PhD student, Elif Kavakci
Daniel Jardine (to be scheduled)

**Comment by arfaye** [comment]
e-mailed Charissa regarding November's interview

**Comment by arfaye** [comment]
Scheduled November's interview for 17th at 3 pm - Moving issue from Github to separate note in G Drive
