### ISSUE TITLE
Sound & Data episode not appearing under 'recent episodes' on ARTECA

### ISSUE THREAD

**Issue by OskarOlssonCD** [creativedisturbance/podcasts#685]
http://arteca.mit.edu/podcasts 

This page should show the _Some Thoughts on Sonification_ episode of Sound & Data that was just recently moved from the beta version of ARTECA to the live version under the 'Recent Episodes' header. 

Note that everything else worked properly with the upload.

**Comment by joelewing** [comment]
I changed the sort to display episodes based on when they were posted, with the more recently ones being posted first.  This means that they are not displayed in the order that they were created.  Worth talking with both Creative Disturbance and ARTECA about the best way to display featured episodes.

**Comment by OskarOlssonCD** [comment]
Thanks! Looks good now.
