### ISSUE TITLE
DOI for Sound & Data podcast

### ISSUE THREAD

**Issue by OskarOlssonCD** [creativedisturbance/podcasts#686]
The Sound & Data podcast episode on the ARTECA alpha site needs a DOI. 

http://arteca.mit.edu/pauline-oliveros-%E2%80%93-some-thoughts-sonification

**Comment by joelewing** [comment]
I'm not familiar with how to add a DOI.  Also, I want to note that arteca.mit.edu is referred to as the live site (the site that users see).

**Comment by OskarOlssonCD** [comment]
@joelewing Who can I contact about the DOI?

**Comment by joelewing** [comment]
MIT Press.

**Comment by OskarOlssonCD** [comment]
Would I talk to Nick Larson about this? He was mentioned in an earlier issue
