### ISSUE TITLE
producers agreement - sharath chandra channel

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#687]
@OskarOlssonCD work with sharath chandra (looplogic@gmail.com) to get his producers agreement sent in. 
heres the form:
https://docs.google.com/forms/d/1x57FyZ7MiVV_4afwGsjZnuw7QRid9vFGqBDwDbFbNsI/edit

**Comment by OskarOlssonCD** [comment]
I've sent the form to Sharath

**Comment by OskarOlssonCD** [comment]
Sharath and I will be meeting Wednesday to complete the forms.
