### ISSUE TITLE
producers agreement - joao silviera

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#688]
@arfaye  work with joao silviera (silvieraufrj@gmail.com) and  Luciano (lucianoocupim@gmail.com) to get their producers agreement forms sent in for the art sci brazilian channel.
heres the form:
https://docs.google.com/forms/d/1x57FyZ7MiVV_4afwGsjZnuw7QRid9vFGqBDwDbFbNsI/edit

**Comment by arfaye** [comment]
Form has been sent, now waiting for reply

**Comment by ritwikjk** [comment]
form received an signed.
