### ISSUE TITLE
Ashton - Setup Jabber

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#69]
Please confirm that you are able to use Jabber. Review the document at [CD 1.3 Working Remotely](https://docs.google.com/document/d/1NP-TLJ38swdwy3bZrvcW4umn3Dmy1q5y8RrTfkkNbuE/edit) for instructions.

**Complete by Monday, May 25**

**Comment by coreysmart92** [comment]
@amb141330  Please do this before Monday, and post any issues here. Thank you

**Comment by amb141330** [comment]
Logged in and setup cam + mic

**Comment by cassininazir** [comment]
Great! I think Jabber will work well for us. 

May need to setup a meeting with Brian Merlo to have him show you how to configure the screen in the lab.

**Comment by amb141330** [comment]
I'll be showing up early for Monday's meeting in order to work on it more myself.

**Comment by cassininazir** [comment]
Great. Start a Google doc and link to it here as well.

Sent from my iPhone

On May 23, 2015, at 7:19 PM, amb141330 <notifications@github.com<mailto:notifications@github.com>> wrote:

I'll be showing up early for Monday's meeting in order to work on it more myself.

�
