### ISSUE TITLE
revise and improve new channel producer form

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#692]
oskar
would you be willing to work with me on looking at the new channel producer form to see if we need to add or improve things or cover any legal issues we havent included

roger

**Comment by OskarOlssonCD** [comment]
@rmalina 

Definitely, I’d like to get this up as soon as possible. I want to record podcasts specifically about sound design. I know people who are involved in a lot of interesting projects or who have commentary on techniques, tools, etc.
