### ISSUE TITLE
renew Libsyn subscription

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#696]
Renew Libsyn subscription for CD to be able to see geographic stats.

**Comment by OskarOlssonCD** [comment]
Upgrade will cost $5 more per month for a total of $20/mo.

**Comment by cassininazir** [comment]
Upgraded to LibSyn Advanced 400. Confirm that this enables the stats you mentioned.

**Comment by OskarOlssonCD** [comment]
@cassininazir 
I just checked, works great!
