### ISSUE TITLE
Benchmarking: Review Podcasts in the Stitcher Awards

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#7]
What can we learn from these podcasts? http://www.stitcher.com/blog/?p=1375

**Comment by porteriffic** [comment]
Didn't get to listen to all of them (on my to-do list) but I love the Alton Browncast. Love the spin on his own name and the word "podcast". Clever! Also, very cool bumper. Definitely suits the podcast.

**Comment by kkondas** [comment]
Here is a list of all the Podcast Awards winner from 2005 to 2012:
http://www.podcastawards.com/index.php?option=pastwinners
