### ISSUE TITLE
Shorten ARTECA url paths

### ISSUE THREAD

**Issue by OskarOlssonCD** [creativedisturbance/podcasts#703]
Retroactively shorten ARTECA podcast url paths to increase accessibility and ease of sharing. 
Click "Edit" on the podcast and scroll down to "URL Path Settings" and un-check "Generate automatic URL alias." 

Enter the following:

podcast/words-moreWords

Podcast titles shouldn't include numbers or more than 15 characters

**Comment by OskarOlssonCD** [comment]
All URLs to date have been shortened.

**Comment by cassininazir** [comment]
Nice work!
