### ISSUE TITLE
Kyle - Setup Jabber

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#71]
Please confirm that you are able to use Jabber. Review the document at [CD 1.3 Working Remotely](https://docs.google.com/document/d/1NP-TLJ38swdwy3bZrvcW4umn3Dmy1q5y8RrTfkkNbuE/edit) for instructions.

**Complete by Monday, May 25**

**Comment by kkondas** [comment]
Had a few problems, but after meeting with Brian, I was able to get Jabber working.
