### ISSUE TITLE
Storing Bumpers

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#72]
@coreysmart92 , @halclark , @amb141330 

If you have a completed bumper, please store on the Creative Disturbance Google Drive in folder "CD 2.2.1.5 Bumpers". 

If you have a draft of a bumper, please store in folder "CD 2.2.1.6 Bumpers (Draft)".

Both of these folders are located in "CD 2.2.2 Audio Files" in the Production Team folder. Path should look something like this:

2.2 Production Team >> CD 2.2.2 Audio Files >> CD 2.2.1.5 Bumpers or CD 2.2.1.6 Bumpers(Drafts)

**Each team member is responsible for getting their own bumper to the right location.**

**Comment by rmalina** [comment]
also- i am interested in short podcasts on each bumper that can be posted on the experimental section explaining what the stinger writer was experimenting with/trying to do to link the stinger to the topic of the channel
roger

**Comment by coreysmart92** [comment]
Write up a cheat sheet on Google Drive about the Stinger making process.

**Comment by cassininazir** [comment]
https://docs.google.com/document/d/1IoYkLJMJkRPqp_F7HD6GZE1EBzCghXxbdZ_tiY6MdQU/edit

**Comment by amb141330** [comment]
Per Cassini's document--We will use that process. We are waiting for that to be implemented.

**Comment by coreysmart92** [comment]
Will be using Google Drive [Bumpers](https://drive.google.com/drive/folders/0B5c7wZNmEjILVE5tRWhsQU9TcGc/0BwvQhnxKj6jFVVV3U3pvMEstN1E/0BwvQhnxKj6jFVU1rSGYwdmtIVmc/0B0RS2YDJUln1fng5aTlnd0tzTXVZamZOeUdHckN0OEJ4RXVDZVFITHlHOTJ4bzdrdjZNNHc) folder. Closing until new developments.
