### ISSUE TITLE
Just a reminder...

### ISSUE THREAD

**Issue by kkondas** [creativedisturbance/podcasts#73]
Corey met with Poe Johnson this morning to give him and go over how to use the xoom recorder for the Conference on Values in Medicine. He said that he'll probably have it back by this weekend.

**Comment by porteriffic** [comment]
Thanks for the update @kkondas. In the future, please refrain from duplicating issues. The issue regarding Poe Johnson was opened on Monday [here](https://github.com/creativedisturbance/podcasts/issues/63)

**Comment by kkondas** [comment]
Sorry about that. My fault. I missed the first one. Will go ahead and close this one.
