### ISSUE TITLE
Rhythmically Inclined - Sound Team Experimental Channel

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#74]
@halclark The Sound Team has decided to hand over the producer position of this channel to you. Could you please write up a plan of action towards this channel.
1. Give a plan of action at next meeting (June 1, 2015)
2. Write up a Guideline Document for this channel (on Google Drive)
3. Have the channel up on Creative Disturbance and producing podcast

Close when you have completed all three of the above items.

**Comment by rmalina** [comment]
i love the name

**Comment by coreysmart92** [comment]
@heiwanalady Please complete the Art work by 6/4/15 by the latest.

**Comment by porteriffic** [comment]
@coreysmart92 @halclark Artwork is done. Please get this channel up ASAP.

**Comment by coreysmart92** [comment]
Meet in week of 6/22/15-6/29/15 to record podcast about bumpers. (6/22/15)
Close when channel is up.

**Comment by cassininazir** [comment]
Listen to this podcast with sound designer/composer Brian Reitzell for ideas on how to discuss sound within a podcast. 

http://99percentinvisible.org/episode/all-in-your-head/

**Comment by rmalina** [comment]
i am available on skype to record podcast about new leonardos bumper
roger @coreysmart92

**Comment by porteriffic** [comment]
@halclark Have the above items been completed? Please have a guideline completed to go along with the channel.

**Comment by cassininazir** [comment]
This is live.
