### ISSUE TITLE
Editor to Producer Email Examples for Cassini

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#75]
@coreysmart92 @halclark @amb141330 @porteriffic Collect at least three example of email correspondence with producers. Send these examples to Cassini to help with email template creation. This should be done no later than May 27, 2015.

Close when all Podcast Editors have sent examples to Cassini.

**Comment by coreysmart92** [comment]
Clarification: 6 examples-3 sent, and 3 received sent to Cassini

**Comment by porteriffic** [comment]
@cassininazir Sent you an email with screenshots.

**Comment by heiwanalady** [comment]
@cassininazir created a doc with my examples (some from the early days!) here
https://docs.google.com/document/d/1Kwu7TmZw34eZx_1zcg1JiBj7g2KX175GgUkHlGL4Gco/edit

**Comment by cassininazir** [comment]
Bellissima!

**Comment by cassininazir** [comment]
@halclark @coreysmart92 still need yours by tomorrow, please.

**Comment by coreysmart92** [comment]
@coreysmart92 @halclark @ashton Send email examples to Cassini by latest 6/3/15. Use Stephanie's as an example.

**Comment by cassininazir** [comment]
@coreysmart92 assigning to you. Have opened other tasks for Hal and Ashton individually. Send to me by June 3.

**Comment by coreysmart92** [comment]
I have completed my examples in [Corey Smart Email Examples](https://docs.google.com/document/d/1MaFJD_nvRqBtEppmCp3VNBb_NSCJuESdXjXHX0WWz_U/edit) . I have organized it in correspondence instead of one by one. I thought this would give a better example of my emails for Creative Disturbance.

@cassininazir Close if this is enough examples.

**Comment by coreysmart92** [comment]
Closing, Cassini has signed off that he received the examples.
