### ISSUE TITLE
The two bumpers per month

### ISSUE THREAD

**Issue by kkondas** [creativedisturbance/podcasts#76]
Hey team, during this coming Monday's sound meeting, let's sit down and make a plan of action for the the bumpers that are to be produced each month.  I say that each month, we should decided on which two channels will have their bumpers worked on.

**Comment by halclark** [comment]
Sounds great! I'm working on a few currently.

**Comment by rmalina** [comment]
creating a tracking sheet for stingers

**Comment by coreysmart92** [comment]
@coreysmart92 One bumper for Bold Roast. To be completed at latest by 5/30/15.

**Comment by rmalina** [comment]
create a short podcast with each stinger explainilng what the composer tried to do connected to the channel them

**Comment by cassininazir** [comment]
First of these will appear this week. Closing as well. Expecting [two additional](https://docs.google.com/document/d/1FWIowgmapa4oWz8yaSpvSMrZYRUQ6UmO4KbJxDco82Y/edit) from Corey and Hal next week.
