### ISSUE TITLE
Forms for Reynaldo Thompson Podcast

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#78]
Remind Roger to fill out forms for Reynaldo Thompson Podcast.

**Comment by halclark** [comment]
@rmalina

**Comment by halclark** [comment]
According to Ashton, will be done by next week.

**Comment by rmalina** [comment]
hal- i have filled out the form- and sent you a copy
roger
@halclark

**Comment by coreysmart92** [comment]
Closing: Forms are completed
