### ISSUE TITLE
Polyglot Splash Page

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#79]
For steps on creating a splash page and/or editing, go here: [Splash Page Procedure](https://docs.google.com/document/d/1UTMi35cU1sZk7z6KbefUQ-ZMkyztFyA-lH6Knl6BFH4/edit)

There is already a "Polyglot Day" draft under the **Pages** tab on WordPress.

Edit the page accordingly.

Contact @cassininazir or @porteriffic for assistance.

**Comment by amb141330** [comment]
I've already contacted Stephanie about creating the art for Polyglot day. She told me she or Lina would see to it.

**Comment by porteriffic** [comment]
@amb141330 Great! Stephanie said she'd have it ready this week.

**Comment by cassininazir** [comment]
@halclark connect with me or @heiwanalady (Stephanie) to learn how to do a splash page. Please be up and running by June 5.

**Comment by heiwanalady** [comment]
Initial concepts:
![cd_polyglot_banner](https://cloud.githubusercontent.com/assets/6133439/7823530/b134625c-03c1-11e5-8dc6-4aea5bca38e9.jpg)
![cd_polyglot_banner2](https://cloud.githubusercontent.com/assets/6133439/7823529/b1314f2c-03c1-11e5-9f87-8631d0d5e291.jpg)

**Comment by cassininazir** [comment]
@porteriffic could you provide a list of podcasts that we are expecting for PolyGlot Day?

**Comment by cassininazir** [comment]
@porteriffic and I gave feedback via email. @heiwanalady is in the process of making the magic happen.

**Comment by porteriffic** [comment]
Here are the languages I'm expecting to have for Polyglot Day:
- German
- Bengali
- Korean
- Bahasa
- Japanese
- Spanish
- Russian 
- Arabic
- French

I've been coordinating all of them except Korean and Japanese. Responses have been slowing down so I'm hoping I can still get them in. 

I can send an email out this week as a reminder to Voices and Producers. Mostly a waiting game right now.

**Comment by cassininazir** [comment]
Update from discussion with @porteriffic. Please check to see your assignment listed below. 

Already recorded: 
- **German** Darren ?? + Max Schich 
  - Discipline: Digital Humanities, Complex Networks and Art History
- **Portuguese** Roger + Patricia

Expecting: 
- **Bengali** Dhru Deb + unknown - ~~@porteriffic will email~~ **Update**: Working on script.
  - Channel: Bold Roast
- **Spanish**: 
  Dario + ~~Manuel +~~ Nahum Mantra - ~~@porteriffic will email~~
  - Discipline: Space, Art & Engineering
  
  Gustavo Garcia + unknown
  - Channel: Bold Roast
- **Bahasa** Susan Erickson + Christina Widiwijayanti - ~~@porteriffic will email~~ **Update**: Might be late due to evacuations/Sinabung crisis response
  - Discipline: Senior Research Fellow Earth Observatory of Singapore
- **Arabic**:
  
  Yasser Jeradi + Huda Hashim - ~~@yvantina need forms~~
  - Discipline: Art, music, artistic connections
  - Channel: Virtual Africa
  
  Haytham Nawar + Roger + Yvan Tina
  - Discipline: Artist, designer and researcher
  - Channel: Virtual Africa
- **French** Yasser Jeradi + Yvan Tina - ~~@yvantina need forms~~
  - Discipline: Art, music, artistic connections
  - Channel: Virtual Africa
- **Russian** Olga + unknown - ~~@porteriffic will email~~
  - Channel: Space Art & Culture
- **Japanese** Kei Takahashi + Taro Toyota + Muneyuki Matsuo
  - Discipline: DNA-lipid and Stem cells
  - Channel: Meta-life?

Uncertain: 
- **Korean** Moon Kim + unknown - ~~@amb141330 please check in with Moon~~ Update: Moon Kim is not available to do a podcast.

**Comment by cassininazir** [comment]
@amb141330 assigning this back to you. Reminder: The task is to create the splash page for PolyGlot Day. **Have a prototype ready for next Monday's meeting (June 8)**.

**Comment by yvantina** [comment]
@cassininazir  @porteriffic @heiwanalady @amb141330 
- We had an issue with the podcast in German (SD card deleted) so Max and Doron agreed to make another one but will not receive this one before June 13 at the best
- The podcast in Japanese will be sent to me later this week (Kei Takahashi + Taro Toyota + Muneyuki Matsuo)
- Another podcast in Egyptian Arabic (Masry) should be added to the list (the one with Haytham Nawar, Roger and me) ++ the ones for the RAMI channel which is supposed to open around the same period (??).
- Am also supposed to receive a podcast in Spanish from Guadalajara (Gustavo Garcia + unknown)
- Not sure to have something in African languages (Swahili or another one) = working very hard on this but it's more difficult
- It's me on the French podcast with Yasser but I'm happy to release this one later as we already have a few of them in French and would rather like to hear another voice than mine...;)

**Comment by porteriffic** [comment]
@yvantina Great! Thank you! I will update above accordingly. 

No worries about the German podcast. We can make an exception for that one since it was accidentally deleted. 

I've seen a channel proposal for RAMI. Do they have a logo already? If they don't, worst case scenario we put their podcasts on a different channel. Either @heiwanalady or @linamoon will have to design a logo.

Also, I agree with you about the other French podcasts. 

Please let us know if anything changes. Thanks again!

**Comment by cassininazir** [comment]
@yvantina if you have SD card, try using an undelete software to try to resurrect the file. @porteriffic you might also help @yvantina with this. Better to spend 30 minutes with the software than have them re-record. 

http://pcsupport.about.com/od/filerecovery/tp/free-file-recovery-programs.htm

**Comment by yvantina** [comment]
@cassininazir Corey unintentionnally deleted the files on the SD card and I assume they have been replaced by new podcasts since then.. but @porteriffic I am happy to try again if it makes things simpler...

**Comment by porteriffic** [comment]
@yvantina I'm more than happy to meet up to try and recover the podcast. According the link Cassini posted, it should be able to recover the file. It doesn't hurt to try!

**Comment by yvantina** [comment]
@porteriffic will be in the lab tomorrow 1-5 pm. Preferred window is 1.30-2pm since Ashton and I should get trained for echo 360 afterwards..

**Comment by porteriffic** [comment]
@yvantina Okay. I can be there around 1:30. See you then

**Comment by heiwanalady** [comment]
@porteriffic @yvantina @cassininazir Am working on the splash page, and have very little information on the podcasts and which channels they will be on. Any info would be helpful! Just a few are on wufoo - so will try and finish those.

**Comment by heiwanalady** [comment]
@porteriffic @amb141330 @cassininazir @coreysmart92  
I'm guessing the RAMI channel will be posted on Polyglot Day - along with their Arabic podcast (    Mayye Zayed)? 
Album Artwork already exists - made it a few months ago. I can upload to the wordpress.

**Comment by yvantina** [comment]
@heiwanalady I've sent an email to Renaud regarding the podcast title
@porteriffic @cassininazir the German podcast has been recovered, thanks ;)
where are we supposed to upload podcasts for the Polyglot day that don't have yet any channel affiliation ?

**Comment by yvantina** [comment]
@heiwanalady For the ones I am involved in (more or less), if it can help:
- Russian (Olga Bannova) = Space Art and Culture
- German (Max + Doron) = TBD, I know they talk about Digital Humanities, Complex Networks and Art History
- Japanese (Tkahashi + Toyota + Matsuo) = TBD, I know they talk about DNA-lipid and Stem cells, so Biology
- Masry (Arabic) (Nawar + Malina + Tina) = Virtual Africa
- Arabic (classic) (Jradi + Hashim) = Virtual Africa
- Spanish (optional) (Garcia + unknown) = Bold Roast ?

**Comment by yvantina** [comment]
@heiwanalady by the way you need to double check with the producers of the channels mentioned..

**Comment by porteriffic** [comment]
@heiwanalady Yes, we'll have the RAMI channel up with Polyglot Day. The soonest I can work on that page is beginning of next week.

@yvantina Glad you were able to recover the podcast! If you have time, I'll need your help in collecting the disciplines of the podcasts you're working with. I only have disciplines for the ones I'm working with. 

@kkondas Can you look into Dropbox to see if we have room to create a folder specifically for Polyglot Day? If not, we can have them upload to the Google Drive.

**Comment by kkondas** [comment]
@porteriffic At the moment we have around 1.5 GB of space free on the dropbox.

**Comment by yvantina** [comment]
@amb141330 @coreysmart92 @porteriffic @kkondas 
Can you please replace / add to the podcast in French with Yasser Jeradi (by) the one in Arabic with Roger and Haytham Nawar for polyglot week ? French is probably the most represented foreign language on CD but it is up to you to keep that this way for next week, I don't want to change your plans.. I'd just like the ones in Arabic to be released also on the same period..Thank you

**Comment by coreysmart92** [comment]
Polyglot Splash page has been published.
Close when taking splash page down.

**Comment by rmalina** [comment]
it does not list the disciplines included in polyglot day
please add as soon as possible
roger

**Comment by porteriffic** [comment]
@rmalina Disciplines are listed under each podcast. See above a post from @cassininazir 20 days ago.

**Comment by porteriffic** [comment]
Splash page should be up to date with disciplines with the exception of the Arabic and Japanese podcast. Some kind of glitch. Working with Stephanie to fix it right now.

**Comment by heiwanalady** [comment]
@porteriffic @rmalina disciplines are now displayed on each podcast and in the intro info!

**Comment by heiwanalady** [comment]
@porteriffic @amb141330 @halclark @coreysmart92 
Just FYI, for future reference, **we should keep all of the foreign language slugs (url links) in English.**
I just changed the Japanese one to _/dna-rna-1_ 
I have not changed the Arabic one yet. I believe foreign text in a link might create glitches in the link's functionality

**Comment by coreysmart92** [comment]
Polyglot Splash page has published.
Closing because the completed version of the page has been published.
