### ISSUE TITLE
Celebrate 10,000 Downloads

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#80]
Let's discuss a plan for this. @porteriffic assigning to you, let's put a team together. We can celebrate via social media. 

Currently at 9,453.

**Comment by heiwanalady** [comment]
Will need graphic for Twitter/Facebook @heiwanalady

**Comment by porteriffic** [comment]
Whoa! That's awesome! 

@cassininazir Will we be doing a splash page for this as well?

**Comment by cassininazir** [comment]
No splash page. We should make use of the blog and social media. Am available Tuesday or Friday if you'd like to discuss.

**Comment by porteriffic** [comment]
@cassininazir  How about Tuesday? I'll be unavailable from Friday through Sunday.

**Comment by porteriffic** [comment]
@cassininazir Would you like for me to work on a blog post for this?

**Comment by rmalina** [comment]
why dont you try and do a social media push including blog posts-not sure what our communication plan -but i can tell you at a distanace creative disturbance is invisible on my social media !!

**Comment by porteriffic** [comment]
@rmalina Yes, a social media push will be in the works on my end.

@cassininazir and I have been trying to disperse community building roles to the sound team. They are a little bit new to it and it will take a little time for them to get accustomed to doing social media pushes. 

Also, we are still adding to the Community Building Plan. Social media pushes are already in there and I will be adding more to it.

**Comment by heiwanalady** [comment]
Here's the graphics I made - one for Twitter (506x253) and one for Facebook (1200x900)
These dimensions are the recommended dimensions for sharing pictures on each platform (did a little research). 
Let me know if you need anything else!
![cd_10k-downloads-facebook2](https://cloud.githubusercontent.com/assets/6133439/7995694/20f5d346-0ade-11e5-91b8-08a515b861c2.png)
![cd_10k-downloads-twitter2](https://cloud.githubusercontent.com/assets/6133439/7995695/2106159e-0ade-11e5-856a-e10c1ee0ecbd.png)

**Comment by porteriffic** [comment]
@cassininazir Started a draft for a blog post on this. Should we post before of after Polyglot Day?

**Comment by rmalina** [comment]
polyglot day is in ten days so you could do it now
roger

**Comment by porteriffic** [comment]
@rmalina Okay. Will work on social media (including blog) today.

**Comment by porteriffic** [comment]
Completed social media push on Facebook, Twitter, blog and emails to the community. Will post and tweet throughout the week. Will close this at end of week.

**Comment by porteriffic** [comment]
Celebrated. Did multiple social media posts.
