### ISSUE TITLE
set up podcast recording with artscilab alumnus cathryn ploehne

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#84]
cathryn ploehne is an atec alumnus who worked in art sci lab

can one of the editors set up a podcast recording with her ?

coordinate with stephanie

will let you assign

roger
Stephanie Brisendine sabrisendine@gmail.com
Apr 21

to Cathryn, Roger 
Roger- Cathryn is ready to do a podcast with us! 

Cathryn, 

We can definitely figure out a time for next week. Yes our podcasts are still audio-based, but if you have any unique suggestions - we are definitely open to them. If you can specify specific days you'd like to talk, that would be amazing. I will try to accommodate your schedule. :)

Best,
Stephanie

On Mon, Apr 20, 2015 at 11:28 AM, Cathryn Ploehn cathrynploehn@hotmail.com wrote:
Stephanie, 

Sorry for the late response - I had to double check with our public relations people to make sure I didn't have to get any approval/clearance before talking about my stuff. 

What do you need from me? Next week should be open for me to Skype after 5:30 usually. Are the podcasts still audio-only?

Thanks!

Cathryn

Great!

I had to speak with a few public affairs people to ensure I didn't need clearance to talk about my work.

Right now I'm working on things related to Cybersecurity, specifically improving policies on text-based passwords. I have a paper accepted to Human Computer Interaction International conference <Aug 2015 , http://2015.hci.international/> I'm also starting a really cool side project in may concerning data science / big data visualization evaluation that I can speak about more in a few weeks. 

I'm also working on a very very new side project (not NIST related) - an algorithm that generates a list of foods to eat in a day that will meet the nutrition recommendation standards set by institutions like the WHO and IOM - something that apparently no other app does at the moment. 

I can talk about any and all of what I'm working on!

Best,

Cathryn Ploehn
214.402.0749

**Comment by coreysmart92** [comment]
Stephanie and Lina are prime candidates to do a podcast with Cathryn. I will contact them and setup a podcast with one or both.

**Comment by coreysmart92** [comment]
I have emailed Cathryn Ploehn again, but yet to receive a response. (6/22/15)

**Comment by coreysmart92** [comment]
Cathryn has responded and would like to do a podcast. I will get in touch with Stephanie for a time to make the podcast.

**Comment by coreysmart92** [comment]
Closing: This podcast has been recorded and published. (8/3/15)
