### ISSUE TITLE
Please always keep a Zoom in the artscilab

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#85]
@amb141330 @coreysmart92 @porteriffic @kkondas @halclark 
hey guys
I think we should ALWAYS be able to record a podcast in the artscilab 
As I explained to Corey last week I had recorded a podcast with Max and Doron for the polyglot day but didn't have time to upload the file on Dropbox because I was traveling that friday. Since I was in a rush I thought I would be able to do so the following monday ..Unfortunately or unintentionally Corey had to clean the SD card without knowing that my file was still stored inside.. 
so to avoid this scenario again, I suggest we should never remove the audio Zoom recorder from the lab and please make sure it is always ready to record a podcast on site..
Talk to you later

**Comment by coreysmart92** [comment]
@corey.smart92 Need to make Cheat Sheet for BLU Microphones in Lab. Complete by latest 6/17/15.

**Comment by cassininazir** [comment]
Closing this issue.
