### ISSUE TITLE
Yasser Jeradi Needs Forms

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#89]
@yvantina @amb141330 Podcast Yasser Jeradi and Huda Hashim needs forms to be published. Ashton is in charge of this podcast, must contact Yvan and have forms by 6/17/15. Yvan is waiting for podcast information from the host. This podcast is in Arabic.

**Comment by yvantina** [comment]
Done

**Comment by coreysmart92** [comment]
Closing: Forms are Completed
