### ISSUE TITLE
correction to reynaldo thompson podcast form

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#95]
correction to form for reynaldo thomson podcast i just submitted
roger

Podcast Title \* Data Base of Latin American Electronic and Digital Artists; Art and Spirituality in the Digital Arts
Short Description of this Podcast \* Reynaldo Thompson Professor of Design at the University of Guanajuato and Roger Malina discuss the project to set up a data base of Latin American electronic and digital artists, but also Thompson's project with Frank Dufour for an exhibition on Art and Spirituality in the Digital Arts.
Key Words for this Podcast \*    Mexico, new media, digital media
Short Bio of Guest \*    Reynaldo Thompson is a professor of digital media at the University of Guanajuato in Mexico. He has a PhD in Aesthetic Studies from the University of Texas at Dallas.

**Comment by halclark** [comment]
Will do. Podcast will be ready to go up by Mondays meeting

**Comment by halclark** [comment]
Hey Roger, the title for this podcast is a tad lengthy. How about just "Art and Spirituality in the Digital Arts"?

**Comment by rmalina** [comment]
ok
roger

**Comment by halclark** [comment]
Corrected info.
