### ISSUE TITLE
Podcast Masry (egyptian arabic)-English Haytham Nawar for Polyglot Day !

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#96]
@coreysmart92 @halclark @amb141330 can you please move the podcast with Haytham, Roger and myself to polyglot Day in your tracking sheet ? Thanks

**Comment by rmalina** [comment]
there are two-one is in arabic-so move the one in arabic-the one in english can be published later

**Comment by yvantina** [comment]
no worry
if needed then

**Comment by yvantina** [comment]
@halclark @coreysmart92 @amb141330 Roger is present in this podcast - can you also please add his name/pic on the website page ? http://creativedisturbance.org/podcast/egyptianart-ar/

**Comment by yvantina** [comment]
RE @halclark @coreysmart92 @amb141330 Roger is present in this podcast - can you also please add his name/pic on the website page ? http://creativedisturbance.org/podcast/egyptianart-ar/

**Comment by coreysmart92** [comment]
Closing: Polyglot Day is over and Roger has been added to the English version of the podcast. (8/3/15)
