### ISSUE TITLE
unacceptable podcast title

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#97]
this noisy people podcast is unacceptably uninformative

06: Roscoe Mitchell

tim perkis is happy to rewrite podcast titles if you ask him to

roger

**Comment by porteriffic** [comment]
@rmalina I emailed Tim about this last week (I copied you in that email). I'm still waiting to hear back from him.

**Comment by rmalina** [comment]
josephine
no problem
but hopefully the procedure cheat sheet used by the sound editors 
has the title approval in the check list so we dont post a podcast in the future
with an unaccetable title
roger

**Comment by porteriffic** [comment]
@rmalina Tim has already submitted some forms for incoming podcasts and those titles are different. So all his future podcasts will have acceptable titles.

**Comment by rmalina** [comment]
great
lets be clear with all the producers !
roger

**Comment by coreysmart92** [comment]
I will add these notes to the producer cheat sheet. But I feel that many producers still want to use the same name for multi-parted podcasts.

**Comment by porteriffic** [comment]
I will send out an email next week to let producers know about naming their podcasts. It's already in the cheat sheets but will emphasize. That way we can avoid any weird podcast titles in the future.
