### ISSUE TITLE
wrong info for reynaldo thompson went up

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#98]
hal 
what happened
this went up with the wrong title- after i approved your excellent suggested change to it
and it went up with the wrong photo after the voice sent you the new photo
also he had other suggested changes-did these get made ?
can you check the text to make sure you made the changes he requested
thanks

roger

with Roger Malina, Reynaldo Thompson
In Person
EN
June 10, 2015

**Comment by coreysmart92** [comment]
This was my mistake, I published the podcast without knowing of the title change. I have fixed it but I do not have the photo change. @halclark could you fix the photo problem and check to make sure that everything else is correct.

**Comment by rmalina** [comment]
no problem- what are you doing up in the middle of the night !
hal-there was both the new photo and the corrections to the bio text i thin k that he send
you
roger

**Comment by halclark** [comment]
I'll fix it as soon as I get back to my computer!

**Comment by halclark** [comment]
Corrected
