### ISSUE TITLE
Virtual Africa folder on updated Dropbox 

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#99]
@kkondas @coreysmart92 @porteriffic @amb141330 Hey Guys I couldn't locate the V-A folder on Dropbox until I found it under the old Creative Disturbance folder..I wonder whether or not it was voluntary since it is not been listed with the other channels..am a bit confused...

**Comment by amb141330** [comment]
I'll be fixing this before monday, Yvan.

**Comment by porteriffic** [comment]
Virtual Africa folder should be available in the new Dropbox folder. You may want to check your email. It says you haven't accepted any of the invites to your folders.
